from django.db import models

from model_utils import Choices

CURRENCY_LIST = [
    'GIP', 'KPW', 'XEU', 'BHD', 'BIF', 'BMD', 'BSD', 'AFN', 'ALL', 'AMD', 'AUD', 'AZN', 'BAM',
    'BBD', 'BDT', 'BZD', 'CUP1', 'BTN', 'ZWL', 'AWG', 'CUC', 'VEF01', 'BND', 'BRL', 'ARS', 'ETB', 'EUR',
    'FJD', 'GBP', 'GEL', 'GHS', 'GNF', 'GTQ', 'GYD', 'HNL', 'CAD', 'CDF', 'CLP', 'CNY', 'COP', 'CRC',
    'CUP', 'CVE', 'DJF', 'DKK', 'DOP', 'DZD', 'EGP', 'HRK', 'LVL', 'LYD', 'MAD', 'MGA', 'MKD', 'KWD',
    'KYD', 'LBP', 'LKR', 'MDL', 'KZT', 'LRD', 'BOB', 'HKD', 'CHF', 'KES', 'MYR', 'NGN', 'KMF', 'SCR',
    'SEK', 'TTD', 'PKR', 'NIO', 'RWF', 'BWP', 'JMD', 'TJS', 'UYU', 'RON', 'PYG', 'SYP', 'LAK', 'ERN',
    'SLE', 'PLN', 'JOD', 'ILS', 'AED', 'NPR', 'NZD', 'SGD', 'JPY', 'PAB', 'ZMW', 'CZK', 'SOS', 'LTL',
    'KGS', 'SHP', 'BGN', 'TOP', 'MVR', 'VEF02', 'TMT', 'GMD', 'MZN', 'RSD', 'MWK', 'PGK', 'MXN', 'XAF',
    'VND', 'INR', 'NOK', 'XPF', 'SSP', 'IQD', 'SRD', 'SAR', 'XCD', 'IRR', 'KPW01', 'HTG', 'IDR', 'XOF',
    'ISK', 'ANG', 'NAD', 'MMK', 'STN', 'VUV', 'LSL', 'SVC', 'KHR', 'SZL', 'RUB', 'UAH', 'UGX', 'THB',
    'AOA', 'YER', 'USD', 'UZS', 'OMR', 'SBD', 'TZS', 'SDG', 'WST', 'QAR', 'MOP', 'MRU', 'VEF', 'TRY',
    'ZAR', 'HUF', 'MUR', 'PHP', 'BYN', 'KRW', 'TND', 'MNT', 'PEN'
]

CURRENCY_DICT = {
    'GIP': 'Gibraltar Pound',
    'KPW': 'North Korean Won',
    'XEU': 'European Currency Unit',
    'BHD': 'Bahraini Dinar',
    'BIF': 'Burundian Franc',
    'BMD': 'Bermudian Dollar',
    'BSD': 'Bahamian Dollar',
    'AFN': 'Afghanistan Afghani',
    'ALL': 'Albanian Lek',
    'AMD': 'Armenian Dram',
    'AUD': 'Australian Dollar',
    'AZN': 'Azerbaijani Manat',
    'BAM': 'Bosnia-Herzegovina Convertible Mark',
    'BBD': 'Barbadian Dollar',
    'BDT': 'Bangladeshi Taka',
    'BZD': 'Belize Dollar',
    'CUP1': 'Cuban Peso (Convertible)',
    'BTN': 'Bhutanese Ngultrum',
    'ZWL': 'Zimbabwean Dollar',
    'AWG': 'Aruban Florin',
    'CUC': 'Cuban Convertible Peso',
    'VEF01': 'Venezuelan Bolívar (Old)',
    'BND': 'Brunei Dollar',
    'BRL': 'Brazilian Real',
    'ARS': 'Argentine Peso',
    'ETB': 'Ethiopian Birr',
    'EUR': 'Euro',
    'FJD': 'Fijian Dollar',
    'GBP': 'British Pound Sterling',
    'GEL': 'Georgian Lari',
    'GHS': 'Ghanaian Cedi',
    'GNF': 'Guinean Franc',
    'GTQ': 'Guatemalan Quetzal',
    'GYD': 'Guyanese Dollar',
    'HNL': 'Honduran Lempira',
    'CAD': 'Canadian Dollar',
    'CDF': 'Congolese Franc',
    'CLP': 'Chilean Peso',
    'CNY': 'Chinese Yuan',
    'COP': 'Colombian Peso',
    'CRC': 'Costa Rican Colón',
    'CUP': 'Cuban Peso',
    'CVE': 'Cape Verdean Escudo',
    'DJF': 'Djiboutian Franc',
    'DKK': 'Danish Krone',
    'DOP': 'Dominican Peso',
    'DZD': 'Algerian Dinar',
    'EGP': 'Egyptian Pound',
    'HRK': 'Croatian Kuna',
    'LVL': 'Latvian Lats',
    'LYD': 'Libyan Dinar',
    'MAD': 'Moroccan Dirham',
    'MGA': 'Malagasy Ariary',
    'MKD': 'Macedonian Denar',
    'KWD': 'Kuwaiti Dinar',
    'KYD': 'Cayman Islands Dollar',
    'LBP': 'Lebanese Pound',
    'LKR': 'Sri Lankan Rupee',
    'MDL': 'Moldovan Leu',
    'KZT': 'Kazakhstani Tenge',
    'LRD': 'Liberian Dollar',
    'BOB': 'Bolivian Boliviano',
    'HKD': 'Hong Kong Dollar',
    'CHF': 'Swiss Franc',
    'KES': 'Kenyan Shilling',
    'MYR': 'Malaysian Ringgit',
    'NGN': 'Nigerian Naira',
    'KMF': 'Comorian Franc',
    'SCR': 'Seychellois Rupee',
    'SEK': 'Swedish Krona',
    'TTD': 'Trinidad and Tobago Dollar',
    'PKR': 'Pakistani Rupee',
    'NIO': 'Nicaraguan Córdoba',
    'RWF': 'Rwandan Franc',
    'BWP': 'Botswanan Pula',
    'JMD': 'Jamaican Dollar',
    'TJS': 'Tajikistani Somoni',
    'UYU': 'Uruguayan Peso',
    'RON': 'Romanian Leu',
    'PYG': 'Paraguayan Guaraní',
    'SYP': 'Syrian Pound',
    'LAK': 'Laotian Kip',
    'ERN': 'Eritrean Nakfa',
    'SLE': 'Sierra Leonean Leone',
    'PLN': 'Polish Złoty',
    'JOD': 'Jordanian Dinar',
    'ILS': 'Israeli New Shekel',
    'AED': 'UAE Dirham',
    'NPR': 'Nepalese Rupee',
    'NZD': 'New Zealand Dollar',
    'SGD': 'Singapore Dollar',
    'JPY': 'Japanese Yen',
    'PAB': 'Panamanian Balboa',
    'ZMW': 'Zambian Kwacha',
    'CZK': 'Czech Koruna',
    'SOS': 'Somali Shilling',
    'LTL': 'Lithuanian Litas',
    'KGS': 'Kyrgystani Som',
    'SHP': 'Saint Helena Pound',
    'BGN': 'Bulgarian Lev',
    'TOP': 'Tongan Paʻanga',
    'MVR': 'Maldivian Rufiyaa',
    'VEF02': 'Venezuelan Bolívar (New)',
    'TMT': 'Turkmenistani Manat',
    'GMD': 'Gambian Dalasi',
    'MZN': 'Mozambican Metical',
    'RSD': 'Serbian Dinar',
    'MWK': 'Malawian Kwacha',
    'PGK': 'Papua New Guinean Kina',
    'MXN': 'Mexican Peso',
    'XAF': 'CFA Franc BEAC',
    'VND': 'Vietnamese Dong',
    'INR': 'Indian Rupee',
    'NOK': 'Norwegian Krone',
    'XPF': 'CFP Franc',
    'SSP': 'South Sudanese Pound',
    'IQD': 'Iraqi Dinar',
    'SRD': 'Surinamese Dollar',
    'SAR': 'Saudi Riyal',
    'XCD': 'East Caribbean Dollar',
    'IRR': 'Iranian Rial',
    'KPW01': 'North Korean Won (Old)',
    'HTG': 'Haitian Gourde',
    'IDR': 'Indonesian Rupiah',
    'XOF': 'CFA Franc BCEAO',
    'ISK': 'Icelandic Króna',
    'ANG': 'Netherlands Antillean Guilder',
    'NAD': 'Namibian Dollar',
    'MMK': 'Myanmar Kyat',
    'STN': 'São Tomé and Príncipe Dobra',
    'VUV': 'Vanuatu Vatu',
    'LSL': 'Lesotho Loti',
    'SVC': 'Salvadoran Colón',
    'KHR': 'Cambodian Riel',
    'SZL': 'Swazi Lilangeni',
    'RUB': 'Russian Ruble',
    'UAH': 'Ukrainian Hryvnia',
    'UGX': 'Ugandan Shilling',
    'THB': 'Thai Baht',
    'AOA': 'Angolan Kwanza',
    'YER': 'Yemeni Rial',
    'USD': 'US Dollar',
    'UZS': 'Uzbekistani Som',
    'OMR': 'Omani Rial',
    'SBD': 'Solomon Islands Dollar',
    'TZS': 'Tanzanian Shilling',
    'SDG': 'Sudanese Pound',
    'WST': 'Samoan Tala',
    'QAR': 'Qatari Riyal',
    'MOP': 'Macanese Pataca',
    'MRU': 'Mauritanian Ouguiya',
    'VEF': 'Venezuelan Bolívar',
    'TRY': 'Turkish Lira',
    'ZAR': 'South African Rand',
    'HUF': 'Hungarian Forint',
    'MUR': 'Mauritian Rupee',
    'PHP': 'Philippine Peso',
    'BYN': 'Belarusian Ruble',
    'KRW': 'South Korean Won',
    'TND': 'Tunisian Dinar',
    'MNT': 'Mongolian Tugrik',
    'PEN': 'Peruvian Sol'
}

CURRENCIES = Choices(*[(c, CURRENCY_DICT.get(c, c)) for c in CURRENCY_LIST])


class CurrencyField(models.CharField):

    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = kwargs.get('max_length', 5)
        kwargs['choices'] = CURRENCIES
        kwargs['null'] = kwargs.get('null', False)
        kwargs['blank'] = kwargs.get('blank', True)
        kwargs['default'] = kwargs.get('default', '')
        super().__init__(*args, **kwargs)
