# Generated by Django 3.2.19 on 2023-10-20 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('environment', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantswitch',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Activate this switch for these countries.', to='users.Country', verbose_name='Countries'),
        ),
        migrations.AddField(
            model_name='tenantflag',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Activate this flag for these countries.', to='users.Country', verbose_name='Countries'),
        ),
        migrations.AddField(
            model_name='tenantflag',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Activate this flag for these user groups.', to='auth.Group', verbose_name='Users'),
        ),
        migrations.AddField(
            model_name='tenantflag',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Activate this flag for these users.', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
