# Generated by Django 2.1.7 on 2019-03-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_auto_20190122_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssueCheckConfig',
        ),
    ]
