# Generated by Django 3.2.6 on 2022-04-20 16:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import etools.applications.t2f.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('partners', '0001_initial'),
        ('action_points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255, verbose_name='Origin')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('departure_date', models.DateField(verbose_name='Departure Date')),
                ('arrival_date', models.DateField(verbose_name='Arrival Date')),
                ('overnight_travel', models.BooleanField(default=False, verbose_name='Overnight Travel')),
                ('mode_of_travel', models.CharField(blank=True, choices=[('Plane', 'Plane'), ('Bus', 'Bus'), ('Car', 'Car'), ('Boat', 'Boat'), ('Rail', 'Rail')], default='', max_length=5, verbose_name='Mode of Travel')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Canceled At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('first_submission_date', models.DateTimeField(blank=True, null=True, verbose_name='First Submission Date')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_note', models.TextField(blank=True, default='', verbose_name='Rejection Note')),
                ('cancellation_note', models.TextField(blank=True, default='', verbose_name='Cancellation Note')),
                ('certification_note', models.TextField(blank=True, default='', verbose_name='Certification Note')),
                ('report_note', models.TextField(blank=True, default='', verbose_name='Report Note')),
                ('misc_expenses', models.TextField(blank=True, default='', verbose_name='Misc Expenses')),
                ('status', django_fsm.FSMField(choices=[('planned', 'Planned'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='planned', max_length=50, protected=True, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('purpose', models.CharField(blank=True, default='', max_length=500, verbose_name='Purpose')),
                ('additional_note', models.TextField(blank=True, default='', verbose_name='Additional Note')),
                ('international_travel', models.BooleanField(blank=True, default=False, null=True, verbose_name='International Travel')),
                ('ta_required', models.BooleanField(blank=True, default=True, null=True, verbose_name='TA Required')),
                ('reference_number', models.CharField(default=etools.applications.t2f.models.make_travel_reference_number, max_length=12, unique=True, verbose_name='Reference Number')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('mode_of_travel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Plane', 'Plane'), ('Bus', 'Bus'), ('Car', 'Car'), ('Boat', 'Boat'), ('Rail', 'Rail')], max_length=5), blank=True, null=True, size=None, verbose_name='Mode of Travel')),
                ('estimated_travel_cost', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Estimated Travel Cost')),
                ('is_driver', models.BooleanField(default=False, verbose_name='Is Driver')),
                ('preserved_expenses_local', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True, verbose_name='Preserved Expenses (Local)')),
                ('preserved_expenses_usd', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True, verbose_name='Preserved Expenses (USD)')),
                ('approved_cost_traveler', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True, verbose_name='Approved Cost Traveler')),
                ('approved_cost_travel_agencies', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True, verbose_name='Approved Cost Travel Agencies')),
            ],
        ),
        migrations.CreateModel(
            name='T2FActionPoint',
            fields=[
            ],
            options={
                'verbose_name': 'T2F Action Point',
                'verbose_name_plural': 'T2F Action Points',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('action_points.actionpoint',),
        ),
        migrations.CreateModel(
            name='TravelAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to=etools.applications.t2f.models.determine_file_upload_path, verbose_name='File')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='t2f.travel', verbose_name='Travel')),
            ],
        ),
        migrations.CreateModel(
            name='TravelActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_type', models.CharField(blank=True, choices=[('Programmatic Visit', 'Programmatic Visit'), ('Spot Check', 'Spot Check'), ('Advocacy', 'Advocacy'), ('Technical Support', 'Technical Support'), ('Meeting', 'Meeting'), ('Staff Development', 'Staff Development'), ('Staff Entitlement', 'Staff Entitlement')], default='Programmatic Visit', max_length=64, verbose_name='Travel Type')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('locations', models.ManyToManyField(related_name='_t2f_travelactivity_locations_+', to='locations.Location', verbose_name='Locations')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.partnerorganization', verbose_name='Partner')),
                ('partnership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_activities', to='partners.intervention', verbose_name='Partnership')),
            ],
            options={
                'verbose_name_plural': 'Travel Activities',
            },
        ),
    ]
