# Generated by Django 1.10.8 on 2018-03-26 16:05

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import django_fsm

import etools.applications.t2f.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('unicef_locations', '0001_initial'),
        ('publics', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=254, verbose_name='Description')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('status', models.CharField(blank=True, choices=[('open', 'Open'), ('ongoing', 'Ongoing'), (
                    'completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=254, null=True, verbose_name='Status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('actions_taken', models.TextField(blank=True, null=True, verbose_name='Actions Taken')),
                ('follow_up', models.BooleanField(default=False, verbose_name='Follow up')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('person_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                         related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsible Person')),
            ],
        ),
        migrations.CreateModel(
            name='Clearances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_clearance', models.CharField(choices=[('requested', 'requested'), ('not_requested', 'not_requested'), (
                    'not_applicable', 'not_applicable')], default='not_applicable', max_length=14, verbose_name='Medical Clearance')),
                ('security_clearance', models.CharField(choices=[('requested', 'requested'), ('not_requested', 'not_requested'), (
                    'not_applicable', 'not_applicable')], default='not_applicable', max_length=14, verbose_name='Security Clearance')),
                ('security_course', models.CharField(choices=[('requested', 'requested'), ('not_requested', 'not_requested'), (
                    'not_applicable', 'not_applicable')], default='not_applicable', max_length=14, verbose_name='Security Course')),
            ],
            options={
                'verbose_name_plural': 'Clearances',
            },
        ),
        migrations.CreateModel(
            name='CostAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.PositiveIntegerField(verbose_name='Share')),
                ('delegate', models.BooleanField(default=False, verbose_name='Delegate')),
                ('business_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='+', to='publics.BusinessArea', verbose_name='Business Area')),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('breakfast', models.BooleanField(default=False, verbose_name='Breakfast')),
                ('lunch', models.BooleanField(default=False, verbose_name='Lunch')),
                ('dinner', models.BooleanField(default=False, verbose_name='Dinner')),
                ('accomodation', models.BooleanField(default=False, verbose_name='Accomodation')),
                ('no_dsa', models.BooleanField(default=False, verbose_name='No DSA')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Amount')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               related_name='+', to='publics.Currency', verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=32, unique=True, verbose_name='Reference Number')),
                ('business_area', models.CharField(max_length=32, verbose_name='Business Area')),
                ('vendor_number', models.CharField(max_length=32, verbose_name='Vendor Number')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'),
                                                     ('success', 'Success'), ('error', 'Error')], max_length=16, verbose_name='Status')),
                ('messages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(
                    blank=True, null=True), default=[], size=None, verbose_name='Messages')),
                ('vision_fi_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Vision FI ID')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='+', to='publics.Currency', verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='items', to='t2f.Invoice', verbose_name='Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255, verbose_name='Origin')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('departure_date', models.DateTimeField(verbose_name='Departure Date')),
                ('arrival_date', models.DateTimeField(verbose_name='Arrival Date')),
                ('overnight_travel', models.BooleanField(default=False, verbose_name='Overnight Travel')),
                ('mode_of_travel', models.CharField(blank=True, choices=[('Plane', 'Plane'), ('Bus', 'Bus'), ('Car', 'Car'), (
                    'Boat', 'Boat'), ('Rail', 'Rail')], max_length=5, null=True, verbose_name='Mode of Travel')),
                ('airlines', models.ManyToManyField(related_name='_itineraryitem_airlines_+',
                                                    to='publics.AirlineCompany', verbose_name='Airlines')),
                ('dsa_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='+', to='publics.DSARegion', verbose_name='DSA Region')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Canceled At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('first_submission_date', models.DateTimeField(blank=True, null=True, verbose_name='First Submission Date')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_note', models.TextField(blank=True, null=True, verbose_name='Rejection Note')),
                ('cancellation_note', models.TextField(blank=True, null=True, verbose_name='Cancellation Note')),
                ('certification_note', models.TextField(blank=True, null=True, verbose_name='Certification Note')),
                ('report_note', models.TextField(blank=True, null=True, verbose_name='Report Note')),
                ('misc_expenses', models.TextField(blank=True, null=True, verbose_name='Misc Expenses')),
                ('status', django_fsm.FSMField(choices=[('planned', 'Planned'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('sent_for_payment', 'Sent for payment'), ('certification_submitted',
                                                                                                                                                                                                                                                                   'Certification submitted'), ('certification_approved', 'Certification approved'), ('certification_rejected', 'Certification rejected'), ('certified', 'Certified'), ('completed', 'Completed')], default='planned', max_length=50, protected=True, verbose_name='Status')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('purpose', models.CharField(blank=True, max_length=500, null=True, verbose_name='Purpose')),
                ('additional_note', models.TextField(blank=True, null=True, verbose_name='Additional Note')),
                ('international_travel', models.BooleanField(default=False, verbose_name='International Travel', blank=True, null=True)),
                ('ta_required', models.BooleanField(default=True, verbose_name='TA Required', blank=True, null=True)),
                ('reference_number', models.CharField(default=etools.applications.t2f.models.make_travel_reference_number,
                                                      max_length=12, unique=True, verbose_name='Reference Number')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('mode_of_travel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Plane', 'Plane'), ('Bus', 'Bus'), (
                    'Car', 'Car'), ('Boat', 'Boat'), ('Rail', 'Rail')], max_length=5), blank=True, null=True, size=None, verbose_name='Mode of Travel')),
                ('estimated_travel_cost', models.DecimalField(decimal_places=4,
                                                              default=0, max_digits=20, verbose_name='Estimated Travel Cost')),
                ('is_driver', models.BooleanField(default=False, verbose_name='Is Driver')),
                ('preserved_expenses_local', models.DecimalField(blank=True, decimal_places=4,
                                                                 default=None, max_digits=20, null=True, verbose_name='Preserved Expenses (Local)')),
                ('preserved_expenses_usd', models.DecimalField(blank=True, decimal_places=4,
                                                               default=None, max_digits=20, null=True, verbose_name='Preserved Expenses (USD)')),
                ('approved_cost_traveler', models.DecimalField(blank=True, decimal_places=4,
                                                               default=None, max_digits=20, null=True, verbose_name='Approved Cost Traveler')),
                ('approved_cost_travel_agencies', models.DecimalField(blank=True, decimal_places=4,
                                                                      default=None, max_digits=20, null=True, verbose_name='Approved Cost Travel Agencies')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               related_name='+', to='publics.Currency', verbose_name='Currency')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='+', to='users.Office', verbose_name='Office')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='+', to='reports.Section', verbose_name='Section')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
                ('traveler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               related_name='travels', to=settings.AUTH_USER_MODEL, verbose_name='Travellert')),
            ],
        ),
        migrations.CreateModel(
            name='TravelActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_type', models.CharField(blank=True, choices=[('Programmatic Visit', 'Programmatic Visit'), ('Spot Check', 'Spot Check'), ('Advocacy', 'Advocacy'), ('Technical Support', 'Technical Support'), (
                    'Meeting', 'Meeting'), ('Staff Development', 'Staff Development'), ('Staff Entitlement', 'Staff Entitlement')], max_length=64, null=True, verbose_name='Travel Type')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('locations', models.ManyToManyField(related_name='_travelactivity_locations_+',
                                                     to='locations.Location', verbose_name='Locations')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='+', to='partners.PartnerOrganization', verbose_name='Partner')),
                ('partnership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='travel_activities', to='partners.Intervention', verbose_name='Partnership')),
                ('primary_traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                       to=settings.AUTH_USER_MODEL, verbose_name='Primary Traveler')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='+', to='reports.Result', verbose_name='Result')),
                ('travels', models.ManyToManyField(related_name='activities', to='t2f.Travel', verbose_name='Travels')),
            ],
            options={
                'verbose_name_plural': 'Travel Activities',
            },
        ),
        migrations.CreateModel(
            name='TravelAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('file', models.FileField(max_length=255,
                                          upload_to=etools.applications.t2f.models.determine_file_upload_path, verbose_name='File')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='attachments', to='t2f.Travel', verbose_name='Travel')),
            ],
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='itinerary', to='t2f.Travel', verbose_name='Travel'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='invoices', to='t2f.Travel', verbose_name='Travel'),
        ),
        migrations.AddField(
            model_name='expense',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='expenses', to='t2f.Travel', verbose_name='Travel'),
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='publics.TravelExpenseType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='deductions', to='t2f.Travel', verbose_name='Deduction'),
        ),
        migrations.AddField(
            model_name='costassignment',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='cost_assignments', to='t2f.Travel', verbose_name='Travel'),
        ),
        migrations.AddField(
            model_name='clearances',
            name='travel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='clearances', to='t2f.Travel', verbose_name='Travel'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='action_points', to='t2f.Travel', verbose_name='Travel'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='itineraryitem',
            order_with_respect_to='travel',
        ),
    ]
