# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-21 12:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0002_fix_null_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionpoint',
            name='actions_taken',
            field=models.TextField(blank=True, default='', verbose_name='Actions Taken'),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('ongoing', 'Ongoing'), (
                'completed', 'Completed'), ('cancelled', 'Cancelled')], default='', max_length=254, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(
                blank=True, default=''), default=[], size=None, verbose_name='Messages'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vision_fi_id',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Vision FI ID'),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='mode_of_travel',
            field=models.CharField(blank=True, choices=[('Plane', 'Plane'), ('Bus', 'Bus'), ('Car', 'Car'), (
                'Boat', 'Boat'), ('Rail', 'Rail')], default='', max_length=5, verbose_name='Mode of Travel'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='additional_note',
            field=models.TextField(blank=True, default='', verbose_name='Additional Note'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='cancellation_note',
            field=models.TextField(blank=True, default='', verbose_name='Cancellation Note'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='certification_note',
            field=models.TextField(blank=True, default='', verbose_name='Certification Note'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='misc_expenses',
            field=models.TextField(blank=True, default='', verbose_name='Misc Expenses'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='rejection_note',
            field=models.TextField(blank=True, default='', verbose_name='Rejection Note'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='report_note',
            field=models.TextField(blank=True, default='', verbose_name='Report Note'),
        ),
        migrations.AlterField(
            model_name='travelactivity',
            name='travel_type',
            field=models.CharField(blank=True, choices=[('Programmatic Visit', 'Programmatic Visit'), ('Spot Check', 'Spot Check'), ('Advocacy', 'Advocacy'), ('Technical Support', 'Technical Support'), (
                'Meeting', 'Meeting'), ('Staff Development', 'Staff Development'), ('Staff Entitlement', 'Staff Entitlement')], default='Programmatic Visit', max_length=64, verbose_name='Travel Type'),
        ),
    ]
