# Generated by Django 4.2.3 on 2024-07-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0001_initial'),
        ('locations', '0001_initial'),
        ('t2f', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryitem',
            name='airlines',
            field=models.ManyToManyField(related_name='+', to='publics.airlinecompany', verbose_name='Airlines'),
        ),
        migrations.AlterField(
            model_name='travelactivity',
            name='locations',
            field=models.ManyToManyField(related_name='+', to='locations.location', verbose_name='Locations'),
        ),
    ]
