# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-03 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0004_auto_20180524_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='section',
        ),
    ]
