# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-03 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0005_remove_travel_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='sector',
            new_name='section',
        ),
    ]
