# Generated by Django 1.10.8 on 2018-08-30 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0007_t2factionpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionpoint',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='actionpoint',
            name='person_responsible',
        ),
        migrations.RemoveField(
            model_name='actionpoint',
            name='travel',
        ),
        migrations.DeleteModel(
            name='ActionPoint',
        ),
    ]
