# Generated by Django 2.0.9 on 2018-12-27 08:15

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0008_auto_20180830_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='status',
            field=django_fsm.FSMField(choices=[('planned', 'Planned'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='planned', max_length=50, protected=True, verbose_name='Status'),
        ),
    ]
