# Generated by Django 2.0.9 on 2018-12-29 02:49

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0009_auto_20181227_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default=''), default=list, size=None, verbose_name='Messages'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='traveler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travels', to=settings.AUTH_USER_MODEL, verbose_name='Traveller'),
        ),
    ]
