# Generated by Django 2.0.8 on 2019-01-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0011_auto_20190102_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearances',
            name='travel',
        ),
        migrations.DeleteModel(
            name='Clearances',
        ),
    ]
