# Generated by Django 2.0.9 on 2019-01-23 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0013_auto_20190103_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costassignment',
            name='business_area',
        ),
        migrations.RemoveField(
            model_name='costassignment',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='type',
        ),
        migrations.DeleteModel(
            name='CostAssignment',
        ),
        migrations.DeleteModel(
            name='Deduction',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
