# Generated by Django 2.1.8 on 2019-04-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0015_auto_20190326_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryitem',
            name='dsa_region',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='approved_cost_travel_agencies',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='approved_cost_traveler',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='preserved_expenses_local',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='preserved_expenses_usd',
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='mode_of_travel',
            field=models.CharField(blank=True, choices=[('Plane', 'Plane'), ('Bus', 'Bus'), ('Car', 'Car'), ('Boat', 'Boat'), ('Rail', 'Rail')], max_length=5, null=True, verbose_name='Mode of Travel'),
        ),
    ]
