# Generated by Django 2.2.1 on 2019-06-20 12:08

from django.db import migrations, models


def set_reference_number(apps, schema_editor):
    TravelActivity = apps.get_model("t2f", "travelactivity")
    for activity in TravelActivity.objects.all():
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0015_auto_20190326_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelactivity',
            name='reference_number',
            field=models.CharField(max_length=12, null=True, verbose_name='Reference Number'),
        ),
        migrations.RunPython(
            set_reference_number,
        ),
    ]
