# Generated by Django 4.2.3 on 2024-07-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('publics', '0006_auto_20190625_1547'),
        ('t2f', '0016_auto_20191011_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryitem',
            name='airlines',
            field=models.ManyToManyField(related_name='+', to='publics.airlinecompany', verbose_name='Airlines'),
        ),
        migrations.AlterField(
            model_name='travelactivity',
            name='locations',
            field=models.ManyToManyField(related_name='+', to='locations.location', verbose_name='Locations'),
        ),
    ]
