# Generated by Django 3.2.19 on 2023-10-24 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('purchase_order', '0002_initial'),
        # ('action_points', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ('partners', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reference_number', models.CharField(max_length=100, unique=True, verbose_name='Reference Number')),
                ('overall_rating', models.IntegerField(blank=True, null=True)),
                ('assessment_date', models.DateField(blank=True, null=True, verbose_name='Assessment Date')),
                ('assessment_type', models.CharField(choices=[('unicef_2020', 'UNICEF Assessment 2020'), ('un_common_other', 'UN Common Assessment- Other UN'), ('un_common_unicef', 'UN Common Assessment- UNICEF')], default='unicef_2020', max_length=16)),
                ('assessment_ingo_reason', models.CharField(blank=True, choices=[('decentralized', 'Decentralization of INGO'), ('sea_allegation', 'SEA allegation'), ('global_policy_implemented', 'Global policy not being implemented at country-level'), ('high_risk_context', 'High risk context')], max_length=32, null=True)),
                ('status', django_fsm.FSMField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('final', 'Final'), ('cancelled', 'Cancelled')], default='draft', max_length=30, verbose_name='Status')),
                ('focal_points', models.ManyToManyField(blank=True, related_name='pse_assessment_focal_point', to=settings.AUTH_USER_MODEL, verbose_name='UNICEF Focal Points')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psea_assessment', to='partners.partnerorganization', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ('-assessment_date',),
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('label', models.TextField(verbose_name='Label')),
                ('requires_description', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidence',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='AssessmentActionPoint',
            fields=[
            ],
            options={
                'verbose_name': 'PSEA Assessment Action Point',
                'verbose_name_plural': 'PSEA Assessment Action Points',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('action_points.actionpoint',),
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('subject', models.TextField(verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
                ('rating_instructions', models.TextField(blank=True, verbose_name='Rating Instructions')),
                ('active', models.BooleanField(default=True)),
                ('evidences', models.ManyToManyField(to='psea.Evidence', verbose_name='Evidences')),
                ('ratings', models.ManyToManyField(to='psea.Rating', verbose_name='Rating')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('assessor_type', models.CharField(choices=[('external', 'External Individual'), ('staff', 'UNICEF Staff'), ('firm', 'Assessing Firm')], max_length=30, verbose_name='Type')),
                ('order_number', models.CharField(blank=True, max_length=30, verbose_name='Order Number')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessor', to='psea.assessment', verbose_name='Assessment')),
                ('auditor_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_order.auditorfirm', verbose_name='Auditor')),
                ('auditor_firm_staff', models.ManyToManyField(blank=True, related_name='_psea_assessor_auditor_firm_staff_+', to=settings.AUTH_USER_MODEL, verbose_name='Auditor Staff')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Assessor',
                'verbose_name_plural': 'Assessors',
            },
        ),
        migrations.CreateModel(
            name='AssessmentStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('final', 'Final'), ('cancelled', 'Cancelled')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='psea.assessment', verbose_name='Assessment')),
            ],
            options={
                'verbose_name': 'Assessment Status History',
                'verbose_name_plural': 'Assessment Status History',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='AnswerEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='psea.answer', verbose_name='Answer')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psea.evidence', verbose_name='Evidence')),
            ],
            options={
                'verbose_name': 'Answer Evidence',
                'verbose_name_plural': 'Answer Evidences',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='psea.assessment', verbose_name='Assessment'),
        ),
        migrations.AddField(
            model_name='answer',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psea.indicator', verbose_name='Indicator'),
        ),
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psea.rating', verbose_name='Rating'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('assessment', 'indicator')},
        ),
    ]
