# Generated by Django 2.2.3 on 2019-08-02 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import etools.applications.psea.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0038_auto_20190620_2024'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PSEA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', django_fsm.FSMField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('final', 'Final'), ('cancelled', 'Cancelled')], default='draft', max_length=30, verbose_name='Status')),
                ('overall_rating', etools.applications.psea.fields.PSEARatingField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=8, null=True)),
                ('date_of_field_visit', models.DateField(blank=True, null=True, verbose_name='Date of Field Visit')),
                ('date_assigned', models.DateField(blank=True, null=True)),
                ('date_accepted', models.DateField(blank=True, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('date_finalized', models.DateField(blank=True, null=True)),
                ('date_canceled', models.DateField(blank=True, null=True)),
                ('focal_points', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='UNICEF Focal Points')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'PSEA',
                'verbose_name_plural': 'PSEAs',
            },
        ),
        migrations.CreateModel(
            name='PSEAIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(verbose_name='Text')),
                ('details', models.TextField(verbose_name='Details')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PSEA Indicator',
                'verbose_name_plural': 'PSEA Indicators',
            },
        ),
        migrations.CreateModel(
            name='PSEAEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('indicators', models.ManyToManyField(to='psea.PSEAIndicator', verbose_name='Indicators')),
            ],
            options={
                'verbose_name': 'PSEA Evidence',
                'verbose_name_plural': 'PSEA Evidence',
            },
        ),
        migrations.CreateModel(
            name='PSEAAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rating', etools.applications.psea.fields.PSEARatingField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=8, null=True)),
                ('other', models.TextField(blank=True, null=True, verbose_name='Other Description')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('evidences', models.ManyToManyField(to='psea.PSEAEvidence', verbose_name='Evidences')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psea.PSEAIndicator', verbose_name='Indicator')),
                ('psea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psea.PSEA', verbose_name='PSEA')),
            ],
            options={
                'verbose_name': 'PSEA Answer',
                'verbose_name_plural': 'PSEA Answers',
            },
        ),
    ]
