# Generated by Django 2.2.4 on 2019-08-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='psea.Assessment', verbose_name='Assessment'),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessors', to='psea.Assessment', verbose_name='Assessment'),
        ),
    ]
