# Generated by Django 2.2.4 on 2019-09-17 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psea', '0008_assessmentactionpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='focal_points',
            field=models.ManyToManyField(blank=True, related_name='pse_assessment_focal_point', to=settings.AUTH_USER_MODEL, verbose_name='UNICEF Focal Points'),
        ),
    ]
