# Generated by Django 2.2.4 on 2019-09-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psea', '0009_auto_20190917_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
