# Generated by Django 2.2.4 on 2019-10-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psea', '0011_indicator_rating_instructions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ('order',), 'verbose_name': 'Indicator', 'verbose_name_plural': 'Indicators'},
        ),
    ]
