# Generated by Django 2.2.20 on 2021-05-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psea', '0012_auto_20191004_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_ingo_reason',
            field=models.CharField(blank=True, choices=[('decentralized', 'Decentralization of INGO'), ('sea_allegation', 'SEA allegation'), ('global_policy_implemented', 'Global policy not being implemented at country-level'), ('high_risk_context', 'High risk context')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('unicef_2020', 'UNICEF Assessment 2020'), ('un_common_other', 'Assessment- Other UN'), ('un_common_unicef', 'Assessment- UNICEF')], default='unicef_2020', max_length=16),
        ),
    ]
