# Generated by Django 2.2.20 on 2021-05-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psea', '0013_auto_20210505_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_ingo_reason',
            field=models.CharField(blank=True, choices=[('decentralized', 'Decentralization of INGO'), ('sea_allegation', 'SEA allegation'), ('global_policy_implemented', 'Global policy not being implemented at country-level'), ('high_risk_context', 'High risk context')], max_length=32, null=True),
        ),
    ]
