# Generated by Django 3.2.6 on 2022-12-16 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psea', '0015_auto_20210607_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessor',
            old_name='auditor_firm_staff',
            new_name='old_auditor_firm_staff',
        )
    ]
