# Generated by Django 3.2.6 on 2022-12-16 09:34

from django.conf import settings
from django.db import migrations, models, connection


def migrate_auditor_firm_staff_to_users(apps, schema_editor):
    if connection.tenant.schema_name in ["public", "test"]:
        return

    Assessor = apps.get_model('psea', 'Assessor')

    for a in Assessor.objects.all():
        a.auditor_firm_staff.add(*[staff_member.user for staff_member in a.old_auditor_firm_staff.all().select_related('user')])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psea', '0016_alter_assessor_auditor_firm_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='auditor_firm_staff',
            field=models.ManyToManyField(blank=True, related_name='_psea_assessor_auditor_firm_staff_+', to=settings.AUTH_USER_MODEL, verbose_name='Auditor Staff'),
        ),
        migrations.RunPython(migrate_auditor_firm_staff_to_users, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='assessor',
            name='old_auditor_firm_staff',
        ),
    ]
