# Generated by Django 4.2.3 on 2024-07-01 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psea', '0017_auto_20221216_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='auditor_firm_staff',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Auditor Staff'),
        ),
    ]
