# pyup.io docs: https://pyup.io/docs/bot/config/

# don't send automated PRs when new package updates are available
update: false

# default branch
branch: develop

# should pyup search for requirement files?
search: False

# specify the requirement files
requirements:
  - src/requirements/production.txt
  - src/requirements/local.txt
