FROM python:3.7-alpine3.11

RUN apk update
RUN apk add --upgrade apk-tools \
    openssl \
    ca-certificates \
    libressl3.0-libcrypto \
    libmagic \
    libxslt \
    geos \
    gdal \
    postgresql-client


# Build-deps
RUN apk add --no-cache --virtual .build-deps --update \
    alpine-sdk \
    libxml2-dev \
    libxslt-dev \
    xmlsec-dev \
    postgresql-dev \
    libffi-dev \
    jpeg-dev \
    python-dev \
    geos-dev \
    gdal-dev \
    gcc \
    g++


# PYTHON
RUN pip install --no-cache-dir --upgrade \
    setuptools \
    pip \
    pipenv
