FROM python:3.12-alpine3.19

RUN apk update

RUN apk add \
    --update alpine-sdk

RUN apk add --upgrade apk-tools \
    openssl \
    ca-certificates \
    libmagic \
    libxslt \
    geos \
    gdal \
    postgresql-client


# Build-deps
RUN apk add --no-cache --virtual .build-deps --update \
    alpine-sdk \
    libxml2-dev \
    libxslt-dev \
    xmlsec-dev \
    postgresql-dev \
    libffi-dev \
    jpeg-dev \
    geos-dev \
    gdal-dev \
    gcc \
    g++ \
    gettext

RUN pip install --no-cache-dir --upgrade \
    pip


WORKDIR /etools/
RUN pip install pdm
ADD .pdm-python .
ADD pdm.lock .
ADD pyproject.toml .
RUN pdm install

ENV PYTHONPATH=/etools/__pypackages__/3.12/lib