FROM robertavram/py27nodejs:latest

RUN apt-get update

ENV CPLUS_INCLUDE_PATH /usr/include/gdal

ENV C_INCLUDE_PATH /usr/include/gdal

ENV PYTHONUNBUFFERED 1

RUN mkdir /req

WORKDIR /req

ADD EquiTrack/requirements /req/

RUN pip install -r production.txt
