version: '2'
services:
  web:
    build:
      context: .
      dockerfile: etools-run.docker
    image: unicef/equitrack:etools
    command: honcho start
    ports:
      - "8080:8080"
    links:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgis://postgres:password@db:5432/postgres
      - DJANGO_SETTINGS_MODULE=EquiTrack.settings.base
      - DJANGO_DEBUG=true
    env_file:
      - env_prod

  beater:
    image: unicef/equitrack:etools
    command: python manage.py celery worker -B -E --loglevel=info
    links:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgis://postgres:password@db:5432/postgres

  db:
    image: mdillon/postgis:9.4
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db_dumps:/tmp/db_dumps

  redis:
    image: redis