# Generated by Django 3.2.19 on 2023-10-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionhistory',
            name='from_sections',
            field=models.ManyToManyField(blank=True, related_name='history_from', to='reports.Section', verbose_name='From'),
        ),
        migrations.AddField(
            model_name='sectionhistory',
            name='to_sections',
            field=models.ManyToManyField(blank=True, related_name='history_to', to='reports.Section', verbose_name='To'),
        ),
    ]
