# Generated by Django 2.2.3 on 2019-07-09 19:39

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0018_section_active'),
        ('management', '0002_auto_20190326_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('history_type', models.CharField(max_length=500, verbose_name='Name')),
                ('permission_type', models.CharField(choices=[('create', 'Create'), ('merge', 'Merge'), ('split', 'Split'), ('close', 'Close')], max_length=10)),
                ('from_sections', models.ManyToManyField(blank=True, related_name='history_from', to='reports.Section', verbose_name='From')),
                ('to_sections', models.ManyToManyField(blank=True, related_name='history_to', to='reports.Section', verbose_name='To')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
