# Generated by Django 3.2.19 on 2024-07-19 11:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import etools.libraries.tenant_support.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorFirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('street_address', models.CharField(blank=True, default='', max_length=500, verbose_name='Address')),
                ('city', models.CharField(blank=True, default='', max_length=255, verbose_name='City')),
                ('postal_code', models.CharField(blank=True, default='', max_length=32, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, default='', max_length=255, verbose_name='Country')),
                ('email', models.CharField(blank=True, default='', max_length=255, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, default='', max_length=32, verbose_name='Phone Number')),
                ('vision_synced', models.BooleanField(default=False, verbose_name='Synced from VISION')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked in VISION')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('deleted_flag', models.BooleanField(default=False, verbose_name='Marked For Deletion in VISION')),
                ('unicef_users_allowed', models.BooleanField(default=False, editable=False, help_text='Allow UNICEF users to join and act as auditors.', verbose_name='UNICEF users allowed')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ('organization__name',),
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Purchase Order Number')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='PO Date')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Contract Expiry Date')),
                ('auditor_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='purchase_order.auditorfirm', verbose_name='Auditor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='PO Item Number')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_order.purchaseorder', verbose_name='Purchase Order')),
            ],
        ),
        migrations.CreateModel(
            name='AuditorStaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('history', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128, verbose_name='History'), blank=True, default=list, size=None)),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('auditor_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_staff_members', to='purchase_order.auditorfirm', verbose_name='Auditor')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ('id',),
                'abstract': False,
            },
            bases=(etools.libraries.tenant_support.models.ModelHavingTenantRelationsMixin, models.Model),
        ),
    ]
