# Generated by Django 1.10.8 on 2018-04-19 12:42
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_make_not_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorfirm',
            name='unicef_users_allowed',
            field=models.BooleanField(
                default=False, help_text='Allow UNICEF users to join and act as auditors.', verbose_name='UNICEF users allowed'),
        ),
    ]
