# Generated by Django 3.2.19 on 2024-04-12 21:26

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0121_auto_20230814_1058'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('wastage_type', models.CharField(choices=[('DAMAGED', 'Damaged'), ('STOLEN', 'Stolen'), ('EXPIRED', 'Expired'), ('LOST', 'Lost')], max_length=30, null=True)),
                ('uom', models.CharField(choices=[('BAG', 'BAG'), ('BOT', 'BOT'), ('BOX', 'BOX'), ('CAR', 'CAR'), ('DRM', 'DRM'), ('DZ', 'DZ'), ('EA', 'EA'), ('KG', 'KG'), ('L', 'L'), ('M', 'M'), ('PAA', 'PAA'), ('PAC', 'PAC'), ('RM', 'RM'), ('ROL', 'ROL'), ('SET', 'SET'), ('TBE', 'TBE'), ('TO', 'TO'), ('VL', 'VL')], max_length=30, null=True)),
                ('conversion_factor', models.IntegerField(null=True)),
                ('quantity', models.IntegerField()),
                ('batch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_prepositioned', models.BooleanField(default=False)),
                ('preposition_qty', models.IntegerField(blank=True, null=True)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('purchase_order_item', models.CharField(blank=True, max_length=255, null=True)),
                ('unicef_ro_item', models.CharField(blank=True, max_length=30, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('other', models.JSONField(blank=True, null=True, verbose_name='Other Details')),
            ],
            options={
                'ordering': ('-id',),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('short_description', models.CharField(max_length=100)),
                ('original_uom', models.CharField(choices=[('BAG', 'BAG'), ('BOT', 'BOT'), ('BOX', 'BOX'), ('CAR', 'CAR'), ('DRM', 'DRM'), ('DZ', 'DZ'), ('EA', 'EA'), ('KG', 'KG'), ('L', 'L'), ('M', 'M'), ('PAA', 'PAA'), ('PAC', 'PAC'), ('RM', 'RM'), ('ROL', 'ROL'), ('SET', 'SET'), ('TBE', 'TBE'), ('TO', 'TO'), ('VL', 'VL')], max_length=30)),
                ('material_type', models.CharField(blank=True, max_length=100, null=True)),
                ('material_type_description', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.CharField(max_length=100)),
                ('group_description', models.CharField(max_length=100)),
                ('purchase_group', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_group_description', models.CharField(blank=True, max_length=100, null=True)),
                ('hazardous_goods', models.CharField(blank=True, max_length=100, null=True)),
                ('hazardous_goods_description', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature_conditions', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature_group', models.CharField(blank=True, max_length=100, null=True)),
                ('purchasing_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('p_code', models.CharField(blank=True, default='', max_length=32, verbose_name='P Code')),
                ('description', models.CharField(max_length=254, verbose_name='Description')),
                ('other', models.JSONField(blank=True, null=True, verbose_name='Other Details')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Point')),
                ('private', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_of_interest', to='locations.location', verbose_name='Parent Location')),
                ('partner_organizations', models.ManyToManyField(blank=True, related_name='points_of_interest', to='partners.PartnerOrganization')),
            ],
            options={
                'verbose_name': 'Point of Interest',
                'verbose_name_plural': 'Points of Interest',
            },
        ),
        migrations.CreateModel(
            name='PointOfInterestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=32, verbose_name='Poi Type Name')),
                ('category', models.CharField(max_length=32, verbose_name='Poi Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('unicef_release_order', models.CharField(max_length=30, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_type', models.CharField(blank=True, choices=[('DELIVERY', 'Delivery'), ('DISTRIBUTION', 'Distribution'), ('WASTAGE', 'Wastage')], max_length=30, null=True)),
                ('transfer_subtype', models.CharField(blank=True, choices=[('SHORT', 'Short'), ('SURPLUS', 'Surplus')], max_length=30, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30)),
                ('origin_check_out_at', models.DateTimeField(blank=True, null=True)),
                ('destination_check_in_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_shipment', models.BooleanField(default=False)),
                ('purchase_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('waybill_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pd_number', models.CharField(blank=True, max_length=255, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_checked_in', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_checked_out', to=settings.AUTH_USER_MODEL)),
                ('destination_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_transfers', to='last_mile.pointofinterest')),
                ('origin_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_transfers', to='last_mile.pointofinterest')),
                ('origin_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_transfers', to='last_mile.transfer')),
                ('partner_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partnerorganization')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='poi_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_of_interest', to='last_mile.pointofinteresttype', verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='PartnerMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(max_length=255)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_material', to='last_mile.material')),
                ('partner_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_material', to='partners.partnerorganization')),
            ],
            options={
                'unique_together': {('partner_organization', 'material')},
            },
        ),
        migrations.AddField(
            model_name='material',
            name='partner_materials',
            field=models.ManyToManyField(through='last_mile.PartnerMaterial', to='partners.PartnerOrganization'),
        ),
        migrations.CreateModel(
            name='ItemTransferHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='last_mile.item')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='last_mile.transfer')),
            ],
            options={
                'unique_together': {('transfer', 'item')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='last_mile.material'),
        ),
        migrations.AddField(
            model_name='item',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='last_mile.transfer'),
        ),
        migrations.AddField(
            model_name='item',
            name='transfers_history',
            field=models.ManyToManyField(through='last_mile.ItemTransferHistory', to='last_mile.Transfer'),
        ),
    ]
