# Generated by Django 3.2.19 on 2024-02-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinteresttype',
            name='category',
            field=models.CharField(default=1, max_length=32, verbose_name='Poi Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('distribution', 'Distribution'), ('wastage', 'Wastage'), ('waybill', 'Waybill'), ('delivery', 'Delivery')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pointofinteresttype',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Poi Type Name'),
        ),
    ]
