# Generated by Django 3.2.19 on 2024-04-26 11:57

from django.db import migrations, models
import etools.applications.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='other',
            field=models.JSONField(blank=True, null=True, validators=[etools.applications.core.validators.JSONSchemaValidator(json_schema={'additionalProperties': True, 'properties': {'uom_map': {'additionalProperties': {'type': 'number'}, 'propertyNames': {'enum': ['BAG', 'BOT', 'BOX', 'CAR', 'DRM', 'DZ', 'EA', 'KG', 'L', 'M', 'PAA', 'PAC', 'RM', 'ROL', 'SET', 'TBE', 'TO', 'VL']}, 'type': 'object'}}, 'title': "Json schema for item 'other' field", 'type': 'object'})], verbose_name='Other Details'),
        ),
        migrations.AlterField(
            model_name='item',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
