# Generated by Django 3.2.19 on 2024-04-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='other',
            field=models.JSONField(blank=True, null=True, verbose_name='Other Details'),
        ),
        migrations.AlterField(
            model_name='item',
            name='conversion_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='uom',
            field=models.CharField(blank=True, choices=[('BAG', 'BAG'), ('BOT', 'BOT'), ('BOX', 'BOX'), ('CAR', 'CAR'), ('DRM', 'DRM'), ('DZ', 'DZ'), ('EA', 'EA'), ('KG', 'KG'), ('L', 'L'), ('M', 'M'), ('PAA', 'PAA'), ('PAC', 'PAC'), ('RM', 'RM'), ('ROL', 'ROL'), ('SET', 'SET'), ('TBE', 'TBE'), ('TO', 'TO'), ('VL', 'VL')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='wastage_type',
            field=models.CharField(blank=True, choices=[('DAMAGED', 'Damaged'), ('STOLEN', 'Stolen'), ('EXPIRED', 'Expired'), ('LOST', 'Lost')], max_length=30, null=True),
        ),
    ]
