# Generated by Django 3.2.19 on 2024-02-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='material',
        ),
    ]
