# Generated by Django 4.2.3 on 2024-10-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='wastage_type',
            field=models.CharField(choices=[('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('LOST', 'Lost')], max_length=30, null=True),
        ),
    ]
