# Generated by Django 3.2.19 on 2024-02-07 13:54

from django.db import migrations, models
import etools.applications.last_mile.models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0002_remove_item_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='filepath',
        ),
        migrations.AddField(
            model_name='transfer',
            name='proof_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=etools.applications.last_mile.models.get_transfers_path, verbose_name='Proof File'),
        ),
    ]
