# Generated by Django 3.2.19 on 2024-02-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0121_auto_20230814_1058'),
        ('last_mile', '0002_auto_20240216_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='partner_organization',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='partner_organizations',
            field=models.ManyToManyField(blank=True, related_name='points_of_interest', to='partners.PartnerOrganization'),
        ),
    ]
