# Generated by Django 3.2.19 on 2024-02-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0003_auto_20240216_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='shipment_type',
            field=models.CharField(choices=[('release_order', 'Release Order'), ('direct_handover', 'Direct Handover')], max_length=30, null=True),
        ),
    ]
