# Generated by Django 3.2.19 on 2024-02-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0004_transfer_shipment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='alternative_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='shipment_type',
            field=models.CharField(choices=[('RELEASE_ORDER', 'Release Order'), ('DIRECT_HANDOVER', 'Direct Handover')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('INCOMING', 'Incoming'), ('CHECKED_IN', 'Checked-In'), ('CHECKED_OUT', 'Checked-Out'), ('COMPLETED', 'Completed')], default='INCOMING', max_length=30),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('DISTRIBUTION', 'Distribution'), ('WASTAGE', 'Wastage'), ('WAYBILL', 'Waybill'), ('WAYBILL', 'Delivery')], max_length=30, null=True),
        ),
    ]
