# Generated by Django 4.2.3 on 2024-11-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0004_alter_transfer_transfer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='dispense_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
