# Generated by Django 4.2.3 on 2025-01-30 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0005_transfer_dispense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='system_destination_check_in_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transfer',
            name='system_origin_check_out_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
