# Generated by Django 3.2.19 on 2024-06-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0005_transferevidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('DELIVERY', 'Delivery'), ('DISTRIBUTION', 'Distribution'), ('HANDOVER', 'Handover'), ('WASTAGE', 'Wastage')], max_length=30, null=True),
        ),
    ]
