# Generated by Django 3.2.19 on 2024-02-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0005_auto_20240219_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='origin_check_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='shipment_type',
            field=models.CharField(blank=True, choices=[('RELEASE_ORDER', 'Release Order'), ('DIRECT_HANDOVER', 'Direct Handover')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('DISTRIBUTION', 'Distribution'), ('WASTAGE', 'Wastage'), ('WAYBILL', 'Waybill'), ('DELIVERY', 'Delivery')], max_length=30, null=True),
        ),
    ]
