# Generated by Django 4.2.3 on 2025-02-10 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_interventionreview_authorized_officer_and_more'),
        ('last_mile', '0006_transfer_system_destination_check_in_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='origin_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_items', to='last_mile.transfer'),
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('origin_transfer_id', models.IntegerField(unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('destination_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_history_destination_partner', to='partners.partnerorganization')),
                ('destination_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_history_destination_point', to='last_mile.pointofinterest')),
                ('from_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_history_from_partner', to='partners.partnerorganization')),
                ('origin_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_history_origin_point', to='last_mile.pointofinterest')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='last_mile.transferhistory'),
        ),
    ]
