# Generated by Django 3.2.19 on 2024-02-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0006_auto_20240220_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='unit',
            new_name='uom',
        ),
    ]
