# Generated by Django 3.2.19 on 2024-02-21 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0007_rename_unit_item_uom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AddField(
            model_name='item',
            name='shipment_item_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='is_shipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_prepositioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='ItemTransferHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='last_mile.item')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='last_mile.transfer')),
            ],
            options={
                'unique_together': {('transfer', 'item')},
            },
        ),
    ]
