# Generated by Django 4.2.3 on 2025-03-18 14:30

from django.db import migrations, models
import django.db.models.deletion

def copy_origin_transfer(apps, schema_editor):
    TransferHistory = apps.get_model('last_mile', 'TransferHistory')
    for obj in TransferHistory.objects.all():
        obj.origin_transfer_id = obj.origin_transfer_id_temp  
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0007_transferhistory_item_origin_transfer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPanelPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'admin_panel_dummy',
                'permissions': (('lmsm_admin_panel_manage_users', 'Can manage users in the admin panel'), ('lmsm_admin_panel_manage_locations', 'Can manage locations in the admin panel'), ('lmsm_admin_panel_manage_users_locations', 'Can manage users locations in the admin panel'), ('lmsm_admin_panel_manage_email_alerts', 'Can manage email alerts in the admin panel'), ('lmsm_admin_panel_manage_stock_management', 'Can manage stock management in the admin panel'), ('lmsm_admin_panel_manage_transfer_history', 'Can manage transfer history in the admin panel')),
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='transferhistory',
            old_name='origin_transfer_id',
            new_name='origin_transfer_id_temp',
        ),
        migrations.AddField(
            model_name='transferhistory',
            name='origin_transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='last_mile.transfer', verbose_name='Origin Transfer'),
        ),
        migrations.RunPython(copy_origin_transfer, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='transferhistory',
            name='origin_transfer_id_temp',
        ),
    ]
