# Generated by Django 3.2.19 on 2024-02-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0008_auto_20240221_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='shipment_type',
        ),
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='last_mile.item', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('DELIVERY', 'Delivery'), ('DISTRIBUTION', 'Distribution'), ('WASTAGE', 'Wastage'), ('WAYBILL', 'Waybill')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='ItemTransferHistory',
        ),
    ]
