# Generated by Django 3.2.19 on 2024-02-22 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0009_auto_20240222_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='sequence_number',
        ),
        migrations.CreateModel(
            name='ItemTransferHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='last_mile.item')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='last_mile.transfer')),
            ],
            options={
                'unique_together': {('transfer', 'item')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='transfers_history',
            field=models.ManyToManyField(through='last_mile.ItemTransferHistory', to='last_mile.Transfer'),
        ),
    ]
