# Generated by Django 4.2.3 on 2025-06-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0009_alter_adminpanelpermission_options_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnermaterial',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='mapped_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='base_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='initial_items',
            field=models.JSONField(blank=True, null=True, verbose_name='Initial Items'),
        ),
    ]
