# Generated by Django 4.2.3 on 2025-06-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0009_alter_adminpanelpermission_options_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='base_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transfer',
            name='initial_items',
            field=models.JSONField(blank=True, db_index=True, null=True, verbose_name='Initial Items'),
        ),
    ]
