# Generated by Django 3.2.19 on 2024-02-29 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0010_auto_20240222_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='origin_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_transfers', to='last_mile.transfer'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('DELIVERY', 'Delivery'), ('DISTRIBUTION', 'Distribution'), ('Loss', 'Loss'), ('WAYBILL', 'Waybill')], max_length=30, null=True),
        ),
    ]
