# Generated by Django 4.2.3 on 2025-09-19 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('last_mile', '0012_squash_dispense_unicef_release_poi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('item_id', models.PositiveIntegerField(verbose_name='Item ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('SOFT_DELETE', 'Soft Deleted')], max_length=20, verbose_name='Action')),
                ('changed_fields', models.JSONField(blank=True, help_text='List of field names that were changed', null=True, verbose_name='Changed Fields')),
                ('old_values', models.JSONField(blank=True, help_text='Previous values of tracked fields', null=True, verbose_name='Previous Values')),
                ('new_values', models.JSONField(blank=True, help_text='New values of tracked fields', null=True, verbose_name='New Values')),
                ('transfer_info', models.JSONField(blank=True, help_text='Transfer details at the time of audit', null=True, verbose_name='Transfer Information')),
                ('material_info', models.JSONField(blank=True, help_text='Material details at the time of audit', null=True, verbose_name='Material Information')),
                ('critical_changes', models.JSONField(blank=True, help_text='Important changes like transfer or material changes', null=True, verbose_name='Critical Changes')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Item Audit Log',
                'verbose_name_plural': 'Item Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['item_id', '-timestamp'], name='last_mile_i_item_id_364fe2_idx'), models.Index(fields=['action', '-timestamp'], name='last_mile_i_action_f79b57_idx'), models.Index(fields=['user', '-timestamp'], name='last_mile_i_user_id_b3e679_idx')],
            },
        ),
    ]
