# Generated by Django 4.2.3 on 2025-08-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0012_alter_transfer_unicef_release_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='base_uom',
            field=models.CharField(choices=[('BAG', 'BAG'), ('BOT', 'BOT'), ('BOX', 'BOX'), ('CAR', 'CAR'), ('DRM', 'DRM'), ('DZ', 'DZ'), ('EA', 'EA'), ('KG', 'KG'), ('L', 'L'), ('M', 'M'), ('PAA', 'PAA'), ('PAC', 'PAC'), ('RM', 'RM'), ('ROL', 'ROL'), ('SET', 'SET'), ('TBE', 'TBE'), ('TO', 'TO'), ('VL', 'VL')], max_length=30, null=True),
        ),
    ]
