# Generated by Django 4.2.3 on 2025-06-04 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('last_mile', '0013_item_base_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_points_of_interest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_points_of_interest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Optional notes from the reviewer regarding approval or rejection.', null=True, verbose_name='Review Notes'),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='The current approval status of this location.', max_length=10, verbose_name='Approval Status'),
        ),
        migrations.CreateModel(
            name='UserPointsOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('point_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='last_mile.pointofinterest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_interest', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Point of Interest',
                'verbose_name_plural': 'User Points of Interest',
                'unique_together': {('user', 'point_of_interest')},
            },
        ),
    ]
