# Generated by Django 3.2.19 on 2024-04-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0014_auto_20240403_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='number',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
