# Generated by Django 3.2.19 on 2024-04-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0016_rename_e_tools_reference_transfer_pd_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='consignee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
