# Generated by Django 3.2.19 on 2024-04-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0017_transfer_consignee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='shipment_item_id',
            new_name='purchase_order_item',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='basic_description',
            new_name='purchasing_text',
        ),
        migrations.RemoveField(
            model_name='material',
            name='other',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='consignee',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='delivery_id',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='delivery_item_id',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='purchase_order_item',
        ),
        migrations.AddField(
            model_name='item',
            name='unicef_ro_item',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='group',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='hazardous_goods',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='hazardous_goods_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='material_type_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='temperature_conditions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='unicef_release_order',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='group_description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='original_uom',
            field=models.CharField(choices=[('BAG', 'BAG'), ('BOT', 'BOT'), ('BOX', 'BOX'), ('CAR', 'CAR'), ('DRM', 'DRM'), ('DZ', 'DZ'), ('EA', 'EA'), ('KG', 'KG'), ('L', 'L'), ('M', 'M'), ('PAA', 'PAA'), ('PAC', 'PAC'), ('RM', 'RM'), ('ROL', 'ROL'), ('SET', 'SET'), ('TBE', 'TBE'), ('TO', 'TO'), ('VL', 'VL')], max_length=30),
        ),
        migrations.AlterField(
            model_name='material',
            name='purchase_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='purchase_group_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='short_description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='temperature_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
