# Generated by Django 4.2.26 on 2026-01-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0017_pointofinteresttypemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='l_consignee_code',
            field=models.CharField(blank=True, db_index=True, help_text='L-Consignee code for identifying destination locations in transfers', max_length=255, null=True, verbose_name='L-Consignee Code'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='l_consignee_code',
            field=models.CharField(blank=True, help_text='L-Consignee code used to determine destination location for this transfer', max_length=255, null=True, verbose_name='L-Consignee Code'),
        ),
    ]
