# Generated by Django 3.2.19 on 2024-04-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0018_auto_20240404_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wastage_type',
            field=models.CharField(choices=[('DAMAGED', 'Damaged'), ('STOLEN', 'Stolen'), ('EXPIRED', 'Expired'), ('LOST', 'Lost')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_subtype',
            field=models.CharField(blank=True, choices=[('SHORT', 'Short'), ('SURPLUS', 'Surplus')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('DELIVERY', 'Delivery'), ('DISTRIBUTION', 'Distribution'), ('WASTAGE', 'Wastage')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='unicef_release_order',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
