# Generated by Django 3.2.19 on 2024-04-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0019_auto_20240405_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='uom',
            field=models.CharField(choices=[('BAG', 'BAG'), ('BOT', 'BOT'), ('BOX', 'BOX'), ('CAR', 'CAR'), ('DRM', 'DRM'), ('DZ', 'DZ'), ('EA', 'EA'), ('KG', 'KG'), ('L', 'L'), ('M', 'M'), ('PAA', 'PAA'), ('PAC', 'PAC'), ('RM', 'RM'), ('ROL', 'ROL'), ('SET', 'SET'), ('TBE', 'TBE'), ('TO', 'TO'), ('VL', 'VL')], max_length=30, null=True),
        ),
    ]
