# Generated by Django 4.2.26 on 2026-02-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0019_pointofinteresttype_type_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
