# Generated by Django 4.2.26 on 2026-02-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0020_transfer_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('DELIVERY', 'Delivery'), ('DISTRIBUTION', 'Distribution'), ('HANDOVER', 'Handover'), ('WASTAGE', 'Wastage'), ('DISPENSE', 'Dispense'), ('UNICEF_HANDOVER', 'UNICEF Handover')], max_length=30, null=True),
        ),
    ]
