# Generated by Django 3.2.19 on 2024-04-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0021_alter_pointofinterest_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='item',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
