# Generated by Django 4.2.26 on 2026-02-27 11:09

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0019_pointofinteresttype_type_role_and_more_squashed_0021_alter_transfer_transfer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferIngestAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('release_order', models.CharField(max_length=255)),
                ('consignee_code', models.CharField(max_length=255)),
                ('vendor_number', models.CharField(max_length=255)),
                ('alert_type', models.CharField(choices=[('consignee_code_not_found', 'Consignee Code does not exist'), ('partner_not_linked', 'Partner not linked to destination')], max_length=50)),
                ('reason', models.CharField(max_length=512)),
                ('country_name', models.CharField(max_length=255)),
                ('notified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
