# Generated by Django 4.2.26 on 2026-02-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0021_alter_transfer_transfer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferIngestAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_order', models.CharField(max_length=255)),
                ('consignee_code', models.CharField(max_length=255)),
                ('vendor_number', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=512)),
                ('country_name', models.CharField(max_length=255)),
                ('notified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
