# Generated by Django 4.2.26

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import connection, migrations, models


SEED_DATA = {
    'PHARMACY':              {'label': 'pharmacy',             'applicability': [1],    'order': 10, 'is_active': True},
    'MOBILE_OTP':            {'label': 'mobile_otp',           'applicability': [1],    'order': 20, 'is_active': True},
    'DISPENSING_UNIT':       {'label': 'dispensing_unite',      'applicability': [1, 2], 'order': 30, 'is_active': True},
    'HOUSEHOLD_MOBILE_TEAM': {'label': 'householdMobileTeam',  'applicability': [2],    'order': 40, 'is_active': True},
    'OTHER':                 {'label': 'other',                 'applicability': [1, 2], 'order': 100, 'is_active': False},
}


def seed_and_migrate_dispensing_types(apps, schema_editor):
    DispensingPointType = apps.get_model('last_mile', 'DispensingPointType')
    Transfer = apps.get_model('last_mile', 'Transfer')

    created_types = {}
    for name, attrs in SEED_DATA.items():
        obj, _ = DispensingPointType.objects.get_or_create(
            name=name,
            defaults={'label': attrs['label'], 'applicability': attrs['applicability'], 'order': attrs['order'], 'is_active': attrs['is_active']}
        )
        created_types[name] = obj

    for old_value, type_obj in created_types.items():
        Transfer.objects.filter(dispense_type=old_value).update(dispense_type_new=type_obj)

    Country = apps.get_model('users', 'Country')
    try:
        country = Country.objects.get(schema_name=connection.schema_name)
    except Country.DoesNotExist:
        return

    if country.country_short_code == 'MOZ':
        DispensingPointType.objects.get_or_create(
            name='COMMUNITY_HEALTH_WORKER',
            defaults={'label': 'communityHealthWorker', 'applicability': [1, 2], 'order': 90}
        )


def reverse_migration(apps, schema_editor):
    DispensingPointType = apps.get_model('last_mile', 'DispensingPointType')
    Transfer = apps.get_model('last_mile', 'Transfer')
    
    for type_obj in DispensingPointType.objects.all():
        Transfer.objects.filter(dispense_type_new=type_obj).update(dispense_type=type_obj.name)


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0022_transferingestalert'),
        ('users', '0001_initial'),
    ]

    operations = [
        # 1. Create DispensingPointType model
        migrations.CreateModel(
            name='DispensingPointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text="Machine identifier sent to/from FE, e.g. 'PHARMACY'", max_length=64, unique=True, verbose_name='Dispensing Point Type Name')),
                ('label', models.CharField(help_text="SimpleLocalize translation key, e.g. 'pharmacy'", max_length=64, verbose_name='Translation Key')),
                ('applicability', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, help_text='1 = batched items, 2 = non-batched. E.g. [1,2] means both.', size=None, verbose_name='Applicability')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order. Lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Dispensing Point Type',
                'verbose_name_plural': 'Dispensing Point Types',
                'ordering': ['order', 'name'],
            },
        ),
        # 2. Add temporary FK field alongside existing CharField
        migrations.AddField(
            model_name='transfer',
            name='dispense_type_new',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='last_mile.dispensingpointtype',
                verbose_name='Dispensing Point Type',
            ),
        ),
        # 3. Seed types, migrate data, add Mozambique type
        migrations.RunPython(
            seed_and_migrate_dispensing_types,
            reverse_migration,
        ),
        # 4. Remove old CharField, rename FK, set final related_name
        migrations.RemoveField(
            model_name='transfer',
            name='dispense_type',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='dispense_type_new',
            new_name='dispense_type',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='dispense_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='transfers',
                to='last_mile.dispensingpointtype',
                verbose_name='Dispensing Point Type',
            ),
        ),
    ]
