# Generated by Django 3.2.19 on 2024-04-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('last_mile', '0023_auto_20240411_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'base_manager_name': 'objects', 'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ('-id',)},
        ),
    ]
