# Generated by Django 3.2.19 on 2023-10-20 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('partners', '0001_initial'),
        ('field_monitoring_settings', '0003_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prcofficerinterventionreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prc_reviews', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='plannedengagement',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planned_engagement', to='partners.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='partnerplannedvisits',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_visits', to='partners.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='lead_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.office', verbose_name='Lead Office'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='lead_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.section', verbose_name='Lead Section'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='interventionsupplyitem',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_items', to='partners.intervention', verbose_name='Intervention'),
        ),
        migrations.AddField(
            model_name='interventionsupplyitem',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.interventionresultlink', verbose_name='Result'),
        ),
        migrations.AddField(
            model_name='interventionrisk',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='partners.intervention', verbose_name='Intervention'),
        ),
        migrations.AddField(
            model_name='interventionreviewnotification',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prc_notifications', to='partners.interventionreview'),
        ),
        migrations.AddField(
            model_name='interventionreviewnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prc_notifications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='amendment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='partners.interventionamendment', verbose_name='Amendment'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='partners.intervention', verbose_name='Intervention'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='overall_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Overall Approver'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='prc_officers',
            field=models.ManyToManyField(blank=True, related_name='_partners_interventionreview_prc_officers_+', to=settings.AUTH_USER_MODEL, verbose_name='PRC Officers'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='PRC Submitted By'),
        ),
        migrations.AddField(
            model_name='interventionresultlink',
            name='cp_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervention_links', to='reports.result', verbose_name='CP Output'),
        ),
        migrations.AddField(
            model_name='interventionresultlink',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_links', to='partners.intervention', verbose_name='Intervention'),
        ),
        migrations.AddField(
            model_name='interventionresultlink',
            name='ram_indicators',
            field=models.ManyToManyField(blank=True, to='reports.Indicator', verbose_name='RAM Indicators'),
        ),
        migrations.AddField(
            model_name='interventionreportingperiod',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='partners.intervention', verbose_name='Intervention'),
        ),
        migrations.AddField(
            model_name='interventionplannedvisitsite',
            name='planned_visits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.interventionplannedvisits'),
        ),
        migrations.AddField(
            model_name='interventionplannedvisitsite',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_settings.locationsite'),
        ),
        migrations.AddField(
            model_name='interventionplannedvisits',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_visits', to='partners.intervention', verbose_name='Intervention'),
        ),
        migrations.AddField(
            model_name='interventionplannedvisits',
            name='sites',
            field=models.ManyToManyField(blank=True, through='partners.InterventionPlannedVisitSite', to='field_monitoring_settings.LocationSite', verbose_name='Sites'),
        ),
        migrations.AddField(
            model_name='interventionmanagementbudgetitem',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='partners.interventionmanagementbudget', verbose_name='Budget'),
        ),
        migrations.AddField(
            model_name='interventionmanagementbudget',
            name='intervention',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management_budgets', to='partners.intervention', verbose_name='Intervention'),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='intervention',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_budget', to='partners.intervention', verbose_name='Intervention'),
        ),
        migrations.AddField(
            model_name='interventionattachment',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='partners.intervention', verbose_name='Intervention'),
        ),
        migrations.AddField(
            model_name='interventionattachment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.filetype', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='amended_intervention',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendment', to='partners.intervention', verbose_name='Amended Intervention'),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='partners.intervention', verbose_name='Reference Number'),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='partner_authorized_officer_signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Signed by Partner'),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='unicef_signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='++', to=settings.AUTH_USER_MODEL, verbose_name='Signed by UNICEF'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='partners.agreement', verbose_name='Agreement'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='budget_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_owner+', to=settings.AUTH_USER_MODEL, verbose_name='Budget Owner'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='country_programme',
            field=models.ForeignKey(blank=True, help_text='Which Country Programme does this Intervention belong to?', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reports.countryprogramme', verbose_name='Country Programme'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='country_programmes',
            field=models.ManyToManyField(blank=True, help_text='Which Country Programme does this Intervention belong to?', related_name='interventions', to='reports.CountryProgramme', verbose_name='Country Programmes'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='flat_locations',
            field=models.ManyToManyField(blank=True, related_name='intervention_flat_locations', to='locations.Location', verbose_name='Locations'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='office_interventions', to='reports.Office', verbose_name='Office'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='partner_authorized_officer_signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_interventions', to=settings.AUTH_USER_MODEL, verbose_name='Signed by Partner'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='partner_focal_points',
            field=models.ManyToManyField(blank=True, related_name='_partners_intervention_partner_focal_points_+', to=settings.AUTH_USER_MODEL, verbose_name='CSO Authorized Officials'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='interventions', to='reports.Section', verbose_name='Sections'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='interventions', to='field_monitoring_settings.LocationSite', verbose_name='Sites'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='unicef_focal_points',
            field=models.ManyToManyField(blank=True, related_name='_partners_intervention_unicef_focal_points_+', to=settings.AUTH_USER_MODEL, verbose_name='UNICEF Focal Points'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='unicef_signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_interventions+', to=settings.AUTH_USER_MODEL, verbose_name='Signed by UNICEF'),
        ),
        migrations.AddField(
            model_name='corevaluesassessment',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_values_assessments', to='partners.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='approving_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Approving Officer'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='partners.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='requesting_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Requesting Officer'),
        ),
        migrations.AddField(
            model_name='agreementamendment',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='partners.agreement', verbose_name='Agreement'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='authorized_officers',
            field=models.ManyToManyField(blank=True, related_name='agreement_authorizations', to=settings.AUTH_USER_MODEL, verbose_name='Partner Authorized Officer'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='country_programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='reports.countryprogramme', verbose_name='Country Programme'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='partners.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='partner_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements_signed', to=settings.AUTH_USER_MODEL, verbose_name='Signed by partner'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements_signed+', to=settings.AUTH_USER_MODEL, verbose_name='Signed By UNICEF'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='terms_acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements_acknowledged+', to=settings.AUTH_USER_MODEL, verbose_name='Terms Acknowledged By'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerplannedvisits',
            unique_together={('partner', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='interventionresultlink',
            unique_together={('intervention', 'cp_output')},
        ),
        migrations.AlterUniqueTogether(
            name='interventionplannedvisitsite',
            unique_together={('planned_visits', 'site', 'quarter')},
        ),
        migrations.AlterUniqueTogether(
            name='interventionplannedvisits',
            unique_together={('intervention', 'year')},
        ),
    ]
