# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20180326_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directcashtransfer',
            name='amount_3_to_6_months_usd',
            field=models.DecimalField(decimal_places=2, max_digits=20,
                                      verbose_name='Amount between 3 and 6 months (USD)'),
        ),
        migrations.AlterField(
            model_name='directcashtransfer',
            name='amount_6_to_9_months_usd',
            field=models.DecimalField(decimal_places=2, max_digits=20,
                                      verbose_name='Amount between 6 and 9 months (USD)'),
        ),
        migrations.AlterField(
            model_name='directcashtransfer',
            name='amount_less_than_3_Months_usd',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount mess than 3 months (USD)'),
        ),
        migrations.AlterField(
            model_name='directcashtransfer',
            name='amount_more_than_9_Months_usd',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount more than 9 months (USD)'),
        ),
        migrations.AlterField(
            model_name='directcashtransfer',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount (USD)'),
        ),
        migrations.AlterField(
            model_name='directcashtransfer',
            name='liquidation_usd',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Liquidation (USD)'),
        ),
        migrations.AlterField(
            model_name='directcashtransfer',
            name='outstanding_balance_usd',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Outstanding Balance (USD)'),
        ),
        migrations.AlterField(
            model_name='fundingcommitment',
            name='agreement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20,
                                      null=True, verbose_name='Agreement Amount'),
        ),
        migrations.AlterField(
            model_name='fundingcommitment',
            name='commitment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20,
                                      null=True, verbose_name='Commitment Amount'),
        ),
        migrations.AlterField(
            model_name='fundingcommitment',
            name='expenditure_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20,
                                      null=True, verbose_name='Expenditure Amount'),
        ),
        migrations.AlterField(
            model_name='fundingcommitment',
            name='fr_item_amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20,
                                      null=True, verbose_name='Item Amount (USD)'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='net_ct_cy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net Cash Transferred per Current Year',
                                      max_digits=20, null=True, verbose_name='Net Cash Transferred'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='reported_cy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Liquidations 1 Oct - 30 Sep',
                                      max_digits=20, null=True, verbose_name='Liquidation'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='total_ct_cp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Cash Transferred for Country Programme',
                                      max_digits=20, null=True, verbose_name='Total Cash Transferred for Country Programme'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='total_ct_cy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Cash Transferred per Current Year',
                                      max_digits=20, null=True, verbose_name='Total Cash Transferred per Current Year'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='total_ct_ytd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cash Transfers Jan - Dec',
                                      max_digits=20, null=True, verbose_name='Cash Transfer Jan - Dec'),
        ),
    ]
