# Generated by Django 4.2.3 on 2024-09-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_intervention_partner_focal_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionattachment',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_attachments', to='partners.intervention', verbose_name='Intervention'),
        ),
    ]
