# Generated by Django 4.2.3 on 2024-09-23 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0003_alter_intervention_partner_focal_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionreview',
            name='authorized_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Authorized Officer'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='is_recommended_for_approval',
            field=models.BooleanField(default=False, verbose_name='Recommend for Approval'),
        ),
    ]
