# Generated by Django 4.2.3 on 2024-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_interventionreview_authorized_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agreement_type',
            field=models.CharField(choices=[('PCA', 'Programme Cooperation Agreement'), ('SSFA', 'Small Scale Funding Agreement'), ('MOU', 'Memorandum of Understanding'), ('GTC', 'General Terms and Conditions')], max_length=10, verbose_name='Agreement Type'),
        ),
    ]
