# Generated by Django 4.2.3 on 2024-10-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_alter_interventionattachment_intervention'),
        ('partners', '0004_interventionreview_authorized_officer_and_more'),
    ]

    operations = [
    ]
