# Generated by Django 4.2.26 on 2026-01-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_add_accountability_to_affected_populations'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='partner_selection_modality',
            field=models.CharField(blank=True, choices=[('open', 'Open selection'), ('direct', 'Direct selection')], help_text='Select how the partner was selected in UNPP (Open selection or Direct selection).', max_length=16, null=True, verbose_name='Partner Selection Modality'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='cfei_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='UNPP Number'),
        ),
    ]
