# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-09 14:26
from __future__ import unicode_literals

import json

from django.db import migrations
from django.db.models import Q

from etools.applications.hact.models import HactEncoder


def update_hact_values_for_non_active_partners(apps, schema_editor):

    PartnerOrganization = apps.get_model('partners', 'PartnerOrganization')

    for partner in PartnerOrganization.objects.exclude(Q(reported_cy__gt=0) | Q(total_ct_cy__gt=0)):
        hact = json.loads(partner.hact_values) if isinstance(partner.hact_values, str) else partner.hact_values
        hact['assurance_coverage'] = partner.assurance_coverage
        partner.hact_values = json.dumps(hact, cls=HactEncoder)
        partner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20180424_1916'),
    ]

    operations = [
        migrations.RunPython(update_hact_values_for_non_active_partners),
    ]
