# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-10 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20180424_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerorganization',
            name='rating',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Significant', 'Significant'), ('Medium', 'Medium'), (
                'Low', 'Low'), ('Non Required', 'Non Required')], max_length=50, null=True, verbose_name='Risk Rating'),
        ),
    ]
