# Generated by Django 1.10.8 on 2018-05-10 19:40
from django.db import migrations


def update_partners_rating(apps, schema_editor):
    PartnerOrganization = apps.get_model("partners", "PartnerOrganization")
    PartnerOrganization.objects.filter(rating='Moderate').update(rating='Medium')
    PartnerOrganization.objects.filter(rating='Non-Assessed').update(rating='Not Required')


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_auto_20180510_1905'),
    ]

    operations = [
        migrations.RunPython(
            update_partners_rating,
            reverse_code=migrations.RunPython.noop,
        )
    ]
