# Generated by Django 1.10.8 on 2018-06-11 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_partnerorganization_manually_blocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plannedengagement',
            old_name='spot_check_follow_up_q1',
            new_name='spot_check_planned_q1',
        ),
        migrations.RenameField(
            model_name='plannedengagement',
            old_name='spot_check_follow_up_q2',
            new_name='spot_check_planned_q2',
        ),
        migrations.RenameField(
            model_name='plannedengagement',
            old_name='spot_check_follow_up_q3',
            new_name='spot_check_planned_q3',
        ),
        migrations.RenameField(
            model_name='plannedengagement',
            old_name='spot_check_follow_up_q4',
            new_name='spot_check_planned_q4',
        ),
        migrations.RemoveField(
            model_name='plannedengagement',
            name='spot_check_mr',
        ),
        migrations.AddField(
            model_name='plannedengagement',
            name='spot_check_follow_up',
            field=models.IntegerField(default=0, verbose_name='Spot Check Follow Up Required'),
        ),
    ]
