# Generated by Django 1.10.8 on 2018-07-17 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0015_ref_number_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='special_conditions_pca',
            field=models.BooleanField(default=False, verbose_name='Special Conditions PCA'),
        ),
    ]
