# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-18 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0016_auto_20180717_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='signed_by_unicef',
            field=models.BooleanField(default=False, verbose_name='Signed By UNICEF Authorized Officer'),
        ),
    ]
