# Generated by Django 1.10.8 on 2018-07-19 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_intervention_signed_by_unicef'),
    ]

    operations = [
    ]
