# Generated by Django 1.10.8 on 2018-08-10 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0021_auto_20180801_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='signed_by_unicef',
        ),
    ]
