# Generated by Django 1.10.8 on 2018-08-14 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0023_auto_20180814_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerorganization',
            name='core_values_assessment',
        ),
    ]
