# Generated by Django 1.10.8 on 2018-08-15 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import etools.applications.partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0024_remove_partnerorganization_core_values_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='activation_letter',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=etools.applications.partners.models.get_intervention_file_path, verbose_name='Activation Document for Contingency PDs'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='termination_doc',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=etools.applications.partners.models.get_intervention_file_path, verbose_name='Termination document for PDs'),
        ),
    ]
