# Generated by Django 1.10.8 on 2018-09-14 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0026_save_interventions'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='outstanding_dct_amount_6_to_9_months_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Outstanding DCT 6/9 months', max_digits=20, null=True, verbose_name='Outstanding DCT 6/9 months'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='outstanding_dct_amount_more_than_9_months_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Outstanding DCT more than 9 months', max_digits=20, null=True, verbose_name='Outstanding DCT more than 9 months'),
        ),
    ]
