# Generated by Django 2.0.9 on 2019-03-01 10:29

from django.db import migrations


def update_document_type(apps, schema_editor):
    Intervention = apps.get_model("partners", "intervention")
    for intervention in Intervention.objects.filter(document_type="SHPD").all():
        intervention.document_type = "HPD",
        intervention.save()


def reset_document_type(apps, schema_editor):
    Intervention = apps.get_model("partners", "intervention")
    for intervention in Intervention.objects.filter(document_type="HPD").all():
        intervention.document_type = "SHPD",
        intervention.save()


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0031_auto_20190122_1412'),
    ]

    operations = [
        migrations.RunPython(
            update_document_type,
            reverse_code=reset_document_type,
        ),
    ]
