# Generated by Django 2.2 on 2019-04-04 08:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0034_auto_20190328_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionamendment',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('admin_error', 'Type 1: Administrative error (correction)'), ('budget_lte_20', 'Type 2: Budget <= 20%'), ('budget_gt_20', 'Type 3: Budget > 20%'), ('change', 'Type 4: Changes to planned results'), ('no_cost', 'Type 5: No cost extension'), ('other', 'Type 6: Other'), ('dates', 'Dates'), ('results', 'Results'), ('budget', 'Budget')], max_length=50, verbose_name='Types'), size=None),
        ),
    ]
