# Generated by Django 2.1.7 on 2019-04-18 18:32

from django.db import connection, migrations, ProgrammingError


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0035_auto_20190404_0858'),
    ]

    operations = [
    ]
