# Generated by Django 2.1.8 on 2019-05-02 14:07

from django.db import migrations


def remove_pd_pca_document_types(apps, schema_editor):
    """Remove PD/PCA document types, but need to convert those
    objects using them.

    'PD' document types converted to 'Signed PD/SSFA'
    'PCA' document types converted to 'Signed PCA'
    """
    AttachmentFileType = apps.get_model('unicef_attachments', 'filetype')
    Attachment = apps.get_model('unicef_attachments', 'attachment')

    mapping = [
        ("pd", "signed_pd/ssfa"),
        ("pca", "attached_agreement"),
    ]
    for from_filetype_name, to_filetype_name in mapping:
        try:
            from_filetype = AttachmentFileType.objects.filter(
                name=from_filetype_name
            )
            to_filetype = AttachmentFileType.objects.get(name=to_filetype_name)
            for attachment in Attachment.objects.filter(file_type__in=from_filetype):
                attachment.filetype = to_filetype
                attachment.save()
            for filetype in from_filetype:
                filetype.delete()
        except AttachmentFileType.DoesNotExist:
            # schema may not have this file type so ignore
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0036_auto_20190418_1832'),
    ]

    operations = [
        migrations.RunPython(
            remove_pd_pca_document_types,
            migrations.RunPython.noop,
        )
    ]
