# Generated by Django 2.1.8 on 2019-05-02 14:07

from django.db import connection, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0036_auto_20190418_1832'),
    ]

    operations = [
    ]
