# Generated by Django 2.2.2 on 2019-06-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0037_auto_20190502_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetype',
            name='name',
            field=models.CharField(choices=[('FACE', 'FACE'), ('Progress Report', 'Progress Report'), ('Final Partnership Review', 'Final Partnership Review'), ('Correspondence', 'Correspondence'), ('Supply/Distribution Plan', 'Supply/Distribution Plan'), ('Other', 'Other')], max_length=64, unique=True, verbose_name='Name'),
        ),
    ]
