# Generated by Django 2.2.4 on 2019-10-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0038_auto_20190620_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='_intervention_offices_+', to='reports.Office', verbose_name='Office'),
        ),
    ]
