# Generated by Django 2.2.8 on 2019-12-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0040_auto_20191011_1429'),
    ]

    operations = [
    ]
