# Generated by Django 2.2.7 on 2020-07-01 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0043_auto_20200729_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='budget_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_owner+', to=settings.AUTH_USER_MODEL, verbose_name='Budget Owner'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='cash_transfer_modalities',
            field=models.CharField(choices=[('payment', 'Direct Payment'), ('reimburse', 'Reimbursement'), ('direct', 'Direct Cash Transfer')], default='direct', max_length=50, verbose_name='Cash Transfer Modalities'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='context',
            field=models.TextField(blank=True, verbose_name='Context'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='date_sent_to_partner',
            field=models.DateField(blank=True, null=True, verbose_name='Date first sent to Partner'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='equity_narrative',
            field=models.TextField(blank=True, verbose_name='Equity Narrative'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='equity_rating',
            field=models.CharField(choices=[('none', 'None'), ('marginal', 'Marginal'), ('significant', 'Significant'), ('principal', 'Principal')], default='none', max_length=50, verbose_name='Equity Rating'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='gender_narrative',
            field=models.TextField(blank=True, verbose_name='Gender Narrative'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='gender_rating',
            field=models.CharField(choices=[('none', 'None'), ('marginal', 'Marginal'), ('significant', 'Significant'), ('principal', 'Principal')], default='none', max_length=50, verbose_name='Gender Rating'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='hq_support_cost',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='HQ Support Cost'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='implementation_strategy',
            field=models.TextField(blank=True, verbose_name='Implementation Strategy'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='ip_program_contribution',
            field=models.TextField(blank=True, verbose_name='Partner Non-Financial Contribution to Programme'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='partner_accepted',
            field=models.BooleanField(default=False, verbose_name='Partner Accepted'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='sustainability_narrative',
            field=models.TextField(blank=True, verbose_name='Sustainability Narrative'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='sustainability_rating',
            field=models.CharField(choices=[('none', 'None'), ('marginal', 'Marginal'), ('significant', 'Significant'), ('principal', 'Principal')], default='none', max_length=50, verbose_name='Sustainability Rating'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='unicef_accepted',
            field=models.BooleanField(default=False, verbose_name='UNICEF Accepted'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='unicef_court',
            field=models.BooleanField(default=True, verbose_name='UNICEF Editing'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='unicef_review_type',
            field=models.CharField(choices=[('none', 'None'), ('prc', 'PRC'), ('non-prc', 'Non-PRC')], default='none', max_length=50, verbose_name='UNICEF Review Type'),
        ),
    ]
