# Generated by Django 2.2.7 on 2020-09-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0043_auto_20200729_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='cfei_number',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='UNPP Number'),
        )
    ]
