# Generated by Django 2.2.7 on 2020-09-24 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0044_auto_20200914_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerstaffmember',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_staff_member', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
