# Generated by Django 2.2.7 on 2020-10-01 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0046_auto_20200924_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerstaffmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='partner_staff_member', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
