# Generated by Django 2.2.7 on 2020-07-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0047_auto_20200716_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionresultlink',
            name='cp_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervention_links', to='reports.Result', verbose_name='CP Output'),
        ),
    ]
