# Generated by Django 2.2.7 on 2020-07-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0048_auto_20200722_1257'),
        ('partners', '0048_auto_20200724_0853'),
    ]

    operations = [
    ]
