# Generated by Django 2.2.20 on 2021-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0010_auto_20210614_0738'),
        ('partners', '0048_auto_20210506_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='hact_excluded_activities',
            field=models.ManyToManyField(blank=True, null=True, to='field_monitoring_planning.MonitoringActivity', verbose_name='Activities to not count as HACT'),
        ),
    ]
