# Generated by Django 3.2.6 on 2022-11-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0049_alter_interventionresultlink_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerorganization',
            name='cso_type',
            field=models.CharField(blank=True, choices=[('International', 'International'), ('National', 'National'), ('Community Based Organization', 'Community Based Organization'), ('Academic Institution', 'Academic Institution'), ('Red Cross/Red Crescent National Societies', 'Red Cross/Red Crescent National Societies')], max_length=50, null=True, verbose_name='CSO Type'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='highest_risk_rating_name',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Significant', 'Significant'), ('Medium', 'Medium'), ('Low', 'Low'), ('Not Required', 'Not Required'), ('Low Capacity (High Risk)', 'Low Capacity (High Risk)'), ('Medium Capacity (Moderate Risk)', 'Medium Capacity (Moderate Risk)'), ('Full Capacity (Low Risk)', 'Full Capacity (Low Risk)'), ('Low Capacity Assumed - Emergency', 'Low Capacity Assumed - Emergency'), ('No Contact with Beneficiaries', 'No Contact with Beneficiaries'), ('Not Assessed', 'Not Assessed')], default='', max_length=150, verbose_name='Highest Risk Rating Name'),
        ),
    ]
