# Generated by Django 2.2.7 on 2020-08-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0052_auto_20200810_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='cash_transfer_modalities',
            field=models.CharField(choices=[('payment', 'Direct Payment'), ('reimbursement', 'Reimbursement'), ('dct', 'Direct Cash Transfer')], default='dct', max_length=50, verbose_name='Cash Transfer Modalities'),
        ),
        migrations.AlterField(
            model_name='interventionmanagementbudget',
            name='act1_partner',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Partner contribution for In-country management and support staff prorated to their contribution to the programme (representation, planning, coordination, logistics, administration, finance)'),
        ),
        migrations.AlterField(
            model_name='interventionmanagementbudget',
            name='act1_unicef',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='UNICEF contribution for In-country management and support staff prorated to their contribution to the programme (representation, planning, coordination, logistics, administration, finance)'),
        ),
        migrations.AlterField(
            model_name='interventionmanagementbudget',
            name='act2_partner',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Partner contribution for Operational costs prorated to their contribution to the programme (office space, equipment, office supplies, maintenance)'),
        ),
        migrations.AlterField(
            model_name='interventionmanagementbudget',
            name='act2_unicef',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='UNICEF contribution for Operational costs prorated to their contribution to the programme (office space, equipment, office supplies, maintenance)'),
        ),
        migrations.AlterField(
            model_name='interventionmanagementbudget',
            name='act3_partner',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Partner contribution for Planning, monitoring, evaluation and communication, prorated to their contribution to the programme (venue, travels, etc.)'),
        ),
        migrations.AlterField(
            model_name='interventionmanagementbudget',
            name='act3_unicef',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='UNICEF contribution for Planning, monitoring, evaluation and communication, prorated to their contribution to the programme (venue, travels, etc.)'),
        ),
        migrations.AlterField(
            model_name='interventionrisk',
            name='risk_type',
            field=models.CharField(choices=[('environment', 'Social & Environmental'), ('financial', 'Financial'), ('operational', 'Operational'), ('organizational', 'Organizational'), ('political', 'Political'), ('strategic', 'Strategic'), ('security', 'Safety & security')], max_length=50, verbose_name='Risk Type'),
        ),
        migrations.AlterField(
            model_name='interventionsupplyitem',
            name='result',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='partners.InterventionResultLink', verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='interventionsupplyitem',
            name='unit_number',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='Unit Number'),
        ),
        migrations.AlterField(
            model_name='interventionsupplyitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Unit Price'),
        ),
    ]
