# Generated by Django 2.2.7 on 2020-08-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0053_auto_20200810_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionmanagementbudget',
            name='intervention',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management_budgets', to='partners.Intervention', verbose_name='Intervention'),
        ),
    ]
