# Generated by Django 2.2.7 on 2020-08-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0054_auto_20200811_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionbudget',
            name='programme_effectiveness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Programme Effectiveness (%)'),
        ),
    ]
