# Generated by Django 2.2.7 on 2020-08-20 15:24

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0055_interventionbudget_programme_effectiveness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=django_fsm.FSMField(blank=True, choices=[('draft', 'Development'), ('review', 'Review'), ('signature', 'Signature'), ('signed', 'Signed'), ('active', 'Active'), ('ended', 'Ended'), ('closed', 'Closed'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='draft', max_length=32, verbose_name='Status'),
        ),
    ]
