# Generated by Django 2.2.7 on 2020-09-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0056_auto_20200820_1524'),
        ('partners', '0057_intervention_cash_transfer_modalities'),
    ]

    operations = [
    ]
