# Generated by Django 2.2.7 on 2020-09-03 14:43

from django.db import migrations, models

DRAFT = 'draft'


def migrate_hpd(apps, schema_editor):
    Intervention = apps.get_model('partners', 'intervention')
    Intervention.objects.filter(
        document_type='HPD'
    ).update(
        document_type='SPD',
        humanitarian_flag=True
    )


def migrate_ssfa(apps, schema_editor):
    Intervention = apps.get_model('partners', 'intervention')

    Intervention.objects.filter(
        document_type='SSFA',
        status='draft',
    ).update(
        document_type='SPD',
        humanitarian_flag=True,
    )

    Intervention.objects.filter(
        document_type='SSFA',
        status__in=[
            'review',
            'signature',
            'signed',
            'active',
            'ended',
            'implemented',
            'suspended',
            'terminated',
        ]
    ).update(
        status='closed'
    )
# In order to avoid skipping active here and checking for extra issues on subsequent migrations
# run the following script on deploy.
# from etools.libraries.tenant_support.utils import run_on_all_tenants as rot
# import datetime
# today = datetime.datetime.now().date()
# def move_ssfas_to_active():
#     print(connection.tenant)
#     interventions = Intervention.objects.filter(
#         agreement__agreement_type="SSFA",
#         start__lte=today,
#         end__gte=today,
#         status=Intervention.CLOSED)
#     print(interventions.values_list("id", flat=True))
#     for i in interventions.all():
#         i.status = i.ACTIVE
#         i.save()
# rot(move_ssfas_to_active)


def revert_hpd(apps, schema_editor):
    Intervention = apps.get_model('partners', 'intervention')
    Intervention.objects.filter(document_type='SPD').update(document_type='HPD')


class Migration(migrations.Migration):
    dependencies = [
        ('partners', '0058_auto_20200902_1119'),
    ]

    operations = [
        migrations.RunPython(migrate_hpd, revert_hpd),
        migrations.RunPython(migrate_ssfa, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='intervention',
            name='document_type',
            field=models.CharField(choices=[('PD', 'Programme Document'), ('SPD', 'Humanitarian Programme Document'), ('SSFA', 'SSFA')], max_length=255, verbose_name='Document Type'),
        ),
    ]
