# Generated by Django 2.2.7 on 2020-09-22 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0060_auto_20200908_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionsupplyitem',
            name='result',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='partners.InterventionResultLink', verbose_name='Result'),
        ),
    ]
