# Generated by Django 2.2.7 on 2020-09-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0061_auto_20200914_0758'),
        ('partners', '0062_auto_20200921_1335'),
    ]

    operations = [
    ]
