# Generated by Django 2.2.7 on 2020-10-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0047_auto_20201001_1337'),
        ('partners', '0064_merge_20200923_1719'),
    ]

    operations = [
    ]
