# Generated by Django 2.2.7 on 2020-09-28 14:11

from django.db import migrations


def migrate_cash_transfer_modalities(apps, schema_editor):
    Intervention = apps.get_model('partners', 'Intervention')
    for intervention in Intervention.objects.all():
        new_value = []
        for i, transfer in enumerate(intervention.cash_transfer_modalities):
            transfer_new = {
                'payment': 'payment',
                'reimburse': 'reimbursement',
                'direct': 'dct'
            }.get(transfer, None)
            if transfer_new:
                new_value.append(transfer_new)

        intervention.cash_transfer_modalities = new_value


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0064_merge_20200923_1719'),
    ]

    operations = [
        migrations.RunPython(migrate_cash_transfer_modalities, migrations.RunPython.noop),
    ]
