# Generated by Django 2.2.7 on 2020-09-24 14:53

from django.conf import settings
from django.core.exceptions import FieldDoesNotExist
from django.db import migrations, models
import django.db.models.deletion


def migrate_staff_members_to_fk(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserProfile = apps.get_model('users', 'UserProfile')
    PartnerStaffMember = apps.get_model('partners', 'PartnerStaffMember')

    try:
        UserProfile._meta.get_field('_partner_staff_member')
    except FieldDoesNotExist:
        # this field was already removed; nothing to do here
        return

    for profile in UserProfile.objects.filter(_partner_staff_member__isnull=False):
        staff_member = PartnerStaffMember.objects.filter(
            models.Q(id=profile._partner_staff_member) | models.Q(email__iexact=profile.user.email)
        ).first()

        if staff_member:
            staff_member.user = profile.user
            staff_member.save()

    not_migrated_staff_members = PartnerStaffMember.objects.filter(user__isnull=True)
    if not not_migrated_staff_members.exists():
        return

    admin = User.objects.order_by('id').first()
    for staff_member in not_migrated_staff_members:
        print('Unable to user for {}; moving to {}'.format(staff_member, admin))
        staff_member.user = admin
        staff_member.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_auto_20200924_1453'),
        ('partners', '0065_partnerstaffmember_user'),
    ]

    operations = [
        migrations.RunPython(migrate_staff_members_to_fk, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='partnerstaffmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='partner_staff_member', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
