# Generated by Django 2.2.7 on 2020-09-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0066_merge_20200929_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='date_draft_by_partner',
            field=models.DateField(blank=True, null=True, verbose_name='Date first draft by Partner'),
        ),
    ]
