# Generated by Django 2.2.7 on 2020-09-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0066_merge_20200929_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='document_type',
            field=models.CharField(choices=[('PD', 'Programme Document'), ('SPD', 'Simplified Programme Document')], max_length=255, verbose_name='Document Type'),
        ),
    ]
