# Generated by Django 2.2.7 on 2020-10-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0065_merge_20201001_1019'),
        ('partners', '0066_merge_20200929_1454'),
    ]

    operations = [
    ]
