# Generated by Django 2.2.7 on 2020-10-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0067_intervention_date_draft_by_partner'),
        ('partners', '0067_auto_20200929_1926'),
    ]

    operations = [
    ]
