# Generated by Django 2.2.7 on 2020-10-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0068_merge_20201002_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='cancel_justification',
            field=models.TextField(blank=True, null=True, verbose_name='Cancel Justification'),
        ),
    ]
