# Generated by Django 2.2.7 on 2020-10-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0068_merge_20201002_1253'),
        ('partners', '0046_auto_20200924_1453'),
    ]

    operations = [
    ]
