# Generated by Django 2.2.7 on 2020-10-14 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0032_merge_20200923_1719'),
        ('partners', '0069_intervention_cancel_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='country_programmes',
            field=models.ManyToManyField(blank=True, help_text='Which Country Programme does this Intervention belong to?', related_name='interventions', to='reports.CountryProgramme', verbose_name='Country Programmes'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='country_programme',
            field=models.ForeignKey(blank=True, help_text='Which Country Programme does this Intervention belong to?', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reports.CountryProgramme', verbose_name='Country Programme'),
        ),
    ]
