# Generated by Django 2.2.7 on 2020-11-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0071_auto_20201014_1521'),
        ('partners', '0069_merge_20201013_1033'),
    ]

    operations = [
    ]
