# Generated by Django 2.2.7 on 2020-10-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0071_auto_20201014_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='date_last_amended',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Last Amended'),
        ),
    ]
