# Generated by Django 2.2.7 on 2020-10-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0071_auto_20201014_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='date_draft_by_partner',
        ),
    ]
