# Generated by Django 2.2.7 on 2020-10-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0071_auto_20201014_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='date_partnership_review_performed',
            field=models.DateField(blank=True, null=True, verbose_name='Date Final Partnership Review Performed'),
        ),
    ]
