# Generated by Django 2.2.7 on 2020-11-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0072_merge_20201104_1529'),
        ('partners', '0072_intervention_date_partnership_review_performed'),
    ]

    operations = [
    ]
