# Generated by Django 2.2.7 on 2020-11-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0073_merge_20201112_0759'),
        ('partners', '0073_merge_20201111_1602'),
    ]

    operations = [
    ]
