# Generated by Django 2.2.7 on 2020-11-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0074_interventionsupplyitem_unicef_product_number'),
        ('partners', '0074_merge_20201113_1516'),
    ]

    operations = [
    ]
