# Generated by Django 2.2.7 on 2020-12-01 21:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0075_merge_20201113_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('review_type', models.CharField(choices=[('prc', 'PRC Review'), ('non-prc', 'Non-PRC Review'), ('no-review', 'No Review Required')], default='prc', max_length=50, verbose_name='Types')),
                ('overall_approval', models.BooleanField(default=False)),
                ('amendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='partners.InterventionAmendment', verbose_name='Amendment')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='partners.Intervention', verbose_name='Intervention')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
