# Generated by Django 2.2.7 on 2020-11-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0075_merge_20201113_1549'),
        ('partners', '0074_merge_20201113_1548'),
    ]

    operations = [
    ]
