# Generated by Django 2.2.7 on 2020-12-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0077_auto_20201201_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionbudget',
            name='total_hq_cash_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total HQ Cash Local'),
        ),
        migrations.AddField(
            model_name='interventionbudget',
            name='total_unicef_cash_local_wo_hq',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total HQ Cash Local'),
        ),
    ]
