# Generated by Django 2.2.19 on 2021-03-31 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0078_auto_20201221_1343'),
        ('partners', '0078_merge_20210315_2141'),
    ]

    operations = [
    ]
