# Generated by Django 2.2.7 on 2021-04-27 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0079_merge_20210331_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionreview',
            name='answer_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='answer_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='meeting_date',
            field=models.DateField(blank=True, null=True, verbose_name='Meeting Date'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='overall_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Overall Approver'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='prc_officers',
            field=models.ManyToManyField(blank=True, related_name='_interventionreview_prc_officers_+', to=settings.AUTH_USER_MODEL, verbose_name='PRC Officers'),
        ),
        migrations.CreateModel(
            name='PRCOfficerInterventionReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('answer_1', models.CharField(blank=True, max_length=100)),
                ('answer_2', models.CharField(blank=True, max_length=100)),
                ('overall_approval', models.BooleanField(default=False)),
                ('amendment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officers_reviews', to='partners.InterventionAmendment', verbose_name='Amendment')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers_reviews', to='partners.Intervention', verbose_name='Intervention')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prc_reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
