# Generated by Django 2.2.7 on 2021-05-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0048_auto_20210506_0803'),
        ('partners', '0079_merge_20210331_1520'),
    ]

    operations = [
    ]
