# Generated by Django 2.2.7 on 2021-06-08 09:41

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import etools.applications.partners.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0079_merge_20210331_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionamendment',
            name='amended_intervention',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendment', to='partners.Intervention', verbose_name='Amended Intervention'),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='difference',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='kind',
            field=models.CharField(choices=[('normal', 'Normal'), ('contingency', 'Contingency')], default='normal', max_length=20, verbose_name='Kind'),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='partner_authorized_officer_signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.PartnerStaffMember', verbose_name='Signed by Partner'),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='related_objects_map',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='signed_by_partner_date',
            field=models.DateField(blank=True, null=True, verbose_name='Signed by Partner Date'),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='signed_by_unicef_date',
            field=models.DateField(blank=True, null=True, verbose_name='Signed by UNICEF Date'),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='unicef_signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='++', to=settings.AUTH_USER_MODEL, verbose_name='Signed by UNICEF'),
        ),
        migrations.AlterField(
            model_name='interventionamendment',
            name='amendment_number',
            field=models.CharField(max_length=15, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='interventionamendment',
            name='signed_amendment',
            field=models.FileField(blank=True, max_length=1024, upload_to=etools.applications.partners.models.get_intervention_amendment_file_path, verbose_name='Amendment Document'),
        ),
        migrations.AlterField(
            model_name='interventionamendment',
            name='signed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Signed Date'),
        ),
    ]
