# Generated by Django 2.2.7 on 2021-04-27 08:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0079_merge_20210331_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionamendment',
            name='amended_intervention',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendment', to='partners.Intervention', verbose_name='Amended Intervention'),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='kind',
            field=models.CharField(choices=[('normal', 'Normal'), ('contingency', 'Contingency')], default='normal', max_length=20, verbose_name='Kind'),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='related_objects_map',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
