# Generated by Django 2.2.7 on 2021-05-17 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0080_merge_20210507_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionreview',
            name='actions_list',
            field=models.TextField(blank=True, verbose_name='Actions List'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='budget_is_aligned',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The budget of the proposed PD/SPD is aligned with the principles of value for money with the effective and efficient programme management costs adhering to office defined limits'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='ges_considered',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='Gender, equity and sustainability have been considered in the programme design process'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='meeting_date',
            field=models.DateField(blank=True, null=True, verbose_name='Meeting Date'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='overall_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Overall Approver'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='overall_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='partner_comparative_advantage',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The partner selection evidences the CSO’s comparative advantage and value for money in relation to the planned results'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='pd_is_guided',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The results framework of the proposed PD/SPD has been guided by M&E feedback during the drafting process'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='pd_is_relevant',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The proposed PD/SPD is relevant to achieving results in the country programme document, the relevant sector workplan and or humanitarian response plan'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='prc_officers',
            field=models.ManyToManyField(blank=True, related_name='_interventionreview_prc_officers_+', to=settings.AUTH_USER_MODEL, verbose_name='PRC Officers'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='relationship_is_represented',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=10, verbose_name='The proposed relationship is best represented and regulated by partnership (as opposed to procurement), with both UNICEF and the CSO making clear contributions to the PD/SPD'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='relationships_are_positive',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='Previous UNICEF/UN relationships with the proposed CSO have been positive'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Started By'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='started_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Review Started'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='submitted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Submitted Date'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='supply_issues_considered',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The relevant supply issues have been duly considered'),
        ),
        migrations.AlterField(
            model_name='interventionreview',
            name='overall_approval',
            field=models.BooleanField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='interventionreview',
            name='review_type',
            field=models.CharField(blank=True, choices=[('prc', 'PRC Review'), ('non-prc', 'Non-PRC Review'), ('no-review', 'No Review Required')], max_length=50, verbose_name='Types'),
        ),
        migrations.CreateModel(
            name='PRCOfficerInterventionReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('relationship_is_represented', models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=10, verbose_name='The proposed relationship is best represented and regulated by partnership (as opposed to procurement), with both UNICEF and the CSO making clear contributions to the PD/SPD')),
                ('partner_comparative_advantage', models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The partner selection evidences the CSO’s comparative advantage and value for money in relation to the planned results')),
                ('relationships_are_positive', models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='Previous UNICEF/UN relationships with the proposed CSO have been positive')),
                ('pd_is_relevant', models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The proposed PD/SPD is relevant to achieving results in the country programme document, the relevant sector workplan and or humanitarian response plan')),
                ('pd_is_guided', models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The results framework of the proposed PD/SPD has been guided by M&E feedback during the drafting process')),
                ('ges_considered', models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='Gender, equity and sustainability have been considered in the programme design process')),
                ('budget_is_aligned', models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The budget of the proposed PD/SPD is aligned with the principles of value for money with the effective and efficient programme management costs adhering to office defined limits')),
                ('supply_issues_considered', models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The relevant supply issues have been duly considered')),
                ('overall_comment', models.TextField(blank=True)),
                ('overall_approval', models.BooleanField(null=True, blank=True)),
                ('started_date', models.DateField(blank=True, null=True, verbose_name='Date Review Started')),
                ('submitted_date', models.DateField(blank=True, null=True, verbose_name='Date Review Submitted')),
                ('overall_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prc_reviews', to='partners.InterventionReview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prc_reviews', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='InterventionReviewNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prc_notifications', to='partners.InterventionReview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prc_notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('review', '-created'),
            },
        ),
    ]
