# Generated by Django 2.2.7 on 2021-04-28 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0081_auto_20210428_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prcofficerinterventionreview',
            name='overall_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prc_reviews', to='partners.InterventionReview'),
        ),
    ]
