# Generated by Django 2.2.7 on 2021-05-24 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0082_intervention_is_amendment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventionamendment',
            name='signed_amendment',
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='partner_authorized_officer_signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.PartnerStaffMember', verbose_name='Signed by Partner'),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='signed_by_partner_date',
            field=models.DateField(blank=True, null=True, verbose_name='Signed by Partner Date'),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='signed_by_unicef_date',
            field=models.DateField(blank=True, null=True, verbose_name='Signed by UNICEF Date'),
        ),
        migrations.AddField(
            model_name='interventionamendment',
            name='unicef_signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='++', to=settings.AUTH_USER_MODEL, verbose_name='Signed by UNICEF'),
        ),
    ]
