# Generated by Django 2.2.7 on 2021-06-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0082_auto_20210601_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interventionreview',
            old_name='created_by',
            new_name='submitted_by',
        ),
    ]
