# Generated by Django 2.2.7 on 2021-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0082_auto_20210428_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionreview',
            name='review_started_date',
            field=models.DateField(blank=True, null=True, verbose_name='Review Started At'),
        ),
        migrations.AlterField(
            model_name='interventionreview',
            name='review_type',
            field=models.CharField(choices=[('na', 'Not Available'), ('prc', 'PRC Review'), ('non-prc', 'Non-PRC Review'), ('no-review', 'No Review Required')], default='na', max_length=50, verbose_name='Types'),
        ),
    ]
