# Generated by Django 2.2.7 on 2021-05-25 08:18

from django.db import migrations


def deactivate_old_amendments(apps, schema_editor):
    InterventionAmendment = apps.get_model('partners', 'InterventionAmendment')
    InterventionAmendment.objects.all().update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0083_auto_20210524_1410'),
    ]

    operations = [
        migrations.RunPython(deactivate_old_amendments, migrations.RunPython.noop),
    ]
