# Generated by Django 2.2.7 on 2021-05-26 10:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0084_auto_20210525_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionamendment',
            name='difference',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='interventionamendment',
            name='signed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Signed Date'),
        ),
    ]
