# Generated by Django 2.2.7 on 2021-04-28 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0084_auto_20210428_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventionreview',
            name='review_submitted_date',
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='submitted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Submitted Date'),
        ),
    ]
