# Generated by Django 2.2.7 on 2021-06-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0084_merge_20210608_0948'),
        ('partners', '0084_merge_20210608_0951'),
    ]

    operations = [
    ]
