# Generated by Django 2.2.7 on 2021-04-29 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0085_auto_20210428_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionReviewNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prc_notifications', to='partners.InterventionReview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prc_notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('review', '-created'),
            },
        ),
    ]
