# Generated by Django 2.2.7 on 2021-05-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0086_interventionreviewnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='prcofficerinterventionreview',
            name='started_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prcofficerinterventionreview',
            name='submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
