# Generated by Django 2.2.7 on 2021-06-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0086_remove_intervention_is_amendment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionamendment',
            name='amendment_number',
            field=models.CharField(max_length=15, verbose_name='Number'),
        ),
    ]
