# Generated by Django 2.2.20 on 2021-07-08 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0086_intervention_accepted_on_behalf_of_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionManagementBudgetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('kind', models.CharField(choices=[('in_country', 'In-country management and support staff prorated to their contribution to the programme (representation, planning, coordination, logistics, administration, finance)'), ('operational', 'Operational costs prorated to their contribution to the programme (office space, equipment, office supplies, maintenance)'), ('planning', 'Planning, monitoring, evaluation and communication, prorated to their contribution to the programme (venue, travels, etc.)')], max_length=15, verbose_name='Kind')),
                ('unicef_cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='UNICEF Cash Local')),
                ('cso_cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='CSO Cash Local')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='partners.InterventionManagementBudget', verbose_name='Budget')),
            ],
        ),
    ]
