# Generated by Django 2.2.20 on 2021-07-12 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0087_interventionmanagementbudgetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionmanagementbudgetitem',
            name='no_units',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Units Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interventionmanagementbudgetitem',
            name='unit',
            field=models.CharField(default='unknown', max_length=150, verbose_name='Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interventionmanagementbudgetitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='Unit Price'),
            preserve_default=False,
        ),
    ]
