# Generated by Django 2.2.7 on 2021-06-02 15:47

from django.db import migrations, models
import etools.applications.partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0088_interventionamendment_signed_amendment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionamendment',
            name='signed_amendment',
            field=models.FileField(blank=True, max_length=1024, upload_to=etools.applications.partners.models.get_intervention_amendment_file_path, verbose_name='Amendment Document'),
        ),
    ]
