# Generated by Django 2.2.7 on 2021-05-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0088_auto_20210503_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionreview',
            name='actions_list',
            field=models.TextField(blank=True, verbose_name='Actions List'),
        ),
    ]
