# Generated by Django 3.2.6 on 2021-08-25 08:05

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0089_merge_0078_auto_20210108_1634_0088_auto_20210712_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=django_fsm.FSMField(blank=True, choices=[('draft', 'Development'), ('review', 'Review'), ('signature', 'Signature'), ('signed', 'Signed'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('ended', 'Ended'), ('closed', 'Closed'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='draft', max_length=32, verbose_name='Status'),
        ),
    ]
