# Generated by Django 2.2.7 on 2021-05-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0089_interventionreview_actions_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventionreview',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='interventionreview',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='prcofficerinterventionreview',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='prcofficerinterventionreview',
            name='answer_2',
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='budget_is_aligned',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The budget of the proposed PD/SPD is aligned with the principles of value for money with the effective and efficient programme management costs adhering to office defined limits'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='ges_considered',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='Gender, equity and sustainability have been considered in the programme design process'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='partner_comparative_advantage',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The partner selection evidences the CSO’s comparative advantage and value for money in relation to the planned results'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='pd_is_guided',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The results framework of the proposed PD/SPD has been guided by M&E feedback during the drafting process'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='pd_is_relevant',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The proposed PD/SPD is relevant to achieving results in the country programme document, the relevant sector workplan and or humanitarian response plan'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='relationship_is_represented',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=10, verbose_name='The proposed relationship is best represented and regulated by partnership (as opposed to procurement), with both UNICEF and the CSO making clear contributions to the PD/SPD'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='relationships_are_positive',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='Previous UNICEF/UN relationships with the proposed CSO have been positive'),
        ),
        migrations.AddField(
            model_name='interventionreview',
            name='supply_issues_considered',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The relevant supply issues have been duly considered'),
        ),
        migrations.AddField(
            model_name='prcofficerinterventionreview',
            name='budget_is_aligned',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The budget of the proposed PD/SPD is aligned with the principles of value for money with the effective and efficient programme management costs adhering to office defined limits'),
        ),
        migrations.AddField(
            model_name='prcofficerinterventionreview',
            name='ges_considered',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='Gender, equity and sustainability have been considered in the programme design process'),
        ),
        migrations.AddField(
            model_name='prcofficerinterventionreview',
            name='partner_comparative_advantage',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The partner selection evidences the CSO’s comparative advantage and value for money in relation to the planned results'),
        ),
        migrations.AddField(
            model_name='prcofficerinterventionreview',
            name='pd_is_guided',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The results framework of the proposed PD/SPD has been guided by M&E feedback during the drafting process'),
        ),
        migrations.AddField(
            model_name='prcofficerinterventionreview',
            name='pd_is_relevant',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The proposed PD/SPD is relevant to achieving results in the country programme document, the relevant sector workplan and or humanitarian response plan'),
        ),
        migrations.AddField(
            model_name='prcofficerinterventionreview',
            name='relationship_is_represented',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=10, verbose_name='The proposed relationship is best represented and regulated by partnership (as opposed to procurement), with both UNICEF and the CSO making clear contributions to the PD/SPD'),
        ),
        migrations.AddField(
            model_name='prcofficerinterventionreview',
            name='relationships_are_positive',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='Previous UNICEF/UN relationships with the proposed CSO have been positive'),
        ),
        migrations.AddField(
            model_name='prcofficerinterventionreview',
            name='supply_issues_considered',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The relevant supply issues have been duly considered'),
        ),
    ]
