# Generated by Django 2.2.7 on 2021-05-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0090_auto_20210505_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionreview',
            name='started_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Review Started'),
        ),
        migrations.AlterField(
            model_name='prcofficerinterventionreview',
            name='started_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Review Started'),
        ),
        migrations.AlterField(
            model_name='prcofficerinterventionreview',
            name='submitted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Review Submitted'),
        ),
    ]
