# Generated by Django 3.2.6 on 2021-09-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0091_intervention_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='activation_protocol',
            field=models.TextField(blank=True, null=True, verbose_name='Activation Protocol'),
        ),
    ]
