# Generated by Django 3.2.6 on 2021-11-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0049_alter_interventionresultlink_unique_together'),
        ('partners', '0092_intervention_activation_protocol'),
    ]

    operations = [
    ]
