# Generated by Django 3.2.6 on 2022-02-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0093_merge_20211109_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionreview',
            name='sent_back_comment',
            field=models.TextField(blank=True, verbose_name='Sent Back by Secretary Comment'),
        ),
    ]
