# Generated by Django 3.2.6 on 2022-02-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0093_merge_20211109_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionresultlink',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code'),
        ),
    ]
