# Generated by Django 3.2.6 on 2022-02-22 11:32

from django.db import migrations


def number_result_links(apps, schema_editor):
    InterventionResultLink = apps.get_model('partners', 'InterventionResultLink')
    Intervention = apps.get_model('partners', 'Intervention')
    for intervention in Intervention.objects.all():
        result_links = intervention.result_links.all()
        for i, result_link in enumerate(result_links):
            result_link.code = str(i + 1)
        InterventionResultLink.objects.bulk_update(result_links, fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0094_interventionresultlink_code'),
    ]

    operations = [
        migrations.RunPython(number_result_links, migrations.RunPython.noop),
    ]
