# Generated by Django 3.2.6 on 2022-04-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0096_merge_20220325_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='confidential',
            field=models.TextField(blank=True, null=True, verbose_name='Confidential'),
        ),
    ]
