# Generated by Django 3.2.6 on 2022-04-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0099_auto_20220426_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='confidential',
        ),
        migrations.AddField(
            model_name='intervention',
            name='confidential',
            field=models.BooleanField(default=False, verbose_name='Confidential'),
        ),
    ]
