# Generated by Django 3.2.6 on 2022-05-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0100_alter_intervention_confidential'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interventionresultlink',
            options={'ordering': ['created']},
        ),
    ]
