# Generated by Django 3.2.6 on 2022-05-10 07:11

from django.db import migrations


def migrate_multiple_temp_result_links_to_one(apps, schema_editor):
    InterventionResultLink = apps.get_model('partners', 'InterventionResultLink')
    Intervention = apps.get_model('partners', 'Intervention')
    for intervention in Intervention.objects.all():
        temp_links = list(intervention.result_links.filter(cp_output=None))
        first_temp_link = None
        if len(temp_links) > 1:
            first_temp_link = temp_links[0]
            for link in temp_links[1:]:
                link.ll_results.update(result_link=first_temp_link)
                link.delete()

        if first_temp_link:
            first_temp_link.code = '0'
            first_temp_link.save()

        result_links = intervention.result_links.exclude(cp_output=None)
        for i, result_link in enumerate(result_links):
            result_link.code = str(i + 1)
        InterventionResultLink.objects.bulk_update(result_links, fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0101_alter_interventionresultlink_options'),
    ]

    operations = [
        migrations.RunPython(migrate_multiple_temp_result_links_to_one, migrations.RunPython.noop),
    ]
