# Generated by Django 3.2.6 on 2022-07-13 12:55

from django.db import migrations, models, transaction
import django.db.models.deletion


def migrate_organizations(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    PartnerOrganization = apps.get_model('partners', 'PartnerOrganization')

    with transaction.atomic():
        for partner_org in PartnerOrganization.objects.all():
            # this should not be the case as Partners should all be sanitized
            if not partner_org.vendor_number:
                continue
            organization, created = Organization.objects.get_or_create(
                name=partner_org.name,
                vendor_number=partner_org.vendor_number,
                defaults={
                    'organization_type': partner_org.partner_type,
                    'cso_type': partner_org.cso_type,
                    'short_name': partner_org.short_name,
                })
            partner_org.organization = organization
            partner_org.save(update_fields=['organization'])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('partners', '0103_merge_20220510_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='organizations.organization'),
        ),
        migrations.RunPython(migrate_organizations, migrations.RunPython.noop),
    ]
