# Generated by Django 3.2.6 on 2022-07-14 10:11

from django.db import migrations, transaction


def reverse_partner_org_removed_fields(apps, schema_editor):
    PartnerOrganization = apps.get_model('partners', 'PartnerOrganization')

    with transaction.atomic():
        for partner_org in PartnerOrganization.objects.select_related('organization'):
            organization = partner_org.organization
            # should not be the case
            if not organization:
                continue
            partner_org.name = organization.name
            partner_org.vendor_number = organization.vendor_number
            partner_org.partner_type = organization.organization_type
            partner_org.cso_type = organization.cso_type
            partner_org.short_name = organization.short_name
            partner_org.save(update_fields=['name', 'vendor_number', 'partner_type',
                                            'cso_type', 'short_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0104_partnerorganization_organization'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, reverse_partner_org_removed_fields),
        migrations.AlterModelOptions(
            name='partnerorganization',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterUniqueTogether(
            name='partnerorganization',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='cso_type',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='name',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='partner_type',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='vendor_number',
        ),
    ]
