# Generated by Django 3.2.6 on 2022-11-24 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0104_auto_20220808_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='terms_acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements_acknowledged+', to=settings.AUTH_USER_MODEL, verbose_name='Terms Acknowledged By'),
        ),
    ]
