# Generated by Django 3.2.6 on 2022-11-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0104_auto_20220808_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='has_activities_involving_children',
            field=models.BooleanField(default=False, verbose_name='Activities involving children and young people'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='has_data_processing_agreement',
            field=models.BooleanField(default=False, verbose_name='Data Processing Agreement'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='has_special_conditions_for_construction',
            field=models.BooleanField(default=False, verbose_name='Special Conditions for Construction Works by Implementing Partners'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='name',
            field=models.CharField(choices=[('FACE', 'FACE'), ('Progress Report', 'Progress Report'), ('Final Partnership Review', 'Final Partnership Review'), ('Correspondence', 'Correspondence'), ('Supply/Distribution Plan', 'Supply/Distribution Plan'), ('Data Processing Agreement', 'Data Processing Agreement'), ('Activities involving children and young people', 'Activities involving children and young people'), ('Special Conditions for Construction Works', 'Special Conditions for Construction Works'), ('Other', 'Other')], max_length=64, unique=True, verbose_name='Name'),
        ),
    ]
