# Generated by Django 3.2.6 on 2022-11-02 10:51

from django.db import migrations


def migrate_staff_members_to_users(apps, schema_editor):
    User = apps.get_model('users', 'User')

    PartnerStaffMember = apps.get_model('partners', 'PartnerStaffMember')
    for psm in PartnerStaffMember.objects.all():
        if not psm.user:
            continue
        psm.user.first_name = psm.first_name
        psm.user.last_name = psm.last_name
        psm.user.save(update_fields=['first_name', 'last_name'])

        psm.user.profile.job_title = psm.title
        psm.user.profile.phone_number = psm.phone
        psm.user.profile.save(update_fields=['job_title', 'phone_number'])

    Agreement = apps.get_model('partners', 'Agreement')
    for agreement in Agreement.objects.all():
        users = User.objects.filter(
            id__in=agreement.old_authorized_officers.all().values_list('user_id', flat=True))
        agreement.authorized_officers.add(*users)
        if agreement.old_partner_manager:
            agreement.partner_manager = agreement.old_partner_manager.user
            agreement.save(update_fields=['partner_manager'])

    Intervention = apps.get_model('partners', 'Intervention')
    for intervention in Intervention.objects.all():
        users = User.objects.filter(
            id__in=intervention.old_partner_focal_points.all().values_list('user_id', flat=True))
        intervention.partner_focal_points.add(*users)
        if intervention.old_partner_authorized_officer_signatory:
            intervention.partner_authorized_officer_signatory = intervention.old_partner_authorized_officer_signatory.user
            intervention.save(update_fields=['partner_authorized_officer_signatory'])

    InterventionAmendment = apps.get_model('partners', 'InterventionAmendment')
    for i_amendment in InterventionAmendment.objects.all():
        if i_amendment.old_partner_authorized_officer_signatory:
            i_amendment.partner_authorized_officer_signatory = i_amendment.old_partner_authorized_officer_signatory.user
            i_amendment.save(update_fields=['partner_authorized_officer_signatory'])


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0108_auto_20221102_1045'),
    ]

    operations = [

        migrations.RunPython(migrate_staff_members_to_users, migrations.RunPython.noop),
    ]
