# Generated by Django 3.2.6 on 2023-02-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0109_merge_0050_auto_20221121_1526_0108_auto_20221213_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='other_details',
            field=models.TextField(blank=True, null=True, verbose_name='Other Document Details'),
        ),
    ]
