# Generated by Django 3.2.6 on 2023-02-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0110_alter_interventionattachment_intervention'),
        ('partners', '0110_intervention_other_details'),
    ]

    operations = [
    ]
