# Generated by Django 3.2.6 on 2023-03-15 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0009_merge_0008_alter_option_label_0008_auto_20210108_1634'),
        ('partners', '0110_intervention_other_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionPlannedVisitSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('planned_visits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.interventionplannedvisits')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_settings.locationsite')),
            ],
        ),
        migrations.AddField(
            model_name='interventionplannedvisits',
            name='sites',
            field=models.ManyToManyField(blank=True, through='partners.InterventionPlannedVisitSite', to='field_monitoring_settings.LocationSite', verbose_name='Sites'),
        ),
        migrations.AlterUniqueTogether(
            name='interventionplannedvisitsite',
            unique_together={('planned_visits', 'site', 'quarter')},
        ),
    ]
