# Generated by Django 3.2.6 on 2023-05-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0112_auto_20230418_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='title',
            field=models.CharField(max_length=306, verbose_name='Document Title'),
        ),
    ]
