# Generated by Django 3.2.6 on 2022-07-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0113_partnerorganization_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerorganization',
            name='cso_type',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='name',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='partner_type',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='vendor_number',
        ),
    ]
