# Generated by Django 3.2.6 on 2022-11-07 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0113_staff_members_to_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='temp_authorized_officers',
            new_name='authorized_officers',
        ),
        migrations.RenameField(
            model_name='intervention',
            old_name='temp_partner_focal_points',
            new_name='partner_focal_points',
        ),
        migrations.AlterField(
            model_name='intervention',
            name='partner_focal_points',
            field=models.ManyToManyField(blank=True, related_name='_partners_intervention_partner_focal_points_+', to=settings.AUTH_USER_MODEL, verbose_name='CSO Authorized Officials'),
        ),
    ]
