# Generated by Django 3.2.6 on 2023-01-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0109_merge_0050_auto_20221121_1526_0108_auto_20221213_1223'),
        ('partners', '0114_auto_20221107_1015'),
    ]

    operations = [
    ]
