# Generated by Django 3.2.6 on 2023-05-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0113_alter_intervention_title'),
        ('partners', '0119_auto_20221107_1015'),
    ]

    operations = [
    ]
