# Generated by Django 3.2.6 on 2023-05-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0111_merge_20230221_0704'),
        ('partners', '0120_merge_20230502_1523'),
    ]

    operations = [
    ]
