# Generated by Django 3.2.19 on 2024-01-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0121_auto_20230614_0841'),
        ('partners', '0121_auto_20230814_1058'),
    ]

    operations = [
    ]
