from rest_framework_csv import renderers as r

from etools.applications.core.renderers import FriendlyCSVRenderer


class PartnerOrganizationCSVRenderer(r.CSVRenderer):
    header = ['vendor_number', 'organization_full_name',
              'short_name', 'alternate_name', 'partner_type', 'shared_with', 'address',
              'phone_number', 'email_address', 'risk_rating', 'date_last_assessment_against_core_values',
              'actual_cash_transfer_for_cp', 'actual_cash_transfer_for_current_year', 'marked_for_deletion', 'blocked',
              'type_of_assessment', 'date_assessed', 'assessments', 'staff_members', 'url', 'planned_visits', ]

    labels = {
        'vendor_number': 'Vendor Number',
        'organization_full_name': 'Organizations Full Name',
        'short_name': 'Short Name',
        'alternate_name': 'Alternate Name',
        'partner_type': 'Partner Type',
        'shared_with': 'Shared Partner',
        'address': 'Address',
        'phone_number': 'Phone Number',
        'email_address': 'Email Address',
        'risk_rating': 'Risk Rating',
        'date_last_assessment_against_core_values': 'Date Last Assessed Against Core Values',
        'actual_cash_transfer_for_cp': 'Actual Cash Transfer for CP (USD)',
        'actual_cash_transfer_for_current_year': 'Actual Cash Transfer for Current Year (USD)',
        'marked_for_deletion': 'Marked for Deletion',
        'blocked': 'Blocked',
        'type_of_assessment': 'Assessment Type',
        'date_assessed': 'Date Assessed',
        'assessments': 'Assessment Type (Date Assessed)',
        'staff_members': 'Staff Members',
        'url': 'URL',
        'planned_visits': "Planned Programmatic Visits",
    }


class PartnerOrganizationHactCsvRenderer(FriendlyCSVRenderer):

    header = [
        'name',
        'vendor_number',
        'partner_type',
        'shared_with',
        'type_of_assessment',
        'net_ct_cy',
        'reported_cy',
        'total_ct_ytd',
        'rating',
        'flags.expiring_assessment_flag',
        'flags.approaching_threshold_flag',
        'hact_values.programmatic_visits.planned.q1',
        'hact_values.programmatic_visits.planned.q2',
        'hact_values.programmatic_visits.planned.q3',
        'hact_values.programmatic_visits.planned.q4',
        'hact_min_requirements.programmatic_visits',
        'hact_values.programmatic_visits.completed.q1',
        'hact_values.programmatic_visits.completed.q2',
        'hact_values.programmatic_visits.completed.q3',
        'hact_values.programmatic_visits.completed.q4',
        'planned_engagement.spot_check_planned_q1',
        'planned_engagement.spot_check_planned_q2',
        'planned_engagement.spot_check_planned_q3',
        'planned_engagement.spot_check_planned_q4',
        'hact_min_requirements.spot_checks',
        'planned_engagement.spot_check_follow_up',
        'hact_values.spot_checks.completed.q1',
        'hact_values.spot_checks.completed.q2',
        'hact_values.spot_checks.completed.q3',
        'hact_values.spot_checks.completed.q4',
        'hact_min_requirements.audits',
        'hact_values.audits.completed',
        'hact_values.outstanding_findings',
    ]

    labels = {
        'name': 'Implementing Partner',
        'vendor_number': 'Vendor Number',
        'partner_type': 'Partner Type',
        'shared_with': 'Shared IP',
        'type_of_assessment': 'Assessment Type',
        'net_ct_cy': 'Cash Transfer 1 OCT - 30 SEP',
        'reported_cy': 'Liquidations 1 OCT - 30 SEP',
        'total_ct_ytd': 'Cash Transfers Jan - Dec',
        'rating': 'Risk Rating',
        'flags.expiring_assessment_flag': 'Expiring Threshold',
        'flags.approaching_threshold_flag': 'Approach Threshold',
        'hact_values.programmatic_visits.planned.q1': 'Programmatic Visits Planned Q1',
        'hact_values.programmatic_visits.planned.q2': 'Q2',
        'hact_values.programmatic_visits.planned.q3': 'Q3',
        'hact_values.programmatic_visits.planned.q4': 'Q4',
        'hact_min_requirements.programmatic_visits': 'Programmatic Visits M.R',
        'hact_values.programmatic_visits.completed.q1': 'Programmatic Visits Completed Q1',
        'hact_values.programmatic_visits.completed.q2': 'Q2',
        'hact_values.programmatic_visits.completed.q3': 'Q3',
        'hact_values.programmatic_visits.completed.q4': 'Q4',
        'planned_engagement.spot_check_planned_q1': 'Spot Checks Planned Q1',
        'planned_engagement.spot_check_planned_q2': 'Q2',
        'planned_engagement.spot_check_planned_q3': 'Q3',
        'planned_engagement.spot_check_planned_q4': 'Q4',
        'hact_min_requirements.spot_checks': 'Spot Checks M.R',
        'planned_engagement.spot_check_follow_up': 'Follow Up',
        'hact_values.spot_checks.completed.q1': 'Spot Checks Completed Q1',
        'hact_values.spot_checks.completed.q2': 'Q2',
        'hact_values.spot_checks.completed.q3': 'Q3',
        'hact_values.spot_checks.completed.q4': 'Q4',
        'hact_min_requirements.audits': 'Audits M.R',
        'hact_values.audits.completed': 'Audit Completed',
        'hact_values.outstanding_findings': 'Audits Outstanding Findings',
    }


class PartnerOrganizationDashboardCsvRenderer(FriendlyCSVRenderer):
    header = [
        'name',
        'sections',
        'locations',
        'action_points',
        'total_ct_cp',
        'total_ct_ytd',
        'outstanding_dct_amount_6_to_9_months_usd',
        'outstanding_dct_amount_more_than_9_months_usd',
        'days_last_pv',
        'alert_no_recent_pv',
        'alert_no_pv',
    ]

    labels = {
        'name': 'Implementing Partner',
        'sections': 'Sections',
        'locations': 'Locations',
        'action_points': 'Action Points #',
        'total_ct_cp': '$ Cash in the Current CP Cycle',
        'total_ct_ytd': '$ Cash in the Current Year',
        'days_last_pv': 'Days Since Last PV',
        'alert_no_recent_pv': 'Alert: No Recent PV',
        'alert_no_pv': 'Alert: No PV',
        'outstanding_dct_amount_6_to_9_months_usd': 'Outstanding DCT Amount between 6 and 9 months',
        'outstanding_dct_amount_more_than_9_months_usd': 'Outstanding DCT Amount more than 9 months',
    }


class PartnerOrganizationSimpleHactCsvRenderer(FriendlyCSVRenderer):

    header = [
        'name',
        'vendor_number',
        'partner_type',
        'shared_with',
        'type_of_assessment',
        'total_ct_ytd',
        'rating',
        'flags.expiring_assessment_flag',
        'flags.approaching_threshold_flag',
        'hact_values.programmatic_visits.planned.total',
        'hact_min_requirements.programmatic_visits',
        'hact_values.programmatic_visits.completed.total',
        'planned_engagement.spot_check_required',
        'hact_values.spot_checks.completed.total',
        'hact_min_requirements.audits',
        'hact_values.audits.completed',
        'hact_values.outstanding_findings',
    ]

    labels = {
        'name': 'Implementing Partner',
        'vendor_number': 'Vendor Number',
        'partner_type': 'Partner Type',
        'shared_with': 'Shared IP',
        'total_ct_ytd': 'Cash Transfers Jan - Dec',
        'type_of_assessment': 'Assessment Type',
        'rating': 'Risk Rating',
        'flags.expiring_assessment_flag': 'Expiring Threshold',
        'flags.approaching_threshold_flag': 'Approach Threshold',
        'hact_values.programmatic_visits.planned.total': 'Programmatic Visits Planned',
        'hact_min_requirements.programmatic_visits': 'Programmatic Visits M.R',
        'hact_values.programmatic_visits.completed.total': 'Programmatic Visits Completed',
        'planned_engagement.spot_check_required': 'Spot Check Required',
        'hact_values.spot_checks.completed.total': 'Spot Checks Completed',
        'hact_min_requirements.audits': 'Audits M.R',
        'hact_values.audits.completed': 'Audit Completed',
        'hact_values.outstanding_findings': 'Audits Outstanding Findings',
    }


class AgreementCSVRenderer(r.CSVRenderer):
    header = [
        "agreement_number",
        "status",
        "partner_name",
        "partner_number",
        "agreement_type",
        "start",
        "end",
        "partner_manager_name",
        "signed_by_partner_date",
        "signed_by_name",
        "signed_by_unicef_date",
        "staff_members",
        "amendments",
        "url",
        "special_conditions_pca",
    ]

    labels = {
        "agreement_number": 'Reference Number',
        "status": 'Status',
        "partner_name": 'Partner Name',
        "partner_number": "Vendor Number",
        "agreement_type": 'Agreement Type',
        "start": 'Start Date',
        "end": 'End Date',
        "partner_manager_name": 'Signed By Partner',
        "signed_by_partner_date": 'Signed By Partner Date',
        "signed_by_name": 'Signed By UNICEF',
        "signed_by_unicef_date": 'Signed By UNICEF Date',
        "staff_members": 'Partner Authorized Officer',
        "amendments": 'Amendments',
        "url": "URL",
        "special_conditions_pca": "Special Conditions PCA",
    }


class InterventionCSVRenderer(r.CSVRenderer):
    header = [
        "partner_name", "vendor_number", "status", "partner_type", "cso_type", "agreement_number", "country_programmes",
        "document_type", "number", "title", "start", "end", "offices", "sectors", "locations", "contingency_pd",
        "intervention_clusters", "unicef_focal_points", "partner_focal_points", "budget_currency", "cso_contribution",
        "unicef_budget", "unicef_supply", "total_planned_budget", "fr_numbers", "fr_currency", "fr_posting_date",
        "fr_amount", "fr_actual_amount", "fr_outstanding_amt", "planned_visits", "submission_date",
        "submission_date_prc", "review_date_prc", "partner_authorized_officer_signatory", "signed_by_partner_date",
        "unicef_signatory", "signed_by_unicef_date", "days_from_submission_to_signed", "days_from_review_to_signed",
        "amendment_sum", "last_amendment_date", "attachment_type", "total_attachments", "cp_outputs", "url",
    ]

    labels = {
        "partner_name": "Partner",
        "vendor_number": "Vendor no.",
        "status": "Status",
        "partner_type": "Partner Type",
        "cso_type": "CSO Type",
        "agreement_number": "Agreement",
        "country_programmes": "Country Programme",
        "document_type": "Document Type",
        "number": "Reference Number",
        "title": "Document Title",
        "start": "Start Date",
        "end": "End Date",
        "offices": "UNICEF Office",
        "sectors": "Sections",
        "locations": "Locations",
        "contingency_pd": "Contingency PD?",
        "intervention_clusters": "Cluster",
        "unicef_focal_points": "UNICEF Focal Points",
        "partner_focal_points": "CSO Authorized Officials",
        "budget_currency": "Budget Currency",
        "cso_contribution": "Total CSO Budget (USD)",
        "unicef_budget": "UNICEF Cash (USD)",
        "unicef_supply": "UNICEF Supply (USD)",
        "total_planned_budget": "Total PD/SSFA Budget (USD)",
        "fr_numbers": "FR Number(s)",
        "fr_currency": "FR Currency",
        "fr_posting_date": "FR Posting Date",
        "fr_amount": "FR Amount",
        "fr_actual_amount": "FR Actual CT",
        "fr_outstanding_amt": "Outstanding DCT",
        "planned_visits": "Planned Programmatic Visits",
        "spot_checks": "Planned Spot Checks",
        "audit": "Planned Audits",
        "submission_date": "Document Submission Date by CSO",
        "submission_date_prc": "Submission Date to PRC",
        "review_date_prc": "Review Date by PRC",
        "partner_authorized_officer_signatory": "Signed by Partner",
        "signed_by_partner_date": "Signed by Partner Date",
        "unicef_signatory": "Signed by UNICEF",
        "signed_by_unicef_date": "Signed by UNICEF Date",
        "days_from_submission_to_signed": "Days from Submission to Signed",
        "days_from_review_to_signed": "Days from Review to Signed",
        "amendment_sum": "Total no. of amendments",
        "last_amendment_date": "Last amendment date",
        "attachment_type": "Attachment Type",
        "total_attachments": "# of attachments",
        "cp_outputs": "CP Outputs",
        "url": "URL",
    }


class PartnershipDashCSVRenderer(r.CSVRenderer):
    header = [
        'partner_name',
        'partner_vendor_number',
        'number',
        'sections',
        'offices_names',
        'status',
        'start',
        'end',
        'budget_currency',
        'cso_contribution',
        'unicef_supplies',
        'unicef_cash',
        'fr_currency',
        'frs_total_frs_amt',
        'disbursement',
        'multi_curr_flag',
        'outstanding_dct',
        'frs_total_frs_amt_usd',
        'disbursement_usd',
        'outstanding_dct_usd',
        'disbursement_percent',
        'days_last_pv',
        'link',
    ]

    labels = {
        "partner_name": "IP Name",
        "partner_vendor_number": "Vendor Number",
        "number": "PD/SSFA Ref #",
        "sections": "Section",
        "offices_names": "Field Office",
        "status": "Status",
        "start": "Start Date",
        "end": "End Date",
        "budget_currency": "PD Currency",
        "cso_contribution": "CSO Contribution (PD Currency)",
        "unicef_supplies": "Total UNICEF Supplies (PD Currency)",
        "unicef_cash": "Total UNICEF Cash (PD Currency)",
        "fr_currency": "FR Currency",
        "frs_total_frs_amt": "FR Grand Total",
        "disbursement": "Actual Disbursements",
        'multi_curr_flag': "Multi-currency Transaction",
        "outstanding_dct": "Outstanding DCT",
        "frs_total_frs_amt_usd": "FR Grand Total (USD)",
        "disbursement_usd": "Actual Disbursement (USD)",
        "outstanding_dct_usd": "Outstanding DCT (USD)",
        "disbursement_percent": "Disbursement To Date (%)",
        "days_last_pv": "Days Since Last PV",
        "link": "Link"
    }


class InterventionLocationCSVRenderer(r.CSVRenderer):
    header = [   # This controls field order in the output
        'partner',
        'partner_vendor_number',
        'pd_ref_number',
        'partnership',
        'status',
        'location',
        'section',
        'cp_output',
        'start',
        'end',
        'focal_point',
        'hyperlink',
    ]
    labels = {
        'cp_output': 'CP output',
        'end': 'End Date',
        'focal_point': 'Name of UNICEF Focal Point',
        'hyperlink': 'Hyperlink',
        'location': 'Location',
        'partner': 'Partner',
        "partner_vendor_number": "Vendor Number",
        'partnership': 'Agreement',
        'pd_ref_number': 'PD Ref Number',
        'section': 'Section',
        'start': 'Start Date',
        'status': 'Status'
    }
