from django.utils.translation import gettext as _

from rest_framework_csv import renderers as r


class GDDCSVRenderer(r.CSVRenderer):
    header = [
        "partner_name", "vendor_number", "status", "partner_type", "agreement_number", "country_programme",
        "number", "title", "start", "end", "offices", "sectors", "locations",
        "unicef_focal_points", "partner_focal_points", "budget_currency",
        "unicef_budget", "unicef_supply", "total_planned_budget", "fr_numbers", "fr_currency", "fr_posting_date",
        "fr_amount", "fr_actual_amount", "fr_outstanding_amt", "planned_visits", "submission_date",
        "submission_date_prc", "review_date_prc", "partner_authorized_officer_signatory", "signed_by_partner_date",
        "unicef_signatory", "signed_by_unicef_date", "days_from_submission_to_approved", "days_from_review_to_approved",
        "amendment_sum", "last_amendment_date", "attachment_type", "total_attachments", "cp_outputs", "url",
    ]

    labels = {
        "partner_name": _("Partner"),
        "vendor_number": _("Vendor no."),
        "status": _("Status"),
        "partner_type": _("Partner Type"),
        "agreement_number": _("Agreement"),
        "country_programme": _("Country Programme"),
        "number": _("Reference Number"),
        "title": _("Document Title"),
        "start": _("Start Date"),
        "end": _("End Date"),
        "offices": _("UNICEF Office"),
        "sectors": _("Sections"),
        "locations": _("Locations"),
        "unicef_focal_points": _("UNICEF Focal Points"),
        "partner_focal_points": _("Government Authorized Officials"),
        "budget_currency": _("Budget Currency"),
        "unicef_budget": _("UNICEF Cash (USD)"),
        "unicef_supply": _("UNICEF Supply (USD)"),
        "total_planned_budget": _("Total GDD Budget (USD)"),
        "fr_numbers": _("FR Number(s)"),
        "fr_currency": _("FR Currency"),
        "fr_posting_date": _("FR Posting Date"),
        "fr_amount": _("FR Amount"),
        "fr_actual_amount": _("FR Actual CT"),
        "fr_outstanding_amt": _("Outstanding DCT"),
        "planned_visits": _("Planned Programmatic Visits"),
        "spot_checks": _("Planned Spot Checks"),
        "audit": _("Planned Audits"),
        "submission_date": _("Document Submission Date by Government"),
        "submission_date_prc": _("Submission Date to PRC"),
        "review_date_prc": _("Review Date by PRC"),
        "partner_authorized_officer_signatory": _("Signed by Partner"),
        "signed_by_partner_date": _("Signed by Partner Date"),
        "unicef_signatory": _("Signed by UNICEF"),
        "signed_by_unicef_date": _("Signed by UNICEF Date"),
        "days_from_submission_to_approved": _("Days from Submission to Approved"),
        "days_from_review_to_approved": _("Days from Review to Approved"),
        "amendment_sum": _("Total no. of amendments"),
        "last_amendment_date": _("Last amendment date"),
        "attachment_type": _("Attachment Type"),
        "total_attachments": _("# of attachments"),
        "cp_outputs": _("CP Outputs"),
        "url": "URL",
    }
