# Generated by Django 2.2.7 on 2021-05-27 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field_monitoring_planning', '0009_auto_20210318_2046'),
        ('locations', '0001_initial'),
        ('reports', '0025_auto_20191220_2022'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0048_auto_20210506_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reference_number', models.CharField(max_length=100, unique=True, verbose_name='Reference Number')),
                ('status', django_fsm.FSMField(choices=[('draft', 'Draft'), ('submission', 'Submission Review'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('review', 'Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30, verbose_name='Status')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips', to='reports.Office', verbose_name='Office')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips', to='reports.Section', verbose_name='Section')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_itineraries', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL, verbose_name='Traveller')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Itineraries',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='TripStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submission', 'Submission Review'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('review', 'Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='travel.Trip', verbose_name='Trip')),
            ],
            options={
                'verbose_name': 'Trip Status History',
                'verbose_name_plural': 'Trip Status History',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('narrative', models.TextField(blank=True, verbose_name='Narrative')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='travel.Trip', verbose_name='Trip')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('travel_method', models.CharField(blank=True, max_length=150, verbose_name='Travel Method')),
                ('destination', models.CharField(blank=True, max_length=150, verbose_name='Destination')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='travel.Trip', verbose_name='Trip')),
            ],
            options={
                'verbose_name': 'Itinerary Item',
                'verbose_name_plural': 'Itinerary Items',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('activity_date', models.DateField(verbose_name='Activity Date')),
                ('activity_type', models.CharField(blank=True, choices=[('Monitoring Activity', 'Monitoring Activity'), ('Technical Support', 'Technical Support'), ('Meeting', 'Meeting'), ('Staff Development', 'Staff Development'), ('Staff Entitlement', 'Staff Entitlement')], default='Monitoring Activity', max_length=64, verbose_name='Activity Type')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_activities', to='locations.Location')),
                ('monitoring_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_activities', to='field_monitoring_planning.MonitoringActivity')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_activities', to='partners.PartnerOrganization')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_activities', to='reports.Section')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='travel.Trip', verbose_name='Trip')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-activity_date'],
            },
        ),
    ]
