# Generated by Django 2.2.7 on 2021-06-11 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0009_auto_20210318_2046'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='monitoring_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_itinerary_items', to='field_monitoring_planning.MonitoringActivity'),
        ),
    ]
