# Generated by Django 2.2.7 on 2021-06-15 01:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_itineraryitem_monitoring_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user_info_text',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='User Information Text'),
        ),
    ]
