# Generated by Django 2.2.7 on 2021-06-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_trip_user_info_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='additional_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
