# Generated by Django 2.2.7 on 2021-06-17 00:44

import django.contrib.postgres.fields.jsonb
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_trip_additional_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('-start_date',), 'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AlterField(
            model_name='trip',
            name='user_info_text',
            field=models.JSONField(blank=True, default=dict, verbose_name='User Information Text'),
        ),
    ]
