# Generated by Django 3.2.6 on 2022-03-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_remove_cartodbtable_location_type_and_more'),
        ('field_monitoring_planning', '0012_auto_20210709_1455'),
        ('partners', '0049_alter_interventionresultlink_unique_together'),
        ('travel', '0006_trip_not_as_planned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_activities', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='monitoring_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_activities', to='field_monitoring_planning.monitoringactivity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_activities', to='partners.partnerorganization'),
        ),
    ]
