# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-10 20:30
from __future__ import unicode_literals

from django.db import migrations


def create_email_templates_blocked_partner(apps, schema):
    # Create a few email templates that the tests expect to exist, just in case.
    # Simpler and more efficient than creating them in every test.
    EmailTemplate = apps.get_model('post_office.EmailTemplate')
    EmailTemplate.objects.create(
        name='partners/blocked_partner',
        description='Unicef Partner Blocked',
        subject='eTools {{environment}} - Unicef Partner Blocked: {{partner_name}}',
        content="""
        Dear Colleague,

        Please note that Partner {{partner_name}} has been blocked in VISION.
        At the same time the partner has a following PDs/SSFA that is either Signed, Active or Ended:
        {{pds}}

        Please discuss follow up actions with UNICEF Authorized Officer including SSFA/PCA Termination.

        Please note that this is an automated message and replies to this address not monitored.
        """,
        html_content="""
        {% extends "email-templates/base" %}

        {% block content %}
        Dear Colleague,<br/><br/>

        Please note that Partner {{partner_name}} has been blocked in VISION.<br/>
        At the same time the partner has a following PDs/SSFA that is either Signed, Active or Ended:<br/>
        {{pds}}<br/>

        Please discuss follow up actions with UNICEF Authorized Officer including SSFA/PCA Termination.<br/>

        Please note that this is an automated message and replies to this address not monitored.<br/>
        {% endblock %}
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_create_email_templates'),
    ]

    operations = [
        migrations.RunPython(create_email_templates_blocked_partner, migrations.RunPython.noop),
    ]
