# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-28 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_data(apps, schema_editor):
    NotificationOld = apps.get_model("notification", "notification")
    Notification = apps.get_model("unicef_notification", "notification")
    for notification in NotificationOld.objects.all():
        Notification.objects.create(
            method_type=notification.type,
            content_type=notification.content_type,
            object_id=notification.object_id,
            from_address=notification.from_address,
            recipients=notification.recipients,
            cc=notification.cc,
            sent_recipients=notification.sent_recipients,
            template_name=notification.template_name,
            template_data=notification.template_data,
            sent_email=notification.sent_email,
            subject=notification.subject,
            text_message=notification.text_message,
            html_message=notification.html_message,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20180510_2030'),
        ('unicef_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_old', to='contenttypes.ContentType', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_email_old', to='post_office.Email'),
        ),
        migrations.RunPython(
            migrate_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
