# Generated by Django 3.2.6 on 2022-04-20 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tpm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_initial'),
        ('tpmpartners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmvisit',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='tpm_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tpmpartners.tpmpartner', verbose_name='TPM Vendor'),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='tpm_partner_focal_points',
            field=models.ManyToManyField(blank=True, related_name='tpm_visits', to='tpmpartners.TPMPartnerStaffMember', verbose_name='TPM Focal Points'),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='offices',
            field=models.ManyToManyField(blank=True, to='reports.Office', verbose_name='Office(s) of UNICEF Focal Point(s)'),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_activities', to='reports.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='tpm_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_activities', to='tpm.tpmvisit', verbose_name='Visit'),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='unicef_focal_points',
            field=models.ManyToManyField(blank=True, related_name='_tpm_tpmactivity_unicef_focal_points_+', to=settings.AUTH_USER_MODEL, verbose_name='UNICEF Focal Points'),
        ),
    ]
