# Generated by Django 1.10.8 on 2018-05-04 13:40
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0003_tpmactivity_unicef_focal_points'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TPMPermission',
        ),
    ]
