# Generated by Django 2.2.1 on 2019-06-20 13:36

from django.db import connection, migrations, models

from etools.applications.core.tests.cases import SCHEMA_NAME


def set_reference_number(apps, schema_editor):
    # Only run this when NOT in test
    if connection.tenant.schema_name != SCHEMA_NAME:
        TPMVisit = apps.get_model("tpm", "tpmvisit")
        for visit in TPMVisit.objects.all():
            visit.reference_number = visit.get_reference_number()
            visit.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0007_auto_20180926_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmvisit',
            name='reference_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Reference Number'),
        ),
        migrations.RunPython(set_reference_number),
    ]
