# Generated by Django 2.2.6 on 2019-10-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0009_auto_20191014_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmactivity',
            name='offices',
            field=models.ManyToManyField(blank=True, to='reports.Office', verbose_name='Office(s) of UNICEF Focal Point(s)'),
        ),
    ]
