# Generated by Django 2.2.3 on 2019-08-14 13:02

from django.db import connection, migrations, models


def set_reference_number(apps, schema_editor):
    # Only run this when NOT in test
    if connection.tenant.schema_name != "test":
        Country = apps.get_model("users", "country")
        TPMVisit = apps.get_model("tpm", "tpmvisit")
        country = Country.objects.get(
            schema_name=connection.tenant.schema_name,
        )
        for visit in TPMVisit.objects.all():
            visit.reference_number = '{}/{}/{}/TPM'.format(
                country.country_short_code,
                visit.created.year,
                visit.pk,
            )
            visit.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0010_auto_20191029_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmvisit',
            name='reference_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Reference Number'),
        ),
        migrations.RunPython(set_reference_number),
    ]
