# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-26 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cp_output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='reports.Result', verbose_name='CP Output'),
        ),
        migrations.AlterField(
            model_name='task',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.Intervention', verbose_name='PD or SSFA'),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='locations.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='task',
            name='location_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='field_monitoring_settings.LocationSite', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='task',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='partners.PartnerOrganization', verbose_name='Partner'),
        ),
    ]
