# Generated by Django 2.0.9 on 2018-12-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearplan',
            name='other_aspects',
            field=models.TextField(blank=True, verbose_name='Other Aspects of the Field Monitoring Plan'),
        ),
    ]
