# Generated by Django 3.2.6 on 2022-04-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('field_monitoring_settings', '0001_initial'),
        ('field_monitoring_planning', '0001_initial'),
        ('reports', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='cp_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reports.result', verbose_name='CP Output'),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.intervention', verbose_name='Intervention'),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='field_monitoring_settings.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='monitoringactivitygroup',
            name='monitoring_activities',
            field=models.ManyToManyField(related_name='groups', to='field_monitoring_planning.MonitoringActivity'),
        ),
        migrations.AddField(
            model_name='monitoringactivitygroup',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_activity_groups', to='partners.partnerorganization'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='cp_outputs',
            field=models.ManyToManyField(blank=True, related_name='monitoring_activities', to='reports.Result', verbose_name='Outputs'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='field_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.office', verbose_name='Field Office'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='interventions',
            field=models.ManyToManyField(blank=True, related_name='monitoring_activities', to='partners.Intervention', verbose_name='PD/SPD'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_activities', to='locations.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='location_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_activities', to='field_monitoring_settings.locationsite', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='offices', to='reports.Office', verbose_name='Field Offices'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='monitoring_activities', to='partners.PartnerOrganization', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='sections',
            field=models.ManyToManyField(blank=True, to='reports.Section', verbose_name='Sections'),
        ),
    ]
