# Generated by Django 2.1.5 on 2019-02-18 10:22

import django.contrib.postgres.fields
from django.db import migrations, models
import etools.applications.field_monitoring.planning.models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0002_yearplan_other_aspects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='plan_by_month',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, default=0), blank=True, default=etools.applications.field_monitoring.planning.models._default_plan_by_month, size=None, verbose_name='Plan By Month'),
        ),
    ]
