# Generated by Django 2.0.9 on 2018-12-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20180709_1348'),
        ('field_monitoring_planning', '0002_yearplan_other_aspects'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sections',
            field=models.ManyToManyField(to='reports.Sector', verbose_name='Sections'),
        ),
    ]
