# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-31 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0006_auto_20181026_1456'),
        ('field_monitoring_planning', '0002_auto_20181026_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cp_output',
        ),
        migrations.AddField(
            model_name='task',
            name='cp_output_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='field_monitoring_settings.CPOutputConfig', verbose_name='CP Output Config'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.Intervention', verbose_name='PD or SSFA'),
        ),
        migrations.AlterField(
            model_name='task',
            name='year_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='field_monitoring_planning.YearPlan', verbose_name='Year Plan'),
        ),
    ]
