# Generated by Django 3.2.19 on 2024-06-03 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field_monitoring_planning', '0002_initial'),
        ('tpmpartners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringactivity',
            name='report_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_to_review', to=settings.AUTH_USER_MODEL, verbose_name='Report Reviewer'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='sections',
            field=models.ManyToManyField(blank=True, to='reports.Section', verbose_name='Sections'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='monitoring_activities', to=settings.AUTH_USER_MODEL, verbose_name='Team Members'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='tpm_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpmpartners.tpmpartner', verbose_name='TPM Partner'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='visit_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Person Responsible'),
        ),
    ]
