# Generated by Django 2.2.1 on 2019-07-05 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_visits', '0006_auto_20190705_1341'),
        ('reports', '0017_auto_20190424_1509'),
        ('partners', '0038_auto_20190620_2024'),
        ('field_monitoring_planning', '0003_task_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('issue', models.TextField(verbose_name='Issue For Attention/Probing')),
                ('status', models.CharField(choices=[('new', 'New'), ('past', 'Past')], default='new', max_length=10)),
            ],
            options={
                'verbose_name': 'Log Issue',
                'verbose_name_plural': 'Log Issues',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('specific_details', models.TextField(blank=True, verbose_name='Specific Details To Probe')),
                ('cp_output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Result', verbose_name='Partner')),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Intervention', verbose_name='Partner')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Question Template',
                'verbose_name_plural': 'Question Templates',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
