# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-06 14:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0003_auto_20181031_1120'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='Deleted At'),
        ),
    ]
