# Generated by Django 2.2.1 on 2019-07-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_visits', '0006_auto_20190710_1402'),
        ('partners', '0038_auto_20190620_2024'),
        ('reports', '0017_auto_20190424_1509'),
        ('field_monitoring_planning', '0003_task_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('specific_details', models.TextField(blank=True, verbose_name='Specific Details To Probe')),
                ('cp_output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Result', verbose_name='Partner')),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Intervention', verbose_name='Partner')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Question Template',
                'verbose_name_plural': 'Question Templates',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
