# Generated by Django 2.2.7 on 2019-12-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0004_auto_20191204_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoringactivity',
            old_name='activity_type',
            new_name='monitor_type',
        ),
    ]
