# Generated by Django 2.2.1 on 2019-07-10 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('locations', '0008_auto_20190422_1537'),
        ('field_monitoring_planning', '0004_auto_20190710_1424'),
        ('reports', '0017_auto_20190424_1509'),
        ('tpmpartners', '0004_auto_20180503_1311'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0038_auto_20190620_2024'),
        ('field_monitoring_settings', '0005_auto_20190710_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_settings.Question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='cp_outputs',
            field=models.ManyToManyField(blank=True, related_name='_monitoringactivity_cp_outputs_+', to='reports.Result', verbose_name='Outputs'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='interventions',
            field=models.ManyToManyField(blank=True, related_name='_monitoringactivity_interventions_+', to='partners.Intervention', verbose_name='PD/SSFA'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_activities', to='locations.Location',
                                    verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='location_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_activities',
                                    to='field_monitoring_settings.LocationSite', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='_monitoringactivity_partners_+', to='partners.PartnerOrganization', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='person_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Person Responsible'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='monitoring_activities', to=settings.AUTH_USER_MODEL, verbose_name='Team Members'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='tpm_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpmpartners.TPMPartner',
                                    verbose_name='TPM Partner'),
        ),
    ]
