# Generated by Django 2.2.1 on 2019-07-05 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0004_auto_20190705_1341'),
        ('locations', '0008_auto_20190422_1537'),
        ('reports', '0017_auto_20190424_1509'),
        ('partners', '0038_auto_20190620_2024'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_monitoring_settings', '0005_auto_20190705_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_settings.Question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='logissue',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_logissues', to=settings.AUTH_USER_MODEL, verbose_name='Issue Raised By'),
        ),
        migrations.AddField(
            model_name='logissue',
            name='cp_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Result', verbose_name='CP Output'),
        ),
        migrations.AddField(
            model_name='logissue',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='logissue',
            name='location_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_settings.LocationSite', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='logissue',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization', verbose_name='Partner'),
        ),
    ]
