# Generated by Django 4.2.3 on 2024-09-20 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_initial'),
        ('categories', '0001_initial'),
        ('partners', '0003_alter_intervention_partner_focal_points_and_more'),
        ('field_monitoring_planning', '0004_monitoringactivity_remote_monitoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPMConcern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference Number')),
                ('description', models.TextField(verbose_name='Description')),
                ('high_priority', models.BooleanField(default=False, verbose_name='High Priority')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tpm_concerns', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Category')),
                ('cp_output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.result', verbose_name='CP Output')),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.intervention', verbose_name='PD/SPD')),
                ('monitoring_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_planning.monitoringactivity', verbose_name='Monitoring Activity')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partnerorganization', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'TPM Concern',
                'verbose_name_plural': 'TPM Concerns',
                'ordering': ('id',),
            },
        ),
    ]
