# Generated by Django 2.2.1 on 2019-07-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0004_auto_20190710_1402'),
        ('field_monitoring_settings', '0005_auto_20190710_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_settings.Question', verbose_name='Question'),
        ),
    ]
