# Generated by Django 2.2.1 on 2019-07-11 10:52

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0005_auto_20190710_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringactivity',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('details_configured', 'Details Configured'), ('checklist_configured', 'Checklist Configured'), ('assigned', 'Assigned'), ('data_collected', 'Data Collected'), ('report_submitted', 'Report Submitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
