# Generated by Django 2.2.7 on 2020-02-05 13:46

from django.db import connection, migrations, models


def assign_reference_number(apps, schema_editor):
    # Only run this when NOT in test
    if connection.tenant.schema_name != "test":
        MonitoringActivity = apps.get_model('field_monitoring_planning', 'MonitoringActivity')
        Country = apps.get_model("users", "country")

        country = Country.objects.get(
            schema_name=connection.tenant.schema_name,
        )
        for activity in MonitoringActivity.admin_objects.all():
            activity.number = '{}/{}/{}/FMA'.format(
                country.country_short_code,
                activity.created.year,
                activity.id,
            )
            activity.save(update_fields=['number'])


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0006_monitoringactivity_report_reject_reason'),
        ('users', '0013_auto_20191010_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringactivity',
            name='number',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Reference Number'),
        ),
        migrations.RunPython(assign_reference_number, migrations.RunPython.noop),
    ]
