# Generated by Django 4.2.3 on 2025-08-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0007_visitgoal_monitoringactivity_visit_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringactivity',
            name='objective',
            field=models.TextField(blank=True, verbose_name='Objective'),
        ),
    ]
