# Generated by Django 2.2.7 on 2021-01-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0007_monitoringactivity_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringactivity',
            name='interventions',
            field=models.ManyToManyField(blank=True, related_name='monitoring_activities', to='partners.Intervention', verbose_name='PD/SPD'),
        ),
    ]
