# Generated by Django 2.2.11 on 2021-03-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_auto_20191220_2022'),
        ('field_monitoring_planning', '0007_monitoringactivity_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringactivity',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='offices', to='reports.Office', verbose_name='Field Offices'),
        ),
    ]
