# Generated by Django 4.2.3 on 2025-08-07 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0007_visitgoal_monitoringactivity_objective_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='facility_types',
            field=models.ManyToManyField(blank=True, related_name='monitoring_activities',
                                         to='field_monitoring_planning.facilitytype', verbose_name='Facility types'),
        ),
    ]
