# Generated by Django 2.2.1 on 2019-07-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('field_monitoring_planning', '0007_auto_20190711_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontemplate',
            name='cp_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reports.Result',
                                    verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.Intervention',
                                    verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.PartnerOrganization',
                                    verbose_name='Partner'),
        ),
    ]
