# Generated by Django 4.2.23 on 2025-09-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0008_facilitytype_monitoringactivity_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringactivity',
            name='monitor_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('tpm', 'TPM'), ('both', 'Both')], default='staff', max_length=10),
        ),
    ]
