# Generated by Django 4.2.23 on 2025-10-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0009_alter_monitoringactivity_monitor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringactivity',
            name='facility_type_duration',
            field=models.CharField(blank=True, choices=[('temporary', 'Temporary'), ('semi_permanent', 'Semi-permanent'), ('permanent', 'Permanent')], max_length=20, verbose_name='Facility Type Duration'),
        ),
    ]
