# Generated by Django 4.2.23 on 2025-11-20 08:59

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
        ('field_monitoring_planning', '0009_alter_monitoringactivity_monitor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringactivity',
            name='facility_types',
        ),
        migrations.AddField(
            model_name='facilitytype',
            name='related_sections',
            field=models.ManyToManyField(blank=True, related_name='facility_types', to='reports.section', verbose_name='Related Sections'),
        ),
        migrations.CreateModel(
            name='MonitoringActivityFacilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type_durations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('temporary', 'Temporary'), ('semi_permanent', 'Semi-permanent'), ('permanent', 'Permanent')], max_length=20), blank=True, default=list, help_text='One or more duration options for this facility type', size=None, verbose_name='Facility Type Durations')),
                ('facility_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_activity_relations', to='field_monitoring_planning.facilitytype', verbose_name='Facility Type')),
                ('monitoring_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_type_relations', to='field_monitoring_planning.monitoringactivity', verbose_name='Monitoring Activity')),
            ],
            options={
                'verbose_name': 'Monitoring Activity Facility Type',
                'verbose_name_plural': 'Monitoring Activity Facility Types',
                'unique_together': {('monitoring_activity', 'facility_type')},
            },
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='facility_types',
            field=models.ManyToManyField(blank=True, related_name='monitoring_activities', through='field_monitoring_planning.MonitoringActivityFacilityType', to='field_monitoring_planning.facilitytype', verbose_name='Facility types'),
        ),
    ]
