# Generated by Django 4.2.26 on 2026-02-03 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0009_alter_monitoringactivity_monitor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyEWPActivityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbs', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DummyGPDModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpd_ref', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='ewp_activity',
            field=models.ManyToManyField(blank=True, related_name='monitoring_activities', to='field_monitoring_planning.dummyewpactivitymodel', verbose_name='eWP activities'),
        ),
        migrations.AddField(
            model_name='monitoringactivity',
            name='gpds',
            field=models.ManyToManyField(blank=True, related_name='monitoring_activities', to='field_monitoring_planning.dummygpdmodel', verbose_name='GDPs'),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='ewp_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='field_monitoring_planning.dummyewpactivitymodel', verbose_name='eWP Activity'),
        ),
        migrations.AddField(
            model_name='questiontemplate',
            name='gpd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='field_monitoring_planning.dummyewpactivitymodel', verbose_name='GPD'),
        ),
    ]
