# Generated by Django 2.2.1 on 2019-08-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20190424_1509'),
        ('field_monitoring_planning', '0010_auto_20190826_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringactivity',
            name='sections',
            field=models.ManyToManyField(blank=True, to='reports.Section', verbose_name='Sections'),
        ),
    ]
