# Generated by Django 4.2.26 on 2026-01-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0010_remove_monitoringactivity_facility_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringactivity',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Mission completion date'),
        ),
    ]
