# Generated by Django 4.2.23 on 2025-11-04 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
        ('field_monitoring_planning', '0010_add_facility_type_durations_through_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitytype',
            name='related_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_types', to='reports.section', verbose_name='Related Section'),
        ),
    ]
