# Generated by Django 2.2.1 on 2019-09-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190513_1804'),
        ('field_monitoring_planning', '0011_monitoringactivity_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringactivity',
            name='field_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Office', verbose_name='Field Office'),
        ),
    ]
