# Generated by Django 2.2.20 on 2021-07-05 09:18

from django.db import migrations, models


def update_is_hact(apps, schema_editor):
    MonitoringActivity = apps.get_model('field_monitoring_planning', 'MonitoringActivity')
    ActivityQuestion = apps.get_model('field_monitoring_data_collection', 'ActivityQuestion')
    MonitoringActivity.admin_objects.filter(
        id__in=ActivityQuestion.objects.filter(question__is_hact=True, overall_finding__value__isnull=False)
    ).update(is_hact=True)


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0011_monitoringactivitygroup'),
        ('field_monitoring_data_collection', '0002_auto_20191116_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringactivity',
            name='is_hact',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(update_is_hact, migrations.RunPython.noop),
    ]
