# Generated by Django 2.2.20 on 2021-07-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0011_monitoringactivitygroup'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='monitoringactivity',
            managers=[
            ],
        ),
    ]
