# Generated by Django 4.2.23 on 2025-11-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
        ('field_monitoring_planning', '0011_add_related_section_to_facility_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitytype',
            name='related_section',
        ),
        migrations.AddField(
            model_name='facilitytype',
            name='related_sections',
            field=models.ManyToManyField(blank=True, related_name='facility_types', to='reports.section', verbose_name='Related Sections'),
        ),
    ]
