# Generated by Django 2.2.1 on 2019-09-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0012_monitoringactivity_field_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringactivity',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_activities', to='locations.Location', verbose_name='Location'),
        ),
    ]
