# Generated by Django 3.2.6 on 2021-08-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0008_auto_20210108_1634'),
        ('field_monitoring_planning', '0012_auto_20210709_1455'),
    ]

    operations = [
    ]
