# Generated by Django 2.2.20 on 2021-07-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0012_monitoringactivity_is_hact'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='monitoringactivity',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='monitoringactivity',
            name='is_hact',
        ),
    ]
