# Generated by Django 4.2.26 on 2026-02-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0012_dummyewpactivitymodel_dummygpdmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyewpactivitymodel',
            name='wbs',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dummygpdmodel',
            name='gpd_ref',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
