# Generated by Django 2.2.1 on 2019-09-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0013_auto_20190919_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringactivity',
            name='activity_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('tpm', 'TPM')], default='staff', max_length=10),
        ),
    ]
