# Generated by Django 3.2.6 on 2023-02-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0013_merge_0008_auto_20210108_1634_0012_auto_20210709_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontemplate',
            name='translations',
            field=models.JSONField(default=dict, verbose_name='Translations'),
        ),
    ]
