# Generated by Django 3.2.19 on 2024-04-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0014_auto_20240402_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringactivity',
            name='report_reviewer_preliminary',
        ),
    ]
