# Generated by Django 4.2.23 on 2026-03-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
        ('field_monitoring_planning', '0015_fix_ewpactivity_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewpactivity',
            name='activity',
            field=models.ForeignKey(blank=True, limit_choices_to={'result_type__name': 'Activity'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fm_ewp_activities', to='reports.result', verbose_name='Activity'),
        ),
    ]
