# Generated by Django 2.2.1 on 2019-09-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0015_auto_20190920_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringactivity',
            name='interventions',
            field=models.ManyToManyField(blank=True, related_name='monitoring_activities', to='partners.Intervention', verbose_name='PD/SSFA'),
        ),
    ]
