# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


def migrate_focal_points(apps, schema_editor):
    TPMActivity = apps.get_model('tpm', 'TPMActivity')

    for activity in TPMActivity.objects.all():
        activity.unicef_focal_points.add(*activity.tpm_visit.unicef_focal_points.all())


def migrate_focal_points_backward(apps, schema_editor):
    TPMActivity = apps.get_model('tpm', 'TPMActivity')

    for activity in TPMActivity.objects.all():
        activity.tpm_visit.unicef_focal_points.add(*activity.unicef_focal_points.all())


def migrate_offices(apps, schema_editor):
    TPMActivity = apps.get_model('tpm', 'TPMActivity')

    for activity in TPMActivity.objects.all():
        activity.offices.add(*activity.tpm_visit.offices.all())


def migrate_offices_backward(apps, schema_editor):
    TPMActivity = apps.get_model('tpm', 'TPMActivity')

    for activity in TPMActivity.objects.all():
        activity.tpm_visit.offices.add(*activity.offices.all())


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tpm', '0002_tpmvisit_cancel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmactivity',
            name='unicef_focal_points',
            field=models.ManyToManyField(blank=True, related_name='_tpmactivity_unicef_focal_points_+', to=settings.AUTH_USER_MODEL, verbose_name='UNICEF Focal Points'),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='_tpmactivity_offices_+', to='users.Office', verbose_name='Office(s) of UNICEF Focal Point(s)'),
        ),
        migrations.RunPython(migrate_focal_points, migrate_focal_points_backward),
        migrations.RunPython(migrate_offices, migrate_offices_backward),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='unicef_focal_points',
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='offices',
        ),
    ]
