# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-02 13:52
from __future__ import unicode_literals

from django.db import migrations


def update_email_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('post_office', 'EmailTemplate')

    EmailTemplate.objects.get_or_create(name='tpm/visit/assign')
    EmailTemplate.objects.get_or_create(name='tpm/visit/reject')
    EmailTemplate.objects.get_or_create(name='tpm/visit/accept')
    EmailTemplate.objects.get_or_create(name='tpm/visit/generate_report')
    EmailTemplate.objects.get_or_create(name='tpm/visit/report')
    EmailTemplate.objects.get_or_create(name='tpm/visit/report_rejected')
    EmailTemplate.objects.get_or_create(name='tpm/visit/approve_report')
    EmailTemplate.objects.get_or_create(name='tpm/visit/approve_report_tpm')
    EmailTemplate.objects.get_or_create(name='tpm/visit/action_point_assigned')


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0003_auto_20170310_1402'),
    ]

    operations = [
        migrations.RunPython(update_email_templates, migrations.RunPython.noop)
    ]
