# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-14 14:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0003_auto_20170310_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMPVisitQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(b'quality', b'Quality'), (b'access', b'Access')], max_length=20)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TPMPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=30)),
                ('permission', models.CharField(choices=[(b'view', b'View'), (b'edit', b'Edit'), (b'action', b'Action')], max_length=10)),
                ('target', models.CharField(max_length=100)),
                ('tpm_visit_status', models.CharField(choices=[(b'draft', b'Draft'), (b'submitted', b'Submitted'), (b'tpm_accepted', b'TPM Accepted'), (b'tpm_rejected', b'TPM Rejected'), (b'unicef_confirmed', b'Confirmed'), (b'tpm_reported', b'TPM Reported'), (b'unicef_approved', b'Approved')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='tpmvisitreport',
            name='selected_indicators',
        ),
        migrations.AddField(
            model_name='tpmvisitreport',
            name='methodologies_used',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(b'focus_group_discussions', b'Focus Group Discussions'), (b'key_informant_interviews', b'Key Informant Interviews'), (b'measurement', b'Measurement'), (b'observation', b'Observation')], max_length=30), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tpmvisitreport',
            name='recommendations',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tpmvisitreport',
            name='supply_list_comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tpmvisitreportedindicator',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tpmvisitreportedindicator',
            name='verification',
            field=models.CharField(choices=[(b'na', b'N/A'), (b'verified', b'Verified'), (b'unverified', b'Unverified')], default=b'na', max_length=10),
        ),
        migrations.AddField(
            model_name='tpmvisitreportedindicator',
            name='verified_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='status',
            field=django_fsm.FSMField(choices=[(b'draft', b'Draft'), (b'submitted', b'Submitted'), (b'tpm_accepted', b'TPM Accepted'), (b'tpm_rejected', b'TPM Rejected'), (b'unicef_confirmed', b'Confirmed'), (b'tpm_reported', b'TPM Reported'), (b'unicef_approved', b'Approved')], default=b'draft', max_length=20, protected=True),
        ),
        migrations.AlterField(
            model_name='tpmvisitreportedindicator',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.IndicatorReport'),
        ),
        migrations.AlterUniqueTogether(
            name='tpmpermission',
            unique_together=set([('user_type', 'tpm_visit_status', 'target')]),
        ),
        migrations.AddField(
            model_name='tmpvisitquestion',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tpm.TPMVisitReport'),
        ),
    ]
