# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-08 13:53
from __future__ import unicode_literals

from django.db import migrations


def migrate_tpm_partners(apps, schema_editor):
    TargetTPMPartner = apps.get_model('tpmpartners', 'TPMPartner')
    TargetTPMPartnerStaffMember = apps.get_model('tpmpartners', 'TPMPartnerStaffMember')

    SourceTPMPartner = apps.get_model('tpm', 'TPMPartner')
    SourceTPMPartnerStaffMember = apps.get_model('tpm', 'TPMPartnerStaffMember')

    partners = dict()
    for partner in SourceTPMPartner.objects.all():
        if TargetTPMPartner.objects.filter(vendor_number=partner.vendor_number).exists():
            partner = TargetTPMPartner.objects.get(vendor_number=partner.vendor_number)

        else:
            partner.__class__ = TargetTPMPartner
            partner.id = None
            partner.save()

        partners[partner.vendor_number] = partner

    for staff_member in SourceTPMPartnerStaffMember.objects.select_related('tpm_partner'):
        if not TargetTPMPartnerStaffMember.objects.filter(user_id=staff_member.user_id).exists():
            staff_member.__class__ = TargetTPMPartnerStaffMember
            staff_member.id = None
            staff_member.tpm_partner = partners[staff_member.tpm_partner.vendor_number]
            staff_member.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0004_auto_20171214_0802'),
        ('tpmpartners', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            migrate_tpm_partners,
        ),
    ]
