# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-14 14:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


def delete_visits(apps, schema_editor):
    TPMVisit = apps.get_model('tpm', 'TPMVisit')
    TPMVisit.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0004_auto_20170314_1640'),
    ]

    operations = [
        migrations.RunPython(
            delete_visits,
        ),
    ]
