# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-31 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_workspacecounter'),
        ('tpm', '0005_1_auto_20170407_1638'),
        ('tpm', '0004_auto_20170314_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPMPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('vendor_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name=b'Vendor Name')),
                ('street_address', models.CharField(blank=True, max_length=500L, null=True)),
                ('city', models.CharField(blank=True, max_length=32L, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=32L, null=True)),
                ('country', models.CharField(blank=True, max_length=32L, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32L, null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TPMPartnerStaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64L, null=True)),
                ('first_name', models.CharField(max_length=64L)),
                ('last_name', models.CharField(max_length=64L)),
                ('email', models.CharField(max_length=128L, unique=True)),
                ('phone', models.CharField(blank=True, max_length=64L)),
                ('active', models.BooleanField(default=True)),
                ('receive_tpm_notifications', models.BooleanField(default=False)),
                ('tpm_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='tpm.TPMPartner')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_member_profile', to='users.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='hyperlink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b'files'),
        ),
        migrations.AlterField(
            model_name='tpmpermission',
            name='user_type',
            field=models.CharField(choices=[(b'UNICEF User', b'UNICEF User'), (b'Third Party Monitor', b'Third Party Monitor'), (b'Planning, Monitoring & Evaluation', b'Planning, Monitoring & Evaluation'), (b'UNICEF Focal Point', b'UNICEF Focal Point')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='tpm_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpm.TPMPartner'),
        ),
        migrations.AlterField(
            model_name='tpmvisitreport',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tpmvisitreport',
            name='supply_list_comment',
            field=models.TextField(blank=True),
        ),
    ]
