# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-09 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0004_auto_20171002_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmactivity',
            name='cp_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Result', verbose_name='CP Output'),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='implementing_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization', verbose_name='Implementing Partner'),
        ),
    ]
