# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-19 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0005_auto_20171009_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmpartner',
            name='date_of_active',
        ),
        migrations.RemoveField(
            model_name='tpmpartner',
            name='date_of_cancel',
        ),
        migrations.RemoveField(
            model_name='tpmpartner',
            name='status',
        ),
    ]
