# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-10 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0005_auto_20170331_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetype',
            name='code',
            field=models.CharField(default=b'', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='filetype',
            unique_together=set([('name', 'code')]),
        ),
    ]
