# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-13 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0006_auto_20171019_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tpmpartner',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='tpmpartnerstaffmember',
            options={'verbose_name': 'Staff Member', 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Blocked in VISION'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='deleted_flag',
            field=models.BooleanField(default=False, verbose_name='Marked For Deletion in VISION'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Vendor Name'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='postal_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='street_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='vendor_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Vendor Number'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='vision_synced',
            field=models.BooleanField(default=False, verbose_name='Synced from VISION'),
        ),
        migrations.AlterField(
            model_name='tpmpartnerstaffmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_tpmpartnerstaffmember', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
