# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-08 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0007_auto_20171208_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmpartnerstaffmember',
            name='tpm_partner',
        ),
        migrations.RemoveField(
            model_name='tpmpartnerstaffmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='tpm_partner',
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='tpm_partner_focal_points',
        ),
        migrations.DeleteModel(
            name='TPMPartner',
        ),
        migrations.DeleteModel(
            name='TPMPartnerStaffMember',
        ),
        migrations.RenameField(
            model_name='tpmvisit',
            old_name='tpm_partner1',
            new_name='tpm_partner',
        ),
        migrations.RenameField(
            model_name='tpmvisit',
            old_name='tpm_partner_focal_points1',
            new_name='tpm_partner_focal_points',
        ),
    ]
