# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-13 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0006_auto_20170410_1431'),
        ('tpm', '0007_auto_20170406_1810'),
    ]

    operations = [
    ]
