# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-08 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_tpm_partner_relation(apps, schema_editor):
    TPMVisit = apps.get_model('tpm', 'TPMVisit')
    TargetTPMPartner = apps.get_model('tpmpartners', 'TPMPartner')
    TargetTPMPartnerStaffMember = apps.get_model('tpmpartners', 'TPMPartnerStaffMember')

    partner_cache = dict()
    for visit in TPMVisit._default_manager.select_related('tpm_partner'):
        tpm_partner = partner_cache.get(visit.tpm_partner.vendor_number, None)
        if tpm_partner is None:
            tpm_partner = TargetTPMPartner.objects.get(vendor_number=visit.tpm_partner.vendor_number)
            partner_cache[tpm_partner.vendor_number] = tpm_partner

        visit.tpm_partner1 = tpm_partner
        visit.save()

    staff_member_cache = dict()
    for visit in TPMVisit._default_manager.prefetch_related('tpm_partner_focal_points'):

        target_staff_members = []
        for staff_member in visit.tpm_partner_focal_points.all():

            target_staff_member = staff_member_cache.get(staff_member.user_id, None)
            if target_staff_member is None:
                target_staff_member = TargetTPMPartnerStaffMember.objects.get(user_id=staff_member.user_id)
                staff_member_cache[target_staff_member.user_id] = target_staff_member

            target_staff_members.append(target_staff_member)

        visit.tpm_partner_focal_points1 = target_staff_members


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0008_auto_20171208_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmvisit',
            name='tpm_partner1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tpmpartners.TPMPartner', verbose_name='TPM Vendor'),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='tpm_partner_focal_points1',
            field=models.ManyToManyField(blank=True, related_name='tpm_visits', to='tpmpartners.TPMPartnerStaffMember', verbose_name='TPM Focal Points'),
        ),
        migrations.RunPython(
            migrate_tpm_partner_relation,
        ),
    ]
