# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-07 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def copy_fields(apps, schema_editor):
    TPMActivity = apps.get_model('tpm', 'TPMActivity')
    for activity in TPMActivity.objects.all().prefetch_related('locations'):
        activity.cp_output1 = activity.cp_output
        activity.date1 = activity.date
        activity.intervention1 = activity.intervention
        activity.partner1 = activity.partner
        activity.locations1.add(*activity.locations.all())
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0054_auto_20171013_2147'),
        ('reports', '0014_auto_20171013_2147'),
        ('locations', '0004_auto_20170112_2051'),
        ('tpm', '0008_auto_20171207_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmactivity',
            name='cp_output1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reports.Result', verbose_name='CP Output'),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='date1',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='intervention1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.Intervention', verbose_name='partnership'),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='locations1',
            field=models.ManyToManyField(related_name='_tpmactivity_locations1_+', to='locations.Location', verbose_name='Locations'),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='partner1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.PartnerOrganization', verbose_name='Implementing Partner'),
        ),
        migrations.RunPython(copy_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='cp_output',
        ),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='intervention',
        ),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='partner',
        ),
    ]
