# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-26 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_sections_to_sectors(apps, schema_editor):
    Sector = apps.get_model('reports', 'Sector')
    TPMActivity = apps.get_model('tpm', 'TPMActivity')

    first_sector = Sector.objects.first()

    for activity in TPMActivity.objects.all():
        activity.section = Sector.objects.filter(name=activity.section1.name).first() or first_sector
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0008_auto_20171208_1421'),
        ('users', '0010_auto_20171127_2158'),
        ('reports', '0017_indicators_p2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmactivity',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_activities', to='users.Section', null=True, verbose_name='Section'),
        ),
        migrations.RenameField(
            model_name='tpmactivity',
            old_name='section',
            new_name='section1',
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Sector', null=True),
        ),
        migrations.RunPython(migrate_sections_to_sectors, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='section1',
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_activities', to='reports.Sector', verbose_name='Section'),
        ),
    ]
