# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-07 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def copy_activity_ptr(apps, schema_editor):
    apps.get_model('tpm', 'TPMActivity').objects.all().update(activity_ptr=models.F('id'))


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0009_auto_20171207_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmactivity',
            name='activity_ptr',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(copy_activity_ptr, migrations.RunPython.noop),
    ]
