# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-12 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0009_auto_20180226_0911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TPMPermission',
        ),
    ]
