# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-19 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0009_auto_20170414_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tpmpermission',
            old_name='tpm_visit_status',
            new_name='instance_status',
        ),
        migrations.AlterField(
            model_name='tpmpermission',
            name='user_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tpmpermission',
            name='instance_status',
            field=models.CharField(choices=[('new', 'New instance'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('tpm_accepted', 'TPM Accepted'), ('tpm_rejected', 'TPM Rejected'), ('unicef_confirmed', 'Confirmed'), ('tpm_reported', 'TPM Reported'), ('unicef_approved', 'Approved')], max_length=32),
        ),
    ]
