# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-07 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0011_auto_20171207_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmactivity',
            name='cp_output1',
        ),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='intervention1',
        ),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='locations1',
        ),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='partner1',
        ),
    ]
