# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-29 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0013_auto_20170421_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmpartnerstaffmember',
            name='active',
        ),
        migrations.RemoveField(
            model_name='tpmpartnerstaffmember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tpmpartnerstaffmember',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tpmpartnerstaffmember',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tpmpartnerstaffmember',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='tpmpartnerstaffmember',
            name='title',
        ),
    ]
