# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-02 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def remove_staff_member_without_user(apps, schema_editor):
    TPMPartnerStaffMember = apps.get_model('tpm', 'TPMPartnerStaffMember')

    TPMPartnerStaffMember.objects.filter(user__isnull=True).delete()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0014_auto_20170429_1504'),
    ]

    operations = [
        migrations.RunPython(
            remove_staff_member_without_user,
            do_nothing
        ),
        migrations.AlterField(
            model_name='tpmpartnerstaffmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_tpmpartnerstaffmember', to=settings.AUTH_USER_MODEL),
        ),
    ]
