# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-06 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0015_auto_20170502_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmpermission',
            name='permission_type',
            field=models.CharField(choices=[('allow', 'Allow'), ('disallow', 'Disallow')], default='allow', max_length=10),
        ),
        migrations.AlterField(
            model_name='tpmpermission',
            name='user_type',
            field=models.CharField(choices=[('UNICEF Focal Point', 'UNICEF Focal Point'), ('Planning, Monitoring & Evaluation', 'Planning, Monitoring & Evaluation'), ('Third Party Monitor', 'Third Party Monitor'), ('UNICEF User', 'UNICEF User')], max_length=30),
        ),
    ]
