# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-10 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0016_auto_20170506_0833'),
        ('tpm', '0016_auto_20170505_1617'),
    ]

    operations = [
    ]
