# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-15 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0018_auto_20170511_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmpartner',
            name='is_removed',
        ),
    ]
