# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-15 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0019_remove_tpmpartner_is_removed'),
        ('tpm', '0019_auto_20170515_1317'),
    ]

    operations = [
    ]
