# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-22 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0020_merge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tpmpermission',
            unique_together=set([('user_type', 'instance_status', 'target', 'permission_type')]),
        ),
    ]
