# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-08 10:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0021_auto_20170522_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tpmpartner',
            options={'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterModelOptions(
            name='tpmpartnerstaffmember',
            options={'verbose_name': 'staff member', 'verbose_name_plural': 'staff members'},
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='blocked'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='city',
            field=models.CharField(blank=True, max_length=255L, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='country',
            field=models.CharField(blank=True, max_length=255L, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='vendor name'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32L, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='postal_code',
            field=models.CharField(blank=True, max_length=32L, null=True, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='street_address',
            field=models.CharField(blank=True, max_length=500L, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='vendor_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='vendor number'),
        ),
        migrations.AlterField(
            model_name='tpmpartnerstaffmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_tpmpartnerstaffmember', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
