# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-15 13:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0022_auto_20170608_1000'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tpmvisit',
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='is_removed',
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
