# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-16 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0029_auto_20170517_2017'),
        ('reports', '0008_auto_20170330_1931'),
        ('tpm', '0023_auto_20170615_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPMActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.Intervention')),
            ],
            options={
                'verbose_name_plural': 'TPM Activities',
            },
        ),
        migrations.CreateModel(
            name='TPMLowResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='partners.InterventionResultLink')),
            ],
        ),
        migrations.CreateModel(
            name='TPMSectorCovered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Sector')),
                ('tpm_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_sectors', to='tpm.TPMActivity')),
            ],
            options={
                'verbose_name_plural': 'TPM Sectors Covered',
            },
        ),
        migrations.RemoveField(
            model_name='tpmvisitquestion',
            name='report',
        ),
        migrations.RemoveField(
            model_name='tpmvisitquestion',
            name='tpm_location',
        ),
        migrations.RemoveField(
            model_name='tpmvisitreportedindicator',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='tpmvisitreportedindicator',
            name='report',
        ),
        migrations.RemoveField(
            model_name='tpmlocation',
            name='sectors_covered',
        ),
        migrations.RemoveField(
            model_name='tpmlocation',
            name='tpm_visit',
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='partnership',
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='results',
        ),
        migrations.RemoveField(
            model_name='tpmvisitreport',
            name='methodologies_used',
        ),
        migrations.RemoveField(
            model_name='tpmvisitreport',
            name='request_verify_supply_list',
        ),
        migrations.RemoveField(
            model_name='tpmvisitreport',
            name='supply_list_comment',
        ),
        migrations.AddField(
            model_name='tpmlocation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmlocation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmpermission',
            name='instance_status',
            field=models.CharField(choices=[('new', 'New instance'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('tpm_accepted', 'TPM Accepted'), ('tpm_rejected', 'TPM Rejected'), ('tpm_reported', 'TPM Reported'), ('tpm_action_required', 'TPM Action required'), ('unicef_approved', 'Approved')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('tpm_accepted', 'TPM Accepted'), ('tpm_rejected', 'TPM Rejected'), ('tpm_reported', 'TPM Reported'), ('tpm_action_required', 'TPM Action required'), ('unicef_approved', 'Approved')], default='draft', max_length=20, protected=True),
        ),
        migrations.DeleteModel(
            name='TPMVisitQuestion',
        ),
        migrations.DeleteModel(
            name='TPMVisitReportedIndicator',
        ),
        migrations.AddField(
            model_name='tpmlowresult',
            name='tpm_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_low_results', to='tpm.TPMSectorCovered'),
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='tpm_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_activities', to='tpm.TPMVisit'),
        ),
        migrations.AddField(
            model_name='tpmlocation',
            name='tpm_low_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpm_locations', to='tpm.TPMLowResult'),
        ),
    ]
