# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-26 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0024_auto_20170616_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmpermission',
            name='instance_status',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='tpmpermission',
            name='user_type',
            field=models.CharField(max_length=30),
        ),
    ]
