# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-26 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tpm', '0025_auto_20170626_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmvisit',
            name='unicef_focal_points',
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='unicef_focal_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpm_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
