# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-28 12:01
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0026_auto_20170626_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmvisitreport',
            name='tpm_visit',
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='visit_end',
        ),
        migrations.RemoveField(
            model_name='tpmvisit',
            name='visit_start',
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('tpm_accepted', 'TPM Accepted'), ('tpm_rejected', 'TPM Rejected'), ('tpm_reported', 'TPM Reported'), ('submitted', 'Submitted'), ('unicef_approved', 'Approved')], default='draft', max_length=20, protected=True),
        ),
        migrations.DeleteModel(
            name='TPMVisitReport',
        ),
    ]
