# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-28 10:38
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0026_auto_20170626_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmpartner',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='draft', max_length=20, protected=True),
        ),
    ]
