# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-28 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


def migrate_focal_points(apps, schema_editor):
    TPMActivity = apps.get_model('tpm', 'TPMActivity')

    for activity in TPMActivity.objects.all():
        activity.unicef_focal_points.add(activity.unicef_focal_point)


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tpm', '0027_auto_20170628_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmactivity',
            name='unicef_focal_points',
            field=models.ManyToManyField(related_name='tpm_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_focal_points, do_nothing),
        migrations.RemoveField(
            model_name='tpmactivity',
            name='unicef_focal_point',
        ),
    ]
