# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-29 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0027_tpmpartner_status'),
        ('tpm', '0028_auto_20170628_1308'),
    ]

    operations = [
    ]
