# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-11 08:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0029_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmactivity',
            name='partnership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.Intervention', verbose_name='partnership'),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='tpm_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_activities', to='tpm.TPMVisit', verbose_name='visit'),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='unicef_focal_points',
            field=models.ManyToManyField(related_name='tpm_activities', to=settings.AUTH_USER_MODEL, verbose_name='UNICEF Focal Point'),
        ),
        migrations.AlterField(
            model_name='tpmlocation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='tpmlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='tpmlocation',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='tpmlocation',
            name='tpm_low_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tpm_locations', to='tpm.TPMLowResult', verbose_name='low_result'),
        ),
        migrations.AlterField(
            model_name='tpmlocation',
            name='type_of_site',
            field=models.CharField(blank=True, max_length=255, verbose_name='Type of site'),
        ),
        migrations.AlterField(
            model_name='tpmlowresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.InterventionResultLink', verbose_name='PD/SSFA Output'),
        ),
        migrations.AlterField(
            model_name='tpmlowresult',
            name='tpm_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_low_results', to='tpm.TPMSectorCovered', verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='draft', max_length=20, protected=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='tpmpartnerstaffmember',
            name='receive_tpm_notifications',
            field=models.BooleanField(default=False, verbose_name='Receive Notifications on TPM Tasks'),
        ),
        migrations.AlterField(
            model_name='tpmpartnerstaffmember',
            name='tpm_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='tpm.TPMPartner', verbose_name='TPM Vendor'),
        ),
        migrations.AlterField(
            model_name='tpmsectorcovered',
            name='sector',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Sector', verbose_name='Sector covered'),
        ),
        migrations.AlterField(
            model_name='tpmsectorcovered',
            name='tpm_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_sectors', to='tpm.TPMActivity', verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='reject_comment',
            field=models.TextField(blank=True, verbose_name='Request for more information'),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('tpm_accepted', 'TPM Accepted'), ('tpm_rejected', 'TPM Rejected'), ('tpm_reported', 'TPM Reported'), ('submitted', 'Submitted'), ('unicef_approved', 'Approved')], default='draft', max_length=20, protected=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='tpm_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpm.TPMPartner', verbose_name='TPM Vendor'),
        ),
    ]
