# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-11 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0030_auto_20170711_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmvisit',
            name='tpm_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tpm.TPMPartner', verbose_name='TPM Vendor'),
        ),
    ]
