# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-11 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0031_auto_20170711_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmpartner',
            name='date_of_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmpartner',
            name='date_of_cancel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='date_of_assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='date_of_tpm_accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='date_of_tpm_rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='date_of_tpm_reported',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='date_of_unicef_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('tpm_accepted', 'TPM Accepted'), ('tpm_rejected', 'TPM Rejected'), ('tpm_reported', 'TPM Reported'), ('unicef_approved', 'UNICEF Approved')], default='draft', max_length=20, protected=True, verbose_name='status'),
        ),
    ]
