# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-16 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0033_auto_20170815_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPMVisitReportRejectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected_at', models.DateTimeField(auto_now=True)),
                ('reject_reason', models.TextField()),
                ('tpm_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_reject_comments', to='tpm.TPMVisit', verbose_name='visit')),
            ],
            options={
                'verbose_name_plural': 'Report Reject Comments',
            },
        ),
    ]
