# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-16 10:16
from __future__ import unicode_literals

from django.db import migrations


def create_email_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('post_office', 'EmailTemplate')

    EmailTemplate.objects.get_or_create(name='tpm/visit/report_rejected')


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0034_tpmvisitreportrejectcomment'),
    ]

    operations = [
        migrations.RunPython(
            create_email_templates,
            do_nothing,
        ),
    ]
