# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-16 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_indicator_active'),
        ('tpm', '0035_auto_20170816_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmactivity',
            name='result',
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='cp_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Result', verbose_name='CP Output'),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('tpm_accepted', 'TPM Accepted'), ('tpm_rejected', 'TPM Rejected'), ('tpm_reported', 'TPM Reported'), ('tpm_report_rejected', 'TPM Report Rejected'), ('unicef_approved', 'UNICEF Approved')], default='draft', max_length=20, protected=True, verbose_name='status'),
        ),
    ]
