# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-16 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0036_auto_20170816_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmvisit',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='tpm_visits', to='users.Section'),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='unicef_focal_points',
            field=models.ManyToManyField(blank=True, related_name='tpm_visits', to=settings.AUTH_USER_MODEL, verbose_name='UNICEF Focal Point'),
        ),
    ]
