# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-17 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0038_auto_20170816_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmactivity',
            name='is_pv',
            field=models.BooleanField(default=False),
        ),
    ]
