# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-16 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0038_auto_20170816_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmvisit',
            name='date_of_tpm_report_rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('cancelled', 'Cancelled'), ('tpm_accepted', 'TPM Accepted'), ('tpm_rejected', 'TPM Rejected'), ('tpm_reported', 'TPM Reported'), ('tpm_report_rejected', 'TPM Report Rejected'), ('unicef_approved', 'UNICEF Approved')], default='draft', max_length=20, protected=True, verbose_name='status'),
        ),
    ]
