# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-17 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0039_auto_20170816_1456'),
        ('tpm', '0039_tpmactivity_is_pv'),
    ]

    operations = [
    ]
