# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-17 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0040_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmpartner',
            name='date_of_active',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmpartner',
            name='date_of_cancel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='date_of_assigned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='date_of_cancelled',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='date_of_tpm_accepted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='date_of_tpm_rejected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='date_of_tpm_report_rejected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='date_of_tpm_reported',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='date_of_unicef_approved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
