# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-18 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_workspacecounter'),
        ('tpm', '0041_auto_20170817_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmvisit',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='tpm_visits', to='users.Office'),
        ),
        migrations.AddField(
            model_name='tpmvisit',
            name='tpm_partner_focal_points',
            field=models.ManyToManyField(blank=True, related_name='tpm_visits', to='tpm.TPMPartnerStaffMember', verbose_name='TPM Focal Points'),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='unicef_focal_points',
            field=models.ManyToManyField(blank=True, related_name='tpm_visits', to=settings.AUTH_USER_MODEL, verbose_name='UNICEF Focal Points'),
        ),
    ]
