# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-18 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0041_tpmactivityactionpoint'),
        ('tpm', '0041_auto_20170817_1238'),
    ]

    operations = [
    ]
