# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-18 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0042_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmactivityactionpoint',
            name='due_date',
            field=models.DateField(),
        ),
    ]
