# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-18 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F


def update_ip(apps, schema_editor):
    TPMActivity = apps.get_model('tpm', 'TPMActivity')
    for activity in TPMActivity.objects.all():
        activity.implementing_partner=activity.partnership.agreement.partner
        activity.save()


def do_nothing(*args):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0043_tpmactivity_implementing_partner'),
    ]

    operations = [
        migrations.RunPython(update_ip, do_nothing),
    ]
