# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-18 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0044_auto_20170818_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmactivity',
            name='implementing_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization', verbose_name='Implementing Partner'),
        ),
    ]
