# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-22 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0045_auto_20170818_1157'),
        ('tpm', '0043_auto_20170818_0809'),
    ]

    operations = [
    ]
