# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-29 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tpm', '0047_auto_20170824_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmactivityactionpoint',
            name='follow_up',
        ),
        migrations.AddField(
            model_name='tpmactivityactionpoint',
            name='follow_up_users',
            field=models.ManyToManyField(blank=True, related_name='followed_up_tpm_activity_action_points', to=settings.AUTH_USER_MODEL),
        ),
    ]
