# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-30 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields

def do_nothing(*args):
    pass

def clean(apps, schema_editor):
    apps.get_model('tpm', 'TPMActivityActionPoint').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0048_auto_20170829_1341'),
    ]

    operations = [
        migrations.RunPython(clean, do_nothing),
        migrations.RemoveField(
            model_name='tpmactivityactionpoint',
            name='actions_taken',
        ),
        migrations.RemoveField(
            model_name='tpmactivityactionpoint',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='tpmactivityactionpoint',
            name='cp_outputs',
        ),
        migrations.RemoveField(
            model_name='tpmactivityactionpoint',
            name='follow_up_users',
        ),
        migrations.RemoveField(
            model_name='tpmactivityactionpoint',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='tpmactivityactionpoint',
            name='section',
        ),
        migrations.AddField(
            model_name='tpmactivityactionpoint',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tpmactivityactionpoint',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='tpmactivityactionpoint',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='tpmactivityactionpoint',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('progress', 'In-Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=9, verbose_name='Status'),
        ),
    ]
