# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-31 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0049_auto_20170830_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmactivity',
            name='additional_information',
            field=models.TextField(blank=True, verbose_name='Additional Information'),
        ),
    ]
