# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-31 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_workspacecounter'),
        ('tpm', '0050_tpmactivity_additional_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpmvisit',
            name='sections',
        ),
        migrations.AddField(
            model_name='tpmactivity',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tpm_activities', to='users.Section', null=True),
            preserve_default=False,
        ),
    ]
