# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-31 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def fill_sections(apps, schema_editor):
    TPMActivity = apps.get_model('tpm', 'tpmactivity')
    Section = apps.get_model('users', 'Section')
    TPMActivity.objects.all().update(section=Section.objects.first())


def do_nothing(*args):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0051_auto_20170831_1345'),
    ]

    operations = [
        migrations.RunPython(fill_sections, do_nothing),
    ]
