# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-31 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0052_auto_20170831_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmactivity',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_activities', to='users.Section'),
        ),
    ]
