# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0054_auto_20170901_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmvisit',
            name='visit_information',
            field=models.TextField(blank=True, verbose_name='Visit Information'),
        ),
    ]
