# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-05 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tpm', '0056_auto_20170905_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPMActionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('due_date', models.DateField()),
                ('description', models.TextField()),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('progress', 'In-Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=9, verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tpm_action_points', to=settings.AUTH_USER_MODEL)),
                ('person_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpm_action_points', to=settings.AUTH_USER_MODEL)),
                ('tpm_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_points', to='tpm.TPMVisit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tpmactivityactionpoint',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tpmactivityactionpoint',
            name='person_responsible',
        ),
        migrations.RemoveField(
            model_name='tpmactivityactionpoint',
            name='tpm_activity',
        ),
        migrations.DeleteModel(
            name='TPMActivityActionPoint',
        ),
    ]
