# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-28 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0059_auto_20170915_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmactivity',
            name='is_pv',
            field=models.BooleanField(default=False, verbose_name='Programmatic Visit'),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='tpm_visits', to='users.Office', verbose_name='Office(s) of UNICEF Focal Point(s)'),
        ),
    ]
