# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-27 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0059_auto_20170915_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmactivity',
            name='cp_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reports.Result', verbose_name='CP Output'),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='implementing_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.PartnerOrganization', verbose_name='Implementing Partner'),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='locations',
            field=models.ManyToManyField(related_name='_tpmactivity_locations_+', to='locations.Location', verbose_name='Locations'),
        ),
        migrations.AlterField(
            model_name='tpmactivity',
            name='partnership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Intervention', verbose_name='partnership'),
        ),
        migrations.AlterField(
            model_name='tpmvisit',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='tpm_visits', to='users.Office', verbose_name='Office(s) of UNICEF Focal Point(s)'),
        ),
    ]
