# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-29 09:31
from __future__ import unicode_literals

from django.db import migrations


def update_email_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('post_office', 'EmailTemplate')

    EmailTemplate.objects.get_or_create(name='tpm/visit/action_point_assigned')


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0060_auto_20170928_0928'),
    ]

    operations = [
        migrations.RunPython(
            update_email_templates,
            do_nothing,
        ),
    ]
