# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-29 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpm', '0060_auto_20170927_1616'),
        ('tpm', '0061_auto_20170929_0931'),
    ]

    operations = [
    ]
