# Generated by Django 4.2.3 on 2024-10-10 15:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0004_question_other'),
        ('reports', '0002_initial'),
        ('locations', '0001_initial'),
        ('funds', '0003_fundsreservationheader_gov_intervention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0004_interventionreview_authorized_officer_and_more'),
        ('governments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GovIntervention',
            new_name='GDD',
        ),
    ]
