# Generated by Django 4.2.3 on 2024-10-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governments', '0002_remove_ewpactivity_ewp_result_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='governmentewp',
            old_name='cp_output',
            new_name='country_programme',
        ),
    ]
