# Generated by Django 4.2.3 on 2025-01-21 10:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import etools.applications.governments.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
        ('governments', '0002_alter_gddrisk_risk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdd',
            name='lead_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='government_gdds', to='reports.section', verbose_name='Lead Section'),
        ),
        migrations.AlterField(
            model_name='gdd',
            name='cash_transfer_modalities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('payment', 'Direct Payment'), ('reimbursement', 'Reimbursement'), ('dct', 'Direct Cash Transfer')], max_length=50, verbose_name='Cash Transfer Modalities'), default=etools.applications.governments.models.get_default_cash_transfer_modalities, size=None),
        ),
        migrations.AlterField(
            model_name='gdd',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='gdds', to='reports.section', verbose_name='Contributing Sections'),
        ),
    ]
