# Generated by Django 4.2.3 on 2025-01-22 13:28

import django.contrib.postgres.fields
from django.db import migrations, models
import etools.applications.governments.models


class Migration(migrations.Migration):

    dependencies = [
        ('governments', '0002_alter_gddrisk_risk_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdd',
            name='cash_transfer_modalities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('payment', 'Direct Payment'), ('reimbursement', 'Reimbursement'), ('dct', 'Direct Cash Transfer')], max_length=50, verbose_name='Cash Transfer Modalities'), default=etools.applications.governments.models.get_default_cash_transfer_modalities, size=None),
        ),
    ]
