# Generated by Django 4.2.3 on 2024-10-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
        ('governments', '0005_rename_workplan_id_governmentewp_ewp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gddresultlink',
            name='cp_output',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='result_links', to='reports.result', verbose_name='CP Output'),
            preserve_default=False,
        ),
    ]
