# Generated by Django 4.2.3 on 2024-10-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governments', '0007_remove_ewpactivity_cp_key_intervention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewpactivity',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='WPA Title'),
        ),
        migrations.AlterField(
            model_name='ewpactivity',
            name='wpa_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Workplan Activity ID'),
        ),
        migrations.AlterField(
            model_name='ewpactivity',
            name='wpa_wbs',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Workplan Activity WBS'),
        ),
        migrations.AlterField(
            model_name='governmentewp',
            name='cost_center_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Cost Center Code'),
        ),
        migrations.AlterField(
            model_name='governmentewp',
            name='cost_center_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Cost Center Name'),
        ),
        migrations.AlterField(
            model_name='governmentewp',
            name='ewp_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Workplan ID'),
        ),
        migrations.AlterField(
            model_name='governmentewp',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Workplan Name'),
        ),
        migrations.AlterField(
            model_name='governmentewp',
            name='wbs',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Workplan WBS'),
        ),
    ]
