# Generated by Django 4.2.3 on 2024-10-17 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_initial'),
        ('governments', '0007_remove_ewpactivity_cp_key_intervention_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gdd',
            old_name='partner_organization',
            new_name='partner',
        ),
        migrations.AddField(
            model_name='gddsupplyitem',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='governments.gddresultlink', verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='gdd',
            name='country_programme',
            field=models.ForeignKey(blank=True, help_text='Which Country Programme does this GDD belong to?', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='government_gdds', to='reports.countryprogramme', verbose_name='Country Programmes'),
        ),
        migrations.AlterField(
            model_name='gddprcofficerreview',
            name='overall_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdd_prc_reviews', to='governments.gddreview'),
        ),
        migrations.AlterField(
            model_name='gddprcofficerreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdd_prc_reviews', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
