# Generated by Django 4.2.3 on 2024-10-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governments', '0008_alter_ewpactivity_title_alter_ewpactivity_wpa_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewpactivity',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Activity End Date'),
        ),
        migrations.AddField(
            model_name='ewpactivity',
            name='other',
            field=models.JSONField(blank=True, null=True, verbose_name='Other'),
        ),
        migrations.AddField(
            model_name='ewpactivity',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Activity Start Date'),
        ),
        migrations.AddField(
            model_name='governmentewp',
            name='other',
            field=models.JSONField(blank=True, null=True, verbose_name='Other'),
        ),
    ]
