# Generated by Django 4.2.3 on 2024-10-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governments', '0008_rename_partner_organization_gdd_partner_and_more'),
        ('governments', '0010_rename_wpa_wbs_ewpactivity_wbs'),
    ]

    operations = [
    ]
