# Generated by Django 4.2.3 on 2024-10-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('governments', '0011_merge_20241018_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='gddactivity',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='gdd_activities', to='locations.location'),
        ),
    ]
