# Generated by Django 4.2.3 on 2024-10-23 08:11

from django.conf import settings
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('governments', '0012_gddactivity_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdd',
            name='partner_focal_points',
            field=models.ManyToManyField(blank=True, related_name='gdds_focal_points+', to=settings.AUTH_USER_MODEL, verbose_name='Government Authorized Officials'),
        ),
        migrations.AlterField(
            model_name='gdd',
            name='status',
            field=django_fsm.FSMField(blank=True, choices=[('draft', 'Development'), ('review', 'Review'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('ended', 'Ended'), ('closed', 'Closed'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='draft', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='gdd',
            name='submission_date',
            field=models.DateField(blank=True, help_text='The date the partner submitted complete GDD documents to Unicef', null=True, verbose_name='Document Submission Date by Government'),
        ),
        migrations.AlterField(
            model_name='gddactivity',
            name='cso_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Government Cash'),
        ),
        migrations.AlterField(
            model_name='gddactivityitem',
            name='cso_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Government Cash'),
        ),
        migrations.AlterField(
            model_name='gddprcofficerreview',
            name='budget_is_aligned',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The budget of the proposed GDD is aligned with the principles of value for money with the effective and efficient programme management costs adhering to office defined limits'),
        ),
        migrations.AlterField(
            model_name='gddprcofficerreview',
            name='partner_comparative_advantage',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The partner selection evidences the Government’s comparative advantage and value for money in relation to the planned results'),
        ),
        migrations.AlterField(
            model_name='gddprcofficerreview',
            name='pd_is_guided',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The results framework of the proposed GDD has been guided by M&E feedback during the drafting process'),
        ),
        migrations.AlterField(
            model_name='gddprcofficerreview',
            name='pd_is_relevant',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The proposed GDD is relevant to achieving results in the country programme document, the relevant sector workplan and or humanitarian response plan'),
        ),
        migrations.AlterField(
            model_name='gddprcofficerreview',
            name='relationship_is_represented',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=10, verbose_name='The proposed relationship is best represented and regulated by partnership (as opposed to procurement), with both UNICEF and the Government making clear contributions to the GDD'),
        ),
        migrations.AlterField(
            model_name='gddprcofficerreview',
            name='relationships_are_positive',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='Previous UNICEF/UN relationships with the proposed Government have been positive'),
        ),
        migrations.AlterField(
            model_name='gddreview',
            name='budget_is_aligned',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The budget of the proposed GDD is aligned with the principles of value for money with the effective and efficient programme management costs adhering to office defined limits'),
        ),
        migrations.AlterField(
            model_name='gddreview',
            name='partner_comparative_advantage',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The partner selection evidences the Government’s comparative advantage and value for money in relation to the planned results'),
        ),
        migrations.AlterField(
            model_name='gddreview',
            name='pd_is_guided',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The results framework of the proposed GDD has been guided by M&E feedback during the drafting process'),
        ),
        migrations.AlterField(
            model_name='gddreview',
            name='pd_is_relevant',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='The proposed GDD is relevant to achieving results in the country programme document, the relevant sector workplan and or humanitarian response plan'),
        ),
        migrations.AlterField(
            model_name='gddreview',
            name='relationship_is_represented',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=10, verbose_name='The proposed relationship is best represented and regulated by partnership (as opposed to procurement), with both UNICEF and the Government making clear contributions to the GDD'),
        ),
        migrations.AlterField(
            model_name='gddreview',
            name='relationships_are_positive',
            field=models.CharField(blank=True, choices=[('', 'Not decided yet'), ('a', 'Yes, strongly agree'), ('b', 'Yes, agree'), ('c', 'No, disagree'), ('d', 'No, strongly disagree')], max_length=100, verbose_name='Previous UNICEF/UN relationships with the proposed Government have been positive'),
        ),
    ]
