# Generated by Django 4.2.3 on 2024-10-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governments', '0013_alter_gdd_partner_focal_points_alter_gdd_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdd',
            name='signature_required',
            field=models.BooleanField(default=False, verbose_name='Signature Required'),
        ),
    ]
