# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-14 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triplocation',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='triplocation',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='triplocation',
            name='region',
        ),
    ]
