# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-11 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_linkedpartner_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triplocation',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='triplocation',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='triplocation',
            name='region',
        ),
    ]
