# Generated by Django 2.2.6 on 2019-11-13 10:19

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('field_monitoring_settings', '0001_initial_20191113'),
        ('reports', '0019_auto_20190816_1609'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_monitoring_planning', '0001_initial_20191113'),
        ('partners', '0039_auto_20191106_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_details', models.TextField(blank=True, verbose_name='Specific Details To Probe')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('cp_output',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='reports.Result', verbose_name='Partner')),
                ('intervention',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='partners.Intervention', verbose_name='Partner')),
                ('monitoring_activity',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions',
                                   to='field_monitoring_planning.MonitoringActivity', verbose_name='Activity')),
                ('partner',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='partners.PartnerOrganization', verbose_name='Partner')),
                ('question',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_questions',
                                   to='field_monitoring_settings.Question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Activity Question',
                'verbose_name_plural': 'Activity Questions',
                'ordering': ('monitoring_activity', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StartedChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_source', models.CharField(max_length=100, verbose_name='Information Source')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists',
                                             to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists',
                                             to='field_monitoring_settings.Method', verbose_name='Methods')),
                ('monitoring_activity',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists',
                                   to='field_monitoring_planning.MonitoringActivity', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Started Checklist',
                'verbose_name_plural': 'Started Checklists',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Value')),
                ('activity_question',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings',
                                   to='field_monitoring_data_collection.ActivityQuestion',
                                   verbose_name='Activity Question')),
                ('started_checklist',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings',
                                   to='field_monitoring_data_collection.StartedChecklist', verbose_name='Checklist')),
            ],
            options={
                'verbose_name': 'Checklist Finding',
                'verbose_name_plural': 'Checklist Findings',
                'ordering': ('started_checklist', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistOverallFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative_finding', models.TextField(blank=True, verbose_name='Narrative Finding')),
                ('cp_output',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='reports.Result', verbose_name='Partner')),
                ('intervention',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='partners.Intervention', verbose_name='Partner')),
                ('partner',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='partners.PartnerOrganization', verbose_name='Partner')),
                ('started_checklist',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_findings',
                                   to='field_monitoring_data_collection.StartedChecklist', verbose_name='Checklist')),
            ],
            options={
                'verbose_name': 'Checklist Overall Finding',
                'verbose_name_plural': 'Checklist Overall Findings',
                'ordering': ('started_checklist', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ActivityQuestionOverallFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Value')),
                ('activity_question',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overall_finding',
                                      to='field_monitoring_data_collection.ActivityQuestion', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Overall Activity Question Finding',
                'verbose_name_plural': 'Overall Activity Question Findings',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ActivityOverallFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative_finding', models.TextField(blank=True, verbose_name='Narrative Finding')),
                ('on_track', models.NullBooleanField()),
                ('cp_output',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='reports.Result', verbose_name='Partner')),
                ('intervention',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='partners.Intervention', verbose_name='Partner')),
                ('monitoring_activity',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_findings',
                                   to='field_monitoring_planning.MonitoringActivity', verbose_name='Activity')),
                ('partner',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                   to='partners.PartnerOrganization', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Activity Overall Finding',
                'verbose_name_plural': 'Activity Overall Findings',
                'ordering': ('monitoring_activity', 'id'),
            },
        ),
    ]
