# Generated by Django 2.0.9 on 2018-12-12 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_monitoring_visits', '0001_initial'),
        ('field_monitoring_data_collection', '0001_initial'),
        ('field_monitoring_shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdata',
            name='visit_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_data', to='field_monitoring_visits.VisitTaskLink'),
        ),
        migrations.AddField(
            model_name='startedmethod',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_methods', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='startedmethod',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_methods', to='field_monitoring_shared.FMMethod', verbose_name='Method'),
        ),
        migrations.AddField(
            model_name='startedmethod',
            name='method_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='started_methods', to='field_monitoring_visits.VisitMethodType', verbose_name='Method Type'),
        ),
        migrations.AddField(
            model_name='startedmethod',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_methods', to='field_monitoring_visits.Visit', verbose_name='Visit'),
        ),
        migrations.AddField(
            model_name='checklistitemvalue',
            name='checklist_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_values', to='field_monitoring_visits.TaskCheckListItem'),
        ),
        migrations.AddField(
            model_name='checklistitemvalue',
            name='task_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_values', to='field_monitoring_data_collection.TaskData'),
        ),
    ]
