# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-28 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field_monitoring_visits', '0001_initial'),
        ('field_monitoring_data_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startedmethod',
            name='method_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='started_methods', to='field_monitoring_visits.VisitMethodType', verbose_name='Method Type'),
        ),
        migrations.AddField(
            model_name='startedmethod',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_methods', to='field_monitoring_visits.Visit', verbose_name='Visit'),
        ),
    ]
