# Generated by Django 2.2.7 on 2020-01-27 09:45

from django.db import migrations, models


def migrate_values_forward(apps, schema_editor):
    Finding = apps.get_model('field_monitoring_data_collection', 'Finding')
    ActivityQuestionOverallFinding = apps.get_model('field_monitoring_data_collection',
                                                    'ActivityQuestionOverallFinding')
    for finding in Finding.objects.all():
        if isinstance(finding.value, (float, int)):
            finding.number_value = finding.value
        else:
            finding.text_value = str(finding.value)
        finding.save()

    for finding in ActivityQuestionOverallFinding.objects.all():
        if isinstance(finding.value, (float, int)):
            finding.number_value = finding.value
        else:
            finding.text_value = str(finding.value)
        finding.save()


def migrate_values_backward(apps, schema_editor):
    Finding = apps.get_model('field_monitoring_data_collection', 'Finding')
    ActivityQuestionOverallFinding = apps.get_model('field_monitoring_data_collection',
                                                    'ActivityQuestionOverallFinding')
    for finding in Finding.objects.all():
        finding.value = finding.number_value or finding.text_value
        finding.save()

    for finding in ActivityQuestionOverallFinding.objects.all():
        finding.value = finding.number_value or finding.text_value
        finding.save()


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_data_collection', '0002_auto_20191116_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityquestionoverallfinding',
            name='number_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityquestionoverallfinding',
            name='text_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='number_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='text_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_values_forward, migrate_values_backward),
        migrations.RemoveField(
            model_name='activityquestionoverallfinding',
            name='value',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='value',
        ),
    ]
