# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-03 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import etools.applications.field_monitoring.visits.models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_visits', '0007_auto_20181203_1408'),
        ('field_monitoring_data_collection', '0002_auto_20181128_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListItemValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_visits.TaskCheckListItem')),
            ],
            bases=(etools.applications.field_monitoring.visits.models.FindingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_probed', models.BooleanField(default=True)),
                ('started_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_data_collection.StartedMethod')),
                ('visit_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_visits.VisitTaskLink')),
            ],
        ),
        migrations.AddField(
            model_name='checklistitemvalue',
            name='task_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_data_collection.TaskData'),
        ),
    ]
