# Generated by Django 2.2.1 on 2019-07-10 14:24

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_monitoring_data_collection', '0002_auto_20181212_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityOverallFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative_finding', models.TextField(blank=True, verbose_name='Narrative Finding')),
            ],
            options={
                'verbose_name': 'Activity Overall Finding',
                'verbose_name_plural': 'Activity Overall Findings',
                'ordering': ('monitoring_activity', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ActivityQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_details', models.TextField(blank=True, verbose_name='Specific Details To Probe')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Activity Question',
                'verbose_name_plural': 'Activity Questions',
                'ordering': ('monitoring_activity', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistOverallFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative_finding', models.TextField(blank=True, verbose_name='Narrative Finding')),
            ],
            options={
                'verbose_name': 'Checklist Overall Finding',
                'verbose_name_plural': 'Checklist Overall Findings',
                'ordering': ('started_checklist', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Checklist Finding',
                'verbose_name_plural': 'Checklist Findings',
                'ordering': ('started_checklist', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StartedChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_source', models.CharField(max_length=100, verbose_name='Information Source')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists',
                                             to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Started Checklist',
                'verbose_name_plural': 'Started Checklists',
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='startedmethod',
            name='author',
        ),
        migrations.RemoveField(
            model_name='startedmethod',
            name='method',
        ),
        migrations.RemoveField(
            model_name='startedmethod',
            name='method_type',
        ),
        migrations.RemoveField(
            model_name='startedmethod',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='taskdata',
            name='started_method',
        ),
        migrations.RemoveField(
            model_name='taskdata',
            name='visit_task',
        ),
        migrations.DeleteModel(
            name='CheckListItemValue',
        ),
        migrations.DeleteModel(
            name='StartedMethod',
        ),
        migrations.DeleteModel(
            name='TaskData',
        ),
    ]
