# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-04 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_data_collection', '0003_auto_20181203_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitemvalue',
            options={'ordering': ('id',), 'verbose_name': 'Checklist Item Value', 'verbose_name_plural': 'Checklists Item Values'},
        ),
        migrations.AlterModelOptions(
            name='startedmethod',
            options={'ordering': ('id',), 'verbose_name': 'Started Method', 'verbose_name_plural': 'Started Methods'},
        ),
        migrations.AlterModelOptions(
            name='taskdata',
            options={'ordering': ('id',), 'verbose_name': 'Task Data', 'verbose_name_plural': 'Tasks Data'},
        ),
    ]
