# Generated by Django 3.2.6 on 2023-02-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_data_collection', '0003_auto_20210923_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityquestion',
            name='translations',
            field=models.JSONField(default=dict, verbose_name='Translations'),
        ),
    ]
