# Generated by Django 2.0.9 on 2018-12-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_data_collection', '0005_auto_20181206_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='is_probed',
            field=models.BooleanField(default=True),
        ),
    ]
