# Generated by Django 2.2.1 on 2019-07-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_data_collection', '0005_auto_20190729_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityoverallfinding',
            name='cp_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='reports.Result', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='activityoverallfinding',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='partners.Intervention', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='activityoverallfinding',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='partners.PartnerOrganization', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='activityquestion',
            name='cp_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='reports.Result', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='activityquestion',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='partners.Intervention', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='activityquestion',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='partners.PartnerOrganization', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='checklistoverallfinding',
            name='cp_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='reports.Result', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='checklistoverallfinding',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='partners.Intervention', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='checklistoverallfinding',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='partners.PartnerOrganization', verbose_name='Partner'),
        ),
    ]
