# Generated by Django 2.0.9 on 2018-12-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_data_collection', '0006_auto_20181211_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitemvalue',
            name='finding_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='checklistitemvalue',
            name='finding_value',
            field=models.CharField(blank=True, choices=[('y', 'As Planned'), ('n', 'Not As Planned')], max_length=1, verbose_name='Finding'),
        ),
    ]
