# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-24 22:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'Email', b'Email')], default=b'Email', max_length=255)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('recipients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('sent_recipients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('template_name', models.CharField(choices=[(b'trips/trip/created/updated', b'trips/trip/created/updated'), (b'trips/trip/approved', b'trips/trip/approved'), (b'trips/trip/approved', b'trips/trip/approved'), (b'trips/trip/cancelled', b'trips/trip/cancelled'), (b'trips/trip/completed', b'trips/trip/completed'), (b'trips/trip/representative', b'trips/trip/representative'), (b'travel/trip/travel_or_admin_assistant', b'travel/trip/travel_or_admin_assistant'), (b'trips/trip/TA_request', b'trips/trip/TA_request'), (b'trips/trip/TA_drafted', b'trips/trip/TA_drafted'), (b'trips/action/created/updated/closed', b'trips/action/created/updated/closed'), (b'trips/trip/summary', b'trips/trip/summary'), (b'partners/partnership/created/updated', b'partners/partnership/created/updated')], max_length=255)),
                ('template_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', null=True)),
            ],
        ),
    ]
