# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-12 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20170712_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(default='Email', max_length=255),
        ),
    ]
