# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-19 14:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import notification.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0004_auto_20160607_0901'),
        ('notification', '0003_auto_20170712_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='notification',
            name='from_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='html_message',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_office.Email'),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='notification',
            name='text_message',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='notification',
            name='template_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='template_name',
            field=models.CharField(blank=True, max_length=255, validators=[notification.models.validate_template_name]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(default=b'Email', max_length=255, validators=[notification.models.validate_notification_type]),
        ),
    ]
