# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-16 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field_monitoring_shared', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='Slug')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Is Recommended')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_shared.Method', verbose_name='Method')),
            ],
        ),
    ]
