# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-22 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def create_site_gateway(apps, schema_editor):
    GatewayType = apps.get_model('locations', 'GatewayType')
    GatewayType.objects.get_or_create(name='Site')


def remove_site_gateway(apps, schema_editor):
    GatewayType = apps.get_model('locations', 'GatewayType')
    GatewayType.objects.filter(name='Site').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_pcode_remap_related'),
        ('field_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_site_gateway, remove_site_gateway),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.Location')),
                ('security_detail', models.TextField(blank=True, verbose_name='Detail on Security')),
            ],
            options={
                'abstract': False,
            },
            bases=('locations.location',),
        ),
    ]
