# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-23 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20180709_1348'),
        ('partners', '0027_auto_20180914_1238'),
        ('field_monitoring', '0002_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPOutputConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_monitored', models.BooleanField(default=True, verbose_name='Monitored At Community Level?')),
                ('is_priority', models.BooleanField(default=False, verbose_name='Priority?')),
                ('cp_output', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fm_config', to='reports.Result', verbose_name='CP Output To Be Monitored')),
                ('government_partners', models.ManyToManyField(blank=True, to='partners.PartnerOrganization', verbose_name='Contributing Government Partners')),
            ],
        ),
    ]
