# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-23 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring', '0003_cpoutputconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methodtype',
            name='is_recommended',
        ),
    ]
