# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-26 12:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.forms import model_to_dict


def migrate_data(apps, schema_editor):
    ActivityOld = apps.get_model("snapshot", "activity")
    Activity = apps.get_model("unicef_snapshot", "activity")
    for activity in ActivityOld.objects.all():
        Activity.objects.create(
            target_content_type=activity.target_content_type,
            target_object_id=activity.target_object_id,
            action=activity.action,
            by_user=activity.by_user,
            data=activity.data,
            change=activity.change,
            created=activity.created,
            modified=activity.modified,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0001_initial'),
        ('unicef_snapshot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_user_old', to=settings.AUTH_USER_MODEL, verbose_name='By User'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='target_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_old', to='contenttypes.ContentType', verbose_name='Content Type'),
        ),
        migrations.RunPython(
            migrate_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
