# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-18 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cartodbtable',
            managers=[
            ],
        ),
    ]
