# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-14 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20161214_1200'),
        ('partners', '0004_auto_20161214_1200'),
        ('locations', '0002_auto_20161118_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governorate',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='linkedlocation',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='linkedlocation',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='linkedlocation',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='linkedlocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='linkedlocation',
            name='region',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='region',
        ),
        migrations.RemoveField(
            model_name='region',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='region',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='location',
            name='locality',
        ),
        migrations.DeleteModel(
            name='Governorate',
        ),
        migrations.DeleteModel(
            name='LinkedLocation',
        ),
        migrations.DeleteModel(
            name='Locality',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
