# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-12 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20170112_2051'),
        ('partners', '0009_auto_20170112_2051'),
        ('locations', '0003_add_trigram_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governorate',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='linkedlocation',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='linkedlocation',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='linkedlocation',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='linkedlocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='linkedlocation',
            name='region',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='region',
        ),
        migrations.RemoveField(
            model_name='region',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='region',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='location',
            name='locality',
        ),
        migrations.DeleteModel(
            name='Governorate',
        ),
        migrations.DeleteModel(
            name='LinkedLocation',
        ),
        migrations.DeleteModel(
            name='Locality',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
