# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-10 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_add_trigram_index'),
        ('locations', '0003_auto_20161214_1200'),
    ]

    operations = [
    ]
