# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-27 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_gatewaytype_admin_level'),
        ('locations', '0005_auto_20171020_0958'),
    ]

    operations = [
    ]
