# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-12 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20171024_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartodbtable',
            name='name_col',
            field=models.CharField(default='name', max_length=254),
        ),
        migrations.AlterField(
            model_name='cartodbtable',
            name='pcode_col',
            field=models.CharField(default='pcode', max_length=254),
        ),
        migrations.AlterField(
            model_name='location',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.GatewayType', verbose_name='Location Type'),
        ),
    ]
