# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-27 17:22
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20160229_1545'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cartodbtable',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
