# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-09 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20161027_2022'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cartodbtable',
            managers=[
            ],
        ),
    ]
