# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-23 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field_monitoring_shared', '0001_initial'),
        ('locations', '0004_pcode_remap_related'),
        ('reports', '0013_auto_20180709_1348'),
        ('partners', '0027_auto_20180914_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPOutputConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_monitored', models.BooleanField(default=True, verbose_name='Monitored At Community Level?')),
                ('is_priority', models.BooleanField(default=False, verbose_name='Priority?')),
                ('cp_output', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fm_config', to='reports.Result', verbose_name='CP Output To Be Monitored')),
                ('government_partners', models.ManyToManyField(blank=True, to='partners.PartnerOrganization', verbose_name='Contributing Government Partners')),
            ],
        ),
        migrations.CreateModel(
            name='MethodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='Slug')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_shared.FMMethod', verbose_name='Method')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.Location')),
                ('security_detail', models.TextField(blank=True, verbose_name='Detail on Security')),
            ],
            options={
                'abstract': False,
            },
            bases=('locations.location',),
        ),
    ]
