# Generated by Django 2.2.6 on 2019-11-13 10:18

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('unicef_locations', '0001_initial'),
        ('partners', '0039_auto_20191106_1345'),
        ('reports', '0019_auto_20190816_1609'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Question Category',
                'verbose_name_plural': 'Questions Categories',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='LocationSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('p_code', models.CharField(blank=True, default='', max_length=32, verbose_name='P Code')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326,
                                                                         verbose_name='Point')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Active')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites',
                                             to='locations.Location', verbose_name='Parent Location')),
            ],
            options={
                'verbose_name': 'Location Site',
                'verbose_name_plural': 'Location Sites',
                'ordering': ('parent', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Method',
                'verbose_name_plural': 'Methods',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('bool', 'Boolean'),
                                                          ('likert_scale', 'Likert Scale')], max_length=15,
                                                 verbose_name='Answer Type')),
                ('choices_size', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Choices Size')),
                ('level',
                 models.CharField(choices=[('partner', 'Partner'), ('output', 'Output'), ('intervention', 'PD/SSFA')],
                                  max_length=15, verbose_name='Level')),
                ('text', models.TextField(verbose_name='Question Text')),
                ('is_hact', models.BooleanField(default=False, verbose_name='Count as HACT')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Is Custom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_settings.Category',
                                   verbose_name='Category')),
                ('methods',
                 models.ManyToManyField(blank=True, to='field_monitoring_settings.Method', verbose_name='Methods')),
                ('sections', models.ManyToManyField(to='reports.Section', verbose_name='Sections')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('value', models.JSONField(blank=True, null=True, verbose_name='Value')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options',
                                               to='field_monitoring_settings.Question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Option',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='LogIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False,
                                                                verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False,
                                                                      verbose_name='modified')),
                ('issue', models.TextField(verbose_name='Issue For Attention/Probing')),
                ('status', models.CharField(choices=[('new', 'New'), ('past', 'Past')], default='new', max_length=10)),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_logissues',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Issue Raised By')),
                ('cp_output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='log_issues', to='reports.Result',
                                                verbose_name='CP Output')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               related_name='log_issues', to='locations.Location',
                                               verbose_name='Location')),
                ('location_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='log_issues',
                                                    to='field_monitoring_settings.LocationSite', verbose_name='Site')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='log_issues', to='partners.PartnerOrganization',
                                              verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Log Issue',
                'verbose_name_plural': 'Log Issues',
                'ordering': ('id',),
            },
        ),
    ]
