# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-23 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicef_attachments', '0002_attachmentlink'),
        ('field_monitoring_settings', '0002_auto_20181122_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMonitoringGeneralAttachment',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('unicef_attachments.attachment',),
        ),
    ]
