# Generated by Django 4.2.3 on 2024-09-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='other',
            field=models.JSONField(blank=True, default=dict, verbose_name='Other details'),
        ),
    ]
