# Generated by Django 2.1.5 on 2019-02-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0003_remove_plannedchecklistitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsite',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Active'),
        ),
    ]
