# Generated by Django 2.2.7 on 2019-12-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0003_method_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Global Config',
                'verbose_name_plural': 'Global Configs',
                'ordering': ('id',),
            },
        ),
    ]
