# Generated by Django 2.2.7 on 2019-12-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0005_auto_20191211_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sections',
            field=models.ManyToManyField(blank=True, to='reports.Section', verbose_name='Sections'),
        ),
    ]
