# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-01 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0006_auto_20181026_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ('category', 'order')},
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='field_monitoring_settings.CheckListCategory', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='question_number',
            field=models.CharField(default=1, max_length=10, verbose_name='Question Number'),
            preserve_default=False,
        ),
    ]
