# Generated by Django 2.2.1 on 2019-08-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0006_auto_20190729_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Choices Size'),
            preserve_default=False,
        ),
    ]
