# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-01 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0027_auto_20180914_1238'),
        ('field_monitoring_settings', '0007_auto_20181101_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannedchecklistitem',
            options={},
        ),
        migrations.AlterField(
            model_name='plannedchecklistitempartnerinfo',
            name='planned_checklist_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners_info', to='field_monitoring_settings.PlannedCheckListItem', verbose_name='Planned Checklist Item'),
        ),
        migrations.AlterUniqueTogether(
            name='plannedchecklistitem',
            unique_together=set([('cp_output_config', 'checklist_item')]),
        ),
        migrations.AlterUniqueTogether(
            name='plannedchecklistitempartnerinfo',
            unique_together=set([('planned_checklist_item', 'partner')]),
        ),
    ]
