# Generated by Django 2.2.1 on 2019-08-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0007_question_choices_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('bool', 'Boolean'), ('likert_scale', 'Likert Scale')],
                                   max_length=15, verbose_name='Answer Type'),
        ),
    ]
