# Generated by Django 2.2.7 on 2021-01-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0007_auto_20200219_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('partner', 'Partner'), ('output', 'Output'), ('intervention', 'PD/SPD')], max_length=15, verbose_name='Level'),
        ),
    ]
