# Generated by Django 2.2.1 on 2019-07-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0006_auto_20190710_1344'),
        ('field_monitoring_monitoring_activities', '0002_auto_20190710_1344'),
        ('field_monitoring_settings', '0007_auto_20190708_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationSite',
        ),
    ]
