# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-02 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_pcode_remap_related'),
        ('partners', '0027_auto_20180914_1238'),
        ('reports', '0013_auto_20180709_1348'),
        ('field_monitoring_settings', '0008_auto_20181101_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logissue',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='logissue',
            name='object_id',
        ),
        migrations.AddField(
            model_name='logissue',
            name='cp_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Result', verbose_name='CP Output'),
        ),
        migrations.AddField(
            model_name='logissue',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='logissue',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='logissue',
            name='location_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_settings.LocationSite', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='logissue',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='logissue',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization', verbose_name='Partner'),
        ),
    ]
