# Generated by Django 3.2.6 on 2022-08-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0008_alter_option_label'),
        ('field_monitoring_settings', '0008_auto_20210108_1634'),
    ]

    operations = [
    ]
