# Generated by Django 3.2.6 on 2022-12-29 14:27

from django.db import migrations
import etools.applications.core.i18n.fields
import etools.applications.core.i18n.utils


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0009_merge_0008_alter_option_label_0008_auto_20210108_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='old_text',
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=etools.applications.core.i18n.fields.TranslatedTextField(default=etools.applications.core.i18n.utils.get_default_translated, verbose_name='Question Text'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='old_text',
        ),
    ]
