# Generated by Django 2.2.1 on 2019-09-24 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0010_auto_20190828_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logissue',
            name='cp_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_issues', to='reports.Result', verbose_name='CP Output'),
        ),
        migrations.AlterField(
            model_name='logissue',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_issues', to='locations.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='logissue',
            name='location_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_issues', to='field_monitoring_settings.LocationSite', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='logissue',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_issues', to='partners.PartnerOrganization', verbose_name='Partner'),
        ),
    ]
