# Generated by Django 2.2.6 on 2019-10-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0011_auto_20190924_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sections',
            field=models.ManyToManyField(to='reports.Section', verbose_name='Sections'),
        ),
    ]
