# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-30 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('et2f', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='preserved_expenses',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=20, null=True),
        ),
    ]
