# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-30 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('et2f', '0002_travel_preserved_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
    ]
