# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-30 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('et2f', '0003_travel_is_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='additional_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
