# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-01 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('et2f', '0004_travel_additional_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeOfTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Plane', 'Plane'), ('Bus', 'Bus'), ('Car', 'Car'), ('Boat', 'Boat')], max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='traveltype',
            name='name',
            field=models.CharField(choices=[('programme_monitoring', 'PROGRAMMATIC VISIT'), ('spot_check', 'SPOT CHECK'), ('advocacy', 'ADVOCACY'), ('technical_support', 'TECHNICAL SUPPORT'), ('meeting', 'MEETING'), ('staff_development', 'STAFF DEVELOPMENT'), ('staff_entitlement', 'STAFF ENTITLEMENT')], max_length=32),
        ),
    ]
