# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-01 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('et2f', '0006_auto_20161201_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteneraryitem',
            name='mode_of_travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='et2f.ModeOfTravel'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='mode_of_travel',
            field=models.ManyToManyField(related_name='_travel_mode_of_travel_+', to='et2f.ModeOfTravel'),
        ),
    ]
