# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-09 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('et2f', '0008_auto_20161209_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveltype',
            name='name',
            field=models.CharField(choices=[('Programmatic Visit', 'Programmatic Visit'), ('Spot Check', 'Spot Check'), ('Advocacy', 'Advocacy'), ('Technical Support', 'Technical Support'), ('Meeting', 'Meeting'), ('Staff Development', 'Staff Development'), ('Staff Entitlement', 'Staff Entitlement')], max_length=32),
        ),
    ]
