# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-09 13:46
from __future__ import unicode_literals

from django.db import migrations


def transform_travel_types(apps, schema_edito):
    mapping = {"programme_monitoring": 'Programmatic Visit',
        "spot_check": 'Spot Check',
        "advocacy": 'Advocacy',
        "technical_support": 'Technical Support',
        "meeting": 'Meeting',
        "staff_development": 'Staff Development',
        "staff_entitlement": 'Staff Entitlement'}

    TravelType = apps.get_model('et2f', 'TravelType')
    for travel_type in TravelType.objects.all():
        travel_type.name = mapping.get(travel_type.name, travel_type.name)
        travel_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('et2f', '0009_auto_20161209_1512'),
    ]

    operations = [
        migrations.RunPython(transform_travel_types),
    ]
