# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-14 08:48
from __future__ import unicode_literals

from django.db import migrations, models

from et2f.models import ModeOfTravel as ModeOfTravelModel


def create_mode_of_travel_models(apps, schema_editor):
    ModeOfTravel = apps.get_model('et2f', 'ModeOfTravel')

    for choice in ModeOfTravelModel.CHOICES:
        ModeOfTravel.objects.get_or_create(name=choice[0])


class Migration(migrations.Migration):

    dependencies = [
        ('et2f', '0011_auto_20161213_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeoftravel',
            name='name',
            field=models.CharField(choices=[('Plane', 'Plane'), ('Bus', 'Bus'), ('Car', 'Car'), ('Boat', 'Boat'), ('Rail', 'Rail')], max_length=8),
        ),
        migrations.RunPython(create_mode_of_travel_models),
    ]
