# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-15 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('et2f', '0012_auto_20161214_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='misc_expenses',
            field=models.TextField(null=True),
        ),
    ]
