# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-18 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('et2f', '0025_auto_20161117_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='report_note',
            field=models.TextField(null=True),
        ),
    ]
