# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-21 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('et2f', '0027_travelactivity_travel_m2m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='traveller',
            new_name='traveler',
        ),
    ]
