# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-21 11:57
from __future__ import unicode_literals

from django.db import migrations, models

PLANE = 'Plane'
BUS = 'Bus'
CAR = 'Car'
BOAT = 'Boat'

def create_initial_travel_types(apps, schema_editor):
    TravelType = apps.get_model('et2f', 'TravelType')
    TravelType.objects.create(name=PLANE)
    TravelType.objects.create(name=BUS)
    TravelType.objects.create(name=CAR)
    TravelType.objects.create(name=BOAT)


class Migration(migrations.Migration):

    dependencies = [
        ('et2f', '0028_auto_20161121_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Plane', 'Plane'), ('Bus', 'Bus'), ('Car', 'Car'), ('Boat', 'Boat')], max_length=8)),
            ],
        ),
        migrations.RunPython(create_initial_travel_types),
    ]
