# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-21 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('et2f', '0029_auto_20161121_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteneraryitem',
            name='new_mode_of_travel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='et2f.TravelType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travel',
            name='new_mode_of_travel',
            field=models.ManyToManyField(related_name='_travel_new_mode_of_travel_+', to='et2f.TravelType'),
        ),
        migrations.AddField(
            model_name='travelactivity',
            name='new_travel_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='et2f.TravelType'),
            preserve_default=False,
        ),
    ]
