# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-21 14:02
from __future__ import unicode_literals

from django.db import migrations

PLANE = 'Plane'
BUS = 'Bus'
CAR = 'Car'
BOAT = 'Boat'


def convert_old_values_itinerary(apps, schema_editor):
    IteneraryItem = apps.get_model('et2f', 'IteneraryItem')
    TravelType = apps.get_model('et2f', 'TravelType')

    plane_tt = TravelType.objects.get(name=PLANE)
    bus_tt = TravelType.objects.get(name=BUS)
    car_tt = TravelType.objects.get(name=CAR)
    boat_tt = TravelType.objects.get(name=BOAT)
    mapping = {PLANE: plane_tt,
               BUS: bus_tt,
               CAR: car_tt,
               BOAT: boat_tt}

    for item in IteneraryItem.objects.all():
        item.new_mode_of_travel = mapping[item.mode_of_travel]
        item.save()


def convert_old_values_travel(apps, schema_editor):
    Travel = apps.get_model('et2f', 'Travel')
    TravelType = apps.get_model('et2f', 'TravelType')

    plane_tt = TravelType.objects.get(name=PLANE)
    bus_tt = TravelType.objects.get(name=BUS)
    car_tt = TravelType.objects.get(name=CAR)
    boat_tt = TravelType.objects.get(name=BOAT)
    mapping = {PLANE: plane_tt,
               BUS: bus_tt,
               CAR: car_tt,
               BOAT: boat_tt}

    for item in Travel.objects.all():
        for mode in item.mode_of_travel:
            item.new_mode_of_travel.add(mapping[mode])


def convert_old_values_travelactivity(apps, schema_editor):
    TravelActivity = apps.get_model('et2f', 'TravelActivity')
    TravelType = apps.get_model('et2f', 'TravelType')

    plane_tt = TravelType.objects.get(name=PLANE)
    bus_tt = TravelType.objects.get(name=BUS)
    car_tt = TravelType.objects.get(name=CAR)
    boat_tt = TravelType.objects.get(name=BOAT)
    mapping = {PLANE: plane_tt,
               BUS: bus_tt,
               CAR: car_tt,
               BOAT: boat_tt}

    for item in TravelActivity.objects.all():
        item.new_travel_type = mapping[item.travel_type]
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('et2f', '0030_auto_20161121_1559'),
    ]

    operations = [
        migrations.RunPython(convert_old_values_itinerary),
        migrations.RunPython(convert_old_values_travel),
        migrations.RunPython(convert_old_values_travelactivity),
    ]
