# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-02 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waffle', '0002_auto_20161201_0958'),
        ('users', '0008_workspacecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ManyToManyField(blank=True, help_text='Activate this flag for these countries.', to='users.Country')),
                ('flag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='waffle.Flag')),
            ],
        ),
    ]
