# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-07 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20161118_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorreport',
            name='result_chain',
        ),
        migrations.AlterField(
            model_name='indicatorreport',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.AppliedIndicator'),
        ),
    ]
