# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-09 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

# def forwards(apps, schema_editor):
#     migrations.RemoveField(
#         model_name='indicatorreport',
#         name='result_chain',
#     ),
#     migrations.AlterField(
#         model_name='indicatorreport',
#         name='indicator',
#         field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports',
#                                 to='reports.AppliedIndicator'),
#     ),
#
# def backwards(apps, schema_editor):
#     migrations.AddField(
#         model_name='indicatorreport',
#         name='result_chain',
#         field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_reports',
#                                 to='partners.ResultChain', blank=True, null=True),
#     ),
#     migrations.AlterField(
#         model_name='indicatorreport',
#         name='indicator',
#         field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports',
#                                 to='reports.Indicator'))


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20161118_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorreport',
            name='result_chain',
        ),
        # Can't yet refer to reports.AppliedIndicator because it's created in reports
        # migration 0003, which depends on this migration. Moved this AlterField
        # to partners migration 0004.
        # migrations.AlterField(
        #     model_name='indicatorreport',
        #     name='indicator',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports',
        #                             to='reports.AppliedIndicator'),
        # ),
        #migrations.RunPython(forwards, reverse_code=backwards),

    ]
