# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-29 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20161118_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
