# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-02 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0002_auto_20161118_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipbudget',
            name='in_kind_amount_local',
            field=models.IntegerField(default=0, verbose_name=b'UNICEF Supplies'),
        ),
        migrations.AddField(
            model_name='partnershipbudget',
            name='partner_contribution_local',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnershipbudget',
            name='unicef_cash_local',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pca',
            name='office',
            field=models.ManyToManyField(blank=True, related_name='_pca_office_+', to='users.Office'),
        ),
        migrations.AddField(
            model_name='pca',
            name='population_focus',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='pca',
            name='programme_focal_points',
            field=models.ManyToManyField(blank=True, related_name='partnership_focals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pca',
            name='partner_focal_point',
        ),
        migrations.AddField(
            model_name='pca',
            name='partner_focal_point',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field=b'partner', chained_model_field=b'partner', related_name='my_partnerships', to='partners.PartnerStaffMember'),
        ),
    ]
