# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-06 21:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0002_auto_20161118_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipbudget',
            name='in_kind_amount_local',
            field=models.IntegerField(default=0, verbose_name=b'UNICEF Supplies Local'),
        ),
        migrations.AddField(
            model_name='partnershipbudget',
            name='partner_contribution_local',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnershipbudget',
            name='unicef_cash_local',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pca',
            name='fr_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=None),
        ),
        migrations.AddField(
            model_name='pca',
            name='office',
            field=models.ManyToManyField(blank=True, related_name='_pca_office_+', to='users.Office'),
        ),
        migrations.AddField(
            model_name='pca',
            name='population_focus',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.AddField(
            model_name='pca',
            name='programme_focal_points',
            field=models.ManyToManyField(blank=True, related_name='partnership_focals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agreementamendmentlog',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('in_process', 'In Process'), ('active', 'Active'), ('implemented', 'Implemented'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], max_length=32L),
        ),
        migrations.AlterField(
            model_name='amendmentlog',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('in_process', 'In Process'), ('active', 'Active'), ('implemented', 'Implemented'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], max_length=32L),
        ),
        migrations.AlterField(
            model_name='amendmentlog',
            name='type',
            field=models.CharField(choices=[(b'No Cost', b'No Cost'), (b'Cost', b'Cost'), (b'Activity', b'Activity'), (b'Other', b'Other'), (b'Change in Programme Result', b'Change in Programme Result'), (b'Change in Population Focus', b'Change in Population Focus'), (b'Change in Georgraphical Coverage', b'Change in Georgraphical Coverage'), (b'Change in Total Budget >20%', b'Change in Total Budget >20%'), (b'Change in Total Budget <=20%', b'Change in Total Budget <=20%'), (b'Changes in Activity Budget <=20% - No Change in Total Budget', b'Changes in Activity Budget <=20% - No Change in Total Budget'), (b'Changes in Activity Budget >20% - No Change in Total Budget - Prior approval in authorized FACE', b'Changes in Activity Budget >20% - No Change in Total Budget - Prior approval in authorized FACE'), (b'Changes in Activity Budget >20% - No Change in Total Budget - Reporting at FACE', b'Changes in Activity Budget >20% - No Change in Total Budget - Reporting at FACE')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='pca',
            name='partner_focal_point',
        ),
        migrations.AddField(
            model_name='pca',
            name='partner_focal_point',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field=b'partner', chained_model_field=b'partner', related_name='my_partnerships', to='partners.PartnerStaffMember'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('in_process', 'In Process'), ('active', 'Active'), ('implemented', 'Implemented'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='in_process', help_text='In Process = In discussion with partner, Active = Currently ongoing, Implemented = completed, Cancelled = cancelled or not approved', max_length=32),
        ),
        migrations.AlterField(
            model_name='pcasector',
            name='pca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcasectors', to='partners.PCA'),
        ),
    ]
