# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-08 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20161206_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2016)),
                ('programmatic', models.IntegerField(default=0)),
                ('spot_checks', models.IntegerField(default=0)),
                ('audit', models.IntegerField(default=0)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='partners.PCA')),
            ],
        ),
    ]
