# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-21 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_fix_null_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='names_of_other_agencies',
            field=models.CharField(blank=True, default=True, help_text='List the names of the other agencies they have worked with', max_length=255, verbose_name='Other Agencies'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='Note any special requests to be considered during the assessment', max_length=255, verbose_name='Special requests'),
        ),
        migrations.AlterField(
            model_name='fundingcommitment',
            name='fc_ref',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='population_focus',
            field=models.CharField(blank=True, default='', max_length=130, verbose_name='Population Focus'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='number',
            field=models.CharField(blank=True, default='', max_length=64, unique=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='interventionamendment',
            name='other_description',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='alternate_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Alternate Name'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='city',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='country',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='rating',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Significant', 'Significant'), ('Moderate', 'Medium'), ('Low', 'Low'), ('Non-Assessed', 'Non Required')], default='', max_length=50, verbose_name='Risk Rating'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='type_of_assessment',
            field=models.CharField(default='', max_length=50, verbose_name='Assessment Type'),
        ),
        migrations.AlterField(
            model_name='partnerstaffmember',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='partnerstaffmember',
            name='title',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Title'),
        ),
    ]
