# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-05 10:59
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import F, Max, Case, When
from t2f.models import TravelType


def set_last_pv_date(apps, schema_editor):
    Intervention = apps.get_model("partners", "intervention")
    for i in Intervention.objects.annotate(
            latest_pv_date=Max(
                Case(
                    When(
                        travel_activities__travel_type=TravelType.PROGRAMME_MONITORING,
                        travel_activities__travels__traveler=F(
                            'travel_activities__primary_traveler'
                        ),
                        travel_activities__travels__status="completed",
                        then=F('travel_activities__date')
                    ),
                )
            )
    ):
        i.last_pv_date = i.latest_pv_date
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0001_initial'),
        ('partners', '0003_auto_20180329_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='last_pv_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(
            set_last_pv_date,
            reverse_code=migrations.RunPython.noop
        )
    ]
