# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-27 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_linkedpartner_result'),
        ('partners', '0003_auto_20161209_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorreport',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports',
                                    to='reports.AppliedIndicator'),
        ),
        migrations.RemoveField(
            model_name='resultchain',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='resultchain',
            name='partnership',
        ),
        migrations.RemoveField(
            model_name='resultchain',
            name='result',
        ),
        migrations.RemoveField(
            model_name='resultchain',
            name='result_type',
        ),
        migrations.DeleteModel(
            name='ResultChain',
        ),
    ]
