# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-12 22:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20161209_2030'),
        ('reports', '0002_auto_20161209_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentinterventionresult',
            name='activities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
