# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-23 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20161123_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='partner_staff_members',
            field=models.ManyToManyField(blank=True, related_name='_agreement_partner_staff_members_+', to='partners.PartnerStaffMember'),
        ),
    ]
