# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-02 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20161202_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementamendmentlog',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('in_process', 'In Process'), ('active', 'Active'), ('implemented', 'Implemented'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], max_length=32L),
        ),
        migrations.AlterField(
            model_name='amendmentlog',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('in_process', 'In Process'), ('active', 'Active'), ('implemented', 'Implemented'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], max_length=32L),
        ),
        migrations.AlterField(
            model_name='pca',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('in_process', 'In Process'), ('active', 'Active'), ('implemented', 'Implemented'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='in_process', help_text='In Process = In discussion with partner, Active = Currently ongoing, Implemented = completed, Cancelled = cancelled or not approved', max_length=32),
        ),
    ]
