# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-27 17:53
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
from django.db.models import Count
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import django_fsm
import model_utils.fields
import partners.models
import smart_selects.db_fields
import EquiTrack.utils

def reverse(apps, schema_editor):
    pass

def agreement_unique_reference_number(apps, schema_editor):
    Agreement = apps.get_model('partners', 'Agreement')

    agreements = Agreement.objects.all()
    for agr in agreements:
        if agr.agreement_number == '':
            print(agr)
            agr.agreement_number = 'TempRef:{}'.format(agr.id)
            agr.save()
    dupes = Agreement.objects.values('agreement_number').annotate(Count('agreement_number')).order_by().filter(agreement_number__count__gt=1).all()
    for dup in dupes:
        cdupes = Agreement.objects.filter(agreement_number=dup['agreement_number'])
        for cdup in cdupes:
            cdup.agreement_number = '{}|{}'.format(cdup.agreement_number, cdup.id)
            print(cdup)
            cdup.save()

def pca_unique_reference_number(apps, schema_editor):
    PCA = apps.get_model('partners', 'PCA')
    pcas = PCA.objects.all()
    for pca in pcas:
        if not pca.number:
            print(pca)
            pca.number = 'blk:{}'.format(pca.id)
            pca.save()
    dupes = PCA.objects.values('number').annotate(
        Count('number')).order_by().filter(number__count__gt=1).all()
    for dup in dupes:
        cdupes = PCA.objects.filter(number=dup['number'])
        for cdup in cdupes:
            if len(cdup.number) > 40:
                cdup.number = cdup.number[len(cdup.number)-40:]
            cdup.number = '{}|{}'.format(cdup.number, cdup.id)
            print(cdup)
            cdup.save()

class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20161118_0631'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_auto_20161209_2030'),
        ('partners', '0004_auto_20161227_1916'),
    ]

    operations = [
        migrations.RunPython(
            agreement_unique_reference_number, reverse_code=reverse
        ),
        migrations.RunPython(
            pca_unique_reference_number, reverse_code=reverse
        ),
        migrations.CreateModel(
            name='AgreementAmendment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.CharField(max_length=5, unique=True)),
                ('type', models.CharField(choices=[(b'Change IP name', b'Change in Legal Name of Implementing Partner'), (b'CP extension', b'Extension of Country Programme Cycle'), (b'Change authorized officer', b'Change Authorized Officer'), (b'Change banking info', b'Banking Information'), (b'Additional clause', b'Additional Clause'), (b'Amend existing clause', b'Amend Existing Clause')], max_length=64)),
                ('signed_amendment', models.FileField(blank=True, max_length=255, null=True, upload_to=partners.models.get_agreement_amd_file_path)),
                ('signed_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('document_type', models.CharField(choices=[('PD', 'Programme Document'), ('SHPD', 'Simplified Humanitarian Programme Document'), ('SSFA', 'SSFA TOR')], max_length=255, verbose_name='Document type')),
                ('number', models.CharField(max_length=64, verbose_name='Reference Number')),
                ('title', models.CharField(max_length=256)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('active', 'Active'), ('implemented', 'Implemented'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled')], default='in_process', help_text='Draft = In discussion with partner, Active = Currently ongoing, Implemented = completed, Terminated = cancelled or not approved', max_length=32)),
                ('start', models.DateField(blank=True, help_text='The date the Intervention will start', null=True)),
                ('end', models.DateField(blank=True, help_text='The date the Intervention will end', null=True)),
                ('submission_date', models.DateField(help_text='The date the partner submitted complete PD/SSFA documents to Unicef')),
                ('submission_date_prc', models.DateField(blank=True, help_text='The date the documents were submitted to the PRC', null=True, verbose_name='Submission Date to PRC')),
                ('review_date_prc', models.DateField(blank=True, help_text='The date the PRC reviewed the partnership', null=True, verbose_name='Review date by PRC')),
                ('prc_review_document', models.FileField(max_length=255, upload_to=partners.models.get_prc_intervention_file_path)),
                ('signed_by_unicef_date', models.DateField(blank=True, null=True)),
                ('signed_by_partner_date', models.DateField(blank=True, null=True)),
                ('fr_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), null=True, size=None)),
                ('population_focus', models.CharField(blank=True, max_length=130, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='InterventionAmendment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[(b'Change in Programme Result', b'Change in Programme Result'), (b'Change in Population Focus', b'Change in Population Focus'), (b'Change in Georgraphical Coverage', b'Change in Georgraphical Coverage'), (b'Change in Total Budget >20%', b'Change in Total Budget >20%'), (b'Change in Total Budget <=20%', b'Change in Total Budget <=20%'), (b'Changes in Activity Budget <=20% - No Change in Total Budget', b'Changes in Activity Budget <=20% - No Change in Total Budget'), (b'Changes in Activity Budget >20% - No Change in Total Budget - Prior approval in authorized FACE', b'Changes in Activity Budget >20% - No Change in Total Budget - Prior approval in authorized FACE'), (b'Changes in Activity Budget >20% - No Change in Total Budget - Reporting at FACE', b'Changes in Activity Budget >20% - No Change in Total Budget - Reporting at FACE')], max_length=50)),
                ('signed_date', models.DateField(null=True)),
                ('amendment_number', models.IntegerField(default=0)),
                ('signed_amendment', models.FileField(max_length=255, upload_to=partners.models.get_intervention_amendment_file_path)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='partners.Intervention')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterventionAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(max_length=255, upload_to=partners.models.get_intervention_attachments_file_path)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='partners.Intervention')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('partner_contribution', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unicef_cash', models.DecimalField(decimal_places=2, max_digits=20)),
                ('in_kind_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name=b'UNICEF Supplies')),
                ('partner_contribution_local', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unicef_cash_local', models.DecimalField(decimal_places=2, max_digits=20)),
                ('in_kind_amount_local', models.DecimalField(decimal_places=2, max_digits=20, verbose_name=b'UNICEF Supplies Local')),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_budget', to='partners.Intervention')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterventionLocationsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionPlannedVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=EquiTrack.utils.get_current_year)),
                ('programmatic', models.IntegerField(default=0)),
                ('spot_checks', models.IntegerField(default=0)),
                ('audit', models.IntegerField(default=0)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_visits', to='partners.Intervention')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionResultLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_links', to='reports.Result')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_links', to='partners.Intervention')),
                ('ram_indicators', models.ManyToManyField(blank=True, to='reports.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceFileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64L, unique=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='agreement',
            managers=[
                ('view_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='agreement',
            name='authorized_officers',
            field=models.ManyToManyField(blank=True, related_name='agreement_authorizations', to='partners.PartnerStaffMember'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='status',
            field=django_fsm.FSMField(blank=True, choices=[(b'draft', b'Draft'), (b'draft', b'Cancelled'), (b'active', b'Active'), (b'ended', b'Ended'), (b'suspended', b'Suspended'), (b'terminated', b'Terminated')], default=b'draft', max_length=32),
        ),
        migrations.AddField(
            model_name='agreementamendmentlog',
            name='signed_document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=partners.models.get_agreement_amd_file_path),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='partner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='partners.PartnerOrganization'),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='city',
            field=models.CharField(blank=True, max_length=32L, null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='country',
            field=models.CharField(blank=True, max_length=32L, null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='postal_code',
            field=models.CharField(blank=True, max_length=32L, null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='shared_with',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[(b'DPKO', b'DPKO'), (b'ECA', b'ECA'), (b'ECLAC', b'ECLAC'), (b'ESCWA', b'ESCWA'), (b'FAO', b'FAO'), (b'ILO', b'ILO'), (b'IOM', b'IOM'), (b'OHCHR', b'OHCHR'), (b'UN', b'UN'), (b'Women', b'Women'), (b'UNAIDS', b'UNAIDS'), (b'UNDP', b'UNDP'), (b'UNESCO', b'UNESCO'), (b'UNFPA', b'UNFPA'), (b'UN - Habitat', b'UN - Habitat'), (b'UNHCR', b'UNHCR'), (b'UNODC', b'UNODC'), (b'UNOPS', b'UNOPS'), (b'UNRWA', b'UNRWA'), (b'UNSC', b'UNSC'), (b'UNU', b'UNU'), (b'WB', b'WB'), (b'WFP', b'WFP'), (b'WHO', b'WHO')], max_length=20), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='street_address',
            field=models.CharField(blank=True, max_length=500L, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_number',
            field=models.CharField(blank=True, max_length=45L, unique=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrements', to='partners.PartnerOrganization'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='partner_manager',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field=b'partner', chained_model_field=b'partner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements_signed', to='partners.PartnerStaffMember', verbose_name='Signed by partner'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements_signed+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agreementamendmentlog',
            name='status',
            field=models.CharField(blank=True, choices=[('in_process', 'In Process'), ('active', 'Active'), ('implemented', 'Implemented'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], max_length=32L),
        ),
        migrations.AlterField(
            model_name='amendmentlog',
            name='status',
            field=models.CharField(blank=True, choices=[('in_process', 'In Process'), ('active', 'Active'), ('implemented', 'Implemented'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], max_length=32L),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=partners.models.get_assesment_path),
        ),
        migrations.AlterField(
            model_name='authorizedofficer',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.Agreement'),
        ),
        migrations.AlterField(
            model_name='distributionplan',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_plans', to='partners.PCA'),
        ),
        migrations.AlterField(
            model_name='partnershipbudget',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_log', to='partners.PCA'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='agreement',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field=b'partner', chained_model_field=b'partner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pca_interventions', to='partners.Agreement'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='status',
            field=models.CharField(blank=True, choices=[('in_process', 'In Process'), ('active', 'Active'), ('implemented', 'Implemented'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='in_process', help_text='In Process = In discussion with partner, Active = Currently ongoing, Implemented = completed, Cancelled = cancelled or not approved', max_length=32),
        ),
        migrations.AlterField(
            model_name='supplyplan',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_plans', to='partners.PCA'),
        ),
        migrations.AddField(
            model_name='interventionlocationslink',
            name='intervention_result_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_link', to='partners.InterventionResultLink'),
        ),
        migrations.AddField(
            model_name='interventionlocationslink',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.AddField(
            model_name='interventionlocationslink',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='intervention_result_locations', to='reports.Sector'),
        ),
        migrations.AddField(
            model_name='interventionattachment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itervention_attachments+', to='partners.WorkspaceFileType'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='partners.Agreement'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='hrp',
            field=models.ForeignKey(blank=True, help_text='Which humanitarian response plan does this PD/SSFA report under?', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interventions', to='reports.ResultStructure'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='office',
            field=models.ManyToManyField(blank=True, related_name='_intervention_office_+', to='users.Office'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='partner_authorized_officer_signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_interventions', to='partners.PartnerStaffMember'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='partner_focal_points',
            field=models.ManyToManyField(blank=True, related_name='_intervention_partner_focal_points_+', to='partners.PartnerStaffMember'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='sector',
            field=models.ManyToManyField(blank=True, related_name='sector_interventions', to='reports.Sector'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='unicef_focal_points',
            field=models.ManyToManyField(blank=True, related_name='_intervention_unicef_focal_points_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intervention',
            name='unicef_signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_interventions+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreementamendment',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='partners.Agreement'),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='partners.Intervention'),
        ),
        migrations.AddField(
            model_name='supplyplan',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='partners.Intervention'),
        ),
        migrations.AlterUniqueTogether(
            name='interventionplannedvisits',
            unique_together=set([('intervention', 'year')]),
        ),
    ]
