# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-23 20:05
from __future__ import unicode_literals

from django.db import migrations


def migrate_authorized_officers(apps, schema_editor):
    AuthorizedOfficer = apps.get_model("partners", "AuthorizedOfficer")
    authorized_officers = AuthorizedOfficer.objects.all()
    for item in authorized_officers:
        agreement = item.agreement
        officer = item.officer
        agreement.partner_staff_members.add(officer)
        agreement.save()


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_agreement_partner_staff_members'),
    ]

    operations = [
        migrations.RunPython(migrate_authorized_officers),
    ]
