# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-06 11:56
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import partners.models
import EquiTrack.utils


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20161118_0631'),
        ('reports', '0003_auto_20161227_1953'),
        ('users', '0002_userprofile_guid'),
        ('partners', '0005_auto_20161227_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionSectorLocationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='interventionlocationslink',
            name='intervention_result_link',
        ),
        migrations.RemoveField(
            model_name='interventionlocationslink',
            name='location',
        ),
        migrations.RemoveField(
            model_name='interventionlocationslink',
            name='sectors',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='account_title',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='bank_address',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='bank_contact_person',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='routing_details',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='amendment',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='office',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='sector',
        ),
        migrations.AddField(
            model_name='agreement',
            name='country_programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='reports.CountryProgramme'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='_intervention_offices_+', to='users.Office'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='partners.PartnerOrganization'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=django_fsm.FSMField(blank=True, choices=[('draft', 'Draft'), ('cancelled', 'Cancelled'), ('active', 'Active'), ('ended', 'Ended'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='agreementamendment',
            name='number',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='fr_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Reference Number'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='prc_review_document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=partners.models.get_prc_intervention_file_path),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='submission_date',
            field=models.DateField(blank=True, help_text='The date the partner submitted complete PD/SSFA documents to Unicef', null=True),
        ),
        migrations.AlterField(
            model_name='interventionamendment',
            name='type',
            field=models.CharField(choices=[('CPR', b'Change in Programme Result'), ('CPF', b'Change in Population Focus'), ('CGC', b'Change in Georgraphical Coverage'), ('CTBGT20', b'Change in Total Budget >20%'), ('CTBLT20', b'Change in Total Budget <=20%'), ('CABLT20', b'Changes in Activity Budget <=20% - No Change in Total Budget'), ('CABGT20', b'Changes in Activity Budget >20% - No Change in Total Budget - Prior approval in authorized FACE'), ('CABGT20FACE', b'Changes in Activity Budget >20% - No Change in Total Budget - Reporting at FACE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='interventionattachment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.FileType'),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='in_kind_amount_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name=b'UNICEF Supplies Local'),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='partner_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='partner_contribution_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='unicef_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='interventionbudget',
            name='unicef_cash_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='interventionplannedvisits',
            name='year',
            field=models.IntegerField(default=EquiTrack.utils.get_current_year),
        ),
        migrations.AlterUniqueTogether(
            name='interventionbudget',
            unique_together=set([('year', 'intervention')]),
        ),
        migrations.DeleteModel(
            name='InterventionLocationsLink',
        ),
        migrations.AddField(
            model_name='interventionsectorlocationlink',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_locations', to='partners.Intervention'),
        ),
        migrations.AddField(
            model_name='interventionsectorlocationlink',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='intervention_sector_locations', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='interventionsectorlocationlink',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_locations', to='reports.Sector'),
        ),
    ]
