# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-12 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_make_not_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerorganization',
            name='type_of_assessment',
            field=models.CharField(choices=[('MICRO ASSESSMENT', 'Micro Assessment'), ('HIGH RISK ASSUMED', 'High Risk Assumed'), ('LOW RISK ASSUMED', 'Low Risk Assumed'), ('NEGATIVE AUDIT RESULTS', 'Negative Audit Results'), ('SIMPLIFIED CHECKLIST', 'Simplified Checklist'), ('OTHERS', 'Others')], default='', max_length=50, verbose_name='Assessment Type'),
        ),
    ]
