# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-28 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_agreement_partner_staff_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='partner_staff_members',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='partners.PartnerStaffMember'),
        ),
    ]
