# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-10 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20161214_1200'),
        ('partners', '0006_auto_20170106_1356'),
    ]

    operations = [
    ]
