# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-09 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def reverse(apps, schema_editor):
    pass

def gov_int_copy_rs_to_cp(apps, schema_editor):
    GovernmentIntervention = apps.get_model('partners', 'GovernmentIntervention')
    CountryProgramme = apps.get_model('reports', 'CountryProgramme')
    for gi in GovernmentIntervention.objects.all():
        try:
            gi.country_programme = CountryProgramme.objects.get(wbs__contains='/A0/',
                                                                from_date__lte=gi.result_structure.from_date,
                                                                to_date__gte=gi.result_structure.to_date)
            gi.save()
            print 'saved gi {}'.format(gi.number)
        except CountryProgramme.DoesNotExist:
            print 'Mismatch in the schema. Country Programme does not exist for all ResultStructures gi:'.format(gi.number)
        except CountryProgramme.MultipleObjectsReturned:
            gi.country_programme = CountryProgramme.objects.filter(wbs__contains='/A0/',
                                                                from_date__lte=gi.result_structure.from_date,
                                                                to_date__gte=gi.result_structure.to_date).first()
            gi.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20161227_1953'),
        ('partners', '0006_auto_20170106_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentintervention',
            name='country_programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name=b'government_interventions', to='reports.CountryProgramme'),
        ),
        migrations.AlterField(
            model_name='governmentintervention',
            name='result_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reports.ResultStructure'),
        ),
        migrations.RunPython(
            gov_int_copy_rs_to_cp, reverse_code=reverse
        )
    ]
