# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-11 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20170106_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gwpcalocation',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='gwpcalocation',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='gwpcalocation',
            name='region',
        ),
    ]
