# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-29 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20161228_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='account_title',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='bank_address',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='bank_contact_person',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='routing_details',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='amendment',
        ),
        migrations.AlterField(
            model_name='agreement',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='partners.PartnerOrganization'),
        ),
        migrations.AlterField(
            model_name='agreementamendment',
            name='number',
            field=models.CharField(max_length=5),
        ),
    ]
