# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-11 18:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20170109_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentinterventionresult',
            name='activities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
