# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_guid'),
        ('partners', '0010_auto_20161230_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='office',
        ),
        migrations.AddField(
            model_name='intervention',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='_intervention_offices_+', to='users.Office'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='prc_review_document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=partners.models.get_prc_intervention_file_path),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='submission_date',
            field=models.DateField(blank=True, help_text='The date the partner submitted complete PD/SSFA documents to Unicef', null=True),
        ),
        migrations.AlterField(
            model_name='interventionplannedvisits',
            name='year',
            field=models.IntegerField(default=2017),
        ),
    ]
