# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-26 21:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_remove_partnerorganization_hact_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='hact_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=partners.models.hact_default, null=True),
        ),
    ]
