# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-06 10:56
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0013_auto_20170105_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='fr_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=None),
        ),
    ]
