# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-31 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0016_auto_20170130_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='agreement',
        ),
    ]
