# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-07 20:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0018_auto_20170203_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementAmendmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'Change IP name', b'Change in Legal Name of Implementing Partner'), (b'CP extension', b'Extension of Country Programme Cycle'), (b'Change authorized officer', b'Change Authorized Officer'), (b'Change banking info', b'Banking Information'), (b'Additional clause', b'Additional Clause'), (b'Amend existing clause', b'Amend Existing Clause')], max_length=64)),
                ('label', models.TextField(blank=True, null=True)),
                ('change_description', models.TextField(blank=True, null=True)),
                ('change_model', models.CharField(max_length=30)),
                ('change_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='agreementamendment',
            name='type',
        ),
        migrations.AddField(
            model_name='agreementamendment',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='partners.AgreementAmendmentType'),
        ),
    ]
