# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-08 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0018_auto_20170203_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementAmendmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'Change IP name', b'Change in Legal Name of Implementing Partner'), (b'CP extension', b'Extension of Country Programme Cycle'), (b'Change authorized officer', b'Change Authorized Officer'), (b'Change banking info', b'Banking Information'), (b'Additional clause', b'Additional Clause'), (b'Amend existing clause', b'Amend Existing Clause')], max_length=64)),
                ('label', models.TextField(blank=True, null=True)),
                ('officer', models.IntegerField(blank=True, null=True)),
                ('bank_info', models.TextField(blank=True, null=True)),
                ('legal_name_of_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('cp_cycle_end', models.DateField(blank=True, null=True)),
                ('additional_clauses', models.TextField(blank=True, null=True)),
                ('existing_clause_amended', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agreementamendment',
            name='type',
        ),
        migrations.AddField(
            model_name='agreementamendmenttype',
            name='agreement_amendment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendment_types', to='partners.AgreementAmendment'),
        ),
    ]
