# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-14 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_auto_20170208_2158'),
        ('partners', '0019_governmentinterventionresultactivity'),
    ]

    operations = [
    ]
