# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20160222_1652'),
        ('locations', '0004_auto_20160222_1652'),
        ('partners', '0021_partnerstaffmember_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('total', models.PositiveIntegerField()),
                ('disaggregated', models.BooleanField(default=False)),
                ('disaggregation', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.Indicator')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('partner_staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_reports', to='partners.PartnerStaffMember')),
                ('result_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_reports', to='partners.ResultChain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
