# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-01 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0021_interventionbudget_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerstaffmember',
            name='title',
            field=models.CharField(blank=True, max_length=64L, null=True),
        ),
    ]
