# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-04 17:41
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import Count

def reverse(apps, schema_editor):
    pass

def gov_int_unique_reference_number(apps, schema_editor):
    GovernmentIntervention = apps.get_model('partners', 'GovernmentIntervention')
    gov_ints = GovernmentIntervention.objects.all()
    for gov in gov_ints:
        if not gov.number:
            print(gov)
            gov.number = 'blk:{}'.format(gov.id)
            gov.save()
    dupes = GovernmentIntervention.objects.values('number').annotate(
        Count('number')).order_by().filter(number__count__gt=1).all()
    for dup in dupes:
        cdupes = GovernmentIntervention.objects.filter(number=dup['number'])
        for cdup in cdupes:
            if len(cdup.number) > 40:
                cdup.number = cdup.number[len(cdup.number) - 40:]
            cdup.number = '{}|{}'.format(cdup.number, cdup.id)
            cdup.save()


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0023_auto_20170301_2324'),
    ]

    operations = [
        migrations.RunPython(
            gov_int_unique_reference_number, reverse_code=reverse),

        migrations.AlterField(
            model_name='governmentintervention',
            name='number',
            field=models.CharField(blank=True, max_length=45L, unique=True, verbose_name=b'Reference Number'),
        ),
    ]
