# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0023_resultchain_current_progress'),
        ('partners', '0022_auto_20160223_2222'),
    ]

    operations = [
    ]
