# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-12 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0024_auto_20170404_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerstaffmember',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
