# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-28 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0025_auto_20170412_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pca',
            options={'ordering': ['-created_at'], 'verbose_name': 'Old Intervention', 'verbose_name_plural': 'Old Interventions'},
        ),
    ]
