# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0024_merge'),
        ('partners', '0026_auto_20160229_1545'),
    ]

    operations = [
    ]
