# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-17 15:16
from __future__ import unicode_literals
import logging
from django.db import migrations, models


def reverse(apps, schema_editor):
    pass


def migrate_assessments(apps, schema_editor):
    Assessment = apps.get_model('partners', 'Assessment')
    # migrating high risk assumed types to other
    assesments = Assessment.objects.filter(type="High Risk Assumed")
    for assesment in assesments:
        assesment.type = "Other"
        assesment.save()
        logging.info("assessment id: {}".format(assesment.id))


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0027_auto_20170503_1430'),
    ]

    operations = [
        migrations.RunPython(
            migrate_assessments, reverse_code=reverse
        ),
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[(b'Micro Assessment', 'Micro Assessment'), (b'Simplified Checklist', 'Simplified Checklist'), (b'Scheduled Audit report', 'Scheduled Audit report'), (b'Special Audit report', 'Special Audit report'), (b'Other', 'Other')], max_length=50),
        ),
    ]
