# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-05 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0029_auto_20170517_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='hrp',
        ),
    ]
