# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-12 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0029_auto_20170517_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='signed_pd_document',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=partners.models.get_prc_intervention_file_path),
        ),
    ]
