# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-14 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_countryprogramme_invalid'),
        ('partners', '0032_auto_20170612_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governmentintervention',
            name='result_structure',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='hrp',
        ),
        migrations.RemoveField(
            model_name='pca',
            name='result_structure',
        ),
        migrations.AddField(
            model_name='intervention',
            name='country_programme',
            field=models.ForeignKey(blank=True, help_text='Which Country Programme does this Intervention belong to?', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interventions', to='reports.CountryProgramme'),
        ),
    ]
