# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-17 20:17
from __future__ import unicode_literals
from django.db import migrations


def reverse(apps, schema_editor):
    pass


def migrate_cps(apps, schema_editor):
    CountryProgramme = apps.get_model('reports', 'CountryProgramme')
    Agreement = apps.get_model('partners', 'Agreement')
    cps = CountryProgramme.objects.filter(invalid=False, wbs__contains='/A0/')
    for cp in cps:
        agrs = Agreement.objects.all()
        agreements = Agreement.objects.filter(start__gte=cp.from_date,
                                              start__lte=cp.to_date,
                                              country_programme__isnull=True).update(country_programme=cp)
        if agreements == 0:
            print('No agreements found with CP {}'.format(cp.name))
        else:
            print('CP {} updated {} agreements'.format(cp.name, agreements))


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0033_auto_20170614_1831'),
    ]

    operations = [
        # This is required or 'apps.get_model' will fail in the end
        migrations.AlterModelManagers(
            name='agreement',
            managers=[
            ],
        ),
        migrations.RunPython(
            migrate_cps, reverse_code=reverse),
    ]
