# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-21 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0033_auto_20170614_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementamendmenttype',
            name='type',
            field=models.CharField(choices=[('Change IP name', 'Change in Legal Name of Implementing Partner'), ('Change authorized officer', 'Change Authorized Officer(s)'), ('Change banking info', 'Banking Information'), ('Change in clause', 'Change in Clause')], max_length=64),
        ),
    ]
