# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-23 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0034_fr_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='fr_numbers',
        ),
    ]
