# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-27 18:50
from __future__ import unicode_literals

from django.db import migrations
import django_fsm
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0035_remove_intervention_fr_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=django_fsm.FSMField(blank=True, choices=[('draft', 'Draft'), ('cancelled', 'Cancelled'), ('active', 'Active'), ('signed', 'Signed'), ('ended', 'Ended'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='draft', max_length=32),
        ),
    ]
