# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-27 16:00
from __future__ import unicode_literals, print_function

from django.db import migrations, models


def reverse(apps, schema_editor):
    pass


def migrate_agreement_status(apps, schema_editor):
    Agreement = apps.get_model('partners', 'Agreement')
    agreements = Agreement.objects.filter(status="active").update(status="signed")
    print(agreements)


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0036_auto_20170627_1850'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agreement',
            managers=[
            ],
        ),

        migrations.RunPython(
            migrate_agreement_status, reverse_code=reverse),

        migrations.AlterModelManagers(
            name='agreement',
            managers=[
                ('view_objects', models.manager.Manager()),
            ],
        ),

    ]
