# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0039_auto_20170629_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='contingency_pd',
            field=models.BooleanField(default=False),
        ),
    ]
