# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-06 17:31
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0040_intervention_contingency_pd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=django_fsm.FSMField(blank=True, choices=[('draft', 'Draft'), ('signed', 'Signed'), ('active', 'Active'), ('ended', 'Ended'), ('closed', 'Closed'), ('implemented', 'Implemented'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
    ]
