# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-05 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0040_auto_20170703_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreementamendmenttype',
            name='agreement_amendment',
        ),
        migrations.DeleteModel(
            name='AgreementAmendmentType',
        ),
    ]
