# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-14 17:38
from __future__ import unicode_literals

from django.db import migrations, models, connection, transaction

MAPPER = {
 'Sudan':
     {'Correspondence': ['Letter of Termination'],
      'Other': ['Partner selection', 'PRC form', 'Others',
                'Third party monitoring report', 'Spot check Report',
                'Field trip report', 'Monthly reports from IP', 'Q-reports from IP',
                'Amendment', 'PCA checklist', 'Programme Document Amendment', 'Annex G PRC form',
                'ADRA PD1 EDU Amendment 1 budget signed', 'ADRA PD1 EDU Amendment 1 signed',
                'ADRA PD1 EDU budget signed', 'Programme Document', 'Situation Monitoring', 'Programme Document budget',
                'Programme Document signed', 'AlAlag PD 1 CP signed', 'test', 'HAD final Budget', 'HAD Proposal',
                'DSRI Budget', 'DSRI Proposal', 'SOL Busget', 'SOL Proposal', 'KSCS Proposal', 'KCSC Budget',
                'KYCCB Budget', 'KYCCB Proposal', 'SSFA FPDO Budget', 'SSFA FPDO Proposal', 'Budget', 'Proposal',
                'RAFA Final Budget', 'RAFA Proposal', 'Almanar Budget', 'Almanar Proposal', 'CIS Budget', 'CIS Proposal',
                'Oxfam Budget', 'Oxfam Proposal', 'Ahnar Budget', 'Ahnar Proposal', 'ZOA Budget', 'ZOA Proposal', 'AlMassar Budget',
                'ElMassar Proposal', 'UPD Budget', 'UPD Proposal', 'WCC Amended Budget', 'WCC Amended project',
                'WCC Budget', 'WCC Proposal', 'CDO Budget', 'CDO Propposal', 'FRDN Budget', 'FRDN Proposal',
                'NCA Amendes Project', 'NCA Budget', 'PCA NCA Proposal', 'CAFOD Revised Budget',
                'Revised CAFOD Proposal', 'Amended CAFOD Budget', 'Amended Proposal', 'ADRA Amended Budget',
                'ADRA 1st Amendment', 'ADRA Budget', 'Adra Proposal', 'Amended Budget', 'SCS Amended Proposal',
                'SCS Scanned document', 'Nutrition budget', 'Nutrition project', 'Amended budget', 'Signed amendment',
                'Plan Budget', 'Final Plan PCA', 'Concern Budget', 'Concern Proposal', 'PBSFDHW Budget',
                'SSFA Document', 'SCS Budget', 'SCS Proposal', 'CDF Budget', 'CDF Project', 'RAFA Budget',
                'RAFA SSFA Format', 'Labena Budget WASH', 'Labena WASH', 'Labena Education', 'Labena Wash',
                'Rayra Budget Final', 'SSFA Rayira Final Doc', 'HAD Budget', 'SSFA HAD Final', 'CAFOD Budget',
                'Final TearFund Budget', 'Final PCA Document', 'Picture'],
      'Partnership Review': ['Joint Partnership Review Report'],
      'FACE': ['Face Form']},
 'Nepal':
     {'Other': ['docx', 't', 'tpm', 'pdf', 'TPM', '*.jpg']},
 'Cambodia':
     {'Progress Report': ['Progress Report'],
      'Other': ['Programme Document', 'Picture', 'aquatabs', 'PCA', 'nfi', 'Budget', 'Amendment'],
      'FACE': ['FACE']},
 'Rwanda':
     {'Correspondence': ['Corresponsdence'],
      'Final Partnership Review': ['Final Partnership Review'],
      'FACE': ['FACE'],
      'Progress Report': ['Progress Report'],
      'Other': ['Other'],
      'Partnership Review': ['Partnership Review']},
 'Somalia':
     {'Other': ['Picture']},
 'Palestine':
     {'Other': ['Trip Report', 'Programme Document', 'PCA']},
 'Nigeria':
     {'Other': ['TCF 2016 Prog Doc. WASH', 'PIND 2016 Prog. Doc. WASH', 'CIDAR 2016 Prog. Doc. WASH', 'Picture',
                'SDG report', 'Ambrose Atalor_docs', 'Emmanuel Olutunde']},
 'China':
     {'Progress Report': ['Progress report'],
      'Other': ['File', 'Picture', 'Picture1']},
 'Jordan':
     {'Other': ['SSFA ToR', 'Trip Report', 'Program visit', 'Cost extension', 'NCE', 'Programme Document',
                      'Programme visit report-MOE-ECD Teachers Training']},
 'Iraq':
     {'Progress Report': ['Spot-Check Report', 'Progress Report'],
      'Other': ['SHPD', 'PRC Submission Form', 'Budget', 'Programme Document'],
      'Partnership Review': ['Annual Review', 'Joint Review Report']},
 'Liberia':
     {'Other': ['ccnccccc', 'Nimba', 'Picture']},
 'Kyrgyzstan':
     {'Correspondence': ['Correspondence'],
      ' TA"': ['"Security Clearance'],
      'Other': ['Security Clearance', 'SC', 'ticket 2', 'ticket 1', 'Other', 'List of Participants',
                'Meeting Minutes', 'Meeting Protocol', 'Agenda', 'Admin Note', 'PICTURE', 'F10']},
 'Indonesia':
     {'Other': ['Minutes of Training', 'Activity Report from STKIP', 'Picture', 'PRODOC YNS',
                         'Prodoc LP4M UNAIR', 'ProDoc STKIP Amendment 1', 'Prodoc ACF', 'ProDoc Pramuka',
                         'ProDoc WVI', 'Prodoc PKPM']},
 'Syria Cross Border':
     {'Correspondence': ['Email Correspondence', 'Official Letter'],
      'FACE': ['ICE Form', 'FACE Forms'],
      'Progress Report': ['Monitoring Report', 'Progress Report (narrative)'],
      'Other': ['SSFA_amendment', 'Amendment to PCA', 'Annex D', 'Annex G Submission Form Draft',
                'Authorization to CSO for Procurement', 'SSFA', 'Budget', 'PRC Submission form',
                'NFR', 'PD amendment', 'PD budget table', 'Old format PCA', 'Programmatic Assessment',
                'PCA word Initial', 'Micro Assessment', 'Report', 'CSO Registration', 'Annex G Submission Form',
                'Annex F CSO Identification Profile', 'Annex E Partner Declaration', 'Annex C Programme Document',
                'PD Draft', 'Annex', 'PD Signed', 'PCA Signed', 'PCA', 'Picture', 'Trip report'],
      'Supply/Distribution Plan': ['Supply Distribution Report', 'Supply Distribution Plan'],
      'Partnership Review': ['Joint Partnership Review']},
 'South Sudan':
     {'Other': ['PCA Signed Package', 'CMD-Edu-Oct16', 'CAO-CP-Oct16', 'AHA-Health-October2016',
                'CMMB-Nutrition-No Cost Extension', 'CMMB-Nutrition-May2016', 'CCC-CP-September2016',
                'CDOT-CP-November2016-Budget Reduction', 'CDOT-CP-April2016 Original', 'CEDS-WASH-September2016',
                'C&D-Education-September2016', 'Picture', 'TDH-CP-Programme Document',
                'ADRA Education Intervention Packet', 'AFOD Nutrition Intervention Packet',
                'AFOD Cholera Intervention Packet']},
 'Syria':
     {'Correspondence': ['extension letter', 'Extention Letters', 'Email correspondences', 'Official letter',
                         'Request letter', 'Ammendment Letter', 'MoFA letter'],
      'Final Partnership Review': ['Closure Report'],
      'FACE': ['Face Form', 'Payment Request', 'Face form for amendment', 'Faceform', 'Financial Statement', 'FACE'],
      'Progress Report': ['Progress Report', 'hala reports'],
      'Other': ['HACT Comittee meeting endoresment on amnedment', 'Tartous Trip Report - Aug 2015', 'Revised Budget', 'Revised Program Document',
                'Cost Extension request', 'Revised PD', 'Simplified Program Document', 'PRC Submission Form',
                'PRC Review and Recommendation', 'Micro Assesement', 'ammendment letter with ammended part of budget',
                'closure letter from Unicef', 'End of agreement', 'Extension Budget-Education', 'PROPOSAL',
                'Legal Document Ext.', 'Ihsan Charity', 'Summary', 'IP report 2', 'IP report 1', 'IP report',
                'IP reports', 'alihsan', 'NCE approval letter', 'Duty travel Meeting', 'PDF', 'duty travel report',
                'Trip Report', 'amandment doc', 'Training', 'Work Plan', 'Closure of PCA', 'Al birr Homs NCE',
                'extension request letter', 'PCA in Arabic', 'PCA Summary', 'IECD Jaramana Final Budget',
                'IECD Jaramana Programme Document', 'IECD Jaramana Final PCA', 'IECD Final PCA',
                'Nour Programme Document', 'Nour Signed Budget', 'Nour signed budget', 'Nour Signed PCA',
                'Damascus FO Duty Travel Reports', 'cancelation', 'Reason of Cancelation', 'another papers',
                'PRC review', 'Risk Mitigation', 'Al Sham Association For health', 'liquidation second payment',
                'Work plan', 'Identification Profile', 'First installment', 'Al Wasal EDU SSFA.pdf',
                'No cost extension', 'Amendment budget', 'Legal Doc Arabic', 'Aoun Authorization',
                'Aoun PD', 'Aoun Budget', '-', 'Programme document', 'IYCF Budget', 'Amendment NFR',
                'Market Assessment', 'Manar', 'Trip report', 'Duty Travel Report', 'Report', 'Cancel the project',
                'Liquidation first payment and request the second one', 'budget annex', 'Mitigation plan',
                'First Payment request', 'Program Document', 'micrp assesemnt', 'Financial Note ( Amendment Request)',
                '"Justification Note "" Amendment Budget"""', 'al namaa', 'Damascus mission report', 'NFR', 'TA',
                'Homs Trip Report', 'Programme Document', 'IP Request', 'Amended Budget', 'Extension request', 'Vendor',
                'PCA', 'Session materials', 'Sessions materials', 'Declaration', 'SSFA Agreement', 'Technical Report',
                'Addendum', 'Simplified Program Doc SSFA', 'Capacity and Integrity Assessment',
                'Programatic Assessment', 'Assessment', 'Installment', 'Partner Declaration',
                'Lattakia mission report 11 ofMay .docx', 'Risk education monitoring', 'Liquidation',
                'Field Mission to Lattakia 29 March 2015', 'SARC PSS Hama/ mobile team', 'Hama field mission',
                'Al Balad Al Ameen Logframe', 'Al Balad Al Ameen Propsal', 'Al Balad Al Ameen Joint Workplan',
                'Al Balad Al Ameen Budget Agreement', 'Al Balad Al Ameen PCA 2015', 'Youth Volunteers Homs - Photos',
                'Syria 4 years mark_ Youth Volunteers Homs - Photos', 'Revised Joint Workplan PSS 2 for Aoun',
                'Aoun 2015 agreement budget', 'Aount PSS Revised 24-2', 'Aoun Revised PSS logframe', 'Aoun 2015 PCA',
                'Al birr Homs H&N Checklist March 015', 'Al Birr Homs H&N Workplan March 015',
                'Al Birr Homs H&N logfram March 015', 'Al Birr Homs H&N Budget March 015',
                'Al Birr Homs H&N Proposal March 015', 'PCA SYR_CP_2014_100.pdf', 'SARC Hesiaa',
                'junenile centre', 'Al Shaheed', '////', '///', '//', '/', '******', '*****', '****',
                '***', '**', '*', '--------', '------', '...................', '----------', '.........',
                '-----', '.....................', '..........', '........', '.......', '.....', '....', '...',
                '..', '.', '----', '---', 'Budget', '--', 'Meeting Minutes of Homs ESWG, 14 June2015'],
      'Partnership Review': ['Joint PAtrnership review', 'partner joint review', 'Joint Partnership Review']},
 'Yemen':
     {'Other': ['Others', 'Partner Declaration', 'signed Programme Document']},
 'Myanmar':
     {'Other': ['Programme Document', 'pdf', 'Picture']},
 'South Africa': {'Other': ['PCA Contract', 'Annex G - PCA Submission', 'Spot-Check Report', 'Annex 1 - SSFA',
                            'Umbrella Agreement', 'Annex E', 'Annex F', 'Annex C', 'Project Budget',
                            'PCA Submission Form', 'Programme Document']},
 'Lebanon':
     {'Correspondence': ['Official Letter to Partner', 'Request Letter from Partner'],
      'Final Partnership Review': ['Final Report'],
      'Progress Report': ['HACT programmatic Report 2', 'HACT programmatic Report',
                          'Mid-Year Review Presentation'],
      'Other': ['Visibilty', 'ARCPA Budget 2017', 'Briefing note', 'Programme Document', 'Handover Document',
                'Chaat', 'Communication and Visibility', 'Case Management assessment', 'Plan', 'assessment',
                'Hact', 'HACT for makhzoumi', 'presentation', 'kjhkj', 'hact wvl', 'Youth', 'Strategy Document',
                'List of sites', 'Programme document', 'Focus Group Discussion', 'Power Point Presentation',
                'Outcome doc', 'Video', 'Heartland Alliance budget', 'Trip Report Zigahta',
                'Programme Overview', 'Presentation', 'Action plan', 'Agenda', 'Work Plan', 'MoM',
                'Stock Count', 'NGO Briefing', 'List of schools', 'Spot Check', 'Schedule', 'Certificate',
                'HACT', 'Picture', 'other', 'Trip report', 'MoU', 'SSFA', 'Fast Track', 'PCARC Minutes',
                'PCA Submission', 'HRRP File', 'Amendment', 'PCA Agreement', 'Proposal', 'pca_signed',
                'Course certificate', 'PCA cover note', 'proposal', 'Addendum', 'Logframe', 'Budget'],
      'Supply/Distribution Plan': ['Supply Plan']},
 'Uganda':
     {'Progress Report': ['ANNEX C_ PROGRAMME PROGRESS/FINAL REPORT'],
      'Other': ['Amendment', 'Annex G_ PRC SUBMISSION_REVIEW_APPROVAL', 'ANNEX C_PROGRAMME WORKPLAN & BUDGET',
                'ANNEX C_ PROGRAMME DOCUMENT'], 'Partnership Review': ['ANNEX I_JOINT PARTNERSHIP REVIEW']},
 'Kenya':
     {'Correspondence': ['Email', 'email approval', 'Invitation letter', "Doctor's Appointment", 'Letter',
                         'Invite letter', 'Travel Plans/Email Approvals'],
      'Other': ['Approved March Travel Plan', 'IP List', 'Trip Funding Source', 'KSM Security Clearance',
                'Trip Report -Wilson Kisiero', 'Travel plan changes request', 'Victoria Travel plan',
                'Travel Authorization', 'Trip Approval', 'security Clearance', 'Special Approval',
                'Travel Approval', 'Zeinab Seurity clearnce', 'Zeinab Security clearnce', 'Garissa travel plan Q1',
                'Zeinab security clearance', '.pdf', 'tp', 'Approval to change travel dates and itinerary',
                'Supporting evidence', 'Budget', 'Concept note', 'security clearance', 'air ticket',
                'Feb 2017 Travel Plan', 'travel plan', 'Agenda Items', 'security', 'Securitysigned trip',
                'Security Clearance Embu', 'Itinerary', 'Security Clearance Tana River', 'Approved Travel Plan',
                'Approval change of destination', 'Approval for change of trip dates', 'Samburu Trip Report',
                'Approved Travel plan', 'Security Clearance Habaswein-Wajir', 'Trip report', 'Security Clearance',
                'Approved change of destination', 'Air Ticket', 'Security clearance', 'Travel Authorization (TA)',
                'Travel Plan', 'Email Approval', 'SPECIAL APPROVAL GRANTED', 'Special Approval Granted',
                'Travel Plans/Email Approvals', 'Trial', 'LZO Bulletin', 'Trip report Ekitela',
                'child marriage report', 'Trip Report Stanley', 'Trip Number', 'List of Schools',
                'Special approval', 'Amolo Trip report', 'Approval for change of dates', 'Picture',
                'Trip Report', 'Jonah', 'November Travel Plan']}}

def reverse(apps, schema_editor):
    # raise BaseException('this migration cannot be reversed')
    pass

@transaction.atomic
def migrate_cps(apps, schema_editor):
    FileType = apps.get_model('partners', 'FileType')
    InterventionAttachment = apps.get_model('partners', 'InterventionAttachment')
    Workspace = apps.get_model('users', 'Country')
    tenant = Workspace.objects.get(schema_name=connection.schema_name)
    country_ft_map = MAPPER.get(tenant.name, None)
    skipped = 0
    migrated = 0


    # make sure the required file types are there
    required_file_types = ['FACE',
                           'Progress Report',
                           'Partnership Review',
                           'Final Partnership Review',
                           'Correspondence',
                           'Supply/Distribution Plan',
                           'Other']

    # dictionary mapping file type string to file type object
    rft = {}
    for ft in required_file_types:
        rft[ft], created = FileType.objects.get_or_create(name=ft)

    attachments = InterventionAttachment.objects.prefetch_related('type').all()
    total = attachments.count()

    if not country_ft_map:
        print('No mapper for %s'%tenant.name)
    else:
        # get all intervention file attachements
        for a in attachments:
            if a.type.name in required_file_types:
                skipped +=1
                # this means that the document is already a valid type
                continue

            for k in country_ft_map.keys():
                if a.type.name in country_ft_map[k]:
                    migrated += 1
                    a.type = rft[k]
                    a.save()

    print('Skipped %s'%skipped)
    print('Migrated %s'%migrated)
    print('Total %s'%total)
    # check to ensure that there are no other file types that have been messed up
    if InterventionAttachment.objects.exclude(type__name__in=required_file_types).all().count():
        print('################################################### Some Attachments are still messed up')
        # raise BaseException('Attachments in {} are still messed up..please check again')


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0044_auto_20170711_1611'),
        ('users', '0007_country_long_name'),
    ]

    operations = [
        migrations.RunPython(
            migrate_cps, reverse_code=reverse),

        migrations.AlterField(
            model_name='filetype',
            name='name',
            field=models.CharField(choices=[('FACE', 'FACE'), ('Progress Report', 'Progress Report'), ('Partnership Review', 'Partnership Review'), ('Correspondence', 'Correspondence'), ('Supply/Distribution Plan', 'Supply/Distribution Plan'), ('Other', 'Other')], max_length=64, unique=True),
        ),
    ]
