# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-14 18:44
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0045_auto_20170714_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionattachment',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='interventionattachment',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterModelOptions(
            name='interventionattachment',
            options={'ordering': ['-created']},
        ),
    ]
