# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-02 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0046_auto_20170714_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'ordering': ['created']},
        ),
    ]
