# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-23 20:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0047_auto_20170807_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementamendment',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Change IP name', 'Change in Legal Name of Implementing Partner'), ('Change authorized officer', 'Change Authorized Officer(s)'), ('Change banking info', 'Banking Information'), ('Change in clause', 'Change in clause')], max_length=50), size=None),
        ),
    ]
