# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-15 17:35
from __future__ import unicode_literals

from django.db import migrations, models, connection, transaction


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0049_intervention_sections'),
    ]

    def reverse(apps, schema_editor):
        pass

    @transaction.atomic
    def migrate_sector_location_links_to_intervention_section(apps, schema_editor):
        InterventionSectorLocationLink = apps.get_model('partners', 'InterventionSectorLocationLink')
        Intervention = apps.get_model('partners', 'Intervention')
        Section = apps.get_model('users', 'Section')

        for interventionsector in InterventionSectorLocationLink.objects.all():
            print "sector: %s" % interventionsector.sector.name
            try:
                section = Section.objects.get(pk=interventionsector.sector.id)
                print "section: %s \n" % section.name
            except Section.DoesNotExist:
                print "no corresponding section\n"

            #Intervention.objects.get(pk=interventionsector.intervention.id).sections.create(
            #    section_id=section.id
            #)

    operations = [
        migrations.RunPython(migrate_sector_location_links_to_intervention_section, reverse_code=reverse)
    ]

