# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-21 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0050_auto_20170914_1510'),
        ('partners', '0050_migrate_intervention_sectors_to_sections'),
    ]

    operations = [
    ]
