# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-29 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0051_remove_governmentinterventionresult_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionplan',
            name='intervention',
        ),
        migrations.RemoveField(
            model_name='distributionplan',
            name='item',
        ),
        migrations.RemoveField(
            model_name='distributionplan',
            name='partnership',
        ),
        migrations.RemoveField(
            model_name='distributionplan',
            name='site',
        ),
        migrations.RemoveField(
            model_name='supplyplan',
            name='intervention',
        ),
        migrations.RemoveField(
            model_name='supplyplan',
            name='item',
        ),
        migrations.RemoveField(
            model_name='supplyplan',
            name='partnership',
        ),
        migrations.DeleteModel(
            name='DistributionPlan',
        ),
        migrations.DeleteModel(
            name='SupplyPlan',
        ),
    ]
