# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-11 13:18
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0052_auto_20170929_1933'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agreementamendment',
            managers=[
                ('view_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
