# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-13 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0053_auto_20171011_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreementamendmentlog',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='indicatorreport',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='indicatorreport',
            name='location',
        ),
        migrations.RemoveField(
            model_name='indicatorreport',
            name='partner_staff_member',
        ),
        migrations.DeleteModel(
            name='AgreementAmendmentLog',
        ),
        migrations.DeleteModel(
            name='IndicatorReport',
        ),
    ]
