# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-25 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0054_auto_20171013_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='document_type',
            field=models.CharField(choices=[('PD', 'Programme Document'), ('SHPD', 'Simplified Humanitarian Programme Document'), ('SSFA', 'Small Scale Funding Agreement')], max_length=255, verbose_name='Document type'),
        ),
    ]
