# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-20 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0055_auto_20171020_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='document_type',
            field=models.CharField(choices=[('PD', 'Programme Document'), ('SHPD', 'Simplified Humanitarian Programme Document'), ('SSFA', 'SSFA')], max_length=255, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='review_date_prc',
            field=models.DateField(blank=True, help_text='The date the PRC reviewed the partnership', null=True, verbose_name='Review Date by PRC'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Document Title'),
        ),
    ]
