# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-15 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_workspacecounter'),
        ('partners', '0055_read_only_api_permission_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='interventions', to='reports.Sector'),
        ),
    ]
