# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-25 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0054_auto_20171013_2147'),
        ('partners', '0056_auto_20171020_1530'),
    ]

    operations = [
    ]
