# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-06 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0058_intervention_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='net_ct_cy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net Cash Transferred per Current Year', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='reported_cy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Liquidations 1 Oct - 30 Sep', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='total_ct_ytd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cash Transfers Jan - Dec', max_digits=12, null=True),
        ),
    ]
