# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-26 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0058_interventionreportingperiod'),
        ('partners', '0053_auto_20171024_1011'),
    ]

    operations = [
    ]
