# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-21 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0059_auto_20180206_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionbudget',
            name='total_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
