# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-16 20:27
from __future__ import unicode_literals

import EquiTrack.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0059_auto_20180206_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedEngagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('spot_check_mr', EquiTrack.fields.QuarterField(blank=True, choices=[(b'q1', b'Q1'), (b'q2', b'Q2'), (b'q3', b'Q3'), (b'q4', b'Q4')], max_length=2, null=True)),
                ('spot_check_follow_up_q1', models.IntegerField(default=0, verbose_name='Spot Check Q1')),
                ('spot_check_follow_up_q2', models.IntegerField(default=0, verbose_name='Spot Check Q2')),
                ('spot_check_follow_up_q3', models.IntegerField(default=0, verbose_name='Spot Check Q3')),
                ('spot_check_follow_up_q4', models.IntegerField(default=0, verbose_name='Spot Check Q4')),
                ('scheduled_audit', models.BooleanField(default=False, verbose_name='Scheduled Audit')),
                ('special_audit', models.BooleanField(default=False, verbose_name='Special Audit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='interventionplannedvisits',
            name='audit',
        ),
        migrations.RemoveField(
            model_name='interventionplannedvisits',
            name='spot_checks',
        ),
        migrations.AddField(
            model_name='interventionplannedvisits',
            name='quarter',
            field=EquiTrack.fields.QuarterField(blank=True, choices=[(b'q1', b'Q1'), (b'q2', b'Q2'), (b'q3', b'Q3'), (b'q4', b'Q4')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='rating',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Significant', 'Significant'), ('Moderate', 'Medium'), ('Low', 'Low'), ('Non-Assessed', 'Non Required')], max_length=50, null=True, verbose_name='Risk Rating'),
        ),
        migrations.AddField(
            model_name='plannedengagement',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planned_engagement', to='partners.PartnerOrganization', verbose_name='Partner'),
        ),
    ]
