# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-05 18:44
from __future__ import unicode_literals

from django.db import migrations


def copy_attached_agreement(apps, schema_editor):
    # Copy attached_agreement field content to
    # attachments model
    FileType = apps.get_model("attachments", "filetype")
    Attachment = apps.get_model("attachments", "attachment")
    Agreement = apps.get_model("partners", "agreement")
    ContentType = apps.get_model("contenttypes", "ContentType")

    file_type, _ = FileType.objects.get_or_create(
        code="partners_agreement",
        defaults={
            "name": "Attached Agreement",
            "label": "attached_agreement",
            "order": 0,
        }
    )

    content_type = ContentType.objects.get_for_model(Agreement)

    for agreement in Agreement.view_objects.filter(
        attached_agreement__isnull=False
    ).all():
        Attachment.objects.create(
            content_type=content_type,
            object_id=agreement.pk,
            file=agreement.attached_agreement,
            file_type=file_type,
            code=file_type.code,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0059_auto_20180206_1548'),
        ('attachments', '0005_auto_20180206_1700'),
    ]

    operations = [
        migrations.RunPython(
            copy_attached_agreement,
            reverse_code=migrations.RunPython.noop
        )
    ]
