# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-27 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0059_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='interventions', to='reports.Sector', verbose_name='Sections'),
        ),
    ]
