# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-09 15:12
from __future__ import unicode_literals

from django.db import migrations


def copy_report(apps, schema_editor):
    # Copy report field content to attachments model
    FileType = apps.get_model("attachments", "filetype")
    Attachment = apps.get_model("attachments", "attachment")
    Assessment = apps.get_model("partners", "assessment")
    ContentType = apps.get_model("contenttypes", "ContentType")

    file_type, _ = FileType.objects.get_or_create(
        code="partners_assessment_report",
        defaults={
            "label": "Assessment Report",
            "name": "assessment_report",
            "order": 0,
        }
    )

    content_type = ContentType.objects.get_for_model(Assessment)

    for assessment in Assessment.objects.filter(
        report__isnull=False
    ).all():
        Attachment.objects.create(
            content_type=content_type,
            object_id=assessment.pk,
            file=assessment.report,
            file_type=file_type,
            code=file_type.code,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0061_auto_20180209_1250'),
    ]

    operations = [
        migrations.RunPython(
            copy_report,
            reverse_code=migrations.RunPython.noop
        )
    ]
