# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-06 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0061_auto_20171024_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='in_amendment',
            field=models.BooleanField(default=False, verbose_name='Amendment Open'),
        ),
    ]
