# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-19 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0061_auto_20180216_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerorganization',
            name='shared_partner',
        ),
    ]
