# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-21 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0062_intervention_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerorganization',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Phone Number'),
        ),
    ]
