# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-09 16:22
from __future__ import unicode_literals

from django.db import migrations


def copy_signed_amendment(apps, schema_editor):
    # Copy signed amendment field content to attachments model
    FileType = apps.get_model("attachments", "filetype")
    Attachment = apps.get_model("attachments", "attachment")
    AgreementAmendment = apps.get_model("partners", "agreementamendment")
    ContentType = apps.get_model("contenttypes", "ContentType")

    file_type, _ = FileType.objects.get_or_create(
        code="partners_agreement_amendment",
        defaults={
            "label": "Agreement Signed Amendment",
            "name": "agreement_signed_amendment",
            "order": 0,
        }
    )

    content_type = ContentType.objects.get_for_model(AgreementAmendment)

    for amendment in AgreementAmendment.view_objects.filter(
        signed_amendment__isnull=False
    ).all():
        Attachment.objects.create(
            content_type=content_type,
            object_id=amendment.pk,
            file=amendment.signed_amendment,
            file_type=file_type,
            code=file_type.code,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0062_auto_20180209_1512'),
    ]

    operations = [
        migrations.RunPython(
            copy_signed_amendment,
            reverse_code=migrations.RunPython.noop
        )
    ]
