# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0063_auto_20180226_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerorganization',
            name='shared_partner',
        ),
    ]
