# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-09 18:35
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Q


def copy_intervention_attachments(apps, schema_editor):
    # Copy prc review and signed pd field content to attachments model
    FileType = apps.get_model("attachments", "filetype")
    Attachment = apps.get_model("attachments", "attachment")
    Intervention = apps.get_model("partners", "intervention")
    ContentType = apps.get_model("contenttypes", "ContentType")

    prc_file_type, _ = FileType.objects.get_or_create(
        code="partners_intervention_prc_review",
        defaults={
            "label": "Intervention PRC Review",
            "name": "intervention_prc_review",
            "order": 0,
        }
    )
    pd_file_type, _ = FileType.objects.get_or_create(
        code="partners_intervention_signed_pd",
        defaults={
            "label": "Intervention Signed PD",
            "name": "intervention_signed_pd",
            "order": 0,
        }
    )

    content_type = ContentType.objects.get_for_model(Intervention)

    for intervention in Intervention.objects.filter(
            Q(prc_review_document__isnull=False) |
            Q(signed_pd_document__isnull=False)
    ).all():
        if intervention.prc_review_document:
            Attachment.objects.create(
                content_type=content_type,
                object_id=intervention.pk,
                file=intervention.prc_review_document,
                file_type=prc_file_type,
                code=prc_file_type.code,
            )
        if intervention.signed_pd_document:
            Attachment.objects.create(
                content_type=content_type,
                object_id=intervention.pk,
                file=intervention.signed_pd_document,
                file_type=pd_file_type,
                code=pd_file_type.code,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0063_auto_20180209_1622'),
    ]

    operations = [
        migrations.RunPython(
            copy_intervention_attachments,
            reverse_code=migrations.RunPython.noop
        )
    ]
