# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-01 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0065_auto_20180228_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='basis_for_risk_rating',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Base for Risk Rating'),
        ),
    ]
