# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-08 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0066_partnerorganization_basis_for_risk_rating'),
        ('partners', '0063_make_not_nullable'),
    ]

    operations = [
    ]
