# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-09 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0066_partnerorganization_basis_for_risk_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interventionplannedvisits',
            options={'verbose_name_plural': 'Intervention Planned Visits'},
        ),
    ]
