# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-15 11:23
from __future__ import unicode_literals

from django.db import migrations


def copy_intervention_attachment(apps, schema_editor):
    # Copy attachment field content to attachments model
    FileType = apps.get_model("attachments", "filetype")
    Attachment = apps.get_model("attachments", "attachment")
    InterventionAttachment = apps.get_model(
        "partners",
        "interventionattachment"
    )
    ContentType = apps.get_model("contenttypes", "ContentType")

    file_type, _ = FileType.objects.get_or_create(
        code="partners_intervention_attachment",
        defaults={
            "label": "Intervention Attachment",
            "name": "intervention_attachment",
            "order": 0,
        }
    )

    content_type = ContentType.objects.get_for_model(InterventionAttachment)

    for attachment in InterventionAttachment.objects.filter(
            attachment__isnull=False
    ).all():
        if attachment.attachment:
            Attachment.objects.create(
                content_type=content_type,
                object_id=attachment.pk,
                file=attachment.attachment,
                file_type=file_type,
                code=file_type.code,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0072_auto_20180212_1306'),
    ]

    operations = [
        migrations.RunPython(
            copy_intervention_attachment,
            reverse_code=migrations.RunPython.noop
        )
    ]
