# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-09 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0074_auto_20161027_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[(b'draft', b'Draft'), (b'active', b'Active'), (b'ended', b'Ended'), (b'suspended', b'Suspended'), (b'terminated', b'Terminated')], default='active', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_type',
            field=models.CharField(choices=[('PCA', 'Programme Cooperation Agreement'), ('SSFA', 'Small Scale Funding Agreement'), ('MOU', 'Memorandum of Understanding')], max_length=10),
        ),
    ]
