# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-07 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0074_auto_20161107_2214'),
        ('reports', '0027_auto_20161107_2245')
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentintervention',
            name='result_structure',
            field=models.ForeignKey(to='reports.ResponsePlan',
                                    help_text='Which response plan does this partnership report under?',
                                    verbose_name=b'Humanitarian response plan',),
        ),
        migrations.AlterField(
            model_name='pca',
            name='result_structure',
            field=models.ForeignKey(on_delete=models.deletion.DO_NOTHING,
                                    blank=True,
                                    to='reports.ResponsePlan',
                                    help_text='Which response plan does this partnership report under?',
                                    verbose_name=b'Humanitarian response plan',
                                    null=True),
        ),

        migrations.RenameField(
            model_name='governmentintervention',
            old_name='result_structure',
            new_name='hrp',

        ),
        migrations.RenameField(
            model_name='pca',
            old_name='result_structure',
            new_name='hrp',
        ),
    ]
