# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-29 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0052_auto_20170929_1933'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplyItem',
        ),
    ]
