# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-27 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='guid',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
