# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-13 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vendor_number',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
