# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-30 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170123_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vendor_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
