# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-17 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170117_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='section_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
