# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fix_null_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='business_area_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Business Area Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_short_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Short Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='long_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Long Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='org_unit_code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Org Unit Code'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='org_unit_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Org Unit Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='post_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Post Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='post_title',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Post Title'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='section_code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Section Code'),
        ),
    ]
