# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-01 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170123_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='threshold_tae_usd',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='threshold_tre_usd',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=20, null=True),
        ),
    ]
