# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-15 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0005_auto_20170209_2353'),
        ('users', '0005_auto_20170213_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='local_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspaces', to='publics.Currency'),
        ),
    ]
