# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-01 23:37
from __future__ import unicode_literals

from django.db import migrations, models


def reverse(apps, schema_editor):
    pass


def country_short_to_long(apps, schema_editor):
    Country = apps.get_model('users', 'Country')
    for country in Country.objects.all():
        country.long_name = country.name
        country.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_country_local_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='long_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(
            country_short_to_long, reverse_code=reverse
        ),

    ]
