# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-22 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_workspacecounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='installation_id',
        ),
    ]
