# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-08 22:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_workspacecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='formal_names',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
