# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-20 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20171127_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ('name',)},
        ),
    ]
