# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180309_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ('name',)},
        ),
    ]
