# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-22 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180321_1830'),
        ('users', '0012_make_not_nullable'),
    ]

    operations = [
    ]
