# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-28 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180321_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
