# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-19 16:38
from __future__ import unicode_literals

from django.db import migrations

from utils.common.migrating import fix_null_values


def fix_nulls(apps, schema):
    # Change null values in these fields to empty strings
    fix_null_values(
        apps.get_model('users.Country'),
        [
            'business_area_code',
            'country_short_code',
            'long_name',
        ]
    )
    fix_null_values(
        apps.get_model('users.UserProfile'),
        [
            'job_title',
            'org_unit_code',
            'org_unit_name',
            'phone_number',
            'post_number',
            'post_title',
            'section_code',
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180321_1830'),
    ]

    operations = [
        migrations.RunPython(fix_nulls, migrations.RunPython.noop)
    ]
