# Generated by Django 2.1.5 on 2019-02-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0003_make_not_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='funds',
        ),
        migrations.RemoveField(
            model_name='wbs',
            name='business_area',
        ),
        migrations.RemoveField(
            model_name='wbs',
            name='grants',
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
        migrations.DeleteModel(
            name='Grant',
        ),
        migrations.DeleteModel(
            name='WBS',
        ),
    ]
