# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-09 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0003_make_not_nullable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsarateupload',
            old_name='upload_date',
            new_name='upload_datetime',
        ),
    ]
