# Generated by Django 2.1.8 on 2019-04-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0004_auto_20190220_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DSARateUpload',
        ),
    ]
