# Generated by Django 2.2.1 on 2019-06-25 15:47

from django.db import migrations

FROM_CODE = "MRO"
TO_CODE = "MRU"


def update_mauritania_currency(apps, schema_editor):
    Currency = apps.get_model("publics", "currency")
    Currency.admin_objects.filter(code=FROM_CODE).update(code=TO_CODE)


def reverse_currency_update(apps, schema_editor):
    Currency = apps.get_model("publics", "currency")
    Currency.admin_objects.filter(code=TO_CODE).update(code=FROM_CODE)


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0005_delete_dsarateupload'),
    ]

    operations = [
        migrations.RunPython(
            update_mauritania_currency,
            reverse_currency_update,
        ),
    ]
