# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-03 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180424_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='section',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='section_code',
        ),
    ]
