# Generated by Django 1.10.8 on 2018-07-16 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180703_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
