# Generated by Django 1.10.8 on 2018-04-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_make_not_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='org_unit_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Org Unit Code'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='org_unit_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Org Unit Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='post_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Post Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='post_title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Post Title'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='section_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Section Code'),
        ),
    ]
