# Generated by Django 2.0.9 on 2018-10-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_middle_name'),
    ]

    operations = [
    ]
