# Generated by Django 2.1.8 on 2019-04-24 14:48

from django.db import migrations, models
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190423_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
    ]
