# Generated by Django 2.2.4 on 2019-10-10 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190513_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='zonal_chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices_old', to=settings.AUTH_USER_MODEL, verbose_name='Chief'),
        ),
    ]
