# Generated by Django 2.2.8 on 2019-12-05 20:06

from django.db import migrations
import etools.libraries.djangolib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191010_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=etools.libraries.djangolib.fields.LowerCaseEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=etools.libraries.djangolib.fields.LowerCaseField(max_length=256, unique=True, verbose_name='username'),
        ),
    ]
