# Generated by Django 2.2.7 on 2020-06-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191010_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso3_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ISO3 Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_short_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='UNICEF Country Reference Code'),
        ),
    ]
