# Generated by Django 2.2.7 on 2020-09-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200611_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='partner_staff_member',
            new_name='_partner_staff_member',
        ),
    ]
