# Generated by Django 2.2.24 on 2021-07-14 21:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import etools.applications.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200924_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='custom_dashboards',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=etools.applications.users.models.custom_dashboards_default, verbose_name='Custom Dashboards'),
        ),
    ]
