# Generated by Django 2.2.11 on 2021-02-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200924_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='business_area_code',
            field=models.CharField(blank=True, default='', max_length=10, unique=True, verbose_name='Business Area Code'),
        ),
    ]
