# Generated by Django 3.2.6 on 2022-01-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_country_custom_dashboards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='_partner_staff_member',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='oic',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='vendor_number',
        ),
    ]
