# Generated by Django 3.2.6 on 2021-08-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210519_1038'),
        ('users', '0016_country_custom_dashboards'),
    ]

    operations = [
    ]
