# Generated by Django 3.2.13 on 2022-05-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20220408_1558'),
        ('users', '0017_merge_20210805_1609'),
    ]

    operations = [
    ]
