# Generated by Django 3.2.6 on 2022-08-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20220511_1411'),
        ('users', '0018_user_preferences'),
    ]

    operations = [
    ]
