# Generated by Django 3.2.6 on 2022-11-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_migrate_to_realms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realm',
            name='is_active',
        ),
    ]
