# Generated by Django 3.2.6 on 2022-12-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_migrate_to_realms'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receive_tpm_notifications',
            field=models.BooleanField(default=False, verbose_name='Receive Notifications on TPM Tasks'),
        ),
    ]
