# Generated by Django 3.2.6 on 2023-05-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_userprofile_receive_tpm_notifications'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop)
    ]
