# Generated by Django 3.2.6 on 2023-01-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='cso_type',
            field=models.CharField(blank=True, choices=[('International', 'International'), ('National', 'National'), ('Community Based Organization', 'Community Based Organization'), ('Academic Institution', 'Academic Institution'), ('Red Cross/Red Crescent National Societies', 'Red Cross/Red Crescent National Societies')], max_length=50, null=True, verbose_name='CSO Type'),
        ),
    ]
