# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-27 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_auto_20161227_1953'),
        ('reports', '0002_auto_20161209_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowerresult',
            name='result_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ll_results', to='partners.InterventionResultLink'),
        ),
        # manually moving contraints update here otherwise intervention field will not exist thanks @nik
        migrations.AlterUniqueTogether(
            name='lowerresult',
            unique_together=set([('result_link', 'code')]),
        ),
        migrations.RemoveField(
            model_name='lowerresult',
            name='cp_result',
        ),
        migrations.RemoveField(
            model_name='lowerresult',
            name='intervention',
        ),

    ]
