# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-21 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20161209_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='activity_info_indicators',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='in_activity_info',
        ),
    ]
