# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-12 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20161227_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='activity_info_indicators',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='in_activity_info',
        ),
    ]
