# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-23 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20170330_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttype',
            name='name',
            field=models.CharField(choices=[('Outcome', 'Outcome'), ('Output', 'Output'), ('Activity', 'Activity')], max_length=150, unique=True),
        ),
    ]
