# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-31 21:08
from __future__ import unicode_literals

from django.db import migrations, models

def reverse(apps, schema_editor):
    pass

def migrate_CPs(apps, schema_editor):
    CountryProgramme = apps.get_model('reports', 'CountryProgramme')
    # use the save method to mark invalid fields
    for cp in CountryProgramme.objects.all():
        cp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20170623_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryprogramme',
            name='invalid',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            migrate_CPs, reverse_code=reverse),
    ]
