# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20160207_2248'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='result',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
