# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-29 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_indicator_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['-active', 'name']},
        ),
    ]
