# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-08 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def reverse(apps, schema_editor):
    return

def remove_llresults_without_resultlink(apps, schema_editor):
    LowerResult = apps.get_model('reports', 'LowerResult')
    # use the save method to mark invalid fields
    deleted = LowerResult.objects.filter(result_link__isnull=True).delete()
    if deleted[0]:
        print("Deleted lower results: {}".format(deleted[0]))

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20170829_1727'),
    ]

    operations = [
        migrations.RunPython(remove_llresults_without_resultlink, reverse_code=reverse),

        migrations.AlterField(
            model_name='lowerresult',
            name='result_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ll_results', to='partners.InterventionResultLink'),
        ),
    ]
