# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-19 18:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20170829_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedindicator',
            name='assumptions',
            field=models.TextField(blank=True, null=True, verbose_name='Assumptions'),
        ),
        migrations.AlterField(
            model_name='appliedindicator',
            name='baseline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Baseline'),
        ),
        migrations.AlterField(
            model_name='appliedindicator',
            name='lower_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_indicators', to='reports.LowerResult', verbose_name='Lower Level Result'),
        ),
        migrations.AlterField(
            model_name='appliedindicator',
            name='means_of_verification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Means of Verification'),
        ),
        migrations.AlterField(
            model_name='appliedindicator',
            name='target',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Target'),
        ),
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='description',
            field=models.CharField(blank=True, max_length=3072, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='disaggregatable',
            field=models.BooleanField(default=False, verbose_name='Disaggregatable'),
        ),
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='subdomain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subdomain'),
        ),
        migrations.AlterField(
            model_name='indicatorblueprint',
            name='unit',
            field=models.CharField(choices=[('number', 'number'), ('percentage', 'percentage'), ('yesno', 'yesno')], default='number', max_length=10, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='lowerresult',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='lowerresult',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='lowerresult',
            name='result_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ll_results', to='partners.InterventionResultLink', verbose_name='Reference Number'),
        ),
    ]
