# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-20 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20170829_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['-active', 'name']},
        ),
    ]
