# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-12 21:13
from __future__ import unicode_literals

from django.db import migrations

def reverse(apps, schema_editor):
   return

def remove_all_indicators(apps, schema_editor):
   IndicatorBlueprint = apps.get_model('reports', 'IndicatorBlueprint')
   # use the save method to mark invalid fields
   deleted = IndicatorBlueprint.objects.all().delete()
   if deleted[0]:
       print "Deleted Indicators: {}".format(deleted[0])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_workspacecounter'),
        ('locations', '0004_auto_20170112_2051'),
        ('reports', '0014_auto_20170908_1307'),
    ]

    operations = [
        migrations.RunPython(remove_all_indicators, reverse_code=reverse),
    ]
