# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-25 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20171013_2147'),
        ('reports', '0015_auto_20171020_0958'),
    ]

    operations = [
    ]
