# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-20 14:53
from __future__ import unicode_literals

from django.db import migrations

# Our goal is to make these 2 fields not-null, so we need to fill existing null or blank values with
# something.


def fill_in_empty_values(apps, schema_editor):
    Disaggregation = apps.get_model('reports', 'Disaggregation')
    DisaggregationValue = apps.get_model('reports', 'DisaggregationValue')

    for d in Disaggregation.objects.all():
        if not d.name:
            d.name = 'Disaggregation {}'.format(d.id)
            d.save()

    for dv in DisaggregationValue.objects.all():
        if not dv.value:
            dv.value = 'Value {}'.format(dv.id)
            dv.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20170912_2113'),
    ]

    operations = [
        migrations.RunPython(fill_in_empty_values, migrations.RunPython.noop)
    ]
