# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-26 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_auto_20170920_1504'),
        ('reports', '0014_auto_20171024_1011'),
    ]

    operations = [
    ]
