# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-27 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_auto_20170920_1504'),
        ('reports', '0017_auto_20171026_1046'),
    ]

    operations = [
    ]
