# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-07 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_auto_20161013_2034'),
        ('partners', '0074_auto_20161107_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='result_structure',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='result_structure',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_structure',
            field=models.IntegerField(null=True, blank=True),
        ),

        migrations.RenameModel('ResultStructure', 'ResponsePlan'),

        migrations.AlterField(
            model_name='goal',
            name='result_structure',
            field=models.ForeignKey(on_delete=models.deletion.DO_NOTHING,
                                    blank=True,
                                    to='reports.ResponsePlan',
                                    null=True,
                                    verbose_name=b'Humanitarian response plan',),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='result_structure',
            field=models.ForeignKey(on_delete=models.deletion.DO_NOTHING,
                                    blank=True,
                                    to='reports.ResponsePlan',
                                    null=True,
                                    verbose_name=b'Humanitarian response plan',),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_structure',
            field=models.ForeignKey(on_delete=models.deletion.DO_NOTHING,
                                    blank=True,
                                    to='reports.ResponsePlan',
                                    null=True,
                                    verbose_name=b'Humanitarian response plan',),
        ),

        migrations.RenameField(
            model_name='goal',
            old_name='result_structure',
            new_name='hrp',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='result_structure',
            new_name='hrp',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='result_structure',
            new_name='hrp',
        ),
    ]
