# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-26 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [(b'publics', '0001_initial'), (b'publics', '0002_auto_20170118_0850'),
                (b'publics', '0003_auto_20170118_0926'), (b'publics', '0004_auto_20170118_0938'),
                (b'publics', '0005_auto_20170118_1024'), (b'publics', '0006_auto_20170118_1213'),
                (b'publics', '0007_wbs_business_area')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.IntegerField()),
                ('iata', models.CharField(max_length=3)),
                ('icao', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('long_name', models.CharField(max_length=128)),
                ('vision_code', models.CharField(max_length=3, null=True)),
                ('iso_2', models.CharField(max_length=2)),
                ('iso_3', models.CharField(max_length=3)),
                ('valid_from', models.DateField(null=True)),
                ('valid_to', models.DateField(null=True)),
                ('business_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='publics.BusinessArea')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('iso_4217', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DSARegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=32)),
                ('area_code', models.CharField(max_length=3)),
                ('dsa_amount_usd', models.DecimalField(decimal_places=4, max_digits=20)),
                ('dsa_amount_60plus_usd', models.DecimalField(decimal_places=4, max_digits=20)),
                ('dsa_amount_local', models.DecimalField(decimal_places=4, max_digits=20)),
                ('dsa_amount_60plus_local', models.DecimalField(decimal_places=4, max_digits=20)),
                ('room_rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('finalization_date', models.DateField()),
                ('eff_date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsa_regions', to='publics.Country')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=16)),
                ('vendor_number', models.CharField(max_length=32)),
                ('unique', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='WBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('business_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publics.BusinessArea')),
            ],
        ),
        migrations.AddField(
            model_name='grant',
            name='wbs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='publics.WBS'),
        ),
        migrations.AddField(
            model_name='fund',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='publics.Grant'),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publics.Currency'),
        ),
        migrations.AddField(
            model_name='businessarea',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_areas', to='publics.BusinessRegion'),
        ),
    ]
