# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-26 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0001_squashed_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensetype',
            old_name='unique',
            new_name='is_travel_agent',
        ),
        migrations.RemoveField(
            model_name='expensetype',
            name='code',
        ),
    ]
