# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-18 07:26
from __future__ import unicode_literals

from datetime import date

from django.db import migrations


def move_countries(apps, schema_editor):
    Country = apps.get_model('publics', 'Country')
    Currency = apps.get_model('publics', 'Currency')
    DSARegion = apps.get_model('publics', 'DSARegion')

    euro, _ = Currency.objects.get_or_create(iso_4217='EUR', defaults={'name': 'Euro'})

    germany = Country.objects.create(name='Germany',
                                     long_name='THE FEDERAL REPUBLIC OF GERMANY',
                                     vision_code='525',
                                     iso_2='DE',
                                     iso_3='DEU',
                                     currency=euro,
                                     valid_from=date(1990, 10, 3),
                                     valid_to=date(9999, 12, 31))

    hungary = Country.objects.create(name='Hungary',
                                     long_name='HUNGARY',
                                     vision_code='195',
                                     iso_2='HU',
                                     iso_3='HUN',
                                     currency=euro,
                                     valid_from=date(1955, 12, 14),
                                     valid_to=date(9999, 12, 31))

    for dsa_region in DSARegion.objects.all():
        if dsa_region.country.lower() == 'hungary':
            dsa_region.new_country = hungary
        elif dsa_region.country.lower() == 'germany':
            dsa_region.new_country = germany
        else:
            raise ValueError('Unknown dsa region country: {}'.format(dsa_region.country))
        dsa_region.area_name = dsa_region.region
        dsa_region.save()


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0002_auto_20170118_0850'),
    ]

    operations = [
        migrations.RunPython(move_countries),
    ]
