# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-26 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0002_auto_20170126_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseType',
            new_name='TravelExpenseType',
        ),
    ]
