# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-18 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0003_auto_20170118_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsaregion',
            name='business_area_code',
        ),
        migrations.RemoveField(
            model_name='dsaregion',
            name='country',
        ),
        migrations.RemoveField(
            model_name='dsaregion',
            name='region',
        ),
        migrations.RenameField(
            model_name='dsaregion',
            old_name='new_country',
            new_name='country',
        ),
    ]
