# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-27 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0003_auto_20170126_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('x_rate', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TravelAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=128)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publics.Country')),
            ],
        ),
        migrations.AlterModelOptions(
            name='travelexpensetype',
            options={'ordering': ('rank', 'title')},
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='iso_4217',
            new_name='code',
        ),
        migrations.AddField(
            model_name='currency',
            name='decimal_places',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='travelexpensetype',
            name='rank',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publics.Currency'),
        ),
    ]
