# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-18 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0004_auto_20170118_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsaregion',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsa_regions', to='publics.Country'),
        ),
    ]
