# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-09 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0004_auto_20170207_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ('valid_from',)},
        ),
    ]
