# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-18 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0005_auto_20170118_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='valid_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='valid_to',
            field=models.DateField(null=True),
        ),
    ]
