# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-22 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0005_auto_20170209_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelagent',
            name='code',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='travelexpensetype',
            name='vendor_number',
            field=models.CharField(max_length=128),
        ),
    ]
