# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-28 00:05
from __future__ import unicode_literals

from django.db import migrations


def delete_wbs_grant_fund(apps, schema_editor):
    WBS = apps.get_model('publics', 'WBS')
    Grant = apps.get_model('publics', 'Grant')
    Fund = apps.get_model('publics', 'Fund')

    Fund.objects.all().delete()
    Grant.objects.all().delete()
    WBS.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0006_auto_20170222_0226'),
        ('t2f', '0004_auto_20170228_0205'),
    ]

    operations = [
        migrations.RunPython(delete_wbs_grant_fund),
    ]
