# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-31 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0006_auto_20170130_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_2',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_3',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='vision_code',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='dsaregion',
            name='area_name',
            field=models.CharField(max_length=120),
        ),
    ]
