# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-23 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0006_auto_20170118_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbs',
            name='business_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publics.BusinessArea'),
        ),
    ]
