# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-28 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0008_auto_20170228_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagent',
            name='expense_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_agent', to='publics.TravelExpenseType'),
        ),
    ]
