# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-28 12:34
from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


def populate_travel_agent_expense_type(apps, schema_editor):
    TravelAgent = apps.get_model('publics', 'TravelAgent')
    TravelExpenseType = apps.get_model('publics', 'TravelExpenseType')

    for travel_agent in TravelAgent.objects.all():
        try:
            expense_type = TravelExpenseType.objects.get(vendor_number=travel_agent.code)
        except ObjectDoesNotExist:
            expense_type = TravelExpenseType.objects.create(title=travel_agent.name, vendor_number=travel_agent.code)

        travel_agent.expense_type = expense_type
        travel_agent.save()


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0009_travelagent_expense_type'),
    ]

    operations = [
        migrations.RunPython(populate_travel_agent_expense_type),
    ]
