# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-04 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    This migration is special. An explicit through table was added to WBS <-> Grant and Grant <-> Fund relations to
    speed up vision syncer. Since just the interface for the middle table was required, the through tables are built on
    the top of the autogenerated django tables which means no db action should happen (just the model states should be
    updated). To achieve this all the actions will be wrapped into a SeparateDatabaseAndState migration (all actions
    will be marked as state change only). By doing this the db is untouched but still give access to the intermediate
    tables.
    """

    dependencies = [
        ('publics', '0011_auto_20170228_1446'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=(
                migrations.CreateModel(
                    name='GrantFundThrough',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publics.Fund')),
                    ],
                    options={
                        'db_table': 'publics_grant_funds',
                    },
                ),
                migrations.CreateModel(
                    name='WBSGrantThrough',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ],
                    options={
                        'db_table': 'publics_wbs_grants',
                    },
                ),
                migrations.AlterField(
                    model_name='grant',
                    name='funds',
                    field=models.ManyToManyField(related_name='grants', through='publics.GrantFundThrough', to='publics.Fund'),
                ),
                migrations.AlterField(
                    model_name='wbs',
                    name='grants',
                    field=models.ManyToManyField(related_name='wbs', through='publics.WBSGrantThrough', to='publics.Grant'),
                ),
                migrations.AddField(
                    model_name='wbsgrantthrough',
                    name='grant',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publics.Grant'),
                ),
                migrations.AddField(
                    model_name='wbsgrantthrough',
                    name='wbs',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publics.WBS'),
                ),
                migrations.AddField(
                    model_name='grantfundthrough',
                    name='grant',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publics.Grant'),
                ),
            )
        )
    ]
