# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-12 08:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0011_auto_20170228_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlinecompany',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='businessarea',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='businessregion',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='country',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='currency',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='dsaregion',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='fund',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='grant',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='travelagent',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='travelexpensetype',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='wbs',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
