# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-19 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0012_auto_20170419_0825'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dsarate',
            unique_together=set([('region', 'valid_to')]),
        ),
    ]
