# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-24 12:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0012_auto_20170421_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSARate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59, tzinfo=utc))),
                ('dsa_amount_usd', models.DecimalField(decimal_places=4, max_digits=20)),
                ('dsa_amount_60plus_usd', models.DecimalField(decimal_places=4, max_digits=20)),
                ('dsa_amount_local', models.DecimalField(decimal_places=4, max_digits=20)),
                ('dsa_amount_60plus_local', models.DecimalField(decimal_places=4, max_digits=20)),
                ('room_rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('finalization_date', models.DateField()),
                ('eff_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='dsaregion',
            name='user_defined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dsarate',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='publics.DSARegion'),
        ),
        migrations.AlterUniqueTogether(
            name='dsarate',
            unique_together=set([('region', 'valid_to')]),
        ),
    ]
