# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-20 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0013_auto_20170419_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsaregion',
            name='used_defined',
            field=models.BooleanField(default=False),
        ),
    ]
