# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-24 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0014_auto_20170424_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsaregion',
            name='dsa_amount_60plus_local',
        ),
        migrations.RemoveField(
            model_name='dsaregion',
            name='dsa_amount_60plus_usd',
        ),
        migrations.RemoveField(
            model_name='dsaregion',
            name='dsa_amount_local',
        ),
        migrations.RemoveField(
            model_name='dsaregion',
            name='dsa_amount_usd',
        ),
        migrations.RemoveField(
            model_name='dsaregion',
            name='eff_date',
        ),
        migrations.RemoveField(
            model_name='dsaregion',
            name='finalization_date',
        ),
        migrations.RemoveField(
            model_name='dsaregion',
            name='room_rate',
        ),
    ]
