# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-26 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0015_auto_20170424_1207'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dsaregion',
            managers=[
            ],
        ),
    ]
