# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-26 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0017_auto_20170426_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsarate',
            old_name='valid_to',
            new_name='effective_till_date',
        ),
        migrations.AlterUniqueTogether(
            name='dsarate',
            unique_together=set([('region', 'effective_till_date')]),
        ),
        migrations.AlterField(
            model_name='dsarate',
            name='effective_till_date',
            field=models.DateField(default=datetime.date(2999, 12, 31)),
        ),
        migrations.AlterField(
            model_name='dsarate',
            name='effective_from_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='dsarate',
            name='valid_from',
        ),
    ]
