# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-27 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0018_auto_20170426_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsarate',
            name='effective_from_date',
            field=models.DateField(),
        ),
    ]
