# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-27 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0019_auto_20170427_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsarate',
            old_name='effective_till_date',
            new_name='effective_to_date',
        ),
        migrations.AlterUniqueTogether(
            name='dsarate',
            unique_together=set([('region', 'effective_to_date')]),
        ),
    ]
