# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-11 12:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0020_auto_20170427_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSARateUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='publics/dsa_rate/')),
                ('status', models.CharField(blank=True, choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('failed', 'Failed'), ('done', 'Done')], max_length=64, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
