# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-26 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0023_auto_20170525_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsarateupload',
            old_name='csv',
            new_name='dsa_file',
        ),
    ]
