# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-09 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0024_auto_20170526_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airlinecompany',
            options={'verbose_name_plural': 'Airline Companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='wbs',
            options={'verbose_name_plural': 'WBSes'},
        ),
    ]
