# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-02 17:19
from __future__ import unicode_literals

import EquiTrack.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacthistory',
            name='year',
            field=models.IntegerField(default=EquiTrack.utils.get_current_year),
        ),
    ]
