# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-24 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0002_auto_20181024_0822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='LocationSite',
        ),
    ]
