# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-26 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('partners', '0027_auto_20180914_1238'),
        ('field_monitoring_shared', '0001_initial'),
        ('field_monitoring_settings', '0004_auto_20181025_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('question_text', models.CharField(max_length=255, verbose_name='Question Text')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='question_text', verbose_name='Slug')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('issue', models.TextField(verbose_name='Issue For Attention/Probing')),
                ('status', models.CharField(choices=[('new', 'New'), ('past', 'Past')], default='new', max_length=10)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_issues', to='contenttypes.ContentType', verbose_name='Content Type')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedCheckListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_settings.CheckListItem', verbose_name='Checklist Item')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlannedCheckListItemPartnerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_details', models.TextField(blank=True, verbose_name='Specific Details To Probe')),
                ('standard_url', models.CharField(blank=True, max_length=1000, verbose_name='URL To Standard')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization', verbose_name='Partner')),
                ('planned_checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_settings.PlannedCheckListItem', verbose_name='Planned Checklist Item')),
            ],
        ),
        migrations.AddField(
            model_name='cpoutputconfig',
            name='recommended_method_types',
            field=models.ManyToManyField(blank=True, to='field_monitoring_settings.MethodType', verbose_name='Method(s)'),
        ),
        migrations.AddField(
            model_name='plannedchecklistitem',
            name='cp_output_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_settings.CPOutputConfig', verbose_name='CP Output Config'),
        ),
        migrations.AddField(
            model_name='plannedchecklistitem',
            name='methods',
            field=models.ManyToManyField(blank=True, to='field_monitoring_shared.Method', verbose_name='Method(s)'),
        ),
    ]
