# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-26 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0005_auto_20181026_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodtype',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='field_monitoring_shared.Method', verbose_name='Method'),
        ),
    ]
