# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-14 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0009_auto_20181102_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedchecklistitem',
            name='cp_output_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_checklist_items', to='field_monitoring_settings.CPOutputConfig', verbose_name='CP Output Config'),
        ),
    ]
