# Generated by Django 2.2.1 on 2019-07-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_monitoring_activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringactivity',
            name='location_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_activities', to='field_monitoring_planning.LocationSite', verbose_name='Site'),
        ),
    ]
