# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-26 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hact', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacthistory',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='related_partner', to='partners.PartnerOrganization', verbose_name='Partner'),
        ),
        migrations.AlterUniqueTogether(
            name='hacthistory',
            unique_together=set([('partner', 'year')]),
        ),
    ]
