# Generated by Django 3.2.19 on 2024-07-19 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('hact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacthistory',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_partner', to='partners.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AlterUniqueTogether(
            name='hacthistory',
            unique_together={('partner', 'year')},
        ),
    ]
