# Generated by Django 2.0.9 on 2019-01-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hact', '0002_auto_20180326_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregatehact',
            options={'verbose_name_plural': 'Aggregate hact'},
        ),
    ]
