# Generated by Django 3.2.6 on 2021-11-05 17:38
import json

from django.db import migrations


def string2json(apps, schema_editor):
    AggregateHact = apps.get_model('hact', 'AggregateHact')
    for ah in AggregateHact.objects.all():
        if isinstance(ah.partner_values, str):
            ah.partner_values = json.loads(ah.partner_values)
        if 'min_required' in ah.partner_values['assurance_activities']['spot_checks']:
            ah.partner_values['assurance_activities']['spot_checks']['required'] = ah.partner_values['assurance_activities']['spot_checks']['min_required']
            ah.partner_values['assurance_activities']['spot_checks'].pop('min_required', None)
        ah.save()

    HactHistory = apps.get_model('hact', 'HactHistory')
    for ah in HactHistory.objects.all():
        if isinstance(ah.partner_values, str):
            ah.partner_values = json.loads(ah.partner_values)
            ah.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hact', '0003_auto_20190122_1412'),
    ]

    operations = [
        migrations.RunPython(string2json, migrations.RunPython.noop),
    ]
