# Generated by Django 2.1.7 on 2019-03-12 14:37

from django.db import connection, migrations


def rename_table(apps, schema_editor):

    if 'EquiTrack_domain' in connection.introspection.table_names():
        print('Rename')
        with connection.cursor() as cursor:
            cursor.execute('ALTER TABLE "EquiTrack_domain" RENAME TO "core_domain";')


def undo_rename_table(apps, schema_editor):
    if 'core_domain' in connection.introspection.table_names():
        print('Undo Rename')
        with connection.cursor() as cursor:
            cursor.execute('ALTER TABLE "core_domain" RENAME TO "EquiTrack_domain";')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rename_table, undo_rename_table),
    ]
