# Generated by Django 4.2.23 on 2025-08-18 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_domain_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDeactivationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_count', models.IntegerField(help_text='Number of records deactivated')),
                ('model_name', models.CharField(help_text='Name of the model that was bulk deactivated', max_length=100)),
                ('app_label', models.CharField(help_text='App label of the model that was bulk deactivated', max_length=100)),
                ('affected_ids', models.JSONField(default=list, help_text='List of IDs of the records that were deactivated')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the bulk deactivation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Deactivation Log',
                'verbose_name_plural': 'Bulk Deactivation Logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
