# Generated by Django 1.10.8 on 2018-03-26 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FundsCommitmentHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('vendor_code', models.CharField(max_length=20, verbose_name='Vendor Code')),
                ('fc_number', models.CharField(max_length=20, unique=True, verbose_name='Number')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Document Date')),
                ('fc_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type')),
                ('currency', models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency')),
                ('document_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document')),
                ('exchange_rate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Exchange Rate')),
                ('responsible_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsible')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundsCommitmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fc_ref_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Number')),
                ('line_item', models.CharField(max_length=5, verbose_name='Line Item')),
                ('wbs', models.CharField(blank=True, max_length=30, null=True, verbose_name='WBS')),
                ('grant_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Grant Number')),
                ('fund', models.CharField(blank=True, max_length=10, null=True, verbose_name='Fund')),
                ('gl_account', models.CharField(blank=True, max_length=15, null=True, verbose_name='GL Account')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('fr_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='FR Number')),
                ('commitment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount')),
                ('commitment_amount_dc', models.DecimalField(decimal_places=2,
                                                             default=0, max_digits=12, verbose_name='Amount DC')),
                ('amount_changed', models.DecimalField(decimal_places=2,
                                                       default=0, max_digits=12, verbose_name='Amount Changed')),
                ('line_item_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='FundsReservationHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('vendor_code', models.CharField(max_length=20, verbose_name='Vendor Code')),
                ('fr_number', models.CharField(max_length=20, unique=True, verbose_name='FR Number')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Document Date')),
                ('fr_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type')),
                ('currency', models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency')),
                ('document_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document Text')),
                ('intervention_amt', models.DecimalField(decimal_places=2,
                                                         default=0, max_digits=12, verbose_name='Current FR Amount')),
                ('total_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='FR Overall Amount')),
                ('total_amt_local', models.DecimalField(decimal_places=2,
                                                        default=0, max_digits=12, verbose_name='FR Overall Amount DC')),
                ('actual_amt', models.DecimalField(decimal_places=2, default=0,
                                                   max_digits=12, verbose_name='Actual Cash Transfer')),
                ('actual_amt_local', models.DecimalField(decimal_places=2, default=0,
                                                         max_digits=12, verbose_name='Actual Cash Transfer Local')),
                ('outstanding_amt', models.DecimalField(decimal_places=2,
                                                        default=0, max_digits=12, verbose_name='Outstanding DCT')),
                ('outstanding_amt_local', models.DecimalField(decimal_places=2,
                                                              default=0, max_digits=12, verbose_name='Outstanding DCT Local')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
            ],
            options={
                'ordering': ['fr_number'],
            },
        ),
        migrations.CreateModel(
            name='FundsReservationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fr_ref_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Item Number')),
                ('line_item', models.CharField(max_length=5, verbose_name='Line Item')),
                ('wbs', models.CharField(blank=True, max_length=30, null=True, verbose_name='WBS')),
                ('grant_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Grant Number')),
                ('fund', models.CharField(blank=True, max_length=10, null=True, verbose_name='Fund')),
                ('overall_amount', models.DecimalField(decimal_places=2,
                                                       default=0, max_digits=12, verbose_name='Overall Amount')),
                ('overall_amount_dc', models.DecimalField(decimal_places=2,
                                                          default=0, max_digits=12, verbose_name='Overall Amount DC')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('line_item_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('fund_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                       related_name='fr_items', to='funds.FundsReservationHeader', verbose_name='FR Number')),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('expiry', models.DateField(blank=True, null=True, verbose_name='Expiry')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.Donor', verbose_name='Donor')),
            ],
            options={
                'ordering': ['donor'],
            },
        ),
    ]
