# Generated by Django 3.2.19 on 2023-10-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundsreservationheader',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frs', to='partners.intervention', verbose_name='Reference Number'),
        ),
        migrations.AddField(
            model_name='fundscommitmentitem',
            name='fund_commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fc_items', to='funds.fundscommitmentheader', verbose_name='Fund Commitment'),
        ),
        migrations.AlterUniqueTogether(
            name='fundsreservationitem',
            unique_together={('fund_reservation', 'line_item')},
        ),
        migrations.AlterUniqueTogether(
            name='fundsreservationheader',
            unique_together={('vendor_code', 'fr_number')},
        ),
        migrations.AlterUniqueTogether(
            name='fundscommitmentitem',
            unique_together={('fund_commitment', 'line_item')},
        ),
    ]
