# Generated by Django 3.2 on 2021-08-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0011_fundsreservationheader_delegated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundsreservationitem',
            name='line_item_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
