# Generated by Django 1.10.8 on 2018-03-30 10:01

import os
from urllib.parse import urlsplit

from django.db import migrations, models


def update_attachments_flat_filename(apps, schema_editor):
    AttachmentFlat = apps.get_model("attachments", "attachmentflat")
    for flat in AttachmentFlat.objects.all():
        flat.filename = os.path.basename(
            flat.attachment.file.name
            if flat.attachment.file
            else urlsplit(flat.attachment.hyperlink).path
        )
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentflat',
            name='filename',
            field=models.CharField(blank=True, max_length=1024, verbose_name='File Name'),
        ),
        migrations.RunPython(
            update_attachments_flat_filename,
            reverse_code=migrations.RunPython.noop,
        )
    ]
