# Generated by Django 1.10.8 on 2018-03-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_attachmentflat_agreement_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attachments.FileType', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='object_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Object ID'),
        ),
    ]
