# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-20 17:23
from __future__ import unicode_literals

from django.urls import reverse
from django.db import migrations, models


def update_agreement_link(apps, schema_editor):
    AttachmentFlat = apps.get_model("attachments", "attachmentflat")
    flat_qs = AttachmentFlat.objects.filter(
        agreement_reference_number__isnull=False
    ).exclude(agreement_reference_number="")
    for flat in flat_qs:
        __, agreement_type_year_pk = flat.agreement_reference_number.split("/")
        if agreement_type_year_pk.startswith(Agreement.PCA):
            pk = agreement_type_year_pk[7:]
        else:
            pk = agreement_type_year_pk[8:]
        flat.agreement_link = reverse(
            "partners_api:agreement-detail",
            args=[pk]
        )
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0008_auto_20180717_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentflat',
            name='agreement_link',
            field=models.URLField(blank=True, verbose_name='Agreement Link'),
        ),
        migrations.RunPython(
            update_agreement_link,
            reverse_code=migrations.RunPython.noop,
        )
    ]
