# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-02 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0009_attachmentflat_agreement_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments_old', to='contenttypes.ContentType', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments_old', to='attachments.FileType', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments_old', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        # TODO add in data migrations here
        migrations.AlterField(
            model_name='attachmentflat',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denormalized', to='unicef_attachments.Attachment'),
        ),
    ]
