# Generated by Django 1.10.8 on 2018-08-20 12:09
from __future__ import unicode_literals

from django.db import connection, migrations
from django.db.models import Max


def reset_attachment_seq(apps, schema_editor):
    Attachment = apps.get_model("unicef_attachments", "attachment")
    qs = Attachment.objects.all().aggregate(max_id=Max("id"))
    with connection.cursor() as cursor:
        cursor.execute(
            "select setval('unicef_attachments_attachment_id_seq', %s, true)",
            [qs["max_id"]]
        )


def reset_filetype_seq(apps, schema_editor):
    FileType = apps.get_model("unicef_attachments", "filetype")
    qs = FileType.objects.all().aggregate(max_id=Max("id"))
    with connection.cursor() as cursor:
        cursor.execute(
            "select setval('unicef_attachments_filetype_id_seq', %s, true)",
            [qs["max_id"]]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0010_auto_20180802_1245'),
    ]

    operations = [
        migrations.RunPython(
            reset_attachment_seq,
            migrations.RunPython.noop
        ),
        migrations.RunPython(
            reset_filetype_seq,
            migrations.RunPython.noop
        ),
    ]
