# Generated by Django 1.10.8 on 2018-08-23 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0011_auto_20180820_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentflat',
            name='source',
            field=models.CharField(blank=True, max_length=150, verbose_name='Source'),
        ),
    ]
