# Generated by Django 2.2.7 on 2019-12-13 17:25

import datetime

from django.db import migrations, models


def set_created_timestamp(apps, schema_view):
    AttachmentFlat = apps.get_model("attachments", "attachmentflat")
    for attachment in AttachmentFlat.objects.all():
        attachment.created_timestamp = datetime.datetime.strptime(
            attachment.created,
            "%d %b %Y",
        )
        attachment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0016_auto_20190708_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentflat',
            name='created_timestamp',
            field=models.DateTimeField(null=True, verbose_name='Created'),
        ),
        migrations.RunPython(
            set_created_timestamp,
            reverse_code=migrations.RunPython.noop,
        )
    ]
