# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-14 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(blank=True, null=True, upload_to=b'files')),
                ('hyperlink', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.IntegerField()),
                ('code', models.CharField(blank=True, max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(default=b'', max_length=64)),
            ],
            options={
                'ordering': ('code', 'order'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='filetype',
            unique_together=set([('name', 'code')]),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attachments.FileType'),
        ),
    ]
