# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-30 11:51
from __future__ import unicode_literals

from django.db import migrations, models


def set_labels(apps, schema_editor):
    FileType = apps.get_model('attachments', 'FileType')

    FileType.objects.update(label=models.F('name'),
                            name=models.Func(models.Func(models.Func(models.F('name'), function='LOWER'),
                                                         models.Value(' '),
                                                         models.Value('_'),
                                                         function='REPLACE'),
                                             models.Value('/'),
                                             models.Value('_'),
                                             function='REPLACE'))


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_auto_20170824_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetype',
            name='label',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.RunPython(
            set_labels,
            migrations.RunPython.noop,
        ),
    ]
