# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-22 15:33
from __future__ import unicode_literals

import attachments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_filetype_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=attachments.models.generate_file_path, verbose_name='File Attachment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attachments.FileType', verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='hyperlink',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hyperlink'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='code',
            field=models.CharField(default='', max_length=64, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='label',
            field=models.CharField(max_length=64, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
    ]
