# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-06 17:00
from __future__ import unicode_literals

import attachments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_auto_20171122_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=attachments.models.generate_file_path, verbose_name='File Attachment'),
        ),
    ]
