# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-06 17:00
from __future__ import unicode_literals

import attachments.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attachments', '0004_auto_20171122_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=attachments.models.generate_file_path, verbose_name='File Attachment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
    ]
