# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-22 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_auto_20180206_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentFlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(blank=True, max_length=150)),
                ('partner_type', models.CharField(blank=True, max_length=150)),
                ('vendor_number', models.CharField(blank=True, max_length=50)),
                ('pd_ssfa_number', models.CharField(blank=True, max_length=50)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('file_link', models.CharField(blank=True, max_length=1024)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
                ('created', models.CharField(max_length=50)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attachments.Attachment')),
            ],
        ),
    ]
