# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 11:27

from django.db import migrations, models


def migrate_countries(apps, schema_editor):
    TPMPartner = apps.get_model('tpmpartners', 'TPMPartner')
    Country = apps.get_model('users', 'Country')

    all_countries = Country.objects.all()
    for partner in TPMPartner.objects.all():
        partner.countries.add(*all_countries)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180419_2113'),
        ('tpmpartners', '0002_auto_20180308_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmpartner',
            name='countries',
            field=models.ManyToManyField(blank=True, to='users.Country'),
        ),
        migrations.RunPython(migrate_countries, migrations.RunPython.noop)
    ]
