# Generated by Django 2.2.20 on 2021-04-15 15:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tpmpartners', '0005_auto_20190625_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmpartnerstaffmember',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='tpmpartnerstaffmember',
            name='history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='History'), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='tpmpartnerstaffmember',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
