# Generated by Django 2.2.20 on 2021-04-21 17:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpmpartners', '0006_auto_20210415_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmpartnerstaffmember',
            name='history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128, verbose_name='History'), blank=True, default=list, size=None),
        ),
    ]
