# Generated by Django 3.2.6 on 2022-08-09 17:16
import logging

from django.db import migrations, models, transaction
import django.db.models.deletion


def migrate_tpm_partners_to_organizations(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    TPMPartner = apps.get_model('tpmpartners', 'TPMPartner')

    with transaction.atomic():
        for tpm_partner in TPMPartner.objects.all():
            if not tpm_partner.vendor_number:
                logging.info(f"No vendor_number set for TPMPartner "
                             f"{tpm_partner.name} id: {tpm_partner.pk}. Skipping..")
                continue
            organization, _ = Organization.objects.get_or_create(
                vendor_number=tpm_partner.vendor_number,
                defaults={
                    'name': tpm_partner.name,
                })
            tpm_partner.organization = organization
            tpm_partner.save(update_fields=['organization'])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tpmpartners', '0007_auto_20210421_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmpartner',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AlterModelOptions(
            name='tpmpartner',
            options={'base_manager_name': 'objects', 'ordering': ('organization__name',), 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.RunPython(migrate_tpm_partners_to_organizations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='tpmpartner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tpmpartner',
            name='vendor_number',
        ),
    ]
