# Generated by Django 3.2.6 on 2022-10-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tpmpartners', '0008_tpmpartner_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpmpartner',
            name='organization',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
            preserve_default=False,
        ),
    ]
