# Generated by Django 3.2.6 on 2022-12-13 12:29

from django.db import migrations, models, IntegrityError, connection
import django.db.models.deletion


def migrate_tpm_staff_members_to_realms(apps, schema_editor):
    if connection.tenant.schema_name in ["public", "test"]:
        return

    Realm = apps.get_model('users', 'Realm')
    Group = apps.get_model('auth', 'Group')
    TPMPartner = apps.get_model('tpmpartners', 'TPMPartner')
    Country = apps.get_model("users", "country")
    country = Country.objects.get(schema_name=connection.tenant.schema_name)

    tpm_group = Group.objects.get_or_create(name='Third Party Monitor')[0]

    for firm in TPMPartner.objects.all():
        for staff_member in firm.staff_members.all():
            try:
                Realm.objects.create(
                    user=staff_member.user,
                    country=country,
                    organization=firm.organization,
                    group=tpm_group,
                )
            except IntegrityError:
                # all good, realm already exists
                pass


def migrate_receive_tpm_notifications_to_profile(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.filter(
        user__tpmpartners_tpmpartnerstaffmember__receive_tpm_notifications=True,
    ).update(receive_tpm_notifications=True)


class Migration(migrations.Migration):

    dependencies = [
        ('tpmpartners', '0009_alter_tpmpartner_organization'),
        ('users', '0022_userprofile_receive_tpm_notifications'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.RunPython(migrate_tpm_staff_members_to_realms, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tpmpartnerstaffmember',
            name='tpm_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_staff_members', to='tpmpartners.tpmpartner', verbose_name='TPM Vendor'),
        ),
        migrations.RunPython(migrate_receive_tpm_notifications_to_profile, migrations.RunPython.noop),
    ]
