# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-11 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waffle', '0002_auto_20161201_0958'),
        ('users', '0010_auto_20171127_2158'),
        ('environment', '0002_tenantflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ManyToManyField(blank=True, help_text='Activate this switch for these countries.', to='users.Country')),
                ('switch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='waffle.Switch')),
            ],
        ),
    ]
