# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-14 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_tenantswitch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantswitch',
            options={'verbose_name_plural': 'Switches'},
        ),
        migrations.RemoveField(
            model_name='tenantswitch',
            name='switch',
        ),
        migrations.AddField(
            model_name='tenantswitch',
            name='active',
            field=models.BooleanField(default=False, help_text='Is this switch active?'),
        ),
        migrations.AddField(
            model_name='tenantswitch',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date when this Switch was created.'),
        ),
        migrations.AddField(
            model_name='tenantswitch',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when this Switch was last modified.'),
        ),
        migrations.AddField(
            model_name='tenantswitch',
            name='name',
            field=models.CharField(default=datetime.datetime(2017, 12, 14, 22, 4, 20, 651783, tzinfo=utc), help_text='The human/computer readable name.', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantswitch',
            name='note',
            field=models.TextField(blank=True, help_text='Note where this Switch is used.'),
        ),
    ]
