# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-27 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundsCommitmentHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=20)),
                ('fc_number', models.CharField(max_length=20)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('fc_type', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('document_text', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundsCommitmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc_ref_number', models.CharField(blank=True, max_length=30, null=True)),
                ('line_item', models.CharField(max_length=5)),
                ('wbs', models.CharField(blank=True, max_length=30, null=True)),
                ('grant_number', models.CharField(blank=True, max_length=20, null=True)),
                ('fund', models.CharField(blank=True, max_length=10, null=True)),
                ('gl_account', models.CharField(blank=True, max_length=15, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('fr_number', models.CharField(blank=True, max_length=20, null=True)),
                ('commitment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commitment_amount_dc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_changed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_item_text', models.CharField(blank=True, max_length=255, null=True)),
                ('fund_commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fc_items', to='funds.FundsCommitmentHeader')),
            ],
        ),
        migrations.CreateModel(
            name='FundsReservationHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=20)),
                ('fr_number', models.CharField(max_length=20, unique=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('fr_type', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('document_text', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['fr_number'],
            },
        ),
        migrations.CreateModel(
            name='FundsReservationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr_ref_number', models.CharField(blank=True, max_length=30, null=True)),
                ('line_item', models.CharField(max_length=5)),
                ('wbs', models.CharField(blank=True, max_length=30, null=True)),
                ('grant_number', models.CharField(blank=True, max_length=20, null=True)),
                ('fund', models.CharField(blank=True, max_length=10, null=True)),
                ('overall_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overall_amount_dc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('line_item_text', models.CharField(blank=True, max_length=255, null=True)),
                ('fund_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_items', to='funds.FundsReservationHeader')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='fundsreservationheader',
            unique_together=set([('vendor_code', 'fr_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='fundsreservationitem',
            unique_together=set([('fund_reservation', 'line_item')]),
        ),
        migrations.AlterUniqueTogether(
            name='fundscommitmentitem',
            unique_together=set([('fund_commitment', 'line_item')]),
        ),
    ]
