# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-19 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundsCommitmentHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=20)),
                ('fc_number', models.CharField(max_length=20)),
                ('fc_doc_date', models.DateField(blank=True, null=True)),
                ('fr_type', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('fc_document_text', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundsCommitmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbs', models.CharField(blank=True, max_length=30, null=True)),
                ('grant_number', models.CharField(blank=True, max_length=20, null=True)),
                ('fund', models.CharField(blank=True, max_length=10, null=True)),
                ('gl_account', models.CharField(blank=True, max_length=15, null=True)),
                ('overall_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overall_amount_dc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('fr_number', models.CharField(blank=True, max_length=20, null=True)),
                ('commitment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_changed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fc_item_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundsReservationHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(max_length=20)),
                ('fr_number', models.CharField(max_length=20)),
                ('fr_doc_date', models.DateField(blank=True, null=True)),
                ('fr_type', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('fr_document_text', models.CharField(blank=True, max_length=255, null=True)),
                ('fr_start_date', models.DateField(blank=True, null=True)),
                ('fr_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundsReservationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item', models.IntegerField(default=0)),
                ('wbs', models.CharField(blank=True, max_length=30, null=True)),
                ('grant_number', models.CharField(blank=True, max_length=20, null=True)),
                ('fund', models.CharField(blank=True, max_length=10, null=True)),
                ('overall_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
