# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-24 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_auto_20170224_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundsreservationitem',
            name='fr_ref_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fundsreservationheader',
            name='fr_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
