# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-28 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_auto_20170227_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundscommitmentheader',
            name='fc_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
