# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-20 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0033_auto_20170614_1831'),
        ('funds', '0003_auto_20170228_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundsreservationheader',
            name='actual_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fundsreservationheader',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frs', to='partners.Intervention'),
        ),
        migrations.AddField(
            model_name='fundsreservationheader',
            name='intervention_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fundsreservationheader',
            name='outstanding_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fundsreservationheader',
            name='total_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
