# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-26 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0008_auto_20171019_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundscommitmentitem',
            name='fr_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='FR Number'),
        ),
        migrations.AlterField(
            model_name='fundscommitmentitem',
            name='gl_account',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='GL Account'),
        ),
        migrations.AlterField(
            model_name='fundsreservationitem',
            name='fund_reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_items', to='funds.FundsReservationHeader', verbose_name='FR Number'),
        ),
    ]
