# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-12 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0010_auto_20171024_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundsreservationheader',
            name='actual_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Actual Cash Transfer'),
        ),
        migrations.AlterField(
            model_name='fundsreservationheader',
            name='intervention_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Current FR Amount'),
        ),
        migrations.AlterField(
            model_name='fundsreservationheader',
            name='outstanding_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Outstanding DCT'),
        ),
        migrations.AlterField(
            model_name='fundsreservationheader',
            name='total_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='FR Overall Amount'),
        ),
    ]
