# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-07 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0011_auto_20180221_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundsreservationheader',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
    ]
