# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-21 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0013_fix_null_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundscommitmentheader',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='fundscommitmentheader',
            name='document_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='fundscommitmentheader',
            name='exchange_rate',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Exchange Rate'),
        ),
        migrations.AlterField(
            model_name='fundscommitmentheader',
            name='fc_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='fundscommitmentheader',
            name='responsible_person',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Responsible'),
        ),
        migrations.AlterField(
            model_name='fundscommitmentitem',
            name='fc_ref_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='fundscommitmentitem',
            name='fr_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='FR Number'),
        ),
        migrations.AlterField(
            model_name='fundscommitmentitem',
            name='fund',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Fund'),
        ),
        migrations.AlterField(
            model_name='fundscommitmentitem',
            name='gl_account',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='GL Account'),
        ),
        migrations.AlterField(
            model_name='fundscommitmentitem',
            name='grant_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Grant Number'),
        ),
        migrations.AlterField(
            model_name='fundscommitmentitem',
            name='line_item_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='fundscommitmentitem',
            name='wbs',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='WBS'),
        ),
        migrations.AlterField(
            model_name='fundsreservationheader',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='fundsreservationheader',
            name='document_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Document Text'),
        ),
        migrations.AlterField(
            model_name='fundsreservationheader',
            name='fr_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='fundsreservationitem',
            name='fr_ref_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Item Number'),
        ),
        migrations.AlterField(
            model_name='fundsreservationitem',
            name='fund',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Fund'),
        ),
        migrations.AlterField(
            model_name='fundsreservationitem',
            name='grant_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Grant Number'),
        ),
        migrations.AlterField(
            model_name='fundsreservationitem',
            name='line_item_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='fundsreservationitem',
            name='wbs',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='WBS'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
    ]
