# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-27 17:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultworkplanproperty',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
