# Generated by Django 3.2.19 on 2024-07-19 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('partners', '0001_initial'),
        ('reports', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cp_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.result', verbose_name='CP Output'),
        ),
        migrations.AddField(
            model_name='activity',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.intervention', verbose_name='Intervention'),
        ),
        migrations.AddField(
            model_name='activity',
            name='locations',
            field=models.ManyToManyField(related_name='_activities_activity_locations_+', to='locations.Location', verbose_name='Locations'),
        ),
        migrations.AddField(
            model_name='activity',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partnerorganization', verbose_name='Implementing Partner'),
        ),
    ]
