# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-18 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('issue_category', models.CharField(choices=[(b'data', b'Data Issue'), (b'compliance', b'Compliance Issue')], default=b'data', max_length=32)),
                ('issue_id', models.CharField(help_text=b'A readable ID associated with the specific issue, e.g. "pca-no-attachment"', max_length=100)),
                ('message', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
