# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-18 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedissue',
            name='issue_status',
            field=models.CharField(choices=[('new', 'New (untriaged)'), ('pending', 'Pending (triaged, not resolved)'), ('resolved', 'Resolved')], default='new', max_length=32),
        ),
    ]
