# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-20 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_flaggedissue_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedissue',
            name='issue_category',
            field=models.CharField(choices=[(b'data', b'Data Issue'), (b'compliance', b'Compliance Issue')], db_index=True, default=b'data', max_length=32),
        ),
        migrations.AlterField(
            model_name='flaggedissue',
            name='issue_id',
            field=models.CharField(db_index=True, help_text=b'A readable ID associated with the specific issue, e.g. "pca-no-attachment"', max_length=100),
        ),
        migrations.AlterField(
            model_name='flaggedissue',
            name='issue_status',
            field=models.CharField(choices=[(b'new', b'New (untriaged)'), (b'pending', b'Pending (triaged, not resolved)'), (b'reactivated', b'Reactivated (was resolved but not fixed)'), (b'resolved', b'Resolved')], db_index=True, default=b'new', max_length=32),
        ),
    ]
