# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-09-20 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20170920_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedissue',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
