# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-10 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20170920_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCheckConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
