# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-10 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_issuecheckconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssueCheckConfig',
        ),
    ]
