# Generated by Django 2.2.7 on 2019-11-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20190820_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='module',
            field=models.CharField(choices=[('apd', 'Action Points'), ('t2f', 'Trip Management'), ('tpm', 'Third Party Monitoring'), ('audit', 'Financial Assurance'), ('psea', 'PSEA Assessment'), ('fm', 'Field Monitoring')], max_length=10, verbose_name='Module'),
        ),
    ]
