# Generated by Django 2.1.4 on 2018-12-05 21:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions2', '0002_auto_20170907_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='condition',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
