# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-16 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_types_applicable', models.BooleanField(default=False, verbose_name='Are types allowed?')),
            ],
        ),
    ]
