# Generated by Django 1.10.8 on 2018-04-06 14:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0002_auto_20180326_1605'),
        ('t2f', '0001_initial'),
        ('users', '0001_initial'),
        ('tpm', '0001_initial'),
        ('reports', '0001_initial'),
        ('locations', '0001_initial'),
        ('unicef_locations', '0001_initial'),
        ('audit', '0002_auto_20180326_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', django_fsm.FSMField(choices=[
                 ('open', 'Open'), ('completed', 'Completed')], default='open', max_length=10, protected=True, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Description')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('priority', models.CharField(choices=[
                 ('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10, verbose_name='Priority')),
                ('action_taken', models.TextField(blank=True, verbose_name='Action Taken')),
                ('date_of_completion', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now,
                                                                       monitor='status', null=True, verbose_name='Date Action Point Completed', when=set(['completed']))),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='assigned_action_points', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='created_action_points', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('cp_output', models.ForeignKey(blank=True, null=True,
                                                on_delete=django.db.models.deletion.CASCADE, to='reports.Result', verbose_name='CP Output')),
                ('engagement', models.ForeignKey(blank=True, null=True,
                                                 on_delete=django.db.models.deletion.CASCADE, to='audit.Engagement', verbose_name='Engagement')),
                ('intervention', models.ForeignKey(blank=True, null=True,
                                                   on_delete=django.db.models.deletion.CASCADE, to='partners.Intervention', verbose_name='PD/SSFA')),
                ('location', models.ForeignKey(blank=True, null=True,
                                               on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Location')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Office', verbose_name='Office')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='partners.PartnerOrganization', verbose_name='Partner')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='reports.Section', verbose_name='Section')),
                ('tpm_activity', models.ForeignKey(blank=True, null=True,
                                                   on_delete=django.db.models.deletion.CASCADE, to='tpm.TPMActivity', verbose_name='TPM Activity')),
                ('travel_activity', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.CASCADE, to='t2f.TravelActivity', verbose_name='Travel Activity')),
            ],
            options={
                'abstract': False,
                'ordering': ('id',),
                'verbose_name': 'Action Point',
                'verbose_name_plural': 'Action Points',
            },
        ),
    ]
