# Generated by Django 1.10.8 on 2018-05-18 08:35
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0003_make_not_nullable'),
        ('action_points', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionpoint',
            name='travel_activity',
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t2f.Travel', verbose_name='Travel'),
        ),
    ]
