# Generated by Django 3.2.19 on 2023-10-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('action_points', '0001_initial'),
        ('locations', '0001_initial'),
        ('partners', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpoint',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_points', to='audit.engagement', verbose_name='Engagement'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.intervention', verbose_name='PD/SPD'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='Location'),
        ),
    ]
