# Generated by Django 3.2.19 on 2024-06-03 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field_monitoring_planning', '0003_initial'),
        ('categories', '0001_initial'),
        ('action_points', '0001_initial'),
        ('partners', '0001_initial'),
        ('tpm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psea', '0003_initial'),
        ('reports', '0001_initial'),
        ('locations', '0001_initial'),
        ('audit', '0004_initial'),
        ('t2f', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpoint',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_action_points', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_action_points', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='cp_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.result', verbose_name='CP Output'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_points', to='audit.engagement', verbose_name='Engagement'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.intervention', verbose_name='PD/SPD'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='monitoring_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_planning.monitoringactivity', verbose_name='Monitoring Activity'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.office', verbose_name='Office'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='potential_verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_points_to_verify', to=settings.AUTH_USER_MODEL, verbose_name='Potential Verifier'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='psea_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_points', to='psea.assessment', verbose_name='PSEA Assessment'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='tpm_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_points', to='tpm.tpmactivity', verbose_name='TPM Activity'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='travel_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t2f.travelactivity', verbose_name='Travel Activity'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_action_points', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
    ]
