# Generated by Django 3.2.19 on 2023-10-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field_monitoring_planning', '0001_initial'),
        ('action_points', '0002_initial'),
        ('partners', '0002_initial'),
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpoint',
            name='monitoring_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_monitoring_planning.monitoringactivity', verbose_name='Monitoring Activity'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.office', verbose_name='Office'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partnerorganization', verbose_name='Partner'),
        ),
    ]
