# Generated by Django 1.10.8 on 2018-07-13 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0004_auto_20180524_1831'),
        ('action_points', '0004_auto_20180521_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionpoint',
            name='travel',
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='travel_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t2f.TravelActivity', verbose_name='Travel'),
        ),
    ]
