# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_points', '0002_auto_20180518_0835'),
        ('action_points', '0004_auto_20180517_1024'),
    ]

    operations = [
    ]
