# Generated by Django 4.2.23 on 2026-03-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_planning', '0015_fix_ewpactivity_unique_constraints'),
        ('action_points', '0004_actionpoint_ewp_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionpoint',
            name='ewp_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_monitoring_planning.ewpactivity', verbose_name='Key Intervention'),
        ),
    ]
