# Generated by Django 1.10.8 on 2018-07-18 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action_points', '0005_auto_20180713_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('module', models.CharField(choices=[('apd', 'Action Points'), ('t2f', 'Trip Management'), ('tpm', 'Third Party Monitoring'), ('audit', 'Financial Assurance')], max_length=10, verbose_name='Module')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'ordering': ('module', 'order'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('description', 'module')]),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='action_points.Category', verbose_name='Category'),
        ),
    ]
