# Generated by Django 1.10.8 on 2018-07-31 09:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


def copy_categories(apps, schema_editor):
    OldCategory = apps.get_model('action_points', 'Category')
    NewCategory = apps.get_model('categories', 'Category')

    for category in OldCategory.objects.all():
        NewCategory.objects.get_or_create(module=category.module, description=category.description,
                                          defaults={'order': category.order})


def migrate_categories(apps, schema_editor):
    ActionPoint = apps.get_model('action_points', 'ActionPoint')
    Category = apps.get_model('categories', 'Category')

    for action_point in ActionPoint.objects.filter(category__isnull=False):
        action_point.category1 = Category.objects.get(module=action_point.category.module,
                                                      description=action_point.category.description)
        action_point.save()


class Migration(migrations.Migration):
    dependencies = [
        ('action_points', '0006_auto_20180718_1439'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpoint',
            name='category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='categories.Category', verbose_name='Category'),
        ),
        migrations.RunPython(copy_categories, migrations.RunPython.noop),
        migrations.RunPython(migrate_categories, migrations.RunPython.noop),
    ]
