# Generated by Django 2.2.1 on 2019-05-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action_points', '0008_auto_20180731_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionpoint',
            name='travel_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t2f.TravelActivity', verbose_name='Travel Activity'),
        ),
    ]
