# Generated by Django 2.2.4 on 2019-08-20 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psea', '0002_auto_20190820_1618'),
        ('action_points', '0009_auto_20190523_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpoint',
            name='psea_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_points', to='psea.Assessment', verbose_name='PSEA Assessment'),
        ),
    ]
