# Generated by Django 2.2.7 on 2021-01-08 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action_points', '0013_actionpoint_monitoring_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionpoint',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Intervention', verbose_name='PD/SPD'),
        ),
    ]
