# Generated by Django 3.2.19 on 2024-02-12 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('action_points', '0014_auto_20210108_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionpoint',
            name='date_of_verification',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='verified_by', null=True, verbose_name='Date Action Point Verified'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='is_adequate',
            field=models.BooleanField(default=False, verbose_name='Is Adequate'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='potential_verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_points_to_verify', to=settings.AUTH_USER_MODEL, verbose_name='Potential Verifier'),
        ),
        migrations.AddField(
            model_name='actionpoint',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_action_points', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
    ]
