# Generated by Django 3.2.19 on 2024-07-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0004_add_object_pk_is_removed_index'),
        ('action_points', '0015_auto_20240212_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPointComment',
            fields=[
            ],
            options={
                'verbose_name': 'Action Point Comment',
                'verbose_name_plural': 'Action Point Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_comments.comment',),
        ),
    ]
