# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-30 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Activities'},
        ),
    ]
