# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-16 11:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapshot', '0002_auto_20171030_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='additional data'),
        ),
    ]
