# Generated by Django 1.10.8 on 2018-03-26 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('unicef_locations', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cluster_indicator_id', models.PositiveIntegerField(
                    blank=True, null=True, verbose_name='Cluster Indicator ID')),
                ('response_plan_name', models.CharField(blank=True,
                                                        max_length=1024, null=True, verbose_name='Response plan name')),
                ('cluster_name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Cluster Name')),
                ('cluster_indicator_title', models.CharField(blank=True,
                                                             max_length=1024, null=True, verbose_name='Cluster Indicator Title')),
                ('context_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code in current context')),
                ('target', models.PositiveIntegerField(default=0, verbose_name='Target')),
                ('baseline', models.PositiveIntegerField(blank=True, null=True, verbose_name='Baseline')),
                ('assumptions', models.TextField(blank=True, null=True, verbose_name='Assumptions')),
                ('means_of_verification', models.CharField(blank=True,
                                                           max_length=255, null=True, verbose_name='Means of Verification')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='Current Total')),
            ],
        ),
        migrations.CreateModel(
            name='CountryProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('wbs', models.CharField(max_length=30, unique=True, verbose_name='WBS')),
                ('invalid', models.BooleanField(default=False, verbose_name='Invalid')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
            ],
        ),
        migrations.CreateModel(
            name='Disaggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisaggregationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.CharField(max_length=15, verbose_name='Value')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('disaggregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                     related_name='disaggregation_values', to='reports.Disaggregation', verbose_name='Disaggregation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='UNICEF Target')),
                ('sector_total', models.IntegerField(blank=True, null=True, verbose_name='Sector Target')),
                ('current', models.IntegerField(blank=True, default=0, null=True, verbose_name='Current')),
                ('sector_current', models.IntegerField(blank=True, null=True, verbose_name='Sector Current')),
                ('assumptions', models.TextField(blank=True, null=True, verbose_name='Assumptions')),
                ('target', models.CharField(blank=True, max_length=255, null=True, verbose_name='Target')),
                ('baseline', models.CharField(blank=True, max_length=255, null=True, verbose_name='Baseline')),
                ('ram_indicator', models.BooleanField(default=False, verbose_name='RAM Indicator')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('view_on_dashboard', models.BooleanField(default=False, verbose_name='View on Dashboard')),
            ],
            options={
                'ordering': ['-active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorBlueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=1024, verbose_name='Title')),
                ('unit', models.CharField(choices=[('number', 'number'), ('percentage',
                                                                          'percentage')], default='number', max_length=10, verbose_name='Unit')),
                ('description', models.CharField(blank=True, max_length=3072, null=True, verbose_name='Description')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code')),
                ('subdomain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subdomain')),
                ('disaggregatable', models.BooleanField(default=False, verbose_name='Disaggregatable')),
                ('calculation_formula_across_periods', models.CharField(choices=[('sum', 'sum'), ('max', 'max'), ('avg', 'avg'), (
                    'percentage', 'percentage'), ('ratio', 'ratio')], default='sum', max_length=10, verbose_name='Calculation Formula across Periods')),
                ('calculation_formula_across_locations', models.CharField(choices=[('sum', 'sum'), ('max', 'max'), ('avg', 'avg'), (
                    'percentage', 'percentage'), ('ratio', 'ratio')], default='sum', max_length=10, verbose_name='Calculation Formula across Locations')),
                ('display_type', models.CharField(choices=[('number', 'number'), ('percentage', 'percentage'), (
                    'ratio', 'ratio')], default='number', max_length=10, verbose_name='Display Type')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LowerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('result_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='ll_results', to='partners.InterventionResultLink', verbose_name='Result Link')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'),
                                                   ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=64, verbose_name='Name')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='To Date')),
                ('humanitarian_tag', models.BooleanField(default=False, verbose_name='Humanitarian Tag')),
                ('wbs', models.CharField(blank=True, max_length=50, null=True, verbose_name='WBS')),
                ('vision_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='VISION ID')),
                ('gic_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='GIC Code')),
                ('gic_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='GIC Name')),
                ('sic_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='SIC Code')),
                ('sic_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='SIC Name')),
                ('activity_focus_code', models.CharField(blank=True,
                                                         max_length=8, null=True, verbose_name='Activity Focus Code')),
                ('activity_focus_name', models.CharField(blank=True,
                                                         max_length=255, null=True, verbose_name='Activity Focus Code')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('ram', models.BooleanField(default=False, verbose_name='RAM')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('country_programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                        to='reports.CountryProgramme', verbose_name='Country Programme')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='children', to='reports.Result', verbose_name='Parent')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Outcome', 'Outcome'), ('Output', 'Output'),
                                                   ('Activity', 'Activity')], max_length=150, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('alternate_id', models.IntegerField(blank=True, null=True, verbose_name='Alternate ID')),
                ('alternate_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternate Name')),
                ('dashboard', models.BooleanField(default=False, verbose_name='Dashboard')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45, unique=True, verbose_name='Type')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.AddField(
            model_name='result',
            name='result_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='reports.ResultType', verbose_name='Result Type'),
        ),
        migrations.AddField(
            model_name='result',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='reports.Section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='reports.Result', verbose_name='Result'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='reports.Section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='reports.Unit', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='appliedindicator',
            name='disaggregation',
            field=models.ManyToManyField(blank=True, related_name='applied_indicators',
                                         to='reports.Disaggregation', verbose_name='Disaggregation Logic'),
        ),
        migrations.AddField(
            model_name='appliedindicator',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='reports.IndicatorBlueprint', verbose_name='Indicator'),
        ),
        migrations.AddField(
            model_name='appliedindicator',
            name='locations',
            field=models.ManyToManyField(related_name='applied_indicators',
                                         to='locations.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='appliedindicator',
            name='lower_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='applied_indicators', to='reports.LowerResult', verbose_name='PD Result'),
        ),
        migrations.AddField(
            model_name='appliedindicator',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='reports.Section', verbose_name='Section'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('wbs', 'country_programme')]),
        ),
        migrations.AlterUniqueTogether(
            name='lowerresult',
            unique_together=set([('result_link', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together=set([('name', 'result', 'sector')]),
        ),
        migrations.AlterUniqueTogether(
            name='appliedindicator',
            unique_together=set([('indicator', 'lower_result')]),
        ),
    ]
