# Generated by Django 3.2.19 on 2024-07-19 11:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import etools.applications.reports.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('measurement_specifications', models.TextField(blank=True, max_length=4048, null=True)),
                ('label', models.TextField(blank=True, max_length=4048, null=True)),
                ('numerator_label', models.CharField(blank=True, max_length=256, null=True)),
                ('denominator_label', models.CharField(blank=True, max_length=256, null=True)),
                ('cluster_indicator_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cluster Indicator ID')),
                ('response_plan_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Response plan name')),
                ('cluster_name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Cluster Name')),
                ('cluster_indicator_title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Cluster Indicator Title')),
                ('context_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code in current context')),
                ('target', models.JSONField(default=etools.applications.reports.models.indicator_default_dict)),
                ('baseline', models.JSONField(default=etools.applications.reports.models.indicator_default_dict, null=True)),
                ('assumptions', models.TextField(blank=True, null=True, verbose_name='Assumptions')),
                ('means_of_verification', models.CharField(blank=True, max_length=255, null=True, verbose_name='Means of Verification')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='Current Total')),
                ('is_high_frequency', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='CountryProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('wbs', models.CharField(max_length=30, unique=True, verbose_name='WBS')),
                ('invalid', models.BooleanField(default=False, verbose_name='Invalid')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
            ],
        ),
        migrations.CreateModel(
            name='Disaggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisaggregationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.CharField(max_length=20, verbose_name='Value')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='UNICEF Target')),
                ('sector_total', models.IntegerField(blank=True, null=True, verbose_name='Sector Target')),
                ('current', models.IntegerField(blank=True, default=0, null=True, verbose_name='Current')),
                ('sector_current', models.IntegerField(blank=True, null=True, verbose_name='Sector Current')),
                ('assumptions', models.TextField(blank=True, null=True, verbose_name='Assumptions')),
                ('target', models.CharField(blank=True, max_length=255, null=True, verbose_name='Target')),
                ('baseline', models.CharField(blank=True, max_length=255, null=True, verbose_name='Baseline')),
                ('ram_indicator', models.BooleanField(default=False, verbose_name='RAM Indicator')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('view_on_dashboard', models.BooleanField(default=False, verbose_name='View on Dashboard')),
            ],
            options={
                'ordering': ['-active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorBlueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=1024, verbose_name='Title')),
                ('unit', models.CharField(choices=[('number', 'number'), ('percentage', 'percentage')], default='number', max_length=10, verbose_name='Unit')),
                ('description', models.CharField(blank=True, max_length=3072, null=True, verbose_name='Description')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code')),
                ('subdomain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subdomain')),
                ('disaggregatable', models.BooleanField(default=False, verbose_name='Disaggregatable')),
                ('calculation_formula_across_periods', models.CharField(choices=[('sum', 'sum'), ('max', 'max'), ('avg', 'avg'), ('percentage', 'percentage'), ('ratio', 'ratio')], default='sum', max_length=10, verbose_name='Calculation Formula across Periods')),
                ('calculation_formula_across_locations', models.CharField(choices=[('sum', 'sum'), ('max', 'max'), ('avg', 'avg'), ('percentage', 'percentage'), ('ratio', 'ratio')], default='sum', max_length=10, verbose_name='Calculation Formula across Locations')),
                ('display_type', models.CharField(choices=[('number', 'number'), ('percentage', 'percentage'), ('ratio', 'ratio')], default='number', max_length=10, verbose_name='Display Type')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InterventionActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('context_details', models.TextField(blank=True, null=True, verbose_name='Context Details')),
                ('unicef_cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='UNICEF Cash')),
                ('cso_cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='CSO Cash')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Intervention Activity',
                'verbose_name_plural': 'Intervention Activities',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='InterventionActivityItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('unit', models.CharField(max_length=150, verbose_name='Unit')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Unit Price')),
                ('no_units', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Units Number')),
                ('unicef_cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='UNICEF Cash')),
                ('cso_cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='CSO Cash')),
            ],
            options={
                'verbose_name': 'Intervention Activity Item',
                'verbose_name_plural': 'Intervention Activity Items',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='InterventionTimeFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quarter', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
            ],
            options={
                'ordering': ('intervention', 'start_date'),
            },
        ),
        migrations.CreateModel(
            name='LowerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=64, verbose_name='Name')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(null=True, verbose_name='End Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('report_type', models.CharField(choices=[('QPR', 'Standard Quarterly Progress Report'), ('HR', 'Humanitarian Report')], max_length=50)),
            ],
            options={
                'ordering': ('-end_date',),
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='To Date')),
                ('humanitarian_tag', models.BooleanField(default=False, verbose_name='Humanitarian Tag')),
                ('humanitarian_marker_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Humanitarian Marker Code')),
                ('humanitarian_marker_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Humanitarian Marker Name')),
                ('wbs', models.CharField(blank=True, max_length=50, null=True, verbose_name='WBS')),
                ('vision_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='VISION ID')),
                ('programme_area_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='Programme Area Code')),
                ('programme_area_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Programme Area Name')),
                ('gic_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='GIC Code')),
                ('gic_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='GIC Name')),
                ('sic_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='SIC Code')),
                ('sic_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='SIC Name')),
                ('activity_focus_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Activity Focus Code')),
                ('activity_focus_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Activity Focus Code')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('ram', models.BooleanField(default=False, verbose_name='RAM')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Outcome', 'Outcome'), ('Output', 'Output'), ('Activity', 'Activity')], max_length=150, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('alternate_id', models.IntegerField(blank=True, null=True, verbose_name='Alternate ID')),
                ('alternate_name', models.CharField(default='', max_length=255, null=True, verbose_name='Alternate Name')),
                ('dashboard', models.BooleanField(default=False, verbose_name='Dashboard')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'db_table': 'reports_sector',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialReportingRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Description')),
                ('due_date', models.DateField(verbose_name='Due Date')),
            ],
            options={
                'ordering': ('-due_date',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45, unique=True, verbose_name='Type')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='UserTenantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.office', verbose_name='Office')),
            ],
        ),
    ]
