# Generated by Django 3.2.19 on 2024-07-19 11:57

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0002_initial'),
        ('users', '0001_initial'),
        ('locations', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertenantprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to='users.userprofile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='specialreportingrequirement',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_reporting_requirements', to='partners.intervention', verbose_name='Intervention'),
        ),
        migrations.AddField(
            model_name='result',
            name='country_programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.countryprogramme', verbose_name='Country Programme'),
        ),
        migrations.AddField(
            model_name='result',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reports.result', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='result',
            name='result_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.resulttype', verbose_name='Result Type'),
        ),
        migrations.AddField(
            model_name='result',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='reportingrequirement',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_requirements', to='partners.intervention', verbose_name='Intervention'),
        ),
        migrations.AddField(
            model_name='lowerresult',
            name='result_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ll_results', to='partners.interventionresultlink', verbose_name='Result Link'),
        ),
        migrations.AddField(
            model_name='interventiontimeframe',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='partners.intervention', verbose_name='Intervention'),
        ),
        migrations.AddField(
            model_name='interventionactivityitem',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.interventionactivity', verbose_name='Activity'),
        ),
        migrations.AddField(
            model_name='interventionactivity',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='reports.lowerresult', verbose_name='Result'),
        ),
        migrations.AddField(
            model_name='interventionactivity',
            name='time_frames',
            field=models.ManyToManyField(blank=True, related_name='activities', to='reports.InterventionTimeFrame', verbose_name='Time Frames Enabled'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.result', verbose_name='Result'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.unit', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='disaggregationvalue',
            name='disaggregation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaggregation_values', to='reports.disaggregation', verbose_name='Disaggregation'),
        ),
        migrations.AddField(
            model_name='appliedindicator',
            name='disaggregation',
            field=models.ManyToManyField(blank=True, related_name='applied_indicators', to='reports.Disaggregation', verbose_name='Disaggregation Logic'),
        ),
        migrations.AddField(
            model_name='appliedindicator',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.indicatorblueprint', verbose_name='Indicator'),
        ),
        migrations.AddField(
            model_name='appliedindicator',
            name='locations',
            field=models.ManyToManyField(related_name='applied_indicators', to='locations.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='appliedindicator',
            name='lower_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_indicators', to='reports.lowerresult', verbose_name='PD Result'),
        ),
        migrations.AddField(
            model_name='appliedindicator',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.section', verbose_name='Section'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('wbs', 'country_programme')},
        ),
        migrations.AlterUniqueTogether(
            name='lowerresult',
            unique_together={('result_link', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('name', 'result', 'sector')},
        ),
        migrations.AlterUniqueTogether(
            name='appliedindicator',
            unique_together={('indicator', 'lower_result')},
        ),
    ]
