# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-15 17:44
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_auto_20180510_1940'),
        ('reports', '0007_auto_20180424_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialReportingRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='Description')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='special_reporting_requirements', to='partners.Intervention', verbose_name='Intervention')),
            ],
            options={
                'ordering': ('-due_date',),
            },
        ),
        migrations.RemoveField(
            model_name='reportingrequirement',
            name='description',
        ),
        migrations.AlterField(
            model_name='reportingrequirement',
            name='report_type',
            field=models.CharField(choices=[('QPR', 'Standard Quarterly Progress Report'),
                                            ('HR', 'Humanitarian Report')], max_length=50),
        ),
    ]
