# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-22 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_auto_20180521_1552'),
        ('reports', '0008_auto_20180515_1744'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specialreportingrequirement',
            unique_together=set([('intervention', 'due_date')]),
        ),
    ]
