# Generated by Django 1.10.8 on 2018-07-09 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_migrate_targets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedindicator',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='appliedindicator',
            name='target',
        ),
    ]
