# Generated by Django 1.10.8 on 2018-07-09 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20180709_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedindicator',
            old_name='baseline_new',
            new_name='baseline',
        ),
        migrations.RenameField(
            model_name='appliedindicator',
            old_name='target_new',
            new_name='target',
        ),
    ]
