# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-12 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20180709_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='type',
            field=models.CharField(choices=[('Outcome', 'Outcome'), ('Output', 'Output'), ('Activity', 'Activity')], default='Output', max_length=10, verbose_name='Result Type'),
        ),
    ]
