# Generated by Django 2.0.9 on 2018-12-29 02:49

from django.db import migrations, models

import etools.applications.reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20180709_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedindicator',
            name='baseline',
            field=models.JSONField(default=etools.applications.reports.models.indicator_default_dict, null=True),
        ),
        migrations.AlterField(
            model_name='appliedindicator',
            name='target',
            field=models.JSONField(default=etools.applications.reports.models.indicator_default_dict),
        ),
    ]
