# Generated by Django 2.1.5 on 2019-02-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20181229_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='humanitarian_marker_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Humanitarian Marker Code'),
        ),
        migrations.AddField(
            model_name='result',
            name='humanitarian_marker_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Humanitarian Marker Name'),
        ),
    ]
