# Generated by Django 2.1.7 on 2019-04-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20190208_2042'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='section',
            table='reports_sector',
        ),
    ]
