# Generated by Django 2.1.8 on 2019-04-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20190412_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
