# Generated by Django 2.2.4 on 2019-08-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_section_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliedindicator',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='lowerresult',
            options={'ordering': ('created',)},
        ),
    ]
