# Generated by Django 2.2.4 on 2019-10-11 12:01

from django.db import migrations


def copy_offices_data(apps, schema):
    OfficeOld = apps.get_model("users", "office")
    Office = apps.get_model("reports", "office")
    for old in OfficeOld.objects.all():
        Office.objects.create(
            pk=old.pk,
            name=old.name,
            zonal_chief=old.zonal_chief,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_office'),
    ]

    operations = [
        migrations.RunPython(copy_offices_data),
    ]
