# Generated by Django 2.2.4 on 2019-10-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191010_1621'),
        ('reports', '0021_auto_20191011_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTenantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.Office', verbose_name='Office')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_office', to='users.UserProfile', verbose_name='Profile')),
            ],
        ),
    ]
