# Generated by Django 2.2.7 on 2019-11-22 15:59

from django.db import connection, migrations
from django.db.models import Max


def reset_office_seq(apps, schema_editor):
    Office = apps.get_model("reports", "office")
    qs = Office.objects.all().aggregate(max_id=Max("id"))
    with connection.cursor() as cursor:
        cursor.execute(
            "select setval('reports_office_id_seq', %s, true)",
            [qs["max_id"]]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_auto_20191014_1546'),
    ]

    operations = [
        migrations.RunPython(
            reset_office_seq,
            migrations.RunPython.noop
        ),
    ]
