# Generated by Django 2.2.17 on 2021-06-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_auto_20191220_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaggregationvalue',
            name='value',
            field=models.CharField(max_length=20, verbose_name='Value'),
        ),
    ]
