# Generated by Django 2.2.7 on 2020-07-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_interventionactivity_interventionactivityitem_interventionactivitytimeframe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interventionactivityitem',
            old_name='unicef_suppies',
            new_name='unicef_supplies',
        ),
        migrations.AlterField(
            model_name='interventionactivityitem',
            name='other_details',
            field=models.TextField(blank=True, verbose_name='Context Details'),
        ),
    ]
