# Generated by Django 2.2.24 on 2021-07-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_auto_20210611_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='programme_area_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Programme Area Code'),
        ),
        migrations.AddField(
            model_name='result',
            name='programme_area_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Programme Area Name'),
        ),
    ]
