# Generated by Django 2.2.7 on 2020-07-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_interventionactivity_interventionactivityitem_interventionactivitytimeframe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interventionactivityitem',
            old_name='unicef_suppies',
            new_name='unicef_supplies',
        ),
    ]
