# Generated by Django 2.2.7 on 2020-09-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_auto_20200807_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventionactivity',
            name='cso_supplies',
        ),
        migrations.RemoveField(
            model_name='interventionactivity',
            name='unicef_supplies',
        ),
        migrations.RemoveField(
            model_name='interventionactivityitem',
            name='cso_supplies',
        ),
        migrations.RemoveField(
            model_name='interventionactivityitem',
            name='other_details',
        ),
        migrations.RemoveField(
            model_name='interventionactivityitem',
            name='unicef_supplies',
        ),
        migrations.AlterField(
            model_name='interventionactivity',
            name='context_details',
            field=models.TextField(blank=True, null=True, verbose_name='Context Details'),
        ),
        migrations.AlterField(
            model_name='interventionactivity',
            name='cso_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='CSO Cash'),
        ),
        migrations.AlterField(
            model_name='interventionactivity',
            name='unicef_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='UNICEF Cash'),
        ),
        migrations.AlterField(
            model_name='interventionactivityitem',
            name='cso_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='CSO Cash'),
        ),
        migrations.AlterField(
            model_name='interventionactivityitem',
            name='unicef_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='UNICEF Cash'),
        ),
    ]
