# Generated by Django 2.2.7 on 2020-09-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_auto_20200918_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interventionactivity',
            options={'ordering': ('id',), 'verbose_name': 'Intervention Activity', 'verbose_name_plural': 'Intervention Activities'},
        ),
        migrations.AlterModelOptions(
            name='interventionactivityitem',
            options={'ordering': ('id',), 'verbose_name': 'Intervention Activity Item', 'verbose_name_plural': 'Intervention Activity Items'},
        ),
    ]
