# Generated by Django 2.2.7 on 2020-09-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0031_auto_20200921_1330'),
        ('reports', '0031_auto_20200923_0922'),
    ]

    operations = [
    ]
