# Generated by Django 2.2.7 on 2021-05-20 13:10
from decimal import Decimal

from django.db import migrations, models
from django.db.models import F


def update_unit_fields(apps, schema_editor):
    InterventionActivityItem = apps.get_model('reports', 'InterventionActivityItem')
    InterventionActivityItem.objects.all().update(
        unit=F('name'),
        no_units=Decimal(1),
        unit_price=F('unicef_cash') + F('cso_cash'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0032_merge_20200923_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionactivityitem',
            name='no_units',
            field=models.IntegerField(default=0, verbose_name='Units Number'),
        ),
        migrations.AddField(
            model_name='interventionactivityitem',
            name='unit',
            field=models.CharField(blank=True, max_length=150, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='interventionactivityitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Unit Price'),
        ),
        migrations.RunPython(update_unit_fields, migrations.RunPython.noop),
    ]
