# Generated by Django 2.2.7 on 2021-05-20 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0033_auto_20210520_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionactivityitem',
            name='no_units',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Units Number'),
        ),
        migrations.AlterField(
            model_name='interventionactivityitem',
            name='unit',
            field=models.CharField(max_length=150, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='interventionactivityitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Unit Price'),
        ),
    ]
