# Generated by Django 2.2.7 on 2021-06-08 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0034_auto_20210520_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionactivityitem',
            name='no_units',
            field=models.DecimalField(decimal_places=1, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Units Number'),
        ),
    ]
