# Generated by Django 2.2.20 on 2021-07-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_auto_20210611_1403'),
        ('reports', '0035_auto_20210608_0915'),
    ]

    operations = [
    ]
