# Generated by Django 2.2.24 on 2021-07-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0035_auto_20210608_0915'),
        ('reports', '0026_auto_20210611_1403'),
    ]

    operations = [
    ]
