# Generated by Django 3.2.6 on 2022-02-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0037_merge_20210805_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionactivity',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code'),
        ),
    ]
