# Generated by Django 3.2.6 on 2022-04-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0040_interventionactivity_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionactivityitem',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code'),
        ),
    ]
