# Generated by Django 3.2.6 on 2022-05-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0043_alter_interventionactivityitem_no_units'),
        ('reports', '0043_auto_20220510_0717'),
    ]

    operations = [
    ]
