# Generated by Django 3.2.6 on 2022-08-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0044_merge_20220510_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowerresult',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
