# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-30 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0001_squashed_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='approved_cost_travel_agencies',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='approved_cost_traveler',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=20, null=True),
        ),
    ]
