# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-21 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
