# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-30 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0002_auto_20170130_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vision_fi_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
