# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-20 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0002_auto_20161220_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsaregion',
            name='business_area_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
