# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 02:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import t2f.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('t2f', '0003_dsaregion_business_area_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_point_number', models.CharField(default=t2f.models.make_action_point_number, max_length=11)),
                ('description', models.CharField(max_length=254)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('ongoing', 'On-going'), ('open', 'Open'), ('cancelled', 'Cancelled')], max_length=254, null=True, verbose_name='Status')),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('actions_taken', models.TextField(blank=True, null=True)),
                ('follow_up', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_points', to='t2f.Travel')),
            ],
        ),
    ]
