# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-11 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import t2f.models


class Migration(migrations.Migration):

    replaces = [(b't2f', '0004_actionpoint'), (b't2f', '0005_auto_20170104_1438'), (b't2f', '0006_auto_20170104_1512'), (b't2f', '0007_invoice_invoiceitem'), (b't2f', '0008_auto_20170106_0444'), (b't2f', '0009_expensetype_x_rate'), (b't2f', '0010_auto_20170106_1257'), (b't2f', '0011_auto_20170106_1403'), (b't2f', '0012_invoice_vision_fi_id'), (b't2f', '0013_auto_20170111_1248'), (b't2f', '0014_auto_20170111_1627')]

    dependencies = [
        ('t2f', '0003_dsaregion_business_area_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_point_number', models.CharField(default=t2f.models.make_action_point_number, max_length=11)),
                ('description', models.CharField(max_length=254)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('ongoing', 'On-going'), ('open', 'Open'), ('cancelled', 'Cancelled')], max_length=254, null=True, verbose_name='Status')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actions_taken', models.TextField(blank=True, null=True)),
                ('follow_up', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_points', to='t2f.Travel')),
                ('assigned_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=32)),
                ('business_area', models.CharField(max_length=32)),
                ('vendor_number', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('error', 'Error')], max_length=8)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='t2f.Currency')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='t2f.Travel')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='t2f.Fund')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='t2f.Grant')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='t2f.Invoice')),
                ('wbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='t2f.WBS')),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('error', 'Error')], max_length=16),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vision_fi_id',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelpermission',
            name='usage_place',
            field=models.CharField(choices=[('travel', 'Travel'), ('action_point', 'Action point')], default='travel', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('error', 'Error')], max_length=16),
        ),
        migrations.AlterField(
            model_name='travelpermission',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='travelpermission',
            name='user_type',
            field=models.CharField(max_length=25),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='vendor_number',
            field=models.CharField(default='user', max_length=32),
            preserve_default=False,
        ),
    ]
