# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-28 15:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0004_auto_20170228_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='message',
        ),
        migrations.AddField(
            model_name='invoice',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), default=[], size=None),
        ),
    ]
