# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-04 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0004_actionpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionpoint',
            old_name='reference_number',
            new_name='action_point_number',
        ),
    ]
