# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-05 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import t2f.models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0005_auto_20170228_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelattachment',
            name='file',
            field=models.FileField(max_length=255, upload_to=t2f.models.determine_file_upload_path),
        ),
    ]
