# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-06 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0006_auto_20170104_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=32)),
                ('business_area', models.CharField(max_length=32)),
                ('vendor_number', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('error', 'Error')], max_length=8)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='t2f.Currency')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='t2f.Travel')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='t2f.Fund')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='t2f.Grant')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='t2f.Invoice')),
                ('wbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='t2f.WBS')),
            ],
        ),
    ]
