# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-08 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0023_auto_20170301_2324'),
        ('t2f', '0006_auto_20170305_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelactivity',
            name='government_partnership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.GovernmentIntervention'),
        ),
    ]
