# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-06 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0008_auto_20170106_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='x_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
