# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-24 09:21
from __future__ import unicode_literals

from django.db import migrations, models


def order_iteneraryitems(apps, schema_editor):
    IteneraryItem = apps.get_model("t2f", "IteneraryItem")
    Travel = apps.get_model("t2f", "Travel")

    for travel in Travel.objects.all():
        iteneraryitems = travel.itinerary.all().order_by('departure_date')
        if len(iteneraryitems) > 1:
            travel.set_iteneraryitem_order([i.pk for i in iteneraryitems])


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0008_auto_20170323_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteneraryitem',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='iteneraryitem',
            order_with_respect_to='travel',
        ),
        migrations.RunPython(order_iteneraryitems),
    ]
