# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-04 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0009_auto_20170324_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='preserved_expenses',
            new_name='preserved_expenses_local',
        ),
        migrations.AddField(
            model_name='travel',
            name='preserved_expenses_usd',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=20, null=True),
        ),
    ]
