# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-13 10:58
from __future__ import unicode_literals

from django.db import migrations


def move_airlines(apps, schema_migrations):
    IteneraryItem = apps.get_model('t2f', 'IteneraryItem')
    for itinerary_item in IteneraryItem.objects.all():
        itinerary_item.airlines.add(*list(itinerary_item.new_airlines.all()))


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0009_auto_20170113_1257'),
    ]

    operations = [
        migrations.RunPython(move_airlines),
    ]
