# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-06 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0010_auto_20170106_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='x_rate',
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
