# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-13 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0010_auto_20170113_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteneraryitem',
            name='new_airlines',
        ),
    ]
