# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-26 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0010_fix_clearances'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='first_submission_date',
            field=models.DateTimeField(null=True),
        ),
    ]
