# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-06 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0011_auto_20170106_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vision_fi_id',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
