# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-18 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0011_remove_iteneraryitem_new_airlines'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseType',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='grant',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='wbs',
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
        migrations.DeleteModel(
            name='Grant',
        ),
        migrations.DeleteModel(
            name='WBS',
        ),
    ]
