# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-23 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publics', '0006_auto_20170118_1213'),
        ('t2f', '0012_auto_20170118_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteneraryitem',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='costassignment',
            name='business_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publics.BusinessArea'),
        ),
        migrations.AddField(
            model_name='costassignment',
            name='delegate',
            field=models.BooleanField(default=False),
        ),
    ]
