# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-27 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0012_auto_20170427_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='account_currency',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='preserved_expenses',
            new_name='preserved_expenses_local',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='document_currency',
        ),
        migrations.AddField(
            model_name='travel',
            name='preserved_expenses_usd',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=20, null=True),
        ),
    ]
