# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-22 13:56
from __future__ import unicode_literals

from django.db import migrations


def fix_empty_invoice_currencies(apps, schema_editor):
    Invoice = apps.get_model('t2f', 'Invoice')

    for invoice in Invoice.objects.filter(currency__isnull=True):
        invoice.currency = invoice.travel.currency
        invoice.save()


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0013_auto_20170427_1730'),
    ]

    operations = [
        migrations.RunPython(fix_empty_invoice_currencies),
    ]
