# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-24 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def clear_everything(apps, schema_editor):
    Travel = apps.get_model('t2f', 'Travel')
    Travel.objects.all().delete()

    TravelActivity = apps.get_model('t2f', 'TravelActivity')
    TravelActivity.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('t2f', '0013_auto_20170123_1417'),
    ]

    operations = [
        migrations.RunPython(clear_everything),
    ]
