# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-11 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0013_auto_20170111_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='vendor_number',
            field=models.CharField(default='user', max_length=32),
            preserve_default=False,
        ),
    ]
