# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-23 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0013_auto_20170427_1730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravelPermission',
        ),
    ]
