# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-24 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def populate_primary_traveler(apps, schema_editor):
    TravelActivity = apps.get_model('t2f', 'TravelActivity')

    for travel_activity in TravelActivity.objects.all():
        travel_activity.primary_traveler = travel_activity.travel.traveler
        travel_activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0014_auto_20170124_2357'),
    ]

    operations = [
        migrations.RunPython(populate_primary_traveler),
    ]
