# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-24 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0015_travelactivity_primary_traveler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelactivity',
            name='primary_traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
