# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-25 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0015_auto_20170524_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TravelPermission',
        ),
    ]
