# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-25 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import t2f.models


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0016_auto_20170124_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelactivity',
            name='primary_traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actionpoint',
            name='action_point_number',
            field=models.CharField(default=t2f.models.make_action_point_number, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reference_number',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='reference_number',
            field=models.CharField(default=t2f.models.make_travel_reference_number, max_length=12, unique=True),
        ),
    ]
