# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-19 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0017_remove_travelactivity_government_partnership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelactivity',
            name='partnership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_activities', to='partners.Intervention'),
        ),
    ]
