# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-28 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0018_auto_20170719_1529'),
    ]

    operations = [
        migrations.RenameModel("IteneraryItem", "ItineraryItem")
    ]
