# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-23 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20170829_1727'),
        ('t2f', '0019_rename_itenerary_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reports.Sector'),
        ),
    ]
