# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-21 16:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0021_auto_20171023_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionpoint',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=254, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='costassignment',
            name='business_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publics.BusinessArea'),
        ),
        migrations.AlterField(
            model_name='costassignment',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='publics.Fund'),
        ),
        migrations.AlterField(
            model_name='costassignment',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='publics.Grant'),
        ),
        migrations.AlterField(
            model_name='costassignment',
            name='wbs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='publics.WBS'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publics.Currency'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publics.TravelExpenseType'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='publics.Fund'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='publics.Grant'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='wbs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='publics.WBS'),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='dsa_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publics.DSARegion'),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='mode_of_travel',
            field=models.CharField(blank=True, choices=[('Plane', 'Plane'), ('Bus', 'Bus'), ('Car', 'Car'), ('Boat', 'Boat'), ('Rail', 'Rail')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='approved_cost_travel_agencies',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='approved_cost_traveler',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='cancellation_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='certification_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publics.Currency'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='first_submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='misc_expenses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='mode_of_travel',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Plane', 'Plane'), ('Bus', 'Bus'), ('Car', 'Car'), ('Boat', 'Boat'), ('Rail', 'Rail')], max_length=5), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='travel',
            name='preserved_expenses_local',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='preserved_expenses_usd',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='report_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelactivity',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelactivity',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.PartnerOrganization'),
        ),
        migrations.AlterField(
            model_name='travelactivity',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_activities', to='partners.Intervention'),
        ),
        migrations.AlterField(
            model_name='travelactivity',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reports.Result'),
        ),
        migrations.AlterField(
            model_name='travelactivity',
            name='travel_type',
            field=models.CharField(blank=True, choices=[('Programmatic Visit', 'Programmatic Visit'), ('Spot Check', 'Spot Check'), ('Advocacy', 'Advocacy'), ('Technical Support', 'Technical Support'), ('Meeting', 'Meeting'), ('Staff Development', 'Staff Development'), ('Staff Entitlement', 'Staff Entitlement')], max_length=64, null=True),
        ),
    ]
