# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-19 16:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models

from utils.common.migrating import fix_null_values


def fix_nulls(apps, schema):
    # Change null values in these fields to empty strings
    fix_null_values(
        apps.get_model('t2f.actionpoint'),
        [
            'actions_taken',
            'comments',
            'status',
        ]
    )
    fix_null_values(
        apps.get_model('t2f.invoice'),
        [
            'vision_fi_id',
        ]
    )
    fix_null_values(
        apps.get_model('t2f.itineraryitem'),
        [
            'mode_of_travel',
        ]
    )
    fix_null_values(
        apps.get_model('t2f.travel'),
        [
            'additional_note',
            'cancellation_note',
            'certification_note',
            'misc_expenses',
            'purpose',
            'rejection_note',
            'report_note',
        ]
    )
    fix_null_values(
        apps.get_model('t2f.travelactivity'),
        [
            'travel_type',
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0022_auto_20171121_1627'),
    ]

    operations = [
        migrations.RunPython(fix_nulls, migrations.RunPython.noop)
    ]
