# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-09 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0022_auto_20171121_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clearances',
            options={'verbose_name_plural': 'Clearances'},
        ),
        migrations.AlterModelOptions(
            name='travelactivity',
            options={'verbose_name_plural': 'Travel Activities'},
        ),
    ]
