# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t2f', '0024_make_not_nullable'),
        ('t2f', '0023_auto_20180309_1210'),
    ]

    operations = [
    ]
