# Generated by Django 3.2.19 on 2024-07-19 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionSyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler_name', models.CharField(max_length=50, verbose_name='Handler Name')),
                ('business_area_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Business Area Code')),
                ('total_records', models.IntegerField(default=0, verbose_name='Total Records')),
                ('total_processed', models.IntegerField(default=0, verbose_name='Total Processed')),
                ('successful', models.BooleanField(default=False, verbose_name='Successful')),
                ('details', models.CharField(blank=True, default='', max_length=2048, verbose_name='Details')),
                ('exception_message', models.TextField(blank=True, default='', verbose_name='Exception Message')),
                ('date_processed', models.DateTimeField(auto_now=True, verbose_name='Date Processed')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.country', verbose_name='Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
