# Generated by Django 4.2.23 on 2025-10-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionsynclog',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Sent Data'),
        ),
    ]
