# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-21 12:33

from django.db import migrations, models

import etools.applications.locations.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_fix_null_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartodbtable',
            name='color',
            field=models.CharField(
                blank=True, default=etools.applications.locations.models.get_random_color, max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='cartodbtable',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='cartodbtable',
            name='parent_code_col',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Parent Code Column'),
        ),
        migrations.AlterField(
            model_name='location',
            name='p_code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='P Code'),
        ),
    ]
