# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-25 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_make_not_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartodbtable',
            name='remap_table_name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Remap Table Name'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        )
    ]
