# Generated by Django 3.2.19 on 2024-06-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='active_pd',
            field=models.ManyToManyField(blank=True, to='partners.Intervention', verbose_name='Active PDs'),
        ),
    ]
