# Generated by Django 3.2.19 on 2024-06-03 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
        ('purchase_order', '0001_initial'),
        ('audit', '0003_engagement_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='authorized_officers',
            field=models.ManyToManyField(blank=True, related_name='engagement_authorizations', to=settings.AUTH_USER_MODEL, verbose_name='Authorized Officers'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='engagements', to='reports.Office', verbose_name='Offices'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partnerorganization', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_order.purchaseorderitem', verbose_name='PO Item Number'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='engagements', to='reports.Section', verbose_name='Sections'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='staff_members',
            field=models.ManyToManyField(related_name='engagements', to=settings.AUTH_USER_MODEL, verbose_name='Staff Members'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='users_notified',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Notified When Completed'),
        ),
        migrations.AddField(
            model_name='specificprocedure',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_procedures', to='audit.specialaudit', verbose_name='Special Audit'),
        ),
        migrations.AddField(
            model_name='specialauditrecommendation',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_recommendations', to='audit.specialaudit', verbose_name='Special Audit'),
        ),
        migrations.AddField(
            model_name='keyinternalcontrol',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_internal_controls', to='audit.audit', verbose_name='Audit'),
        ),
        migrations.AddField(
            model_name='finding',
            name='spot_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audit.spotcheck', verbose_name='Spot Check'),
        ),
        migrations.AddField(
            model_name='financialfinding',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_finding_set', to='audit.audit', verbose_name='Audit'),
        ),
        migrations.AddField(
            model_name='detailedfindinginfo',
            name='micro_assesment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audit.microassessment', verbose_name='Micro Assessment'),
        ),
    ]
