# Generated by Django 3.2.6 on 2022-04-20 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='users_notified',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Notified When Completed'),
        ),
        migrations.AddField(
            model_name='specificprocedure',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_procedures', to='audit.specialaudit', verbose_name='Special Audit'),
        ),
        migrations.AddField(
            model_name='specialauditrecommendation',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_recommendations', to='audit.specialaudit', verbose_name='Special Audit'),
        ),
        migrations.AddField(
            model_name='keyinternalcontrol',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_internal_controls', to='audit.audit', verbose_name='Audit'),
        ),
        migrations.AddField(
            model_name='finding',
            name='spot_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audit.spotcheck', verbose_name='Spot Check'),
        ),
        migrations.AddField(
            model_name='financialfinding',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_finding_set', to='audit.audit', verbose_name='Audit'),
        ),
        migrations.AddField(
            model_name='detailedfindinginfo',
            name='micro_assesment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audit.microassessment', verbose_name='Micro Assessment'),
        ),
    ]
