# Generated by Django 4.2.15 on 2025-07-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSubjectAreas',
            fields=[
            ],
            options={
                'verbose_name': 'Test Subject Areas',
                'verbose_name_plural': 'Test Subject Areas',
                'ordering': ('id',),
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('audit.risk',),
        ),
    ]
