# Generated by Django 4.2.3 on 2025-04-14 12:27

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('commitment_ref', models.CharField(max_length=255, verbose_name='Commitment Reference')),
            ],
            options={
                'verbose_name': 'Face Form',
                'verbose_name_plural': 'Face Forms',
            },
        ),
        migrations.AddField(
            model_name='engagement',
            name='face_forms',
            field=models.ManyToManyField(blank=True, related_name='engagements', to='audit.faceform', verbose_name='Face Forms'),
        ),
    ]
