# Generated by Django 4.2.15 on 2025-07-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_faceform_engagement_face_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='total_value_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total value of selected FACE form(s)'),
        ),
        migrations.AddField(
            model_name='faceform',
            name='dct_amt_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Direct Cash Transfer Amount (local)'),
        ),
        migrations.AddField(
            model_name='faceform',
            name='dct_amt_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Direct Cash Transfer Amount ($)'),
        ),
        migrations.AddField(
            model_name='faceform',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='faceform',
            name='grant_ref',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Grant Reference'),
        ),
        migrations.AddField(
            model_name='faceform',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='faceform',
            name='wbs_element_ex',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='WBS Element Ex'),
        ),
    ]
