# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-10 09:03
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auto_20180410_0837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditPermission',
        ),
    ]
