# Generated by Django 4.2.23 on 2025-08-22 07:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import etools.libraries.djangolib.fields
import model_utils.fields


class Migration(migrations.Migration):

    replaces = [('audit', '0006_engagement_additional_supporting_documentation_provided_local_and_more'), ('audit', '0007_engagement_conducted_by_sai')]

    dependencies = [
        ('audit', '0005_testsubjectareas'),
        ('partners', '0005_alter_agreement_agreement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='additional_supporting_documentation_provided_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Additional Supporting Documentation Provided (local)'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='amount_refunded_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Amount Refunded (local)'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='justification_provided_and_accepted_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Justification Provided and Accepted (local)'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='total_value_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total value of selected FACE form(s) (local)'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='write_off_required_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Impairment (Local)'),
        ),
        migrations.AddField(
            model_name='spotcheck',
            name='total_amount_of_ineligible_expenditure_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Total Amount of Ineligible Expenditure (local)'),
        ),
        migrations.AddField(
            model_name='spotcheck',
            name='total_amount_tested_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Total Amount Tested (local)'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='audited_expenditure_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Audited Expenditure Local Currency'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='financial_findings_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Financial Findings Local Currency'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='additional_supporting_documentation_provided',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Additional Supporting Documentation Provided ($)'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='amount_refunded',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Amount Refunded ($)'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='justification_provided_and_accepted',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Justification Provided and Accepted ($)'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total value of selected FACE form(s) ($)'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='write_off_required',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Impairment ($)'),
        ),
        migrations.AlterField(
            model_name='spotcheck',
            name='total_amount_of_ineligible_expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Total Amount of Ineligible Expenditure ($)'),
        ),
        migrations.AlterField(
            model_name='spotcheck',
            name='total_amount_tested',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Total Amount Tested ($)'),
        ),
        migrations.CreateModel(
            name='SpotCheckFinancialFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('no-supporting-documentation', 'No supporting documentation'), ('insufficient-supporting-documentation', 'Insufficient supporting documentation'), ('cut-off-error', 'Cut-off error'), ('expenditure-not-for-project-purposes', 'Expenditure not for project purposes'), ('no-proof-of-payment', 'No proof of payment'), ('no-proof-of-goods-services-received', 'No proof of goods / services received'), ('vat-incorrectly-claimed', 'VAT incorrectly claimed'), ('dsa-rates-exceeded', 'DSA rates exceeded'), ('unreasonable-price', 'Unreasonable price'), ('bank-interest-not-reported', 'Bank interest not reported'), ('support-costs-incorrectly-calculated', 'Support costs incorrectly calculated'), ('expenditure-claimed-but-activities-not-undertaken', 'Expenditure claimed but activities not undertaken'), ('advance-claimed-as-expenditure', 'Advance claimed as expenditure'), ('commitments-treated-as-expenditure', 'Commitments treated as expenditure'), ('ineligible-salary-costs', 'Ineligible salary costs'), ('ineligible-costs-other', 'Ineligible costs (other)')], max_length=255, verbose_name='Title (Category)')),
                ('local_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount (local)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount (USD)')),
                ('description', models.TextField(verbose_name='Description')),
                ('recommendation', models.TextField(blank=True, verbose_name='Recommendation')),
                ('ip_comments', models.TextField(blank=True, verbose_name='IP Comments')),
                ('spot_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_finding_set', to='audit.spotcheck', verbose_name='SpotCheck')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FaceForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('face_number', models.CharField(max_length=255, verbose_name='Face Form Number')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('date_of_liquidation', models.DateField(blank=True, null=True, verbose_name='Date of Liquidation')),
                ('modality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modality')),
                ('currency', etools.libraries.djangolib.fields.CurrencyField(blank=True, choices=[('GIP', 'GIP'), ('KPW', 'KPW'), ('XEU', 'XEU'), ('BHD', 'BHD'), ('BIF', 'BIF'), ('BMD', 'BMD'), ('BSD', 'BSD'), ('AFN', 'AFN'), ('ALL', 'ALL'), ('AMD', 'AMD'), ('AUD', 'AUD'), ('AZN', 'AZN'), ('BAM', 'BAM'), ('BBD', 'BBD'), ('BDT', 'BDT'), ('BZD', 'BZD'), ('CUP1', 'CUP1'), ('BTN', 'BTN'), ('ZWL', 'ZWL'), ('AWG', 'AWG'), ('CUC', 'CUC'), ('VEF01', 'VEF01'), ('BND', 'BND'), ('BRL', 'BRL'), ('ARS', 'ARS'), ('ETB', 'ETB'), ('EUR', 'EUR'), ('FJD', 'FJD'), ('GBP', 'GBP'), ('GEL', 'GEL'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('GTQ', 'GTQ'), ('GYD', 'GYD'), ('HNL', 'HNL'), ('CAD', 'CAD'), ('CDF', 'CDF'), ('CLP', 'CLP'), ('CNY', 'CNY'), ('COP', 'COP'), ('CRC', 'CRC'), ('CUP', 'CUP'), ('CVE', 'CVE'), ('DJF', 'DJF'), ('DKK', 'DKK'), ('DOP', 'DOP'), ('DZD', 'DZD'), ('EGP', 'EGP'), ('HRK', 'HRK'), ('LVL', 'LVL'), ('LYD', 'LYD'), ('MAD', 'MAD'), ('MGA', 'MGA'), ('MKD', 'MKD'), ('KWD', 'KWD'), ('KYD', 'KYD'), ('LBP', 'LBP'), ('LKR', 'LKR'), ('MDL', 'MDL'), ('KZT', 'KZT'), ('LRD', 'LRD'), ('BOB', 'BOB'), ('HKD', 'HKD'), ('CHF', 'CHF'), ('KES', 'KES'), ('MYR', 'MYR'), ('NGN', 'NGN'), ('KMF', 'KMF'), ('SCR', 'SCR'), ('SEK', 'SEK'), ('TTD', 'TTD'), ('PKR', 'PKR'), ('NIO', 'NIO'), ('RWF', 'RWF'), ('BWP', 'BWP'), ('JMD', 'JMD'), ('TJS', 'TJS'), ('UYU', 'UYU'), ('RON', 'RON'), ('PYG', 'PYG'), ('SYP', 'SYP'), ('LAK', 'LAK'), ('ERN', 'ERN'), ('SLE', 'SLE'), ('PLN', 'PLN'), ('JOD', 'JOD'), ('ILS', 'ILS'), ('AED', 'AED'), ('NPR', 'NPR'), ('NZD', 'NZD'), ('SGD', 'SGD'), ('JPY', 'JPY'), ('PAB', 'PAB'), ('ZMW', 'ZMW'), ('CZK', 'CZK'), ('SOS', 'SOS'), ('LTL', 'LTL'), ('KGS', 'KGS'), ('SHP', 'SHP'), ('BGN', 'BGN'), ('TOP', 'TOP'), ('MVR', 'MVR'), ('VEF02', 'VEF02'), ('TMT', 'TMT'), ('GMD', 'GMD'), ('MZN', 'MZN'), ('RSD', 'RSD'), ('MWK', 'MWK'), ('PGK', 'PGK'), ('MXN', 'MXN'), ('XAF', 'XAF'), ('VND', 'VND'), ('INR', 'INR'), ('NOK', 'NOK'), ('XPF', 'XPF'), ('SSP', 'SSP'), ('IQD', 'IQD'), ('SRD', 'SRD'), ('SAR', 'SAR'), ('XCD', 'XCD'), ('IRR', 'IRR'), ('KPW01', 'KPW01'), ('HTG', 'HTG'), ('IDR', 'IDR'), ('XOF', 'XOF'), ('ISK', 'ISK'), ('ANG', 'ANG'), ('NAD', 'NAD'), ('MMK', 'MMK'), ('STN', 'STN'), ('VUV', 'VUV'), ('LSL', 'LSL'), ('SVC', 'SVC'), ('KHR', 'KHR'), ('SZL', 'SZL'), ('RUB', 'RUB'), ('UAH', 'UAH'), ('UGX', 'UGX'), ('THB', 'THB'), ('AOA', 'AOA'), ('YER', 'YER'), ('USD', 'USD'), ('UZS', 'UZS'), ('OMR', 'OMR'), ('SBD', 'SBD'), ('TZS', 'TZS'), ('SDG', 'SDG'), ('WST', 'WST'), ('QAR', 'QAR'), ('MOP', 'MOP'), ('MRU', 'MRU'), ('VEF', 'VEF'), ('TRY', 'TRY'), ('ZAR', 'ZAR'), ('HUF', 'HUF'), ('MUR', 'MUR'), ('PHP', 'PHP'), ('BYN', 'BYN'), ('KRW', 'KRW'), ('TND', 'TND'), ('MNT', 'MNT'), ('PEN', 'PEN')], default='', max_length=5, null=True, verbose_name='Currency of Report')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount ($)')),
                ('amount_local', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount (local)')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faceforms', to='partners.partnerorganization', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Face Form',
                'verbose_name_plural': 'Face Forms',
            },
        ),
        migrations.AddField(
            model_name='engagement',
            name='face_forms',
            field=models.ManyToManyField(blank=True, related_name='engagements', to='audit.faceform', verbose_name='Face Forms'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='conducted_by_sai',
            field=models.BooleanField(blank=True, null=True, verbose_name='Conducted by SAI'),
        ),
    ]
