# Generated by Django 4.2.15 on 2025-07-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_engagement_total_value_local_faceform_dct_amt_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceform',
            name='grant_ref',
        ),
        migrations.RemoveField(
            model_name='faceform',
            name='wbs_element_ex',
        ),
        migrations.AddField(
            model_name='engagement',
            name='additional_supporting_documentation_provided_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Additional Supporting Documentation Provided (local)'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='amount_refunded_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Amount Refunded (local)'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='justification_provided_and_accepted_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Justification Provided and Accepted (local)'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='write_off_required_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Impairment (Local)'),
        ),
        migrations.AddField(
            model_name='spotcheck',
            name='total_amount_of_ineligible_expenditure_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Total Amount of Ineligible Expenditure (local)'),
        ),
        migrations.AddField(
            model_name='spotcheck',
            name='total_amount_tested_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Total Amount Tested (local)'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='additional_supporting_documentation_provided',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Additional Supporting Documentation Provided ($)'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='amount_refunded',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Amount Refunded ($)'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='justification_provided_and_accepted',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Justification Provided and Accepted ($)'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='write_off_required',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Impairment ($)'),
        ),
        migrations.AlterField(
            model_name='spotcheck',
            name='total_amount_of_ineligible_expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Total Amount of Ineligible Expenditure ($)'),
        ),
        migrations.AlterField(
            model_name='spotcheck',
            name='total_amount_tested',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Total Amount Tested ($)'),
        ),
    ]
