# Generated by Django 4.2.15 on 2025-07-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_remove_faceform_grant_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='audited_expenditure_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Audited Expenditure Local Currency'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='financial_findings_local',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Financial Findings Local Currency'),
        ),
    ]
