# Generated by Django 4.2.23 on 2025-08-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_engagement_additional_supporting_documentation_provided_local_and_more_squashed_0007_engagement_conducted_by_sai'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceform',
            name='face_accounted',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Face Accounted'),
        ),
    ]
