# Generated by Django 4.2.23 on 2025-08-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_faceform_face_accounted'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceform',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Exchange Rate'),
        ),
    ]
