# Generated by Django 4.2.15 on 2025-07-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_alter_audit_audited_expenditure_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total value of selected FACE form(s) ($)'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='total_value_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total value of selected FACE form(s) (local)'),
        ),
    ]
