# Generated by Django 4.2.15 on 2025-07-22 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_alter_engagement_total_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotCheckFinancialFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('no-supporting-documentation', 'No supporting documentation'), ('insufficient-supporting-documentation', 'Insufficient supporting documentation'), ('cut-off-error', 'Cut-off error'), ('expenditure-not-for-project-purposes', 'Expenditure not for project purposes'), ('no-proof-of-payment', 'No proof of payment'), ('no-proof-of-goods-services-received', 'No proof of goods / services received'), ('vat-incorrectly-claimed', 'VAT incorrectly claimed'), ('dsa-rates-exceeded', 'DSA rates exceeded'), ('unreasonable-price', 'Unreasonable price'), ('bank-interest-not-reported', 'Bank interest not reported'), ('support-costs-incorrectly-calculated', 'Support costs incorrectly calculated'), ('expenditure-claimed-but-activities-not-undertaken', 'Expenditure claimed but activities not undertaken'), ('advance-claimed-as-expenditure', 'Advance claimed as expenditure'), ('commitments-treated-as-expenditure', 'Commitments treated as expenditure'), ('ineligible-salary-costs', 'Ineligible salary costs'), ('ineligible-costs-other', 'Ineligible costs (other)')], max_length=255, verbose_name='Title (Category)')),
                ('local_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount (local)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount (USD)')),
                ('description', models.TextField(verbose_name='Description')),
                ('recommendation', models.TextField(blank=True, verbose_name='Recommendation')),
                ('ip_comments', models.TextField(blank=True, verbose_name='IP Comments')),
                ('spot_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_finding_set', to='audit.spotcheck', verbose_name='SpotCheck')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
