# Generated by Django 2.1.4 on 2019-01-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_auto_20181229_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='joint_audit',
            field=models.BooleanField(blank=True, default=False, verbose_name='Joint Audit'),
        ),
    ]
