# Generated by Django 2.1.5 on 2019-03-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0013_auto_20190102_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyinternalcontrol',
            name='audit_observation',
            field=models.TextField(verbose_name='Audit Observation'),
        ),
        migrations.AlterField(
            model_name='keyinternalcontrol',
            name='ip_response',
            field=models.TextField(verbose_name='IP response'),
        ),
        migrations.AlterField(
            model_name='keyinternalcontrol',
            name='recommendation',
            field=models.TextField(verbose_name='Recommendation'),
        ),
        migrations.AlterField(
            model_name='riskblueprint',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='riskcategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
