# Generated by Django 2.1.8 on 2019-05-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0016_auto_20190328_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='active_pd',
            field=models.ManyToManyField(blank=True, to='partners.Intervention', verbose_name='Active PDs'),
        ),
    ]
