# Generated by Django 2.2.1 on 2019-06-20 12:45

from django.db import migrations, models


def set_reference_number(apps, schema_editor):
    Engagement = apps.get_model("audit", "engagement")
    for engagement in Engagement.objects.all():
        engagement.save()


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0017_auto_20190501_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='reference_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Reference Number'),
        ),
        migrations.RunPython(set_reference_number),
    ]
