# Generated by Django 2.2.7 on 2019-11-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_auto_20191122_1559'),
        ('audit', '0019_engagement_users_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='engagements', to='reports.Office', verbose_name='Offices'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='engagements', to='reports.Section', verbose_name='Sections'),
        ),
    ]
