# Generated by Django 2.2.7 on 2019-11-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190513_1804'),
        ('reports', '0019_auto_20190816_1609'),
        ('audit', '0019_engagement_users_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotcheck',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Office', verbose_name='Office'),
        ),
        migrations.AddField(
            model_name='spotcheck',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='spot_checks', to='reports.Section', verbose_name='Sections'),
        ),
    ]
