# Generated by Django 2.2.7 on 2019-11-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_auto_20190816_1609'),
        ('audit', '0019_engagement_users_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotcheck',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='spot_checks', to='reports.Office', verbose_name='Offices'),
        ),
        migrations.AddField(
            model_name='spotcheck',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='spot_checks', to='reports.Section', verbose_name='Sections'),
        ),
    ]
