# Generated by Django 2.2.3 on 2019-08-14 12:17

from django.db import connection, migrations, models


def set_reference_number(apps, schema_editor):
    Country = apps.get_model("users", "country")
    Engagement = apps.get_model("audit", "engagement")
    country = Country.objects.get(
        schema_name=connection.tenant.schema_name,
    )
    for engagement in Engagement.objects.all():
        if engagement.engagement_type == 'audit':
            engagement_code = 'a'
        else:
            engagement_code = engagement.engagement_type
        engagement.reference_number = '{}/{}/{}/{}/{}'.format(
            country.country_short_code,
            engagement.partner.name[:5],
            engagement_code.upper(),
            engagement.created.year,
            engagement.pk
        )
        engagement.save()


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0021_auto_20200729_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='reference_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Reference Number'),
        ),
        migrations.RunPython(set_reference_number, migrations.RunPython.noop),
    ]
