# Generated by Django 3.2.6 on 2022-04-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0022_engagement_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Exchange Rate'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total value of selected FACE form(s)'),
        ),
    ]
