# Generated by Django 3.2.6 on 2023-04-14 07:53

from django.db import migrations, models
from django.db.models import F, Subquery, OuterRef
from django.db.models.functions import Extract
from django.utils import timezone

import etools.applications.audit.models


def fill_year_of_audit(apps, schema_editor):
    Audit = apps.get_model('audit', 'Audit')
    Audit.objects.filter(
        end_date__isnull=False
    ).update(
        year_of_audit=Subquery(
            Audit.objects.filter(
                pk=OuterRef('pk')
            ).annotate(
                end_year=Extract("end_date", "year")
            ).values('end_year')[:1]
        )
    )
    Audit.objects.filter(end_date__isnull=True).update(year_of_audit=timezone.now().year)


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0023_auto_20220415_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='year_of_audit',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(fill_year_of_audit, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='audit',
            name='year_of_audit',
            field=models.PositiveSmallIntegerField(default=etools.applications.audit.models.get_current_year),
        ),
    ]
