# Generated by Django 3.2.6 on 2023-04-14 07:53

from django.db import migrations, models
from django.db.models import F, Subquery, OuterRef
from django.db.models.functions import Extract
from django.utils import timezone

import etools.applications.audit.models


def fill_year_of_audit(apps, schema_editor):
    Engagement = apps.get_model('audit', 'Engagement')
    Engagement.objects.filter(
        engagement_type='audit',
        end_date__isnull=False,
    ).update(
        year_of_audit=Subquery(
            Engagement.objects.filter(
                pk=OuterRef('pk')
            ).annotate(
                end_year=Extract("end_date", "year")
            ).values('end_year')[:1]
        )
    )
    Engagement.objects.filter(engagement_type='audit', end_date__isnull=True).update(year_of_audit=timezone.now().year)


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0023_auto_20220415_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='year_of_audit',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
        migrations.RunPython(fill_year_of_audit, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='engagement',
            name='year_of_audit',
            field=models.PositiveSmallIntegerField(default=etools.applications.audit.models.get_current_year, null=True),
        ),
    ]
