# Generated by Django 3.2.6 on 2023-05-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0025_alter_engagement_year_of_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='microassessment',
            name='questionnaire_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='microassessment',
            name='questionnaire_version',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
