# Generated by Django 3.2.6 on 2023-05-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0026_microassessment_questionnaire_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskcategory',
            name='header',
            field=models.CharField(max_length=500, verbose_name='Header'),
        ),
    ]
