# Generated by Django 3.2.6 on 2023-05-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0027_engagement_staff_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='microassessment',
            name='questionnaire_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='microassessment',
            name='questionnaire_version',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='riskcategory',
            name='header',
            field=models.CharField(max_length=500, verbose_name='Header'),
        ),
    ]
