# Generated by Django 3.2.6 on 2023-05-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0028_audit_year_of_audit_recalculate'),
        ('audit', '0028_auto_20230515_0551'),
    ]

    operations = [
    ]
