# Generated by Django 3.2.19 on 2024-06-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0031_auto_20240507_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date of last reporting FACE'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date of first reporting FACE'),
        ),
    ]
