# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-05 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionsynclog',
            name='details',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
