# Generated by Django 4.2.26 on 2026-03-17 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('object_id', models.CharField(max_length=255, verbose_name='Object ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('SOFT_DELETE', 'Soft Deleted')], max_length=20, verbose_name='Action')),
                ('changed_fields', models.JSONField(blank=True, help_text='List of field names that were changed', null=True, verbose_name='Changed Fields')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Previous Values')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='New Values')),
                ('description', models.TextField(blank=True, default='', help_text='Optional human-readable description of the change', verbose_name='Description')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='audit_log_a_content_f92223_idx'), models.Index(fields=['content_type', 'object_id', '-created'], name='audit_log_a_content_30006a_idx'), models.Index(fields=['action'], name='audit_log_a_action_77d9ba_idx'), models.Index(fields=['user'], name='audit_log_a_user_id_e7ad88_idx'), models.Index(fields=['created'], name='audit_log_a_created_ca8442_idx')],
            },
        ),
    ]
