# Generated by Django 2.0.9 on 2019-01-04 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_settings', '0002_auto_20181122_1525'),
        ('locations', '0004_pcode_remap_related'),
        ('field_monitoring_visits', '0002_auto_20190104_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='locations.Location', verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='location_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='field_monitoring_settings.LocationSite', verbose_name='Site'),
        ),
    ]
