# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-29 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_visits', '0002_visitmethodtype_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitmethodtype',
            name='cp_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_method_types', to='reports.Result', verbose_name='CP Output'),
        ),
    ]
