# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-29 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_shared', '0001_initial'),
        ('field_monitoring_visits', '0003_auto_20181129_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='methods',
            field=models.ManyToManyField(blank=True, to='field_monitoring_shared.FMMethod'),
        ),
    ]
