# Generated by Django 2.2.1 on 2019-07-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_data_collection', '0003_auto_20190710_1424'),
        ('field_monitoring_visits', '0005_auto_20190218_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='author',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='location',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='location_site',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='primary_field_monitor',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='visitcpoutputconfig',
            name='government_partners',
        ),
        migrations.RemoveField(
            model_name='visitcpoutputconfig',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='visitcpoutputconfig',
            name='recommended_method_types',
        ),
        migrations.RemoveField(
            model_name='visitcpoutputconfig',
            name='visit_task',
        ),
        migrations.RemoveField(
            model_name='visitmethodtype',
            name='method',
        ),
        migrations.RemoveField(
            model_name='visitmethodtype',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='visittasklink',
            name='task',
        ),
        migrations.RemoveField(
            model_name='visittasklink',
            name='visit',
        ),
        migrations.DeleteModel(
            name='TaskCheckListItem',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
        migrations.DeleteModel(
            name='VisitCPOutputConfig',
        ),
        migrations.DeleteModel(
            name='VisitMethodType',
        ),
        migrations.DeleteModel(
            name='VisitTaskLink',
        ),
    ]
