# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-03 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_visits', '0005_auto_20181130_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='methods',
        ),
    ]
