# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-03 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_visits', '0006_remove_visit_methods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitcpoutputconfig',
            name='visit',
        ),
        migrations.AddField(
            model_name='visitcpoutputconfig',
            name='visit_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cp_output_configs', to='field_monitoring_visits.VisitTaskLink', verbose_name='Visit Task'),
            preserve_default=False,
        ),
    ]
