# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-04 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_visits', '0007_auto_20181203_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskchecklistitem',
            options={'ordering': ('visit_task', 'order'), 'verbose_name': 'Task Checklist Item', 'verbose_name_plural': 'Task Checklist Items'},
        ),
        migrations.AlterModelOptions(
            name='unicefvisit',
            options={'ordering': ('id',), 'verbose_name': 'UNICEF Visit', 'verbose_name_plural': 'UNICEF Visits'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('id',), 'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
        migrations.AlterModelOptions(
            name='visitcpoutputconfig',
            options={'ordering': ('id',), 'verbose_name': 'Visit CPOutput Config', 'verbose_name_plural': 'Visit CPOutput Configs'},
        ),
        migrations.AlterModelOptions(
            name='visitmethodtype',
            options={'ordering': ('id',), 'verbose_name': 'Visit Method Type', 'verbose_name_plural': 'Visit Method Types'},
        ),
    ]
