# Generated by Django 2.0.9 on 2018-12-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring_visits', '0008_auto_20181204_1044'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='unicefvisit',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='taskchecklistitem',
            name='visit_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='field_monitoring_visits.VisitTaskLink', verbose_name='Task Link'),
        ),
    ]
