# Generated by Django 2.2.20 on 2021-07-09 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
from django.utils.timezone import utc
import django.utils.timezone
import django_fsm
import model_utils.fields
import unicef_djangolib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0086_intervention_accepted_on_behalf_of_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EFaceForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='Deleted At')),
                ('reference_number_year', models.IntegerField()),
                ('reference_number', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Reference Number')),
                ('title', models.CharField(max_length=255)),
                ('currency', unicef_djangolib.fields.CurrencyField(blank=True, choices=[('GIP', 'GIP'), ('KPW', 'KPW'), ('XEU', 'XEU'), ('BHD', 'BHD'), ('BIF', 'BIF'), ('BMD', 'BMD'), ('BSD', 'BSD'), ('AFN', 'AFN'), ('ALL', 'ALL'), ('AMD', 'AMD'), ('AUD', 'AUD'), ('AZN', 'AZN'), ('BAM', 'BAM'), ('BBD', 'BBD'), ('BDT', 'BDT'), ('BZD', 'BZD'), ('CUP1', 'CUP1'), ('BTN', 'BTN'), ('ZWL', 'ZWL'), ('AWG', 'AWG'), ('CUC', 'CUC'), ('VEF01', 'VEF01'), ('BND', 'BND'), ('BRL', 'BRL'), ('ARS', 'ARS'), ('ETB', 'ETB'), ('EUR', 'EUR'), ('FJD', 'FJD'), ('GBP', 'GBP'), ('GEL', 'GEL'), ('GHS', 'GHS'), ('GNF', 'GNF'), ('GTQ', 'GTQ'), ('GYD', 'GYD'), ('HNL', 'HNL'), ('CAD', 'CAD'), ('CDF', 'CDF'), ('CLP', 'CLP'), ('CNY', 'CNY'), ('COP', 'COP'), ('CRC', 'CRC'), ('CUP', 'CUP'), ('CVE', 'CVE'), ('DJF', 'DJF'), ('DKK', 'DKK'), ('DOP', 'DOP'), ('DZD', 'DZD'), ('EGP', 'EGP'), ('HRK', 'HRK'), ('LVL', 'LVL'), ('LYD', 'LYD'), ('MAD', 'MAD'), ('MGA', 'MGA'), ('MKD', 'MKD'), ('KWD', 'KWD'), ('KYD', 'KYD'), ('LBP', 'LBP'), ('LKR', 'LKR'), ('MDL', 'MDL'), ('KZT', 'KZT'), ('LRD', 'LRD'), ('BOB', 'BOB'), ('HKD', 'HKD'), ('CHF', 'CHF'), ('KES', 'KES'), ('MYR', 'MYR'), ('NGN', 'NGN'), ('KMF', 'KMF'), ('SCR', 'SCR'), ('SEK', 'SEK'), ('TTD', 'TTD'), ('PKR', 'PKR'), ('NIO', 'NIO'), ('RWF', 'RWF'), ('BWP', 'BWP'), ('JMD', 'JMD'), ('TJS', 'TJS'), ('UYU', 'UYU'), ('RON', 'RON'), ('PYG', 'PYG'), ('SYP', 'SYP'), ('LAK', 'LAK'), ('ERN', 'ERN'), ('SLL', 'SLL'), ('PLN', 'PLN'), ('JOD', 'JOD'), ('ILS', 'ILS'), ('AED', 'AED'), ('NPR', 'NPR'), ('NZD', 'NZD'), ('SGD', 'SGD'), ('JPY', 'JPY'), ('PAB', 'PAB'), ('ZMW', 'ZMW'), ('CZK', 'CZK'), ('SOS', 'SOS'), ('LTL', 'LTL'), ('KGS', 'KGS'), ('SHP', 'SHP'), ('BGN', 'BGN'), ('TOP', 'TOP'), ('MVR', 'MVR'), ('VEF02', 'VEF02'), ('TMT', 'TMT'), ('GMD', 'GMD'), ('MZN', 'MZN'), ('RSD', 'RSD'), ('MWK', 'MWK'), ('PGK', 'PGK'), ('MXN', 'MXN'), ('XAF', 'XAF'), ('VND', 'VND'), ('INR', 'INR'), ('NOK', 'NOK'), ('XPF', 'XPF'), ('SSP', 'SSP'), ('IQD', 'IQD'), ('SRD', 'SRD'), ('SAR', 'SAR'), ('XCD', 'XCD'), ('IRR', 'IRR'), ('KPW01', 'KPW01'), ('HTG', 'HTG'), ('IDR', 'IDR'), ('XOF', 'XOF'), ('ISK', 'ISK'), ('ANG', 'ANG'), ('NAD', 'NAD'), ('MMK', 'MMK'), ('STD', 'STD'), ('VUV', 'VUV'), ('LSL', 'LSL'), ('SVC', 'SVC'), ('KHR', 'KHR'), ('SZL', 'SZL'), ('RUB', 'RUB'), ('UAH', 'UAH'), ('UGX', 'UGX'), ('THB', 'THB'), ('AOA', 'AOA'), ('YER', 'YER'), ('USD', 'USD'), ('UZS', 'UZS'), ('OMR', 'OMR'), ('SBD', 'SBD'), ('TZS', 'TZS'), ('SDG', 'SDG'), ('WST', 'WST'), ('QAR', 'QAR'), ('MOP', 'MOP'), ('MRU', 'MRU'), ('VEF', 'VEF'), ('TRY', 'TRY'), ('ZAR', 'ZAR'), ('HUF', 'HUF'), ('MUR', 'MUR'), ('PHP', 'PHP'), ('BYN', 'BYN'), ('KRW', 'KRW'), ('TND', 'TND'), ('MNT', 'MNT'), ('PEN', 'PEN')], default='', max_length=5, verbose_name='Currency')),
                ('request_type', models.CharField(choices=[('dct', 'Direct Cash Transfer'), ('rmb', 'Reimbursement'), ('dp', 'Direct Payment')], max_length=3)),
                ('request_represents_expenditures', models.BooleanField(default=False)),
                ('expenditures_disbursed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('authorized_amount_date', models.DateField(blank=True, null=True)),
                ('requested_amount_date', models.DateField(blank=True, null=True)),
                ('status', django_fsm.FSMField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('unicef_approved', 'UNICEF Approved'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('date_submitted', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when={'b', 's', 'e', 't', 'u', 'd', 'm', 'i'})),
                ('date_unicef_approved', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when={'e', 'p', '_', 'o', 'c', 'u', 'd', 'a', 'v', 'f', 'i', 'n', 'r'})),
                ('date_transaction_rejected', models.DateField(blank=True, null=True)),
                ('date_finalized', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when={'e', 'z', 'd', 'a', 'f', 'i', 'n', 'l'})),
                ('date_cancelled', model_utils.fields.MonitorField(blank=True, default=django.utils.timezone.now, monitor='status', null=True, when={'e', 'a', 'n', 'c', 'l', 'd'})),
                ('rejection_reason', models.TextField(blank=True)),
                ('transaction_rejection_reason', models.TextField(blank=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.Intervention', verbose_name='Intervention')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FormActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('coding', models.CharField(blank=True, max_length=100)),
                ('reporting_authorized_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Reporting - Authorized Amount')),
                ('reporting_actual_project_expenditure', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Reporting - Actual Project Expenditure')),
                ('reporting_expenditures_accepted_by_agency', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Reporting - Expenditures Accepted by Agency')),
                ('reporting_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Reporting - Balance')),
                ('requested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Requests - Amount')),
                ('requested_authorized_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Requests - Authorized Amount')),
                ('requested_outstanding_authorized_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Requests Outstanding Authorized Amount')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eface.EFaceForm')),
            ],
        ),
    ]
