# Generated by Django 2.2.20 on 2021-07-14 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eface', '0003_auto_20210712_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efaceform',
            name='currency',
        ),
        migrations.AddField(
            model_name='efaceform',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='efaceform',
            name='submitted_by_unicef_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formactivity',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='eface.EFaceForm'),
        ),
    ]
