# Generated by Django 2.2.20 on 2021-07-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eface', '0004_auto_20210714_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='efaceform',
            old_name='authorized_amount_date',
            new_name='authorized_amount_date_start',
        ),
        migrations.RenameField(
            model_name='efaceform',
            old_name='requested_amount_date',
            new_name='requested_amount_date_start',
        ),
        migrations.AddField(
            model_name='efaceform',
            name='authorized_amount_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='efaceform',
            name='reporting_actual_project_expenditure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Reporting - Actual Project Expenditure'),
        ),
        migrations.AddField(
            model_name='efaceform',
            name='reporting_authorized_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Reporting - Authorized Amount'),
        ),
        migrations.AddField(
            model_name='efaceform',
            name='reporting_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Reporting - Balance'),
        ),
        migrations.AddField(
            model_name='efaceform',
            name='reporting_expenditures_accepted_by_agency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Reporting - Expenditures Accepted by Agency'),
        ),
        migrations.AddField(
            model_name='efaceform',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Requests - Amount'),
        ),
        migrations.AddField(
            model_name='efaceform',
            name='requested_amount_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='efaceform',
            name='requested_authorized_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Requests - Authorized Amount'),
        ),
        migrations.AddField(
            model_name='efaceform',
            name='requested_outstanding_authorized_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Requests Outstanding Authorized Amount'),
        ),
    ]
