# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-11 11:35
from __future__ import unicode_literals

from django.db import migrations


def create_email_template(apps, schema_editor):
    EmailTemplate = apps.get_model('post_office', 'EmailTemplate')

    EmailTemplate.objects.get_or_create(name='organisations/staff_member/invite')
    EmailTemplate.objects.filter(name='organisations/staff_member/set_password').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
        ('post_office', '0004_auto_20160607_0901'),
    ]

    operations = [
        migrations.RunPython(create_email_template, migrations.RunPython.noop)
    ]
