# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-07 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('vendor_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='vendor number')),
                ('name', models.CharField(max_length=255, verbose_name='vendor name')),
                ('street_address', models.CharField(blank=True, max_length=500L, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=255L, null=True, verbose_name='city')),
                ('postal_code', models.CharField(blank=True, max_length=32L, null=True, verbose_name='postal code')),
                ('country', models.CharField(blank=True, max_length=255L, null=True, verbose_name='country')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=32L, null=True, verbose_name='phone number')),
                ('blocked', models.BooleanField(default=False, verbose_name='blocked')),
                ('hidden', models.BooleanField(default=False, verbose_name='hidden')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='AuditOrganizationStaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='audit.AuditOrganization', verbose_name='organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_auditorganizationstaffmember', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'staff member',
                'verbose_name_plural': 'staff members',
            },
        ),
    ]
