# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-26 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_order', '0001_initial'),
        ('audit', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='active_pd',
            field=models.ManyToManyField(to='partners.Intervention', verbose_name='Active PDs'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_order.PurchaseOrder', verbose_name='Purchase Order'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='authorized_officers',
            field=models.ManyToManyField(blank=True, related_name='engagement_authorizations', to='partners.PartnerStaffMember', verbose_name='Authorized Officers'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.PartnerOrganization', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='po_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_order.PurchaseOrderItem', verbose_name='PO Item Number'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='staff_members',
            field=models.ManyToManyField(to='purchase_order.AuditorStaffMember', verbose_name='Staff Members'),
        ),
        migrations.AlterUniqueTogether(
            name='auditpermission',
            unique_together=set([('user_type', 'instance_status', 'target', 'permission_type')]),
        ),
        migrations.AddField(
            model_name='specificprocedure',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_procedures', to='audit.SpecialAudit', verbose_name='Special Audit'),
        ),
        migrations.AddField(
            model_name='specialauditrecommendation',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_recommendations', to='audit.SpecialAudit', verbose_name='Special Audit'),
        ),
        migrations.AlterUniqueTogether(
            name='risk',
            unique_together=set([('engagement', 'blueprint')]),
        ),
        migrations.AddField(
            model_name='keyinternalcontrol',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_internal_controls', to='audit.Audit', verbose_name='Audit'),
        ),
        migrations.AddField(
            model_name='finding',
            name='spot_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audit.SpotCheck', verbose_name='Spot Check'),
        ),
        migrations.AddField(
            model_name='financialfinding',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_finding_set', to='audit.Audit', verbose_name='Audit'),
        ),
        migrations.AddField(
            model_name='detailedfindinginfo',
            name='micro_assesment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audit.MicroAssessment', verbose_name='Micro Assessment'),
        ),
    ]
