# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-20 13:34
from __future__ import unicode_literals

from django.db import migrations


def create_email_template(apps, schema_editor):
    EmailTemplate = apps.get_model('post_office', 'EmailTemplate')

    EmailTemplate.objects.get_or_create(name='audit/engagement/submit_to_auditor')
    EmailTemplate.objects.get_or_create(name='audit/engagement/reported_by_auditor')
    EmailTemplate.objects.get_or_create(name='audit/staff_member/appointed_to_engagement')


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('post_office', '0004_auto_20160607_0901'),
    ]

    operations = [
        migrations.RunPython(create_email_template, do_nothing),
    ]
