# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-30 06:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20170622_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='percent_of_audited_expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='% of audited expenditure'),
        ),
    ]
