# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-27 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20170622_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contract Expiry Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='PO Date'),
        ),
    ]
