# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-06 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20180330_0818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditPermission',
        ),
    ]
