# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-21 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_fix_null_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='audit_opinion',
            field=models.CharField(blank=True, choices=[('unqualified', 'Unqualified'), ('qualified', 'Qualified'), ('disclaimer_opinion', 'Disclaimer opinion'), ('adverse_opinion', 'Adverse opinion')], default='', max_length=20, verbose_name='Audit Opinion'),
        ),
    ]
