# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-14 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0030_intervention_signed_pd_document'),
        ('audit', '0005_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='authorized_officers',
            field=models.ManyToManyField(blank=True, related_name='engagement_authorizations', to='partners.PartnerStaffMember'),
        ),
    ]
