# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-24 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='date_of_cancel',
            field=models.DateField(blank=True, null=True, verbose_name='date report cancelled'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='status',
            field=django_fsm.FSMField(choices=[('partner_contacted', 'Partner Contacted'), ('report_submitted', 'Report Submitted'), ('final', 'Final Report'), ('canceled', 'Cancelled')], default='partner_contacted', max_length=30, protected=True, verbose_name='status'),
        ),
    ]
