# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-07 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0046_auto_20170714_1844'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0005_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementActionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('Invoice and receive reimbursement of ineligible expenditure', 'Invoice and receive reimbursement of ineligible expenditure'), ('Change cash transfer modality (DCT, reimbursement or direct payment)', 'Change cash transfer modality (DCT, reimbursement or direct payment)'), ('IP to incur and report on additional expenditure', 'IP to incur and report on additional expenditure'), ('Review and amend ICE or budget', 'Review and amend ICE or budget'), ('IP to correct FACE form or Statement of Expenditure', 'IP to correct FACE form or Statement of Expenditure'), ('Schedule a programmatic visit', 'Schedule a programmatic visit'), ('Schedule a follow-up spot check', 'Schedule a follow-up spot check'), ('Schedule an audit', 'Schedule an audit'), ('Block future cash transfers', 'Block future cash transfers'), ('Block or mark vendor for deletion', 'Block or mark vendor for deletion'), ('Escalate to Chief of Operations, Dep Rep, or Rep', 'Escalate to Chief of Operations, Dep Rep, or Rep'), ('Escalate to Investigation', 'Escalate to Investigation'), ('Capacity building / Discussion with partner', 'Capacity building / Discussion with partner'), ('Other', 'Other')], max_length=100)),
                ('due_date', models.DateField()),
                ('comments', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_engagement_action_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='riskcategory',
            old_name='type',
            new_name='category_type',
        ),
        migrations.RenameField(
            model_name='engagement',
            old_name='type',
            new_name='engagement_type'
        ),
        migrations.RemoveField(
            model_name='audit',
            name='high_risk',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='low_risk',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='medium_risk',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='number_of_financial_findings',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='pending_unsupported_amount',
        ),
        migrations.AddField(
            model_name='engagement',
            name='authorized_officers',
            field=models.ManyToManyField(blank=True, related_name='engagement_authorizations', to='partners.PartnerStaffMember'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='engagement_type',
            field=models.CharField(choices=[('audit', 'Audit'), ('ma', 'Micro Accessment'), ('sc', 'Spot Check')], max_length=10, verbose_name='Engagement type'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='audited_expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Audited expenditure (USD)'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='financial_findings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Financial findings (USD)'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='additional_supporting_documentation_provided',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='additional supporting documentation provided'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='amount_refunded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='amount refunded'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='date_of_cancel',
            field=models.DateField(blank=True, null=True, verbose_name='date report cancelled'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='justification_provided_and_accepted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='justification provided and accepted'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='status',
            field=django_fsm.FSMField(choices=[('partner_contacted', 'Partner Contacted'), ('report_submitted', 'Report Submitted'), ('final', 'Final Report'), ('cancelled', 'Cancelled')], default='partner_contacted', max_length=30, protected=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='write_off_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='write off required'),
        ),
        migrations.AlterField(
            model_name='financialfinding',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount (USD)'),
        ),
        migrations.AlterField(
            model_name='financialfinding',
            name='local_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount (local)'),
        ),
        migrations.AlterField(
            model_name='spotcheck',
            name='total_amount_of_ineligible_expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total amount of ineligible expenditure'),
        ),
        migrations.AlterField(
            model_name='spotcheck',
            name='total_amount_tested',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total amount tested'),
        ),
        migrations.AddField(
            model_name='engagementactionpoint',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_points', to='audit.Engagement'),
        ),
        migrations.AddField(
            model_name='engagementactionpoint',
            name='person_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_action_points', to=settings.AUTH_USER_MODEL),
        ),
    ]
