# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-17 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='high_risk',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='low_risk',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='medium_risk',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='number_of_financial_findings',
        ),
    ]
