# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_delete_auditpermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='risk',
            unique_together=set([]),
        ),
    ]
