# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-07 11:58
from __future__ import unicode_literals

from django.db import migrations


def create_email_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('post_office', 'EmailTemplate')
    EmailTemplate.objects.get_or_create(name='audit/engagement/action_point_assigned')


def migrate_cancelled_status(apps, schema_editor):
    Engagement = apps.get_model('audit', 'Engagement')
    Engagement.objects.filter(status='canceled').update(status='cancelled')


def revert_migrate_cancelled_status(apps, schema_editor):
    Engagement = apps.get_model('audit', 'Engagement')
    Engagement.objects.filter(status='cancelled').update(status='canceled')


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auto_20170807_1156'),
    ]

    operations = [
        migrations.RunPython(create_email_templates, migrations.RunPython.noop),
        migrations.RunPython(migrate_cancelled_status, revert_migrate_cancelled_status),
    ]
