# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-19 10:01
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings

import django.db.models.deletion


def create_email_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('post_office', 'EmailTemplate')
    EmailTemplate.objects.get_or_create(name='audit/engagement/action_point_assigned')


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_engagementactionpoint'),
        ('post_office', '0004_auto_20160607_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementactionpoint',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_engagement_action_points', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engagementactionpoint',
            name='person_responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_action_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            create_email_templates,
            do_nothing,
        ),
    ]
