# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-14 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_financialfinding_finding_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financialfinding',
            unique_together=set([('audit', 'finding_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='finding',
            unique_together=set([('spot_check', 'finding_number')]),
        ),
    ]
