# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-01 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_auto_20170807_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorfirm',
            name='deleted_flag',
            field=models.BooleanField(default=False, verbose_name=b'Marked for deletion'),
        ),
        migrations.AddField(
            model_name='auditorfirm',
            name='vision_synced',
            field=models.BooleanField(default=False),
        ),
    ]
