# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-21 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_auto_20170719_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='pending_unsupported_amount',
        ),
    ]
