# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-22 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_auto_20170901_1536'),
        ('audit', '0008_auto_20170921_1045'),
    ]

    operations = [
    ]
