# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-24 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auto_20170717_1247'),
        ('audit', '0006_auto_20170724_0748'),
        ('audit', '0006_auto_20170720_0915'),
        ('audit', '0006_engagement_authorized_officers'),
        ('audit', '0008_remove_engagement_pending_unsupported_amount'),
        ('audit', '0007_auto_20170714_1318'),
    ]

    operations = [
    ]
