# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-28 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_merge'),
        ('audit', '0009_purchaseorder_item_number'),
    ]

    operations = [
    ]
