# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-02 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_purchaseorder_item_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='date_of_cancel',
            field=models.DateField(blank=True, null=True, verbose_name='Date report cancelled'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='date_of_comments_by_ip',
            field=models.DateField(blank=True, null=True, verbose_name='Date comments received from IP'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='date_of_comments_by_unicef',
            field=models.DateField(blank=True, null=True, verbose_name='Date comments received from UNICEF'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='date_of_draft_report_to_ip',
            field=models.DateField(blank=True, null=True, verbose_name='Date draft report issued to IP'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='date_of_draft_report_to_unicef',
            field=models.DateField(blank=True, null=True, verbose_name='Date draft report issued to UNICEF'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='date_of_field_visit',
            field=models.DateField(blank=True, null=True, verbose_name='Date of field visit'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='date_of_final_report',
            field=models.DateField(blank=True, null=True, verbose_name='Date report finalized'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='date_of_report_submit',
            field=models.DateField(blank=True, null=True, verbose_name='Date report submitted'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='partner_contacted_at',
            field=models.DateField(blank=True, null=True, verbose_name='Date IP was contacted'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='status',
            field=django_fsm.FSMField(choices=[('partner_contacted', 'IP Contacted'), ('report_submitted', 'Report Submitted'), ('final', 'Final Report'), ('cancelled', 'Cancelled')], default='partner_contacted', max_length=30, protected=True, verbose_name='status'),
        ),
    ]
