# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-16 10:03
from __future__ import unicode_literals

import json

from django.db import migrations
from django.utils import six


def unwrap_risks_extra(apps, schema_editor):
    Risk = apps.get_model('audit', 'Risk')
    for risk in Risk.objects.filter(extra__isnull=False):
        if not isinstance(risk.extra, six.string_types):
            continue

        risk.extra = json.loads(risk.extra)
        risk.save()


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_auto_20171002_1347'),
    ]

    operations = [
        migrations.RunPython(unwrap_risks_extra, migrations.RunPython.noop)
    ]
