# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-08-04 10:46
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


def migrate_cancelled_status(apps, schema_editor):
    Engagement = apps.get_model('audit', 'Engagement')
    Engagement.objects.filter(status='canceled').update(status='cancelled')


def revert_migrate_cancelled_status(apps, schema_editor):
    Engagement = apps.get_model('audit', 'Engagement')
    Engagement.objects.filter(status='cancelled').update(status='canceled')


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_auto_20170804_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='status',
            field=django_fsm.FSMField(choices=[('partner_contacted', 'Partner Contacted'), ('report_submitted', 'Report Submitted'), ('final', 'Final Report'), ('cancelled', 'Cancelled')], default='partner_contacted', max_length=30, protected=True, verbose_name='status'),
        ),
        migrations.RunPython(
            migrate_cancelled_status,
            revert_migrate_cancelled_status
        )
    ]
