# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-19 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_auto_20171017_0947'),
        ('audit', '0012_auto_20171017_1239'),
    ]

    operations = [
    ]
