# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-10-20 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0014_auto_20171020_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificprocedure',
            name='finding',
            field=models.TextField(blank=True),
        ),
    ]
