# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-16 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0018_auto_20171113_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='basis_for_risk_rating',
            field=models.BooleanField(default=False, verbose_name='Basic for Risk Rating'),
        ),
    ]
