# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-12-14 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0018_auto_20171113_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='write_off_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Impairment'),
        ),
    ]
