# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-19 08:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


def migrate_shared_ip_with(apps, schema_editor):
    Engagement = apps.get_model('audit', 'engagement')
    for engagement in Engagement.objects.exclude(shared_ip_with1=''):
        engagement.shared_ip_with = [engagement.shared_ip_with1]
        engagement.save()


def migrate_shared_ip_with_backwards(apps, schema_editor):
    Engagement = apps.get_model('audit', 'engagement')
    for engagement in Engagement.objects.exclude(shared_ip_with=[]):
        engagement.shared_ip_with1 = engagement.shared_ip_with[0]
        engagement.save()


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0023_auto_20171206_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engagement',
            old_name='shared_ip_with',
            new_name='shared_ip_with1'
        ),
        migrations.AddField(
            model_name='engagement',
            name='shared_ip_with',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DPKO', 'DPKO'), ('ECA', 'ECA'), ('ECLAC', 'ECLAC'), ('ESCWA', 'ESCWA'), ('FAO', 'FAO'), ('ILO', 'ILO'), ('IOM', 'IOM'), ('OHCHR', 'OHCHR'), ('UN', 'UN'), ('UN Women', 'UN Women'), ('UNAIDS', 'UNAIDS'), ('UNDP', 'UNDP'), ('UNESCO', 'UNESCO'), ('UNFPA', 'UNFPA'), ('UN - Habitat', 'UN - Habitat'), ('UNHCR', 'UNHCR'), ('UNODC', 'UNODC'), ('UNOPS', 'UNOPS'), ('UNRWA', 'UNRWA'), ('UNSC', 'UNSC'), ('UNU', 'UNU'), ('WB', 'WB'), ('WFP', 'WFP'), ('WHO', 'WHO')], max_length=20), blank=True, default=[], size=None, verbose_name='Shared IP with'),
        ),
        migrations.RunPython(migrate_shared_ip_with, migrate_shared_ip_with_backwards)
    ]
