# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-19 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0024_auto_20180119_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='shared_ip_with1'
        ),
    ]
