# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-19 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0026_auto_20180119_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='percent_of_audited_expenditure',
        ),
    ]
