# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-24 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_keyinternalcontrols(apps, schema_editor):
    Audit = apps.get_model('audit', 'Audit')
    KeyInternalControl = apps.get_model('audit', 'KeyInternalControl')

    for audit in Audit.objects.filter(~models.Q(recommendation='') | ~models.Q(audit_observation='') | ~models.Q(ip_response='')):
        KeyInternalControl.objects.create(
            recommendation=audit.recommendation,
            audit_observation=audit.audit_observation,
            ip_response=audit.ip_response,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0028_auto_20180120_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyInternalControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(blank=True, verbose_name='Recommendation')),
                ('audit_observation', models.TextField(blank=True, verbose_name='Audit Observation')),
                ('ip_response', models.TextField(blank=True, verbose_name='IP response')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='financialfinding',
            options={'ordering': ('id',)},
        ),
        migrations.RunPython(migrate_keyinternalcontrols, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='audit',
            name='audit_observation',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='ip_response',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='keyinternalcontrol',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_internal_controls', to='audit.Audit', verbose_name='Audit'),
        ),
    ]
