# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-02-19 14:02
from __future__ import unicode_literals

from django.db import migrations


def create_email_template(apps, schema_editor):
    EmailTemplate = apps.get_model('post_office', 'EmailTemplate')

    EmailTemplate.objects.get_or_create(name='audit/staff_member/invite')


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0029_auto_20180124_0934'),
        ('post_office', '0004_auto_20160607_0901'),
    ]

    operations = [
        migrations.RunPython(create_email_template, migrations.RunPython.noop),
    ]
