# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-13 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0030_auto_20180219_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Exchange Rate'),
        ),
        migrations.AlterModelOptions(
            name='riskcategory',
            options={'verbose_name_plural': 'Risk Categories'},
        ),
        migrations.AlterField(
            model_name='finding',
            name='recommendation',
            field=models.TextField(blank=True, verbose_name='Finding and Recommendation'),
        ),
    ]
